#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->getActiveTab();
Tab M = Tab("p", "lll","lll");
wind->getActiveTab();
Tab P = Tab("fff", "oo","x");
wind->print();
Tab C = Tab("hhh", "x","z");
wind->changeActiveTabTo(5);
Tab Z = Tab("bbb", "mmm","hh");
wind->isEmpty();
Tab J = Tab("iii", "jjj","rrr");
wind->newTab(C);
wind->newTab(J);
wind->print();
wind->print();
wind->moveActiveTabTo(2);
Tab R = Tab("o", "aa","h");
wind->moveActiveTabTo(5);
Tab U = Tab("nnn", "nn","t");
wind->moveActiveTabTo(5);
Tab D = Tab("yy", "xxx","hhh");
wind->print();
Tab B = Tab("www", "n","jjj");
wind->newTab(B);
wind->newTab(D);
Tab I = Tab("nnn", "sss","p");
wind->isEmpty();
Tab L = Tab("rrr", "g","e");
wind->isEmpty();
Tab A = Tab("a", "xx","hhh");
wind->newTab(A);
Tab K = Tab("i", "ff","ee");
wind->closeTab();
wind->moveActiveTabTo(2);
wind->getActiveTab();
Tab Y = Tab("yyy", "oo","qqq");
wind->moveActiveTabTo(1);
Tab N = Tab("mm", "hhh","l");
wind->print();
Tab F = Tab("y", "a","fff");
wind->newTab(F);
Tab H = Tab("eee", "ccc","ooo");
wind->isEmpty();
Tab Q = Tab("r", "q","ggg");
wind->closeTab();
wind->changeActiveTabTo(5);
wind->newTab(H);
wind->changeActiveTabTo(1);
Tab O = Tab("sss", "vv","qq");
wind->closeTab();
Tab E = Tab("aa", "aaa","qqq");
wind->closeTab();
wind->changeActiveTabTo(5);
wind->closeTab();
wind->print();
Tab T = Tab("s", "q","x");
wind->closeTab();
wind->getActiveTab();
wind->isEmpty();
wind->changeActiveTabTo(4);
wind->getActiveTab();
wind->moveActiveTabTo(4);
wind->newTab(E);
wind->newTab(I);
wind->changeActiveTabTo(2);
Tab X = Tab("zzz", "pp","j");
wind->moveActiveTabTo(4);
wind->print();
wind->closeTab();
Tab V = Tab("nnn", "cc","uu");
wind->moveActiveTabTo(1);
wind->print();
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->closeTab();
wind->closeTab();
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->closeTab();
wind->moveActiveTabTo(1);
wind->print();
wind->moveActiveTabTo(2);
wind->newTab(K);
wind->newTab(L);
wind->print();
wind->changeActiveTabTo(3);
Tab S = Tab("b", "kkk","r");
wind->print();
wind->changeActiveTabTo(4);
wind->isEmpty();
wind->closeTab();
Tab W = Tab("aa", "d","vvv");
wind->print();
wind->isEmpty();
wind->print();
wind->getActiveTab();
wind->newTab(M);
wind->print();
wind->print();
wind->closeTab();
wind->print();
wind->print();
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->newTab(N);
wind->getActiveTab();
wind->isEmpty();
wind->closeTab();
wind->print();
wind->isEmpty();
wind->closeTab();
wind->moveActiveTabTo(3);
wind->changeActiveTabTo(3);
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(2);
wind->closeTab();
wind->closeTab();
wind->print();
wind->moveActiveTabTo(3);
wind->moveActiveTabTo(4);
wind->print();
wind->newTab(O);
delete wind;
}
	return 0;
};

