#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->print();
Tab P = Tab("ll", "r","sss");
wind->getActiveTab();
Tab A = Tab("ww", "z","nnn");
wind->changeActiveTabTo(3);
Tab F = Tab("lll", "ggg","rr");
wind->moveActiveTabTo(3);
Tab R = Tab("k", "l","x");
wind->print();
Tab B = Tab("sss", "m","u");
wind->closeTab();
Tab X = Tab("zzz", "ii","qqq");
wind->closeTab();
wind->isEmpty();
Tab Z = Tab("dd", "xxx","c");
wind->isEmpty();
Tab D = Tab("t", "uuu","qq");
wind->newTab(A);
Tab O = Tab("yy", "f","bbb");
wind->getActiveTab();
Tab E = Tab("q", "rr","mm");
wind->closeTab();
wind->newTab(B);
Tab S = Tab("ll", "h","fff");
wind->print();
Tab V = Tab("f", "o","m");
wind->getActiveTab();
wind->newTab(D);
wind->changeActiveTabTo(1);
Tab Y = Tab("t", "s","gg");
wind->print();
wind->newTab(E);
wind->getActiveTab();
Tab G = Tab("o", "sss","sss");
wind->changeActiveTabTo(3);
Tab Q = Tab("z", "mmm","ss");
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(3);
wind->closeTab();
wind->moveActiveTabTo(1);
Tab J = Tab("ss", "s","ff");
wind->closeTab();
wind->print();
wind->changeActiveTabTo(2);
wind->closeTab();
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->newTab(F);
Tab U = Tab("r", "uuu","aaa");
wind->newTab(G);
wind->print();
Tab N = Tab("yyy", "qqq","ss");
wind->newTab(J);
Tab L = Tab("uu", "ee","n");
wind->changeActiveTabTo(5);
Tab I = Tab("vv", "c","j");
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->print();
Tab W = Tab("dd", "ff","mmm");
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->closeTab();
Tab M = Tab("d", "rrr","jjj");
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
wind->getActiveTab();
wind->moveActiveTabTo(4);
wind->closeTab();
Tab K = Tab("xxx", "yyy","jjj");
wind->getActiveTab();
wind->changeActiveTabTo(3);
Tab C = Tab("u", "bbb","kk");
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->print();
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(1);
wind->print();
wind->newTab(C);
wind->isEmpty();
wind->print();
wind->newTab(I);
wind->newTab(K);
wind->moveActiveTabTo(0);
wind->closeTab();
wind->newTab(L);
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(2);
wind->newTab(M);
wind->closeTab();
wind->isEmpty();
wind->newTab(N);
wind->newTab(O);
wind->getActiveTab();
wind->newTab(P);
wind->print();
wind->isEmpty();
wind->isEmpty();
wind->moveActiveTabTo(5);
Tab H = Tab("uuu", "z","qq");
wind->changeActiveTabTo(2);
wind->moveActiveTabTo(5);
wind->newTab(H);
wind->print();
Tab T = Tab("uuu", "z","lll");
wind->isEmpty();
wind->isEmpty();
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(2);
wind->closeTab();
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
wind->print();
wind->moveActiveTabTo(4);
wind->closeTab();
delete wind;
}
	return 0;
}