#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->closeTab();
Tab F = Tab("xx", "rrr","aa");
wind->closeTab();
Tab O = Tab("aa", "a","u");
wind->isEmpty();
Tab W = Tab("b", "fff","ww");
wind->print();
Tab E = Tab("h", "vv","ff");
wind->getActiveTab();
Tab L = Tab("aa", "hhh","jjj");
wind->isEmpty();
Tab H = Tab("ff", "w","v");
wind->newTab(E);
Tab J = Tab("hhh", "ddd","gg");
wind->changeActiveTabTo(1);
Tab R = Tab("uuu", "pp","i");
wind->newTab(F);
Tab G = Tab("ee", "zzz","l");
wind->print();
wind->getActiveTab();
Tab B = Tab("rrr", "i","q");
wind->print();
wind->closeTab();
Tab U = Tab("r", "p","x");
wind->newTab(B);
Tab S = Tab("mmm", "d","j");
wind->moveActiveTabTo(0);
Tab D = Tab("l", "ttt","vvv");
wind->print();
wind->closeTab();
Tab V = Tab("ooo", "pp","ggg");
wind->changeActiveTabTo(1);
wind->print();
wind->newTab(D);
wind->closeTab();
Tab P = Tab("ggg", "kk","yy");
wind->moveActiveTabTo(3);
wind->isEmpty();
wind->getActiveTab();
wind->isEmpty();
wind->getActiveTab();
wind->newTab(G);
Tab C = Tab("nn", "ooo","ggg");
wind->newTab(C);
Tab Z = Tab("jj", "aa","r");
wind->newTab(H);
Tab K = Tab("ll", "ee","zz");
wind->closeTab();
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(0);
Tab T = Tab("eee", "q","ee");
wind->changeActiveTabTo(1);
Tab Y = Tab("ccc", "a","oo");
wind->isEmpty();
wind->print();
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(2);
wind->moveActiveTabTo(3);
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(0);
wind->newTab(J);
wind->newTab(K);
wind->newTab(L);
Tab A = Tab("m", "oo","h");
wind->closeTab();
wind->newTab(A);
wind->closeTab();
wind->moveActiveTabTo(2);
Tab X = Tab("t", "ggg","q");
wind->isEmpty();
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(3);
Tab Q = Tab("y", "ggg","qqq");
wind->print();
wind->closeTab();
wind->closeTab();
wind->closeTab();
wind->getActiveTab();
wind->print();
wind->newTab(O);
wind->closeTab();
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(0);
wind->newTab(P);
wind->changeActiveTabTo(4);
wind->print();
wind->newTab(Q);
wind->moveActiveTabTo(2);
Tab M = Tab("d", "ddd","p");
wind->newTab(M);
wind->moveActiveTabTo(3);
wind->newTab(R);
wind->changeActiveTabTo(2);
wind->moveActiveTabTo(4);
wind->closeTab();
wind->print();
wind->closeTab();
wind->changeActiveTabTo(5);
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(4);
wind->closeTab();
wind->print();
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->closeTab();
wind->print();
wind->getActiveTab();
Tab N = Tab("n", "ddd","w");
wind->newTab(N);
wind->getActiveTab();
wind->print();
wind->newTab(S);
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(4);
wind->isEmpty();
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(2);
wind->closeTab();
wind->print();
wind->print();
wind->print();
delete wind;
}
	return 0;
}