#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->moveActiveTabTo(3);
Tab O = Tab("yyy", "cc","eee");
wind->closeTab();
Tab A = Tab("pp", "c","zz");
wind->closeTab();
Tab C = Tab("ss", "z","u");
wind->changeActiveTabTo(1);
Tab T = Tab("tt", "ggg","xxx");
wind->getActiveTab();
Tab H = Tab("t", "qq","hh");
wind->getActiveTab();
Tab S = Tab("o", "ggg","vvv");
wind->closeTab();
wind->changeActiveTabTo(0);
wind->isEmpty();
Tab B = Tab("kk", "p","qqq");
wind->changeActiveTabTo(4);
Tab G = Tab("fff", "mmm","v");
wind->newTab(A);
Tab D = Tab("ppp", "eee","dd");
wind->moveActiveTabTo(0);
Tab V = Tab("ll", "t","oo");
wind->closeTab();
wind->changeActiveTabTo(2);
Tab K = Tab("hh", "uu","r");
wind->moveActiveTabTo(0);
Tab J = Tab("zz", "f","s");
wind->moveActiveTabTo(0);
wind->newTab(B);
Tab W = Tab("k", "b","rrr");
wind->moveActiveTabTo(2);
wind->closeTab();
Tab R = Tab("aaa", "ll","w");
wind->getActiveTab();
Tab Q = Tab("zzz", "p","yy");
wind->isEmpty();
Tab I = Tab("ooo", "cc","bb");
wind->print();
Tab Y = Tab("fff", "pp","xxx");
wind->closeTab();
Tab Z = Tab("k", "u","i");
wind->getActiveTab();
wind->newTab(C);
Tab E = Tab("ggg", "sss","mmm");
wind->getActiveTab();
wind->closeTab();
Tab N = Tab("ii", "vvv","rr");
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(4);
wind->closeTab();
wind->changeActiveTabTo(0);
Tab X = Tab("b", "p","nn");
wind->print();
Tab F = Tab("zzz", "ww","g");
wind->getActiveTab();
wind->print();
wind->moveActiveTabTo(1);
Tab U = Tab("t", "bbb","qqq");
wind->print();
wind->closeTab();
wind->isEmpty();
wind->newTab(D);
wind->print();
wind->isEmpty();
wind->newTab(E);
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
wind->newTab(F);
wind->isEmpty();
wind->print();
wind->changeActiveTabTo(1);
wind->print();
Tab L = Tab("s", "p","ggg");
wind->newTab(G);
wind->changeActiveTabTo(5);
wind->newTab(H);
wind->changeActiveTabTo(1);
wind->newTab(I);
wind->isEmpty();
wind->changeActiveTabTo(2);
wind->moveActiveTabTo(3);
wind->print();
wind->print();
wind->changeActiveTabTo(2);
wind->getActiveTab();
Tab M = Tab("ii", "fff","zzz");
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->closeTab();
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
wind->closeTab();
wind->print();
wind->isEmpty();
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->print();
wind->getActiveTab();
wind->print();
wind->closeTab();
wind->moveActiveTabTo(1);
wind->print();
wind->getActiveTab();
wind->print();
wind->print();
wind->changeActiveTabTo(1);
wind->isEmpty();
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->newTab(J);
wind->closeTab();
wind->newTab(K);
wind->moveActiveTabTo(3);
delete wind;
}
	return 0;
}