#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->changeActiveTabTo(1);
Tab W = Tab("yy", "nn","zzz");
wind->isEmpty();
wind->closeTab();
Tab P = Tab("ddd", "eee","bbb");
wind->getActiveTab();
Tab G = Tab("f", "t","ss");
wind->print();
Tab I = Tab("vv", "xxx","rrr");
wind->newTab(G);
Tab V = Tab("fff", "bb","s");
wind->print();
Tab S = Tab("l", "iii","nn");
wind->newTab(I);
Tab B = Tab("j", "fff","c");
wind->changeActiveTabTo(1);
Tab F = Tab("j", "hhh","yyy");
wind->newTab(B);
wind->print();
Tab T = Tab("bb", "t","ggg");
wind->changeActiveTabTo(2);
Tab Z = Tab("i", "a","ddd");
wind->print();
wind->newTab(F);
Tab Y = Tab("pp", "ss","a");
wind->closeTab();
wind->closeTab();
wind->changeActiveTabTo(1);
Tab L = Tab("uu", "p","ww");
wind->getActiveTab();
Tab J = Tab("w", "a","dd");
wind->print();
Tab Q = Tab("jj", "a","o");
wind->isEmpty();
Tab X = Tab("ccc", "bb","pp");
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(4);
Tab E = Tab("pp", "qq","mm");
wind->moveActiveTabTo(5);
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
wind->print();
wind->changeActiveTabTo(5);
Tab C = Tab("g", "zzz","mm");
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(5);
Tab N = Tab("ss", "bb","qqq");
wind->newTab(C);
wind->isEmpty();
Tab D = Tab("www", "ggg","ddd");
wind->closeTab();
Tab U = Tab("yy", "tt","c");
wind->print();
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
wind->moveActiveTabTo(2);
Tab R = Tab("fff", "fff","hh");
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(3);
wind->newTab(D);
wind->newTab(E);
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(2);
Tab H = Tab("ff", "ttt","k");
wind->newTab(H);
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->newTab(J);
wind->newTab(L);
wind->getActiveTab();
Tab K = Tab("uuu", "j","yy");
wind->closeTab();
wind->print();
wind->newTab(K);
wind->changeActiveTabTo(2);
Tab O = Tab("jjj", "mm","uu");
wind->print();
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->print();
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(1);
wind->newTab(N);
wind->newTab(O);
wind->closeTab();
wind->print();
wind->changeActiveTabTo(3);
wind->getActiveTab();
wind->isEmpty();
wind->changeActiveTabTo(2);
wind->newTab(P);
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
wind->newTab(Q);
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->changeActiveTabTo(4);
wind->print();
wind->isEmpty();
wind->newTab(R);
wind->closeTab();
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->closeTab();
wind->closeTab();
Tab M = Tab("qqq", "dd","r");
wind->getActiveTab();
wind->print();
wind->getActiveTab();
wind->isEmpty();
wind->closeTab();
wind->changeActiveTabTo(0);
Tab A = Tab("q", "ttt","ww");
wind->print();
wind->changeActiveTabTo(3);
delete wind;
}
	return 0;
}