#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->closeTab();
Tab Y = Tab("c", "aaa","rrr");
wind->closeTab();
Tab X = Tab("a", "zzz","sss");
wind->getActiveTab();
Tab E = Tab("vvv", "h","w");
wind->changeActiveTabTo(5);
Tab Z = Tab("mmm", "h","ppp");
wind->newTab(E);
Tab I = Tab("ii", "qq","m");
wind->moveActiveTabTo(4);
Tab G = Tab("o", "www","mmm");
wind->print();
wind->isEmpty();
wind->newTab(G);
Tab N = Tab("sss", "gg","f");
wind->moveActiveTabTo(4);
Tab V = Tab("y", "qqq","p");
wind->moveActiveTabTo(0);
Tab W = Tab("p", "k","sss");
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(1);
Tab A = Tab("l", "jj","sss");
wind->changeActiveTabTo(1);
Tab K = Tab("n", "www","eee");
wind->getActiveTab();
wind->newTab(A);
wind->closeTab();
wind->print();
Tab D = Tab("l", "vv","ww");
wind->moveActiveTabTo(3);
wind->getActiveTab();
Tab C = Tab("xxx", "g","e");
wind->moveActiveTabTo(1);
Tab T = Tab("bb", "tt","kkk");
wind->getActiveTab();
wind->print();
Tab B = Tab("p", "jjj","ttt");
wind->print();
Tab H = Tab("q", "uu","v");
wind->print();
wind->changeActiveTabTo(1);
wind->newTab(B);
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(4);
wind->newTab(C);
Tab J = Tab("kk", "oo","z");
wind->print();
Tab S = Tab("a", "hhh","ccc");
wind->closeTab();
wind->newTab(D);
wind->changeActiveTabTo(4);
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->print();
wind->isEmpty();
wind->newTab(H);
Tab O = Tab("cc", "qq","rrr");
wind->closeTab();
wind->closeTab();
wind->print();
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->newTab(I);
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(1);
Tab Q = Tab("vv", "kk","yy");
wind->isEmpty();
wind->getActiveTab();
wind->newTab(J);
Tab U = Tab("bb", "eee","e");
wind->isEmpty();
wind->newTab(K);
wind->newTab(N);
wind->newTab(O);
wind->changeActiveTabTo(0);
wind->print();
wind->print();
Tab L = Tab("m", "vvv","zzz");
wind->isEmpty();
wind->closeTab();
wind->moveActiveTabTo(0);
Tab F = Tab("ddd", "jjj","i");
wind->isEmpty();
wind->print();
wind->newTab(F);
wind->print();
wind->newTab(L);
Tab P = Tab("y", "rr","nnn");
wind->isEmpty();
wind->newTab(P);
wind->print();
wind->changeActiveTabTo(0);
wind->print();
wind->print();
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(4);
wind->isEmpty();
Tab R = Tab("hh", "l","b");
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(1);
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->getActiveTab();
wind->changeActiveTabTo(0);
wind->closeTab();
wind->changeActiveTabTo(4);
wind->getActiveTab();
wind->closeTab();
wind->closeTab();
wind->getActiveTab();
wind->print();
wind->newTab(Q);
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->closeTab();
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
delete wind;
}
	return 0;
}