#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->closeTab();
Tab V = Tab("m", "bb","p");
wind->changeActiveTabTo(3);
Tab N = Tab("kk", "uuu","k");
wind->moveActiveTabTo(0);
Tab J = Tab("tt", "d","s");
wind->moveActiveTabTo(3);
wind->getActiveTab();
Tab Y = Tab("vv", "u","ccc");
wind->changeActiveTabTo(1);
Tab E = Tab("ttt", "b","jjj");
wind->getActiveTab();
wind->moveActiveTabTo(2);
Tab F = Tab("tt", "q","o");
wind->print();
wind->newTab(E);
Tab W = Tab("f", "c","hhh");
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(2);
Tab Q = Tab("n", "uu","v");
wind->isEmpty();
wind->print();
wind->getActiveTab();
Tab I = Tab("xx", "ss","p");
wind->changeActiveTabTo(1);
Tab B = Tab("f", "l","vv");
wind->isEmpty();
wind->isEmpty();
wind->getActiveTab();
Tab H = Tab("yy", "kkk","qq");
wind->moveActiveTabTo(1);
Tab M = Tab("bb", "kkk","www");
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(0);
Tab L = Tab("g", "nn","o");
wind->moveActiveTabTo(1);
wind->moveActiveTabTo(0);
wind->newTab(B);
wind->closeTab();
wind->getActiveTab();
Tab C = Tab("e", "uu","pp");
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->newTab(C);
wind->isEmpty();
Tab K = Tab("vvv", "vvv","z");
wind->print();
Tab U = Tab("ttt", "uu","www");
wind->newTab(F);
Tab O = Tab("oo", "d","mmm");
wind->isEmpty();
Tab R = Tab("iii", "c","qq");
wind->changeActiveTabTo(5);
Tab A = Tab("e", "r","m");
wind->getActiveTab();
wind->closeTab();
wind->getActiveTab();
wind->moveActiveTabTo(4);
wind->print();
wind->getActiveTab();
Tab D = Tab("g", "s","bbb");
wind->newTab(A);
wind->isEmpty();
wind->closeTab();
wind->changeActiveTabTo(4);
wind->changeActiveTabTo(5);
wind->print();
wind->changeActiveTabTo(3);
wind->print();
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(1);
wind->getActiveTab();
Tab P = Tab("vv", "jjj","qqq");
wind->print();
wind->closeTab();
wind->moveActiveTabTo(4);
Tab G = Tab("oo", "hhh","x");
wind->getActiveTab();
wind->closeTab();
wind->closeTab();
wind->newTab(D);
wind->newTab(G);
wind->closeTab();
wind->changeActiveTabTo(5);
wind->print();
wind->print();
Tab T = Tab("ll", "g","vv");
wind->print();
wind->moveActiveTabTo(1);
wind->newTab(H);
wind->closeTab();
wind->moveActiveTabTo(4);
wind->changeActiveTabTo(3);
wind->print();
wind->isEmpty();
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->isEmpty();
wind->closeTab();
wind->moveActiveTabTo(1);
wind->print();
wind->isEmpty();
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(2);
wind->print();
Tab S = Tab("xx", "tt","rrr");
wind->print();
wind->isEmpty();
Tab X = Tab("xxx", "mmm","l");
wind->changeActiveTabTo(2);
wind->closeTab();
delete wind;
}
	return 0;
}