#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->changeActiveTabTo(5);
Tab Y = Tab("dd", "ff","e");
wind->moveActiveTabTo(2);
Tab V = Tab("f", "ee","n");
wind->isEmpty();
Tab D = Tab("u", "ee","ggg");
wind->newTab(D);
Tab Q = Tab("j", "g","jjj");
wind->closeTab();
Tab O = Tab("ttt", "b","jj");
wind->getActiveTab();
Tab T = Tab("j", "yyy","iii");
wind->closeTab();
Tab W = Tab("rrr", "v","u");
wind->newTab(O);
Tab R = Tab("jjj", "jjj","yy");
wind->changeActiveTabTo(4);
Tab X = Tab("www", "q","tt");
wind->print();
Tab H = Tab("g", "uu","nn");
wind->getActiveTab();
wind->changeActiveTabTo(1);
Tab J = Tab("ddd", "uu","fff");
wind->isEmpty();
Tab U = Tab("aa", "sss","a");
wind->changeActiveTabTo(0);
wind->newTab(H);
Tab N = Tab("ooo", "hh","kkk");
wind->getActiveTab();
wind->closeTab();
wind->newTab(J);
wind->closeTab();
Tab E = Tab("kkk", "nnn","yy");
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->closeTab();
Tab C = Tab("gg", "nnn","qq");
wind->changeActiveTabTo(1);
Tab Z = Tab("u", "rrr","uu");
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
wind->newTab(C);
Tab I = Tab("z", "www","cc");
wind->newTab(E);
wind->getActiveTab();
wind->print();
wind->closeTab();
Tab P = Tab("h", "v","a");
wind->moveActiveTabTo(2);
Tab G = Tab("oo", "x","bb");
wind->getActiveTab();
wind->newTab(G);
wind->getActiveTab();
wind->newTab(I);
wind->print();
wind->closeTab();
wind->moveActiveTabTo(5);
Tab F = Tab("s", "vvv","k");
wind->changeActiveTabTo(3);
wind->newTab(F);
wind->closeTab();
wind->moveActiveTabTo(1);
wind->getActiveTab();
wind->newTab(N);
Tab L = Tab("c", "www","t");
wind->newTab(L);
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
wind->changeActiveTabTo(5);
Tab A = Tab("rr", "aa","tt");
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->getActiveTab();
Tab B = Tab("p", "m","xx");
wind->newTab(A);
wind->closeTab();
wind->moveActiveTabTo(5);
Tab S = Tab("c", "xxx","rrr");
wind->newTab(B);
wind->print();
wind->isEmpty();
wind->closeTab();
wind->moveActiveTabTo(1);
wind->closeTab();
wind->closeTab();
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(3);
wind->moveActiveTabTo(4);
wind->newTab(P);
wind->newTab(Q);
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->closeTab();
wind->changeActiveTabTo(1);
wind->closeTab();
wind->changeActiveTabTo(1);
Tab K = Tab("tt", "v","vv");
wind->print();
wind->closeTab();
wind->newTab(K);
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->newTab(R);
wind->isEmpty();
wind->print();
wind->print();
Tab M = Tab("lll", "aaa","w");
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
wind->print();
wind->changeActiveTabTo(4);
wind->newTab(M);
wind->getActiveTab();
wind->newTab(S);
wind->changeActiveTabTo(3);
delete wind;
}
	return 0;
}