#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->print();
Tab M = Tab("hhh", "r","w");
wind->isEmpty();
wind->closeTab();
Tab S = Tab("p", "b","tt");
wind->changeActiveTabTo(1);
Tab N = Tab("jjj", "nnn","ggg");
wind->isEmpty();
Tab C = Tab("qq", "vv","gg");
wind->isEmpty();
Tab D = Tab("gg", "vvv","i");
wind->changeActiveTabTo(5);
Tab I = Tab("zzz", "g","hh");
wind->moveActiveTabTo(0);
Tab A = Tab("cc", "rrr","ttt");
wind->moveActiveTabTo(5);
wind->newTab(A);
wind->moveActiveTabTo(2);
Tab J = Tab("hh", "qqq","w");
wind->closeTab();
Tab Z = Tab("s", "d","b");
wind->closeTab();
Tab U = Tab("vvv", "pp","aa");
wind->newTab(C);
wind->print();
Tab X = Tab("c", "hh","xxx");
wind->print();
wind->moveActiveTabTo(0);
Tab E = Tab("nn", "k","jj");
wind->moveActiveTabTo(3);
Tab R = Tab("ccc", "m","www");
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(3);
Tab F = Tab("f", "nn","tt");
wind->closeTab();
wind->changeActiveTabTo(3);
Tab T = Tab("x", "lll","rrr");
wind->isEmpty();
wind->newTab(D);
wind->getActiveTab();
Tab H = Tab("w", "n","vv");
wind->changeActiveTabTo(3);
Tab Y = Tab("lll", "jj","zz");
wind->getActiveTab();
wind->isEmpty();
wind->newTab(E);
wind->closeTab();
Tab W = Tab("uu", "ccc","ttt");
wind->isEmpty();
wind->newTab(F);
wind->getActiveTab();
wind->getActiveTab();
Tab G = Tab("sss", "kk","s");
wind->newTab(G);
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(0);
Tab O = Tab("fff", "mmm","fff");
wind->closeTab();
Tab B = Tab("eee", "h","ww");
wind->getActiveTab();
Tab K = Tab("uu", "z","u");
wind->getActiveTab();
wind->newTab(B);
Tab P = Tab("b", "e","www");
wind->print();
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->newTab(H);
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->print();
wind->newTab(I);
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(4);
wind->isEmpty();
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(4);
wind->newTab(J);
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->getActiveTab();
wind->isEmpty();
wind->print();
wind->closeTab();
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(3);
wind->newTab(K);
wind->changeActiveTabTo(1);
wind->newTab(M);
wind->closeTab();
wind->getActiveTab();
wind->print();
wind->getActiveTab();
Tab L = Tab("xxx", "u","gg");
wind->isEmpty();
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(3);
wind->newTab(L);
wind->newTab(N);
wind->print();
Tab V = Tab("lll", "nn","i");
wind->moveActiveTabTo(3);
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->closeTab();
wind->print();
wind->print();
wind->print();
wind->newTab(O);
wind->isEmpty();
wind->getActiveTab();
wind->print();
wind->newTab(P);
wind->newTab(R);
wind->isEmpty();
wind->isEmpty();
delete wind;
}
	return 0;
}