#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->changeActiveTabTo(2);
Tab P = Tab("o", "ee","xx");
wind->getActiveTab();
Tab V = Tab("w", "ss","uu");
wind->closeTab();
Tab F = Tab("x", "yy","ww");
wind->moveActiveTabTo(3);
Tab X = Tab("y", "r","pp");
wind->closeTab();
Tab W = Tab("kk", "p","uu");
wind->changeActiveTabTo(5);
Tab O = Tab("t", "d","fff");
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(3);
Tab N = Tab("jj", "www","cc");
wind->changeActiveTabTo(1);
wind->closeTab();
Tab G = Tab("oo", "ccc","mmm");
wind->moveActiveTabTo(0);
Tab H = Tab("a", "w","q");
wind->newTab(F);
wind->changeActiveTabTo(5);
Tab R = Tab("ii", "ss","rrr");
wind->isEmpty();
Tab U = Tab("cc", "k","vv");
wind->newTab(G);
Tab A = Tab("ff", "ccc","ss");
wind->isEmpty();
wind->newTab(A);
wind->moveActiveTabTo(0);
Tab M = Tab("p", "d","e");
wind->isEmpty();
Tab Q = Tab("cc", "fff","yyy");
wind->getActiveTab();
Tab T = Tab("m", "zz","ddd");
wind->getActiveTab();
Tab S = Tab("k", "sss","uu");
wind->getActiveTab();
wind->changeActiveTabTo(0);
Tab C = Tab("o", "nnn","o");
wind->print();
Tab D = Tab("pp", "l","qq");
wind->print();
wind->print();
wind->changeActiveTabTo(2);
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
Tab Z = Tab("mmm", "lll","w");
wind->newTab(C);
wind->moveActiveTabTo(2);
wind->closeTab();
Tab B = Tab("fff", "ii","ff");
wind->isEmpty();
Tab Y = Tab("vv", "ddd","ll");
wind->changeActiveTabTo(1);
wind->print();
wind->print();
Tab J = Tab("f", "v","x");
wind->closeTab();
Tab I = Tab("ooo", "zzz","v");
wind->getActiveTab();
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(1);
wind->closeTab();
wind->print();
wind->closeTab();
wind->newTab(B);
wind->closeTab();
wind->newTab(D);
wind->getActiveTab();
wind->moveActiveTabTo(4);
Tab L = Tab("ss", "aa","e");
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->closeTab();
wind->print();
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(1);
wind->getActiveTab();
wind->closeTab();
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(4);
wind->isEmpty();
wind->changeActiveTabTo(2);
Tab K = Tab("ccc", "y","eee");
wind->print();
wind->changeActiveTabTo(5);
wind->closeTab();
wind->newTab(H);
Tab E = Tab("nn", "jjj","ee");
wind->moveActiveTabTo(2);
wind->closeTab();
wind->print();
wind->newTab(E);
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(4);
wind->newTab(I);
wind->print();
wind->changeActiveTabTo(2);
wind->print();
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->closeTab();
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(4);
wind->getActiveTab();
wind->getActiveTab();
wind->print();
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
wind->isEmpty();
wind->print();
wind->print();
delete wind;
}
	return 0;
}