#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->changeActiveTabTo(5);
Tab F = Tab("rr", "kk","hh");
wind->newTab(F);
Tab X = Tab("r", "bbb","m");
wind->print();
Tab E = Tab("l", "gg","l");
wind->print();
Tab A = Tab("nnn", "d","nn");
wind->moveActiveTabTo(4);
Tab S = Tab("nn", "jjj","l");
wind->newTab(A);
wind->closeTab();
wind->closeTab();
Tab C = Tab("uu", "iii","ddd");
wind->isEmpty();
Tab R = Tab("lll", "g","ss");
wind->getActiveTab();
Tab N = Tab("rrr", "ccc","mmm");
wind->isEmpty();
Tab T = Tab("iii", "kk","z");
wind->getActiveTab();
Tab Z = Tab("rr", "pp","ddd");
wind->newTab(C);
wind->changeActiveTabTo(5);
Tab P = Tab("hh", "g","gg");
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(5);
Tab Y = Tab("ww", "z","tt");
wind->closeTab();
Tab W = Tab("kk", "kk","mmm");
wind->print();
Tab J = Tab("z", "ee","yy");
wind->newTab(E);
wind->print();
wind->newTab(J);
Tab U = Tab("i", "aa","d");
wind->changeActiveTabTo(0);
wind->getActiveTab();
Tab H = Tab("dd", "gg","s");
wind->closeTab();
wind->print();
Tab L = Tab("bbb", "vvv","bb");
wind->closeTab();
wind->changeActiveTabTo(0);
Tab D = Tab("kkk", "vvv","vvv");
wind->isEmpty();
wind->isEmpty();
wind->moveActiveTabTo(5);
Tab B = Tab("sss", "f","xx");
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(1);
wind->getActiveTab();
wind->changeActiveTabTo(1);
Tab V = Tab("pp", "w","www");
wind->isEmpty();
Tab K = Tab("xx", "bbb","eee");
wind->newTab(B);
wind->changeActiveTabTo(5);
wind->newTab(D);
Tab Q = Tab("lll", "yy","bb");
wind->changeActiveTabTo(2);
Tab G = Tab("q", "qqq","xxx");
wind->isEmpty();
Tab O = Tab("q", "dd","x");
wind->newTab(G);
wind->closeTab();
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(5);
Tab I = Tab("mm", "d","p");
wind->moveActiveTabTo(1);
wind->print();
wind->moveActiveTabTo(0);
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
wind->closeTab();
wind->print();
wind->print();
wind->print();
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->newTab(H);
wind->print();
wind->getActiveTab();
wind->closeTab();
wind->closeTab();
wind->isEmpty();
wind->changeActiveTabTo(4);
wind->print();
wind->isEmpty();
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->isEmpty();
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(2);
wind->print();
wind->newTab(I);
wind->getActiveTab();
wind->getActiveTab();
wind->print();
wind->print();
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(2);
wind->newTab(K);
wind->closeTab();
wind->isEmpty();
wind->changeActiveTabTo(4);
wind->print();
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->getActiveTab();
wind->changeActiveTabTo(4);
wind->closeTab();
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->newTab(L);
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->closeTab();
delete wind;
}
	return 0;
}