#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->isEmpty();
Tab C = Tab("t", "ww","iii");
wind->newTab(C);
Tab Y = Tab("ss", "ii","yyy");
wind->isEmpty();
Tab R = Tab("nn", "qq","fff");
wind->closeTab();
Tab W = Tab("s", "h","s");
wind->print();
Tab I = Tab("mmm", "l","l");
wind->getActiveTab();
Tab H = Tab("p", "lll","s");
wind->getActiveTab();
Tab A = Tab("ooo", "yyy","lll");
wind->closeTab();
Tab U = Tab("qqq", "jjj","mm");
wind->moveActiveTabTo(0);
Tab E = Tab("fff", "kkk","kkk");
wind->changeActiveTabTo(5);
wind->newTab(A);
Tab M = Tab("hhh", "i","n");
wind->isEmpty();
wind->getActiveTab();
wind->moveActiveTabTo(0);
Tab L = Tab("ggg", "i","ii");
wind->isEmpty();
Tab X = Tab("bb", "gg","bbb");
wind->isEmpty();
Tab V = Tab("yy", "ggg","kk");
wind->closeTab();
wind->changeActiveTabTo(0);
wind->getActiveTab();
Tab P = Tab("s", "ii","yy");
wind->print();
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(5);
wind->print();
Tab T = Tab("mmm", "mm","o");
wind->getActiveTab();
wind->newTab(E);
Tab Q = Tab("ccc", "xxx","ii");
wind->newTab(H);
wind->newTab(I);
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
wind->newTab(L);
Tab N = Tab("yy", "ee","ll");
wind->changeActiveTabTo(2);
wind->closeTab();
Tab J = Tab("j", "kkk","fff");
wind->changeActiveTabTo(5);
wind->getActiveTab();
wind->closeTab();
Tab F = Tab("z", "nnn","www");
wind->newTab(F);
wind->changeActiveTabTo(4);
Tab K = Tab("aaa", "hhh","e");
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->changeActiveTabTo(4);
wind->changeActiveTabTo(0);
wind->print();
wind->newTab(J);
wind->closeTab();
wind->isEmpty();
wind->print();
wind->closeTab();
wind->changeActiveTabTo(3);
wind->getActiveTab();
Tab D = Tab("k", "p","ww");
wind->print();
wind->newTab(D);
wind->newTab(K);
wind->print();
wind->changeActiveTabTo(5);
Tab S = Tab("ttt", "iii","ww");
wind->closeTab();
Tab B = Tab("tt", "m","cc");
wind->changeActiveTabTo(0);
Tab Z = Tab("jjj", "mm","r");
wind->isEmpty();
wind->print();
wind->print();
wind->closeTab();
wind->closeTab();
wind->changeActiveTabTo(3);
Tab G = Tab("qqq", "yyy","e");
wind->changeActiveTabTo(0);
Tab O = Tab("www", "kk","ccc");
wind->print();
wind->getActiveTab();
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(4);
wind->closeTab();
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->print();
wind->closeTab();
wind->newTab(B);
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->getActiveTab();
wind->isEmpty();
wind->changeActiveTabTo(2);
wind->newTab(G);
wind->isEmpty();
wind->changeActiveTabTo(4);
wind->getActiveTab();
wind->newTab(M);
wind->print();
wind->newTab(N);
wind->print();
wind->moveActiveTabTo(1);
wind->newTab(O);
wind->changeActiveTabTo(1);
wind->print();
wind->getActiveTab();
wind->newTab(P);
delete wind;
}
	return 0;
}