#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->getActiveTab();
Tab O = Tab("ee", "j","aaa");
wind->changeActiveTabTo(2);
Tab I = Tab("fff", "s","a");
wind->newTab(I);
Tab R = Tab("oo", "ddd","ddd");
wind->changeActiveTabTo(1);
Tab Z = Tab("ll", "h","nn");
wind->isEmpty();
Tab T = Tab("bb", "f","k");
wind->changeActiveTabTo(5);
Tab B = Tab("w", "o","sss");
wind->print();
Tab M = Tab("hh", "n","f");
wind->closeTab();
Tab K = Tab("bb", "d","l");
wind->isEmpty();
wind->isEmpty();
wind->print();
Tab D = Tab("zz", "f","ee");
wind->isEmpty();
Tab X = Tab("qqq", "aa","kkk");
wind->moveActiveTabTo(0);
Tab A = Tab("o", "mmm","aa");
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
Tab Y = Tab("ooo", "uuu","ccc");
wind->closeTab();
Tab F = Tab("hh", "tt","oo");
wind->closeTab();
Tab H = Tab("s", "c","rrr");
wind->changeActiveTabTo(0);
wind->isEmpty();
Tab L = Tab("u", "zz","cc");
wind->newTab(A);
Tab S = Tab("mmm", "aa","rrr");
wind->isEmpty();
wind->isEmpty();
Tab E = Tab("nn", "e","y");
wind->isEmpty();
wind->getActiveTab();
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->getActiveTab();
Tab J = Tab("hh", "bb","p");
wind->changeActiveTabTo(0);
wind->closeTab();
wind->isEmpty();
wind->print();
wind->closeTab();
wind->changeActiveTabTo(5);
wind->closeTab();
Tab W = Tab("b", "iii","fff");
wind->closeTab();
wind->closeTab();
wind->print();
Tab P = Tab("qq", "tt","nn");
wind->getActiveTab();
wind->getActiveTab();
Tab G = Tab("ggg", "ddd","x");
wind->getActiveTab();
Tab U = Tab("p", "xx","g");
wind->newTab(B);
Tab Q = Tab("y", "ooo","k");
wind->changeActiveTabTo(4);
wind->changeActiveTabTo(3);
wind->newTab(D);
wind->moveActiveTabTo(2);
wind->print();
wind->changeActiveTabTo(2);
wind->closeTab();
wind->changeActiveTabTo(2);
wind->getActiveTab();
Tab V = Tab("ww", "c","e");
wind->changeActiveTabTo(2);
wind->print();
wind->moveActiveTabTo(5);
wind->print();
wind->print();
wind->closeTab();
wind->closeTab();
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(2);
wind->newTab(E);
wind->closeTab();
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->print();
wind->changeActiveTabTo(5);
wind->newTab(F);
wind->getActiveTab();
wind->print();
wind->print();
wind->newTab(G);
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
wind->moveActiveTabTo(1);
wind->newTab(H);
wind->changeActiveTabTo(1);
wind->closeTab();
wind->isEmpty();
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(4);
Tab C = Tab("kk", "b","jjj");
wind->changeActiveTabTo(4);
wind->changeActiveTabTo(0);
wind->closeTab();
wind->closeTab();
wind->newTab(C);
wind->print();
wind->getActiveTab();
Tab N = Tab("xx", "ooo","uuu");
wind->changeActiveTabTo(3);
wind->closeTab();
wind->newTab(J);
wind->isEmpty();
wind->closeTab();
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->closeTab();
delete wind;
}
	return 0;
}