#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
Tab A = Tab("ss", "y","ttt");
wind->print();
Tab G = Tab("x", "bbb","gg");
wind->getActiveTab();
Tab I = Tab("ff", "ttt","ppp");
wind->print();
Tab Z = Tab("w", "k","kk");
wind->moveActiveTabTo(0);
wind->getActiveTab();
Tab B = Tab("cc", "lll","nn");
wind->newTab(A);
Tab P = Tab("w", "yy","eee");
wind->newTab(B);
wind->changeActiveTabTo(2);
Tab O = Tab("l", "tt","lll");
wind->moveActiveTabTo(4);
Tab F = Tab("tt", "kkk","uu");
wind->moveActiveTabTo(3);
Tab W = Tab("r", "uu","lll");
wind->print();
wind->changeActiveTabTo(5);
Tab N = Tab("rr", "zzz","ii");
wind->closeTab();
wind->changeActiveTabTo(4);
Tab M = Tab("mmm", "oo","gg");
wind->closeTab();
Tab Q = Tab("iii", "nn","qqq");
wind->changeActiveTabTo(0);
Tab Y = Tab("d", "iii","rrr");
wind->changeActiveTabTo(2);
Tab V = Tab("tt", "gg","bbb");
wind->closeTab();
wind->moveActiveTabTo(0);
Tab K = Tab("u", "www","f");
wind->changeActiveTabTo(1);
wind->getActiveTab();
Tab E = Tab("ll", "oo","aaa");
wind->closeTab();
wind->closeTab();
Tab H = Tab("www", "ii","vvv");
wind->closeTab();
wind->changeActiveTabTo(1);
wind->newTab(E);
Tab L = Tab("hhh", "sss","f");
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->newTab(F);
Tab R = Tab("sss", "pp","r");
wind->closeTab();
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->isEmpty();
Tab C = Tab("a", "z","sss");
wind->newTab(C);
wind->newTab(G);
wind->print();
Tab S = Tab("yyy", "iii","p");
wind->closeTab();
wind->closeTab();
wind->moveActiveTabTo(2);
wind->print();
wind->closeTab();
wind->newTab(H);
wind->moveActiveTabTo(0);
wind->closeTab();
wind->newTab(I);
wind->newTab(K);
wind->closeTab();
wind->isEmpty();
wind->newTab(L);
wind->moveActiveTabTo(4);
wind->isEmpty();
Tab X = Tab("l", "u","b");
wind->print();
wind->getActiveTab();
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
Tab U = Tab("hhh", "a","eee");
wind->closeTab();
wind->print();
wind->print();
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->newTab(M);
Tab D = Tab("ss", "uuu","e");
wind->closeTab();
wind->newTab(D);
Tab J = Tab("tt", "b","zzz");
wind->newTab(J);
wind->print();
wind->print();
wind->getActiveTab();
Tab T = Tab("z", "w","fff");
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->closeTab();
wind->changeActiveTabTo(0);
wind->newTab(N);
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->print();
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(0);
wind->isEmpty();
wind->closeTab();
wind->print();
wind->newTab(O);
wind->newTab(P);
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(3);
wind->isEmpty();
delete wind;
}
	return 0;
}