#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->getActiveTab();
Tab F = Tab("t", "qqq","mmm");
wind->changeActiveTabTo(5);
Tab U = Tab("g", "eee","jj");
wind->getActiveTab();
Tab B = Tab("cc", "nnn","lll");
wind->newTab(B);
Tab E = Tab("hh", "zzz","y");
wind->moveActiveTabTo(2);
Tab V = Tab("a", "ff","l");
wind->print();
wind->isEmpty();
wind->print();
Tab W = Tab("vvv", "qq","lll");
wind->getActiveTab();
Tab A = Tab("yyy", "zzz","ddd");
wind->changeActiveTabTo(3);
Tab R = Tab("cc", "www","w");
wind->changeActiveTabTo(2);
Tab I = Tab("ppp", "hh","o");
wind->print();
Tab K = Tab("e", "o","u");
wind->isEmpty();
wind->isEmpty();
Tab N = Tab("pp", "bbb","xxx");
wind->closeTab();
Tab O = Tab("a", "lll","f");
wind->moveActiveTabTo(1);
wind->newTab(A);
wind->moveActiveTabTo(5);
Tab Q = Tab("aaa", "m","w");
wind->newTab(E);
wind->getActiveTab();
Tab G = Tab("sss", "x","nnn");
wind->isEmpty();
wind->newTab(F);
wind->print();
wind->getActiveTab();
wind->closeTab();
Tab J = Tab("ii", "ww","ppp");
wind->print();
Tab C = Tab("vvv", "u","uu");
wind->newTab(C);
wind->getActiveTab();
wind->newTab(G);
Tab P = Tab("kkk", "vvv","ggg");
wind->print();
wind->newTab(I);
Tab Y = Tab("ggg", "aa","iii");
wind->print();
wind->newTab(J);
wind->closeTab();
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(3);
Tab M = Tab("b", "uu","ccc");
wind->closeTab();
wind->isEmpty();
wind->newTab(K);
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->print();
wind->closeTab();
wind->newTab(M);
Tab X = Tab("yyy", "l","jjj");
wind->newTab(N);
wind->print();
wind->isEmpty();
Tab H = Tab("d", "cc","ppp");
wind->closeTab();
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(3);
wind->changeActiveTabTo(4);
Tab Z = Tab("tt", "c","m");
wind->moveActiveTabTo(5);
wind->newTab(H);
wind->print();
wind->closeTab();
wind->moveActiveTabTo(5);
wind->print();
wind->moveActiveTabTo(5);
Tab T = Tab("g", "l","vvv");
wind->print();
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(4);
wind->changeActiveTabTo(5);
wind->print();
wind->moveActiveTabTo(1);
wind->closeTab();
wind->newTab(O);
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(5);
wind->print();
wind->changeActiveTabTo(3);
wind->newTab(P);
wind->newTab(Q);
Tab L = Tab("ww", "s","ll");
wind->moveActiveTabTo(4);
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(1);
wind->moveActiveTabTo(3);
wind->print();
wind->newTab(L);
wind->print();
wind->changeActiveTabTo(4);
Tab D = Tab("u", "zzz","z");
wind->isEmpty();
wind->closeTab();
wind->getActiveTab();
wind->getActiveTab();
Tab S = Tab("bbb", "ee","ff");
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->getActiveTab();
wind->moveActiveTabTo(1);
wind->newTab(D);
wind->newTab(R);
wind->newTab(S);
delete wind;
}
	return 0;
}