#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->print();
Tab J = Tab("yyy", "g","xxx");
wind->print();
Tab I = Tab("oo", "nnn","ii");
wind->moveActiveTabTo(3);
Tab T = Tab("t", "e","w");
wind->changeActiveTabTo(0);
wind->closeTab();
wind->print();
Tab N = Tab("ff", "oo","ss");
wind->getActiveTab();
Tab K = Tab("z", "n","tt");
wind->print();
wind->print();
Tab H = Tab("ee", "uuu","fff");
wind->closeTab();
Tab Y = Tab("jjj", "tt","j");
wind->closeTab();
Tab F = Tab("c", "p","ttt");
wind->closeTab();
wind->getActiveTab();
Tab L = Tab("uuu", "i","bbb");
wind->print();
Tab A = Tab("zz", "v","xxx");
wind->newTab(A);
wind->isEmpty();
wind->newTab(F);
wind->newTab(H);
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->isEmpty();
Tab U = Tab("t", "u","zz");
wind->newTab(I);
Tab E = Tab("rr", "aa","jj");
wind->closeTab();
wind->isEmpty();
wind->print();
wind->changeActiveTabTo(0);
wind->getActiveTab();
Tab Z = Tab("www", "s","p");
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->newTab(E);
Tab S = Tab("vv", "t","ss");
wind->changeActiveTabTo(0);
Tab P = Tab("ll", "vvv","i");
wind->print();
Tab B = Tab("gg", "o","yyy");
wind->closeTab();
wind->getActiveTab();
Tab C = Tab("kk", "g","gg");
wind->print();
Tab O = Tab("d", "gg","g");
wind->isEmpty();
wind->print();
Tab M = Tab("ll", "rrr","www");
wind->moveActiveTabTo(3);
Tab G = Tab("q", "n","nn");
wind->print();
Tab R = Tab("mmm", "yyy","ggg");
wind->newTab(B);
wind->closeTab();
wind->changeActiveTabTo(5);
wind->isEmpty();
Tab D = Tab("z", "qq","yyy");
wind->print();
wind->newTab(C);
wind->closeTab();
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
Tab W = Tab("eee", "hhh","mmm");
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(3);
wind->isEmpty();
Tab V = Tab("ss", "ff","eee");
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(1);
wind->getActiveTab();
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
Tab X = Tab("f", "xx","qq");
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(0);
wind->isEmpty();
wind->print();
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(2);
wind->print();
wind->closeTab();
wind->newTab(D);
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->closeTab();
wind->isEmpty();
wind->closeTab();
wind->newTab(G);
wind->getActiveTab();
Tab Q = Tab("aa", "ee","ss");
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(J);
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->closeTab();
wind->print();
wind->closeTab();
wind->changeActiveTabTo(4);
wind->newTab(K);
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(3);
wind->getActiveTab();
wind->moveActiveTabTo(1);
wind->print();
wind->print();
delete wind;
}
	return 0;
}