#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->isEmpty();
Tab B = Tab("dd", "p","e");
wind->moveActiveTabTo(5);
Tab K = Tab("xx", "zzz","g");
wind->newTab(B);
Tab I = Tab("a", "hh","vv");
wind->getActiveTab();
Tab X = Tab("h", "jj","xx");
wind->closeTab();
wind->closeTab();
Tab O = Tab("kkk", "t","hh");
wind->closeTab();
Tab Y = Tab("r", "h","r");
wind->closeTab();
wind->getActiveTab();
Tab C = Tab("yyy", "uu","uuu");
wind->isEmpty();
Tab G = Tab("ff", "nn","q");
wind->changeActiveTabTo(1);
Tab D = Tab("qqq", "www","nn");
wind->moveActiveTabTo(0);
Tab Q = Tab("ee", "ppp","sss");
wind->getActiveTab();
Tab S = Tab("ss", "ttt","vv");
wind->moveActiveTabTo(2);
wind->getActiveTab();
Tab F = Tab("rr", "p","nnn");
wind->print();
wind->changeActiveTabTo(4);
Tab J = Tab("jjj", "ddd","lll");
wind->moveActiveTabTo(5);
Tab E = Tab("pp", "bbb","e");
wind->print();
wind->newTab(C);
Tab U = Tab("kk", "zzz","bb");
wind->changeActiveTabTo(0);
Tab N = Tab("ooo", "b","ttt");
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(1);
wind->newTab(D);
Tab V = Tab("z", "a","l");
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->moveActiveTabTo(5);
Tab A = Tab("hh", "qq","kk");
wind->closeTab();
wind->getActiveTab();
Tab M = Tab("b", "jj","k");
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(0);
wind->closeTab();
wind->closeTab();
wind->getActiveTab();
Tab H = Tab("j", "ooo","rrr");
wind->getActiveTab();
wind->changeActiveTabTo(0);
wind->newTab(A);
wind->changeActiveTabTo(0);
wind->print();
wind->isEmpty();
wind->newTab(E);
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(2);
Tab Z = Tab("xx", "uuu","ll");
wind->moveActiveTabTo(3);
wind->print();
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(2);
wind->print();
wind->closeTab();
Tab T = Tab("t", "j","e");
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
Tab W = Tab("c", "qq","yy");
wind->isEmpty();
Tab L = Tab("nnn", "jj","b");
wind->changeActiveTabTo(3);
wind->getActiveTab();
Tab R = Tab("r", "ggg","v");
wind->print();
wind->getActiveTab();
wind->newTab(F);
wind->newTab(G);
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->print();
wind->newTab(H);
wind->changeActiveTabTo(3);
wind->closeTab();
Tab P = Tab("jj", "qq","ccc");
wind->changeActiveTabTo(3);
wind->getActiveTab();
wind->print();
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->isEmpty();
wind->newTab(I);
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->changeActiveTabTo(5);
wind->newTab(J);
wind->newTab(K);
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(5);
wind->print();
wind->closeTab();
wind->print();
wind->changeActiveTabTo(1);
delete wind;
}
	return 0;
}