#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->isEmpty();
Tab Z = Tab("ll", "mmm","d");
wind->changeActiveTabTo(4);
Tab B = Tab("ttt", "ccc","u");
wind->closeTab();
wind->print();
Tab E = Tab("u", "o","r");
wind->moveActiveTabTo(4);
Tab H = Tab("ggg", "jjj","d");
wind->getActiveTab();
Tab V = Tab("bbb", "l","cc");
wind->moveActiveTabTo(4);
Tab U = Tab("s", "x","cc");
wind->print();
Tab M = Tab("fff", "ii","ggg");
wind->isEmpty();
Tab J = Tab("ooo", "fff","ggg");
wind->getActiveTab();
Tab O = Tab("ss", "cc","tt");
wind->closeTab();
Tab X = Tab("k", "qqq","mm");
wind->newTab(B);
wind->isEmpty();
Tab T = Tab("zzz", "ff","iii");
wind->newTab(E);
Tab P = Tab("kkk", "iii","x");
wind->isEmpty();
Tab Y = Tab("xxx", "yy","nn");
wind->changeActiveTabTo(0);
Tab Q = Tab("bbb", "dd","aaa");
wind->moveActiveTabTo(3);
wind->changeActiveTabTo(1);
Tab I = Tab("ee", "ff","ppp");
wind->getActiveTab();
Tab G = Tab("qq", "ttt","ww");
wind->closeTab();
Tab A = Tab("o", "ooo","nnn");
wind->print();
wind->isEmpty();
wind->newTab(A);
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(5);
Tab K = Tab("www", "hh","iii");
wind->isEmpty();
wind->getActiveTab();
Tab W = Tab("mm", "f","n");
wind->isEmpty();
Tab C = Tab("ll", "ccc","c");
wind->moveActiveTabTo(1);
Tab L = Tab("f", "aaa","n");
wind->isEmpty();
wind->newTab(C);
wind->getActiveTab();
Tab R = Tab("j", "yy","vvv");
wind->newTab(G);
Tab S = Tab("pp", "sss","ww");
wind->print();
wind->isEmpty();
wind->newTab(H);
wind->moveActiveTabTo(0);
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->isEmpty();
wind->changeActiveTabTo(4);
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->newTab(I);
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(5);
Tab N = Tab("ccc", "l","jj");
wind->changeActiveTabTo(2);
wind->moveActiveTabTo(4);
wind->changeActiveTabTo(5);
Tab F = Tab("b", "eee","yyy");
wind->isEmpty();
wind->closeTab();
wind->changeActiveTabTo(5);
wind->newTab(F);
wind->print();
wind->closeTab();
wind->isEmpty();
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(3);
wind->print();
wind->newTab(J);
wind->moveActiveTabTo(1);
wind->closeTab();
wind->closeTab();
wind->isEmpty();
wind->closeTab();
wind->moveActiveTabTo(2);
wind->print();
wind->moveActiveTabTo(4);
wind->newTab(K);
wind->moveActiveTabTo(5);
wind->newTab(L);
wind->getActiveTab();
wind->isEmpty();
wind->isEmpty();
Tab D = Tab("g", "p","ll");
wind->changeActiveTabTo(1);
wind->isEmpty();
wind->getActiveTab();
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->getActiveTab();
wind->print();
wind->closeTab();
wind->isEmpty();
wind->newTab(D);
wind->print();
wind->newTab(M);
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(3);
wind->getActiveTab();
wind->newTab(N);
wind->moveActiveTabTo(5);
wind->print();
wind->changeActiveTabTo(3);
wind->newTab(O);
wind->print();
wind->moveActiveTabTo(2);
delete wind;
}
	return 0;
}