#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->print();
Tab X = Tab("qq", "jj","c");
wind->newTab(X);
Tab R = Tab("aa", "iii","eee");
wind->print();
Tab B = Tab("o", "uu","eee");
wind->changeActiveTabTo(0);
Tab G = Tab("a", "fff","ddd");
wind->getActiveTab();
wind->print();
Tab M = Tab("aa", "y","ppp");
wind->moveActiveTabTo(1);
Tab Q = Tab("ddd", "iii","ww");
wind->isEmpty();
wind->changeActiveTabTo(4);
Tab N = Tab("d", "hhh","vv");
wind->print();
Tab C = Tab("ddd", "cc","kk");
wind->changeActiveTabTo(5);
Tab W = Tab("yy", "n","vvv");
wind->closeTab();
wind->changeActiveTabTo(0);
Tab K = Tab("o", "oo","eee");
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->closeTab();
Tab I = Tab("bbb", "zz","q");
wind->print();
Tab A = Tab("f", "sss","ee");
wind->isEmpty();
wind->moveActiveTabTo(2);
Tab Z = Tab("ttt", "nnn","f");
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(0);
Tab S = Tab("ss", "ff","hhh");
wind->getActiveTab();
Tab V = Tab("ggg", "o","vvv");
wind->getActiveTab();
wind->newTab(A);
wind->print();
wind->print();
Tab T = Tab("ooo", "ddd","y");
wind->closeTab();
Tab J = Tab("d", "oo","qq");
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(2);
Tab H = Tab("vv", "n","jjj");
wind->isEmpty();
wind->getActiveTab();
wind->closeTab();
Tab D = Tab("ii", "kkk","ttt");
wind->print();
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(4);
wind->changeActiveTabTo(4);
wind->print();
wind->changeActiveTabTo(3);
Tab P = Tab("bbb", "f","k");
wind->changeActiveTabTo(5);
wind->closeTab();
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(2);
wind->newTab(B);
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->print();
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(0);
wind->print();
wind->newTab(C);
wind->print();
wind->moveActiveTabTo(0);
wind->closeTab();
Tab O = Tab("ee", "ppp","nnn");
wind->print();
wind->closeTab();
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(1);
wind->closeTab();
wind->getActiveTab();
wind->getActiveTab();
wind->isEmpty();
wind->newTab(D);
wind->print();
wind->isEmpty();
wind->print();
wind->isEmpty();
Tab L = Tab("mm", "ii","a");
wind->newTab(G);
wind->moveActiveTabTo(0);
wind->newTab(H);
wind->getActiveTab();
wind->isEmpty();
wind->print();
wind->moveActiveTabTo(4);
wind->newTab(I);
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(4);
wind->closeTab();
Tab E = Tab("ll", "ccc","b");
wind->changeActiveTabTo(5);
wind->print();
wind->getActiveTab();
Tab U = Tab("nnn", "ee","aa");
wind->closeTab();
wind->isEmpty();
Tab F = Tab("ddd", "bbb","i");
wind->moveActiveTabTo(3);
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->moveActiveTabTo(3);
wind->moveActiveTabTo(1);
wind->newTab(E);
wind->print();
wind->getActiveTab();
Tab Y = Tab("fff", "vvv","t");
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(2);
wind->isEmpty();
delete wind;
}
	return 0;
}