#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->closeTab();
Tab B = Tab("ii", "lll","ppp");
wind->print();
Tab O = Tab("b", "pp","p");
wind->newTab(B);
Tab S = Tab("d", "eee","fff");
wind->isEmpty();
Tab C = Tab("s", "zzz","kk");
wind->closeTab();
Tab P = Tab("kkk", "p","m");
wind->getActiveTab();
Tab F = Tab("t", "ll","jjj");
wind->changeActiveTabTo(3);
Tab T = Tab("kk", "b","gg");
wind->moveActiveTabTo(5);
Tab W = Tab("qq", "y","yy");
wind->closeTab();
Tab J = Tab("ii", "yyy","hh");
wind->closeTab();
wind->newTab(C);
Tab E = Tab("c", "jjj","i");
wind->closeTab();
wind->closeTab();
Tab Y = Tab("l", "o","k");
wind->getActiveTab();
wind->print();
Tab A = Tab("r", "zzz","qq");
wind->isEmpty();
Tab V = Tab("n", "y","l");
wind->closeTab();
wind->newTab(A);
Tab I = Tab("xx", "tt","bb");
wind->changeActiveTabTo(1);
wind->print();
Tab R = Tab("h", "u","rrr");
wind->print();
wind->changeActiveTabTo(5);
Tab D = Tab("r", "uuu","sss");
wind->print();
wind->moveActiveTabTo(2);
wind->newTab(D);
wind->changeActiveTabTo(4);
Tab K = Tab("ggg", "oo","bbb");
wind->closeTab();
Tab U = Tab("hhh", "e","ii");
wind->newTab(E);
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(5);
Tab H = Tab("a", "qq","ttt");
wind->print();
wind->moveActiveTabTo(4);
Tab L = Tab("oo", "ttt","uu");
wind->moveActiveTabTo(1);
wind->print();
wind->closeTab();
wind->newTab(F);
Tab Q = Tab("cc", "a","eee");
wind->getActiveTab();
wind->closeTab();
wind->newTab(H);
Tab M = Tab("nn", "iii","nnn");
wind->newTab(I);
wind->closeTab();
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->print();
wind->changeActiveTabTo(5);
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
Tab Z = Tab("www", "f","nn");
wind->getActiveTab();
wind->moveActiveTabTo(2);
wind->print();
wind->closeTab();
wind->changeActiveTabTo(0);
wind->print();
wind->getActiveTab();
wind->isEmpty();
wind->closeTab();
Tab G = Tab("fff", "ooo","h");
wind->print();
wind->getActiveTab();
wind->isEmpty();
wind->closeTab();
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->isEmpty();
wind->newTab(G);
wind->closeTab();
wind->closeTab();
Tab X = Tab("sss", "u","a");
wind->newTab(J);
wind->changeActiveTabTo(3);
wind->getActiveTab();
wind->getActiveTab();
wind->isEmpty();
wind->closeTab();
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(K);
wind->print();
wind->closeTab();
wind->newTab(L);
wind->moveActiveTabTo(2);
wind->newTab(M);
wind->changeActiveTabTo(4);
wind->changeActiveTabTo(4);
wind->print();
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(4);
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->closeTab();
wind->print();
wind->print();
wind->isEmpty();
wind->closeTab();
wind->closeTab();
wind->isEmpty();
wind->moveActiveTabTo(0);
delete wind;
}
	return 0;
}