#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->closeTab();
Tab P = Tab("z", "c","u");
wind->getActiveTab();
Tab C = Tab("ee", "ggg","tt");
wind->moveActiveTabTo(5);
Tab V = Tab("j", "jj","ll");
wind->closeTab();
Tab G = Tab("d", "kk","jjj");
wind->print();
Tab R = Tab("x", "rrr","nn");
wind->print();
wind->print();
Tab J = Tab("nnn", "vvv","p");
wind->closeTab();
Tab D = Tab("k", "ooo","f");
wind->getActiveTab();
Tab N = Tab("ccc", "k","c");
wind->changeActiveTabTo(5);
Tab Y = Tab("u", "hhh","cc");
wind->moveActiveTabTo(2);
Tab I = Tab("oo", "hh","ff");
wind->moveActiveTabTo(5);
Tab W = Tab("y", "gg","rr");
wind->getActiveTab();
Tab Q = Tab("oo", "c","e");
wind->print();
Tab M = Tab("oo", "s","ccc");
wind->newTab(C);
Tab L = Tab("zz", "dd","b");
wind->isEmpty();
Tab T = Tab("u", "jj","ff");
wind->changeActiveTabTo(0);
wind->newTab(D);
wind->print();
Tab A = Tab("mmm", "m","ll");
wind->moveActiveTabTo(5);
Tab U = Tab("x", "m","w");
wind->newTab(A);
Tab H = Tab("zzz", "f","ii");
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->changeActiveTabTo(5);
Tab O = Tab("nnn", "ttt","vvv");
wind->newTab(G);
Tab X = Tab("zzz", "q","oo");
wind->print();
wind->isEmpty();
Tab E = Tab("kkk", "aa","h");
wind->changeActiveTabTo(2);
Tab F = Tab("h", "w","jjj");
wind->closeTab();
wind->isEmpty();
wind->moveActiveTabTo(4);
Tab K = Tab("uuu", "i","aa");
wind->getActiveTab();
wind->closeTab();
wind->newTab(E);
wind->getActiveTab();
wind->isEmpty();
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->getActiveTab();
wind->isEmpty();
wind->print();
Tab Z = Tab("mmm", "n","y");
wind->isEmpty();
wind->closeTab();
wind->print();
Tab S = Tab("c", "sss","t");
wind->moveActiveTabTo(1);
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->newTab(F);
wind->newTab(H);
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(4);
wind->print();
wind->moveActiveTabTo(1);
Tab B = Tab("yyy", "pp","yy");
wind->isEmpty();
wind->closeTab();
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->closeTab();
wind->newTab(B);
wind->moveActiveTabTo(3);
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(5);
wind->isEmpty();
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->closeTab();
wind->changeActiveTabTo(4);
wind->changeActiveTabTo(5);
wind->newTab(I);
wind->closeTab();
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(2);
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(2);
wind->getActiveTab();
wind->changeActiveTabTo(5);
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->newTab(J);
wind->print();
wind->closeTab();
wind->print();
wind->print();
wind->closeTab();
wind->print();
wind->getActiveTab();
wind->newTab(K);
wind->newTab(L);
wind->changeActiveTabTo(3);
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(3);
delete wind;
}
	return 0;
}