#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->isEmpty();
Tab I = Tab("k", "hhh","a");
wind->getActiveTab();
Tab G = Tab("h", "lll","cc");
wind->closeTab();
Tab B = Tab("mmm", "dd","rrr");
wind->moveActiveTabTo(5);
Tab U = Tab("xxx", "ddd","z");
wind->changeActiveTabTo(1);
Tab N = Tab("ee", "aaa","bb");
wind->newTab(B);
Tab T = Tab("jj", "xxx","jjj");
wind->closeTab();
Tab M = Tab("w", "y","jj");
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(0);
wind->isEmpty();
Tab A = Tab("xxx", "fff","f");
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->getActiveTab();
Tab P = Tab("c", "ww","ss");
wind->closeTab();
Tab X = Tab("d", "j","iii");
wind->changeActiveTabTo(3);
Tab S = Tab("qq", "ff","ddd");
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
Tab Z = Tab("cc", "vv","w");
wind->print();
Tab J = Tab("eee", "zz","n");
wind->changeActiveTabTo(2);
Tab V = Tab("yy", "aa","m");
wind->moveActiveTabTo(3);
wind->newTab(A);
wind->newTab(G);
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(0);
Tab L = Tab("nn", "x","ff");
wind->moveActiveTabTo(3);
wind->closeTab();
Tab D = Tab("hhh", "l","mmm");
wind->closeTab();
wind->closeTab();
wind->newTab(D);
wind->closeTab();
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
wind->newTab(I);
Tab C = Tab("w", "w","s");
wind->newTab(C);
Tab O = Tab("gg", "ttt","ttt");
wind->getActiveTab();
Tab H = Tab("aaa", "uuu","vvv");
wind->newTab(H);
wind->getActiveTab();
wind->newTab(J);
wind->isEmpty();
Tab E = Tab("z", "ll","i");
wind->print();
wind->changeActiveTabTo(3);
wind->closeTab();
Tab Q = Tab("bb", "ccc","ppp");
wind->isEmpty();
Tab F = Tab("zzz", "ddd","e");
wind->moveActiveTabTo(3);
wind->getActiveTab();
wind->getActiveTab();
wind->print();
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->print();
wind->moveActiveTabTo(0);
wind->getActiveTab();
Tab K = Tab("x", "r","ooo");
wind->newTab(E);
wind->changeActiveTabTo(3);
Tab Y = Tab("gg", "r","i");
wind->moveActiveTabTo(3);
wind->moveActiveTabTo(1);
wind->print();
Tab W = Tab("qqq", "f","rr");
wind->changeActiveTabTo(0);
wind->newTab(F);
wind->closeTab();
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
wind->newTab(K);
wind->moveActiveTabTo(0);
wind->closeTab();
wind->print();
wind->newTab(L);
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(3);
wind->newTab(M);
wind->newTab(N);
wind->getActiveTab();
wind->changeActiveTabTo(4);
wind->closeTab();
wind->print();
wind->changeActiveTabTo(1);
wind->newTab(O);
wind->newTab(P);
wind->newTab(Q);
wind->isEmpty();
wind->closeTab();
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->print();
wind->isEmpty();
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(2);
wind->isEmpty();
delete wind;
}
	return 0;
}