#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->isEmpty();
Tab Z = Tab("w", "cc","lll");
wind->getActiveTab();
Tab G = Tab("ii", "aa","h");
wind->closeTab();
Tab W = Tab("hhh", "c","yy");
wind->moveActiveTabTo(4);
Tab F = Tab("s", "qqq","ggg");
wind->moveActiveTabTo(5);
Tab L = Tab("ooo", "o","dd");
wind->newTab(F);
Tab A = Tab("z", "f","d");
wind->print();
Tab R = Tab("tt", "u","xxx");
wind->changeActiveTabTo(0);
Tab C = Tab("kk", "rrr","z");
wind->getActiveTab();
Tab S = Tab("dd", "zz","b");
wind->closeTab();
Tab N = Tab("ccc", "yy","t");
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->getActiveTab();
wind->isEmpty();
Tab K = Tab("b", "ppp","ww");
wind->moveActiveTabTo(4);
Tab Q = Tab("l", "ii","jjj");
wind->getActiveTab();
wind->getActiveTab();
Tab P = Tab("zz", "q","e");
wind->getActiveTab();
wind->isEmpty();
wind->print();
Tab J = Tab("hhh", "zzz","r");
wind->isEmpty();
Tab U = Tab("ppp", "x","w");
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(1);
Tab T = Tab("ddd", "rrr","i");
wind->isEmpty();
wind->getActiveTab();
Tab B = Tab("s", "k","kk");
wind->isEmpty();
Tab V = Tab("u", "f","u");
wind->getActiveTab();
Tab E = Tab("n", "jj","c");
wind->isEmpty();
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->closeTab();
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->closeTab();
wind->moveActiveTabTo(0);
wind->newTab(A);
wind->closeTab();
wind->closeTab();
wind->getActiveTab();
wind->print();
Tab I = Tab("i", "nn","mm");
wind->print();
wind->getActiveTab();
Tab Y = Tab("ss", "mmm","xx");
wind->newTab(B);
wind->moveActiveTabTo(0);
wind->closeTab();
wind->newTab(C);
Tab M = Tab("vv", "uuu","c");
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->isEmpty();
Tab D = Tab("xx", "kk","n");
wind->newTab(D);
wind->isEmpty();
wind->newTab(E);
wind->isEmpty();
wind->newTab(G);
wind->print();
wind->print();
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->print();
wind->newTab(I);
wind->moveActiveTabTo(5);
wind->closeTab();
wind->moveActiveTabTo(1);
wind->print();
Tab O = Tab("yy", "x","xx");
wind->print();
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(5);
wind->closeTab();
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
wind->newTab(J);
wind->closeTab();
wind->newTab(K);
wind->moveActiveTabTo(4);
wind->changeActiveTabTo(5);
wind->getActiveTab();
wind->newTab(L);
wind->newTab(M);
wind->newTab(N);
wind->closeTab();
wind->newTab(O);
wind->moveActiveTabTo(2);
wind->closeTab();
wind->print();
wind->getActiveTab();
wind->print();
Tab X = Tab("vvv", "yy","pp");
wind->closeTab();
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(1);
wind->newTab(P);
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(0);
wind->print();
wind->changeActiveTabTo(5);
delete wind;
}
	return 0;
}