#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->isEmpty();
Tab T = Tab("ff", "m","oo");
wind->closeTab();
Tab R = Tab("c", "w","x");
wind->newTab(R);
Tab U = Tab("x", "bbb","rr");
wind->print();
Tab G = Tab("ooo", "kk","dd");
wind->print();
Tab Y = Tab("v", "f","cc");
wind->getActiveTab();
Tab X = Tab("pp", "t","ooo");
wind->newTab(G);
Tab B = Tab("ppp", "sss","hhh");
wind->changeActiveTabTo(5);
Tab H = Tab("ooo", "mmm","tt");
wind->print();
wind->newTab(B);
Tab D = Tab("hh", "w","uuu");
wind->moveActiveTabTo(0);
Tab K = Tab("zz", "kkk","uuu");
wind->getActiveTab();
Tab V = Tab("yy", "aaa","ppp");
wind->changeActiveTabTo(4);
wind->changeActiveTabTo(4);
wind->closeTab();
Tab E = Tab("ll", "ddd","l");
wind->getActiveTab();
wind->print();
wind->isEmpty();
Tab A = Tab("qqq", "nn","mm");
wind->moveActiveTabTo(4);
Tab W = Tab("ggg", "vvv","o");
wind->changeActiveTabTo(0);
Tab J = Tab("x", "e","uuu");
wind->moveActiveTabTo(4);
wind->isEmpty();
Tab P = Tab("i", "zzz","m");
wind->closeTab();
wind->print();
wind->newTab(A);
Tab L = Tab("iii", "aa","oo");
wind->isEmpty();
wind->moveActiveTabTo(2);
Tab F = Tab("xx", "z","vv");
wind->moveActiveTabTo(1);
Tab Z = Tab("h", "kkk","u");
wind->closeTab();
wind->isEmpty();
wind->closeTab();
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->closeTab();
wind->newTab(D);
Tab I = Tab("j", "u","lll");
wind->closeTab();
wind->moveActiveTabTo(3);
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(5);
Tab C = Tab("n", "ppp","zzz");
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(5);
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->closeTab();
wind->moveActiveTabTo(2);
wind->isEmpty();
Tab S = Tab("ll", "ee","yyy");
wind->moveActiveTabTo(0);
wind->closeTab();
wind->getActiveTab();
wind->newTab(C);
Tab O = Tab("ggg", "nnn","v");
wind->getActiveTab();
wind->closeTab();
wind->moveActiveTabTo(4);
wind->newTab(E);
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
wind->newTab(F);
wind->changeActiveTabTo(5);
Tab Q = Tab("n", "ttt","ggg");
wind->isEmpty();
wind->isEmpty();
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(2);
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
wind->newTab(H);
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->newTab(I);
wind->isEmpty();
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->print();
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->closeTab();
wind->getActiveTab();
wind->newTab(J);
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(1);
wind->newTab(K);
wind->closeTab();
Tab M = Tab("l", "oo","vvv");
wind->print();
wind->newTab(L);
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->getActiveTab();
wind->isEmpty();
Tab N = Tab("yyy", "yyy","kk");
wind->isEmpty();
wind->isEmpty();
wind->print();
delete wind;
}
	return 0;
}