#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->changeActiveTabTo(3);
Tab C = Tab("vv", "yy","eee");
wind->closeTab();
Tab N = Tab("xxx", "xxx","hh");
wind->print();
Tab D = Tab("u", "yyy","ff");
wind->moveActiveTabTo(1);
Tab G = Tab("xxx", "t","dd");
wind->isEmpty();
Tab M = Tab("f", "qqq","xxx");
wind->isEmpty();
Tab R = Tab("h", "g","aaa");
wind->print();
Tab Y = Tab("jjj", "oo","uu");
wind->newTab(C);
wind->moveActiveTabTo(1);
wind->getActiveTab();
Tab V = Tab("dd", "a","sss");
wind->newTab(D);
wind->newTab(G);
Tab B = Tab("pp", "z","hh");
wind->getActiveTab();
Tab P = Tab("y", "rr","vvv");
wind->changeActiveTabTo(5);
Tab F = Tab("r", "r","p");
wind->newTab(B);
Tab U = Tab("ttt", "t","l");
wind->print();
wind->isEmpty();
wind->newTab(F);
Tab O = Tab("hhh", "oo","nn");
wind->isEmpty();
wind->closeTab();
wind->newTab(M);
wind->newTab(N);
wind->isEmpty();
Tab E = Tab("ii", "hhh","o");
wind->isEmpty();
Tab J = Tab("v", "l","rrr");
wind->moveActiveTabTo(3);
Tab H = Tab("tt", "jjj","qqq");
wind->changeActiveTabTo(4);
wind->print();
Tab T = Tab("k", "mmm","aaa");
wind->moveActiveTabTo(2);
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
Tab Q = Tab("s", "rr","ccc");
wind->isEmpty();
wind->getActiveTab();
Tab A = Tab("c", "i","k");
wind->isEmpty();
Tab X = Tab("qqq", "aaa","vvv");
wind->newTab(A);
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(0);
wind->print();
Tab S = Tab("mmm", "tt","ww");
wind->changeActiveTabTo(4);
wind->print();
wind->getActiveTab();
Tab Z = Tab("o", "l","o");
wind->print();
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->getActiveTab();
wind->isEmpty();
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->getActiveTab();
Tab K = Tab("sss", "nn","uu");
wind->newTab(E);
wind->isEmpty();
wind->closeTab();
Tab L = Tab("qq", "cc","nn");
wind->moveActiveTabTo(0);
wind->isEmpty();
wind->newTab(H);
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->newTab(J);
wind->closeTab();
wind->newTab(K);
wind->closeTab();
wind->isEmpty();
Tab I = Tab("v", "ll","o");
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->print();
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(4);
wind->getActiveTab();
wind->changeActiveTabTo(0);
wind->newTab(I);
wind->getActiveTab();
wind->isEmpty();
wind->newTab(L);
wind->isEmpty();
wind->newTab(O);
wind->print();
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(2);
Tab W = Tab("eee", "aa","jj");
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
wind->newTab(P);
wind->closeTab();
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->print();
delete wind;
}
	return 0;
}