#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->closeTab();
Tab Q = Tab("r", "mmm","f");
wind->getActiveTab();
Tab C = Tab("zzz", "fff","bb");
wind->isEmpty();
Tab R = Tab("rr", "j","t");
wind->changeActiveTabTo(5);
Tab H = Tab("nnn", "n","jjj");
wind->changeActiveTabTo(1);
Tab O = Tab("kk", "c","ggg");
wind->closeTab();
Tab F = Tab("q", "m","mmm");
wind->getActiveTab();
Tab A = Tab("m", "q","w");
wind->print();
Tab X = Tab("vv", "jj","rr");
wind->isEmpty();
wind->isEmpty();
Tab E = Tab("jj", "lll","f");
wind->changeActiveTabTo(4);
Tab D = Tab("y", "jj","q");
wind->closeTab();
Tab G = Tab("tt", "n","v");
wind->moveActiveTabTo(1);
Tab M = Tab("p", "jj","yy");
wind->closeTab();
wind->moveActiveTabTo(5);
Tab U = Tab("uuu", "sss","mm");
wind->isEmpty();
Tab I = Tab("jjj", "a","iii");
wind->closeTab();
wind->moveActiveTabTo(0);
Tab J = Tab("u", "ee","ll");
wind->isEmpty();
wind->newTab(A);
Tab T = Tab("vv", "f","n");
wind->changeActiveTabTo(0);
Tab N = Tab("fff", "q","hhh");
wind->closeTab();
wind->isEmpty();
wind->newTab(C);
Tab S = Tab("ww", "vvv","cc");
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->moveActiveTabTo(0);
Tab Z = Tab("x", "g","o");
wind->print();
wind->print();
Tab L = Tab("xxx", "s","qqq");
wind->isEmpty();
wind->print();
wind->closeTab();
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(0);
Tab K = Tab("ooo", "qq","aaa");
wind->closeTab();
wind->print();
wind->newTab(D);
Tab V = Tab("yyy", "p","gg");
wind->changeActiveTabTo(2);
wind->newTab(E);
wind->closeTab();
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(3);
wind->print();
wind->print();
Tab B = Tab("g", "mmm","tt");
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(0);
Tab W = Tab("b", "h","pp");
wind->getActiveTab();
wind->moveActiveTabTo(2);
wind->closeTab();
wind->getActiveTab();
Tab P = Tab("g", "z","pp");
wind->getActiveTab();
wind->moveActiveTabTo(3);
Tab Y = Tab("gg", "j","n");
wind->closeTab();
wind->closeTab();
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(3);
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(3);
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(B);
wind->getActiveTab();
wind->isEmpty();
wind->newTab(F);
wind->closeTab();
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(3);
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(4);
wind->print();
wind->print();
wind->newTab(G);
wind->closeTab();
wind->print();
wind->print();
wind->newTab(H);
wind->isEmpty();
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->newTab(I);
wind->print();
wind->getActiveTab();
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
wind->changeActiveTabTo(1);
wind->isEmpty();
delete wind;
}
	return 0;
}