#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->moveActiveTabTo(1);
Tab E = Tab("nnn", "r","sss");
wind->getActiveTab();
Tab K = Tab("a", "zz","xx");
wind->changeActiveTabTo(3);
Tab D = Tab("aaa", "hhh","d");
wind->getActiveTab();
Tab Q = Tab("nn", "qq","oo");
wind->getActiveTab();
Tab T = Tab("a", "vvv","ggg");
wind->isEmpty();
Tab Z = Tab("dd", "gg","yy");
wind->isEmpty();
Tab U = Tab("hhh", "dd","q");
wind->closeTab();
Tab L = Tab("m", "bb","iii");
wind->changeActiveTabTo(0);
wind->newTab(D);
Tab P = Tab("dd", "dd","fff");
wind->getActiveTab();
Tab A = Tab("e", "nnn","e");
wind->moveActiveTabTo(0);
wind->isEmpty();
Tab O = Tab("aaa", "uuu","d");
wind->newTab(A);
wind->print();
wind->changeActiveTabTo(4);
Tab S = Tab("uu", "nnn","kk");
wind->changeActiveTabTo(4);
Tab V = Tab("vv", "kk","mmm");
wind->closeTab();
wind->newTab(E);
wind->moveActiveTabTo(0);
Tab G = Tab("u", "pp","z");
wind->isEmpty();
wind->changeActiveTabTo(0);
Tab W = Tab("c", "eee","qqq");
wind->getActiveTab();
wind->isEmpty();
Tab X = Tab("ttt", "ooo","f");
wind->newTab(G);
Tab N = Tab("dd", "bb","p");
wind->isEmpty();
wind->print();
wind->closeTab();
wind->closeTab();
Tab M = Tab("b", "oo","ss");
wind->getActiveTab();
Tab R = Tab("ff", "uuu","c");
wind->newTab(K);
wind->newTab(L);
wind->newTab(M);
wind->print();
Tab J = Tab("qq", "ee","r");
wind->newTab(J);
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(1);
wind->newTab(N);
wind->print();
wind->newTab(O);
wind->newTab(P);
wind->getActiveTab();
wind->moveActiveTabTo(2);
Tab F = Tab("t", "mm","zz");
wind->print();
wind->getActiveTab();
wind->print();
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(0);
Tab C = Tab("www", "dd","r");
wind->closeTab();
wind->closeTab();
wind->newTab(C);
wind->changeActiveTabTo(5);
wind->print();
wind->newTab(F);
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->closeTab();
wind->getActiveTab();
wind->moveActiveTabTo(2);
Tab B = Tab("ss", "lll","ii");
wind->closeTab();
wind->closeTab();
wind->isEmpty();
wind->moveActiveTabTo(4);
wind->isEmpty();
wind->newTab(B);
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->getActiveTab();
wind->newTab(Q);
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->isEmpty();
wind->newTab(R);
wind->closeTab();
Tab H = Tab("ll", "r","uu");
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(1);
wind->newTab(H);
Tab Y = Tab("uuu", "ddd","ee");
wind->moveActiveTabTo(4);
wind->closeTab();
wind->closeTab();
wind->isEmpty();
wind->print();
wind->print();
wind->closeTab();
Tab I = Tab("ppp", "ii","www");
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(4);
wind->getActiveTab();
wind->closeTab();
wind->closeTab();
wind->closeTab();
wind->moveActiveTabTo(5);
wind->print();
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
wind->closeTab();
wind->getActiveTab();
delete wind;
}
	return 0;
}