#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->isEmpty();
Tab V = Tab("xxx", "ii","rrr");
wind->print();
wind->changeActiveTabTo(2);
Tab M = Tab("yy", "hh","qqq");
wind->moveActiveTabTo(4);
Tab G = Tab("m", "nnn","h");
wind->closeTab();
Tab P = Tab("ff", "q","ttt");
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(3);
Tab C = Tab("nnn", "t","jj");
wind->getActiveTab();
Tab F = Tab("ooo", "ggg","zzz");
wind->print();
wind->print();
Tab O = Tab("sss", "bb","b");
wind->getActiveTab();
Tab Q = Tab("f", "hh","xx");
wind->getActiveTab();
wind->closeTab();
Tab Z = Tab("uuu", "aa","pp");
wind->isEmpty();
Tab L = Tab("j", "jjj","rr");
wind->print();
Tab T = Tab("w", "oo","c");
wind->closeTab();
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->closeTab();
wind->changeActiveTabTo(3);
wind->isEmpty();
Tab I = Tab("r", "xxx","g");
wind->closeTab();
Tab X = Tab("xx", "jjj","ddd");
wind->closeTab();
wind->moveActiveTabTo(2);
wind->moveActiveTabTo(1);
wind->getActiveTab();
wind->moveActiveTabTo(1);
Tab S = Tab("tt", "pp","l");
wind->isEmpty();
wind->moveActiveTabTo(0);
Tab W = Tab("yy", "zzz","eee");
wind->print();
Tab R = Tab("ss", "zz","ww");
wind->isEmpty();
wind->getActiveTab();
wind->changeActiveTabTo(2);
Tab E = Tab("o", "w","a");
wind->changeActiveTabTo(4);
Tab D = Tab("e", "hhh","w");
wind->isEmpty();
wind->changeActiveTabTo(2);
wind->closeTab();
wind->changeActiveTabTo(5);
wind->newTab(C);
wind->closeTab();
wind->moveActiveTabTo(3);
wind->getActiveTab();
Tab A = Tab("n", "rrr","ff");
wind->print();
Tab J = Tab("bb", "oo","z");
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(2);
wind->print();
Tab U = Tab("a", "pp","eee");
wind->print();
wind->isEmpty();
Tab B = Tab("w", "gg","tt");
wind->closeTab();
wind->newTab(A);
wind->closeTab();
wind->closeTab();
wind->newTab(B);
wind->isEmpty();
Tab K = Tab("e", "ooo","zz");
wind->print();
Tab N = Tab("rr", "f","m");
wind->getActiveTab();
wind->newTab(D);
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(4);
wind->newTab(E);
wind->newTab(F);
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->closeTab();
wind->moveActiveTabTo(0);
wind->print();
wind->isEmpty();
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(1);
wind->newTab(G);
wind->changeActiveTabTo(4);
wind->newTab(I);
wind->isEmpty();
wind->closeTab();
wind->print();
wind->getActiveTab();
wind->print();
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->print();
wind->print();
Tab Y = Tab("ddd", "kkk","iii");
wind->changeActiveTabTo(2);
wind->newTab(J);
wind->isEmpty();
wind->getActiveTab();
wind->newTab(K);
wind->closeTab();
wind->print();
wind->print();
wind->moveActiveTabTo(1);
wind->newTab(L);
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(4);
wind->changeActiveTabTo(5);
wind->newTab(M);
wind->getActiveTab();
delete wind;
}
	return 0;
}