#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->getActiveTab();
Tab B = Tab("ll", "b","cc");
wind->print();
Tab Z = Tab("h", "t","ii");
wind->newTab(B);
Tab A = Tab("bb", "jjj","j");
wind->isEmpty();
Tab D = Tab("m", "bbb","ll");
wind->print();
Tab M = Tab("a", "l","qqq");
wind->isEmpty();
Tab H = Tab("ddd", "xx","aaa");
wind->getActiveTab();
Tab I = Tab("yy", "hh","p");
wind->changeActiveTabTo(5);
Tab P = Tab("k", "uuu","hh");
wind->newTab(A);
Tab S = Tab("nn", "hh","e");
wind->isEmpty();
Tab O = Tab("aaa", "kk","ttt");
wind->changeActiveTabTo(2);
wind->moveActiveTabTo(1);
Tab L = Tab("v", "bbb","www");
wind->closeTab();
Tab G = Tab("mmm", "www","ddd");
wind->moveActiveTabTo(3);
Tab V = Tab("oo", "xx","iii");
wind->closeTab();
Tab J = Tab("e", "yyy","d");
wind->print();
wind->newTab(D);
wind->changeActiveTabTo(5);
wind->print();
wind->getActiveTab();
Tab R = Tab("rrr", "j","ddd");
wind->moveActiveTabTo(2);
Tab K = Tab("a", "vvv","h");
wind->changeActiveTabTo(2);
Tab C = Tab("ppp", "f","c");
wind->closeTab();
wind->print();
wind->closeTab();
Tab X = Tab("n", "www","www");
wind->getActiveTab();
Tab Q = Tab("bbb", "qq","zz");
wind->isEmpty();
Tab W = Tab("c", "iii","nnn");
wind->print();
wind->closeTab();
Tab T = Tab("mmm", "dd","iii");
wind->closeTab();
Tab F = Tab("yyy", "vvv","uuu");
wind->newTab(C);
wind->getActiveTab();
wind->print();
Tab U = Tab("ss", "n","m");
wind->print();
wind->isEmpty();
wind->newTab(F);
wind->closeTab();
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(2);
wind->closeTab();
wind->newTab(G);
wind->changeActiveTabTo(1);
wind->newTab(H);
wind->getActiveTab();
Tab N = Tab("cc", "yyy","zz");
wind->print();
wind->closeTab();
wind->newTab(I);
wind->isEmpty();
wind->getActiveTab();
wind->newTab(J);
wind->closeTab();
wind->moveActiveTabTo(5);
wind->closeTab();
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(1);
Tab E = Tab("ee", "u","rrr");
wind->print();
wind->closeTab();
Tab Y = Tab("x", "hh","p");
wind->isEmpty();
wind->isEmpty();
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->newTab(E);
wind->closeTab();
wind->getActiveTab();
wind->isEmpty();
wind->newTab(K);
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->closeTab();
wind->changeActiveTabTo(4);
wind->newTab(L);
wind->moveActiveTabTo(4);
wind->newTab(M);
wind->closeTab();
wind->closeTab();
wind->changeActiveTabTo(3);
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->print();
wind->isEmpty();
wind->newTab(N);
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->getActiveTab();
wind->print();
wind->getActiveTab();
wind->print();
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
delete wind;
}
	return 0;
}