#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->getActiveTab();
Tab Z = Tab("aa", "ss","aa");
wind->newTab(Z);
Tab U = Tab("x", "yy","rrr");
wind->print();
Tab R = Tab("k", "ee","hhh");
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(2);
Tab I = Tab("r", "iii","www");
wind->changeActiveTabTo(1);
wind->isEmpty();
wind->print();
Tab J = Tab("eee", "pp","zz");
wind->moveActiveTabTo(4);
Tab A = Tab("ww", "mm","pp");
wind->closeTab();
Tab N = Tab("l", "cc","oo");
wind->isEmpty();
Tab X = Tab("q", "s","dd");
wind->newTab(A);
Tab L = Tab("ccc", "m","i");
wind->getActiveTab();
Tab K = Tab("h", "iii","z");
wind->moveActiveTabTo(0);
Tab B = Tab("hh", "n","ss");
wind->newTab(B);
wind->changeActiveTabTo(5);
Tab T = Tab("hhh", "e","ddd");
wind->getActiveTab();
Tab V = Tab("ff", "d","m");
wind->isEmpty();
wind->changeActiveTabTo(1);
Tab G = Tab("u", "gg","zz");
wind->changeActiveTabTo(3);
Tab D = Tab("uu", "ppp","a");
wind->getActiveTab();
wind->moveActiveTabTo(1);
wind->print();
wind->isEmpty();
Tab Y = Tab("ppp", "zz","kkk");
wind->isEmpty();
Tab Q = Tab("aaa", "jjj","b");
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->changeActiveTabTo(0);
wind->newTab(D);
wind->isEmpty();
wind->print();
wind->moveActiveTabTo(3);
wind->moveActiveTabTo(2);
Tab H = Tab("c", "mmm","l");
wind->getActiveTab();
Tab W = Tab("yy", "ff","i");
wind->closeTab();
wind->moveActiveTabTo(4);
wind->closeTab();
wind->newTab(G);
wind->closeTab();
wind->newTab(H);
wind->getActiveTab();
wind->closeTab();
wind->moveActiveTabTo(3);
Tab P = Tab("q", "iii","v");
wind->closeTab();
Tab F = Tab("yy", "ww","ooo");
wind->newTab(F);
wind->closeTab();
wind->closeTab();
wind->print();
wind->print();
wind->newTab(I);
wind->closeTab();
wind->changeActiveTabTo(5);
Tab S = Tab("qqq", "ttt","rr");
wind->print();
wind->closeTab();
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(4);
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(3);
Tab M = Tab("t", "vvv","sss");
wind->print();
wind->print();
wind->newTab(J);
wind->closeTab();
Tab O = Tab("hhh", "qq","iii");
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->getActiveTab();
wind->print();
wind->print();
wind->closeTab();
wind->newTab(K);
wind->getActiveTab();
wind->newTab(L);
wind->getActiveTab();
Tab E = Tab("n", "aa","e");
wind->closeTab();
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->newTab(E);
wind->changeActiveTabTo(3);
wind->closeTab();
wind->changeActiveTabTo(2);
Tab C = Tab("aa", "cc","h");
wind->newTab(C);
wind->print();
wind->newTab(M);
wind->isEmpty();
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
wind->print();
wind->changeActiveTabTo(5);
wind->closeTab();
wind->closeTab();
wind->moveActiveTabTo(4);
wind->newTab(N);
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(O);
delete wind;
}
	return 0;
}