#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
Tab J = Tab("hh", "k","sss");
wind->getActiveTab();
Tab M = Tab("tt", "s","uu");
wind->moveActiveTabTo(0);
Tab Z = Tab("cc", "ff","bb");
wind->moveActiveTabTo(3);
Tab X = Tab("aaa", "cc","mmm");
wind->changeActiveTabTo(3);
Tab W = Tab("e", "jjj","f");
wind->closeTab();
Tab Y = Tab("yyy", "rr","jjj");
wind->getActiveTab();
Tab U = Tab("ttt", "ii","v");
wind->changeActiveTabTo(4);
Tab K = Tab("hhh", "j","g");
wind->isEmpty();
wind->isEmpty();
Tab E = Tab("d", "tt","a");
wind->newTab(E);
Tab P = Tab("ii", "x","vv");
wind->moveActiveTabTo(2);
Tab R = Tab("d", "gg","ii");
wind->changeActiveTabTo(1);
Tab F = Tab("w", "n","qqq");
wind->changeActiveTabTo(2);
Tab C = Tab("sss", "oo","i");
wind->newTab(C);
wind->getActiveTab();
wind->moveActiveTabTo(4);
Tab I = Tab("c", "vvv","m");
wind->closeTab();
wind->closeTab();
wind->closeTab();
Tab S = Tab("lll", "qqq","z");
wind->newTab(F);
wind->moveActiveTabTo(1);
Tab Q = Tab("xxx", "j","rr");
wind->closeTab();
Tab H = Tab("f", "vvv","eee");
wind->newTab(H);
wind->newTab(I);
wind->isEmpty();
wind->newTab(J);
Tab B = Tab("nn", "l","lll");
wind->changeActiveTabTo(4);
Tab G = Tab("jjj", "mm","lll");
wind->moveActiveTabTo(0);
Tab D = Tab("iii", "z","aaa");
wind->newTab(B);
wind->isEmpty();
wind->isEmpty();
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(2);
wind->newTab(D);
wind->moveActiveTabTo(4);
Tab L = Tab("ccc", "d","rr");
wind->changeActiveTabTo(3);
wind->getActiveTab();
wind->newTab(G);
wind->newTab(K);
Tab V = Tab("cc", "iii","mmm");
wind->isEmpty();
wind->print();
Tab N = Tab("eee", "kkk","kk");
wind->closeTab();
wind->moveActiveTabTo(3);
wind->changeActiveTabTo(0);
wind->newTab(L);
Tab A = Tab("e", "bb","lll");
wind->closeTab();
Tab O = Tab("bbb", "ss","p");
wind->closeTab();
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(4);
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(3);
Tab T = Tab("gg", "vvv","hh");
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->print();
wind->print();
wind->newTab(A);
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(1);
wind->print();
wind->newTab(M);
wind->closeTab();
wind->changeActiveTabTo(5);
wind->isEmpty();
wind->print();
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->changeActiveTabTo(0);
wind->closeTab();
wind->moveActiveTabTo(0);
wind->closeTab();
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(4);
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->moveActiveTabTo(1);
wind->print();
wind->print();
wind->moveActiveTabTo(3);
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(1);
wind->moveActiveTabTo(3);
wind->newTab(N);
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(O);
wind->changeActiveTabTo(4);
wind->newTab(P);
delete wind;
}
	return 0;
}