#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
Tab Z = Tab("x", "yyy","xxx");
wind->isEmpty();
Tab N = Tab("q", "aa","uu");
wind->newTab(N);
Tab E = Tab("n", "tt","ii");
wind->print();
Tab K = Tab("hhh", "x","n");
wind->print();
Tab A = Tab("q", "sss","f");
wind->closeTab();
Tab D = Tab("oo", "h","m");
wind->print();
Tab J = Tab("oo", "nn","ee");
wind->getActiveTab();
wind->newTab(A);
Tab O = Tab("i", "q","k");
wind->closeTab();
Tab Q = Tab("zz", "z","h");
wind->changeActiveTabTo(3);
Tab M = Tab("sss", "ddd","ll");
wind->getActiveTab();
wind->isEmpty();
wind->closeTab();
Tab W = Tab("nnn", "v","e");
wind->newTab(D);
wind->changeActiveTabTo(2);
wind->closeTab();
Tab I = Tab("nn", "www","fff");
wind->newTab(E);
wind->isEmpty();
wind->getActiveTab();
Tab V = Tab("d", "ss","lll");
wind->getActiveTab();
Tab B = Tab("ccc", "www","b");
wind->moveActiveTabTo(1);
Tab T = Tab("tt", "ppp","j");
wind->moveActiveTabTo(3);
wind->newTab(B);
wind->isEmpty();
wind->getActiveTab();
Tab P = Tab("v", "hh","aaa");
wind->changeActiveTabTo(2);
Tab U = Tab("kkk", "e","tt");
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(2);
wind->closeTab();
Tab S = Tab("ll", "sss","o");
wind->changeActiveTabTo(3);
wind->closeTab();
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->changeActiveTabTo(2);
Tab H = Tab("g", "h","oo");
wind->newTab(H);
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->closeTab();
wind->print();
wind->print();
wind->closeTab();
Tab C = Tab("cc", "hh","eee");
wind->changeActiveTabTo(2);
Tab Y = Tab("ggg", "z","jjj");
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(1);
wind->newTab(C);
Tab L = Tab("hhh", "q","q");
wind->newTab(I);
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->getActiveTab();
wind->closeTab();
wind->newTab(J);
wind->newTab(K);
Tab R = Tab("xxx", "yy","ppp");
wind->changeActiveTabTo(3);
wind->newTab(L);
wind->isEmpty();
wind->newTab(M);
wind->moveActiveTabTo(5);
wind->newTab(O);
Tab X = Tab("www", "w","o");
wind->isEmpty();
wind->moveActiveTabTo(4);
wind->closeTab();
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(2);
wind->closeTab();
wind->getActiveTab();
wind->newTab(P);
wind->changeActiveTabTo(1);
wind->print();
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
Tab F = Tab("j", "ss","a");
wind->getActiveTab();
wind->closeTab();
wind->getActiveTab();
Tab G = Tab("m", "lll","c");
wind->moveActiveTabTo(3);
wind->moveActiveTabTo(4);
wind->newTab(F);
wind->getActiveTab();
wind->closeTab();
wind->newTab(G);
wind->isEmpty();
wind->closeTab();
wind->getActiveTab();
wind->newTab(Q);
wind->getActiveTab();
wind->print();
wind->getActiveTab();
wind->isEmpty();
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(R);
wind->moveActiveTabTo(0);
wind->print();
delete wind;
}
	return 0;
}