#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->moveActiveTabTo(1);
Tab K = Tab("u", "ww","ss");
wind->newTab(K);
Tab P = Tab("gg", "yyy","tt");
wind->changeActiveTabTo(2);
Tab R = Tab("m", "c","hh");
wind->getActiveTab();
Tab Y = Tab("x", "ii","e");
wind->closeTab();
Tab G = Tab("tt", "zz","o");
wind->moveActiveTabTo(3);
Tab H = Tab("i", "nn","tt");
wind->isEmpty();
Tab N = Tab("f", "f","sss");
wind->closeTab();
Tab D = Tab("rrr", "l","ccc");
wind->getActiveTab();
Tab L = Tab("ww", "qq","v");
wind->getActiveTab();
Tab B = Tab("ww", "mm","xx");
wind->newTab(B);
wind->closeTab();
wind->moveActiveTabTo(4);
Tab T = Tab("p", "b","ggg");
wind->print();
Tab U = Tab("qq", "rrr","kkk");
wind->isEmpty();
Tab Q = Tab("zz", "ppp","eee");
wind->closeTab();
Tab S = Tab("zz", "n","k");
wind->changeActiveTabTo(3);
wind->print();
wind->getActiveTab();
Tab F = Tab("kk", "qq","gg");
wind->changeActiveTabTo(1);
Tab X = Tab("uuu", "uu","cc");
wind->print();
wind->moveActiveTabTo(5);
Tab V = Tab("ii", "eee","k");
wind->closeTab();
wind->isEmpty();
Tab W = Tab("v", "bbb","fff");
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(4);
wind->print();
Tab Z = Tab("hh", "kk","rrr");
wind->closeTab();
wind->print();
wind->moveActiveTabTo(4);
wind->changeActiveTabTo(0);
Tab O = Tab("xxx", "nn","aa");
wind->isEmpty();
Tab M = Tab("y", "ss","ttt");
wind->moveActiveTabTo(0);
wind->newTab(D);
wind->newTab(F);
wind->changeActiveTabTo(4);
wind->closeTab();
wind->print();
Tab J = Tab("hh", "ii","w");
wind->isEmpty();
wind->newTab(G);
wind->moveActiveTabTo(5);
Tab A = Tab("bbb", "eee","r");
wind->isEmpty();
wind->changeActiveTabTo(4);
wind->closeTab();
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(2);
wind->newTab(A);
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(4);
wind->print();
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(5);
wind->getActiveTab();
wind->newTab(H);
wind->isEmpty();
wind->newTab(J);
wind->isEmpty();
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->closeTab();
wind->newTab(L);
wind->newTab(M);
Tab E = Tab("u", "eee","r");
wind->changeActiveTabTo(1);
wind->closeTab();
wind->isEmpty();
wind->print();
wind->getActiveTab();
wind->closeTab();
wind->print();
wind->newTab(E);
wind->closeTab();
wind->newTab(N);
wind->print();
wind->getActiveTab();
wind->isEmpty();
Tab C = Tab("w", "vv","ppp");
wind->changeActiveTabTo(0);
wind->print();
wind->getActiveTab();
wind->isEmpty();
wind->newTab(C);
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->isEmpty();
wind->newTab(O);
wind->moveActiveTabTo(2);
wind->moveActiveTabTo(0);
wind->isEmpty();
wind->print();
wind->closeTab();
wind->getActiveTab();
delete wind;
}
	return 0;
}