#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->moveActiveTabTo(2);
Tab J = Tab("ppp", "ppp","bbb");
wind->closeTab();
Tab X = Tab("l", "x","ooo");
wind->closeTab();
Tab R = Tab("yyy", "dd","uuu");
wind->moveActiveTabTo(5);
Tab I = Tab("xx", "d","lll");
wind->isEmpty();
Tab E = Tab("xx", "zzz","jj");
wind->print();
Tab K = Tab("fff", "kk","oo");
wind->isEmpty();
wind->isEmpty();
wind->moveActiveTabTo(4);
Tab C = Tab("pp", "rr","bb");
wind->isEmpty();
Tab G = Tab("vv", "bb","jj");
wind->print();
wind->moveActiveTabTo(3);
wind->newTab(C);
wind->getActiveTab();
Tab U = Tab("ccc", "dd","j");
wind->getActiveTab();
wind->moveActiveTabTo(4);
wind->isEmpty();
wind->closeTab();
wind->moveActiveTabTo(5);
wind->getActiveTab();
Tab Q = Tab("f", "bbb","ll");
wind->newTab(E);
wind->print();
Tab S = Tab("vvv", "ss","ttt");
wind->print();
Tab O = Tab("rr", "r","ff");
wind->newTab(G);
Tab P = Tab("bbb", "tt","v");
wind->changeActiveTabTo(0);
wind->closeTab();
Tab W = Tab("kkk", "hhh","ttt");
wind->moveActiveTabTo(3);
wind->getActiveTab();
wind->changeActiveTabTo(2);
Tab H = Tab("ggg", "jjj","aaa");
wind->closeTab();
wind->moveActiveTabTo(2);
wind->isEmpty();
Tab F = Tab("s", "v","dd");
wind->changeActiveTabTo(4);
Tab T = Tab("mmm", "qq","oo");
wind->closeTab();
wind->newTab(F);
wind->newTab(H);
wind->moveActiveTabTo(5);
Tab V = Tab("b", "rr","ww");
wind->newTab(I);
Tab Y = Tab("www", "bb","jj");
wind->moveActiveTabTo(2);
wind->newTab(J);
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(K);
wind->closeTab();
wind->changeActiveTabTo(2);
wind->newTab(O);
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->print();
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(1);
Tab L = Tab("aa", "mmm","ll");
wind->moveActiveTabTo(0);
wind->print();
wind->moveActiveTabTo(0);
wind->closeTab();
wind->closeTab();
wind->print();
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(0);
wind->print();
wind->newTab(L);
Tab A = Tab("mmm", "vvv","z");
wind->getActiveTab();
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
Tab Z = Tab("t", "j","pp");
wind->isEmpty();
wind->closeTab();
wind->print();
wind->getActiveTab();
Tab D = Tab("kkk", "qq","hh");
wind->isEmpty();
wind->closeTab();
Tab M = Tab("n", "bbb","ee");
wind->moveActiveTabTo(4);
wind->closeTab();
wind->print();
wind->moveActiveTabTo(2);
wind->newTab(A);
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->closeTab();
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(4);
Tab N = Tab("iii", "kk","vv");
wind->changeActiveTabTo(3);
wind->newTab(D);
wind->newTab(M);
wind->isEmpty();
wind->closeTab();
wind->closeTab();
wind->print();
delete wind;
}
	return 0;
}