#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
Tab D = Tab("ppp", "w","q");
wind->isEmpty();
Tab U = Tab("yy", "h","eee");
wind->newTab(D);
Tab S = Tab("jjj", "www","xx");
wind->print();
Tab A = Tab("z", "mmm","qqq");
wind->moveActiveTabTo(1);
wind->print();
Tab X = Tab("z", "nn","mm");
wind->moveActiveTabTo(5);
Tab B = Tab("gg", "e","r");
wind->closeTab();
Tab P = Tab("n", "fff","bbb");
wind->isEmpty();
wind->getActiveTab();
Tab M = Tab("vv", "x","oo");
wind->closeTab();
wind->moveActiveTabTo(5);
Tab V = Tab("u", "zzz","w");
wind->closeTab();
wind->print();
Tab G = Tab("s", "kk","oo");
wind->closeTab();
Tab C = Tab("iii", "yyy","eee");
wind->newTab(A);
Tab N = Tab("uuu", "mmm","l");
wind->changeActiveTabTo(0);
Tab O = Tab("z", "v","iii");
wind->print();
Tab H = Tab("uuu", "tt","oo");
wind->moveActiveTabTo(2);
wind->newTab(B);
Tab Z = Tab("ggg", "o","w");
wind->newTab(C);
wind->isEmpty();
Tab E = Tab("ooo", "rrr","mm");
wind->closeTab();
Tab F = Tab("a", "zzz","mm");
wind->isEmpty();
Tab Y = Tab("gg", "e","z");
wind->changeActiveTabTo(2);
wind->print();
wind->changeActiveTabTo(3);
Tab L = Tab("rrr", "t","kk");
wind->newTab(E);
wind->isEmpty();
Tab K = Tab("ttt", "mmm","g");
wind->closeTab();
wind->print();
wind->print();
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
wind->closeTab();
wind->isEmpty();
Tab R = Tab("qqq", "lll","b");
wind->newTab(F);
wind->changeActiveTabTo(5);
wind->closeTab();
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->isEmpty();
wind->isEmpty();
wind->newTab(G);
wind->print();
Tab J = Tab("s", "zzz","jj");
wind->print();
Tab W = Tab("uu", "u","yy");
wind->print();
wind->print();
Tab T = Tab("nnn", "rrr","ttt");
wind->print();
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->newTab(H);
Tab I = Tab("mmm", "nn","bb");
wind->isEmpty();
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->getActiveTab();
wind->newTab(I);
wind->newTab(J);
wind->newTab(K);
wind->moveActiveTabTo(3);
wind->moveActiveTabTo(1);
wind->closeTab();
Tab Q = Tab("nn", "gg","vv");
wind->isEmpty();
wind->getActiveTab();
wind->isEmpty();
wind->changeActiveTabTo(4);
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->closeTab();
wind->closeTab();
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(2);
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(2);
wind->moveActiveTabTo(3);
wind->moveActiveTabTo(3);
wind->getActiveTab();
wind->getActiveTab();
wind->isEmpty();
wind->newTab(L);
wind->changeActiveTabTo(1);
wind->closeTab();
wind->isEmpty();
wind->closeTab();
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->newTab(M);
wind->getActiveTab();
wind->newTab(N);
wind->changeActiveTabTo(5);
wind->closeTab();
wind->print();
wind->newTab(O);
delete wind;
}
	return 0;
}