#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
Tab A = Tab("a", "ttt","j");
wind->print();
Tab Z = Tab("vvv", "jjj","m");
wind->moveActiveTabTo(5);
Tab N = Tab("i", "j","z");
wind->moveActiveTabTo(5);
Tab W = Tab("f", "u","ttt");
wind->isEmpty();
wind->changeActiveTabTo(0);
Tab K = Tab("jjj", "hh","i");
wind->print();
Tab D = Tab("ff", "c","t");
wind->newTab(A);
Tab C = Tab("bbb", "oo","i");
wind->newTab(C);
Tab L = Tab("xxx", "hh","bbb");
wind->newTab(D);
wind->isEmpty();
Tab M = Tab("j", "eee","zz");
wind->moveActiveTabTo(5);
Tab H = Tab("r", "c","a");
wind->changeActiveTabTo(2);
Tab O = Tab("ccc", "mm","r");
wind->isEmpty();
Tab U = Tab("mmm", "n","p");
wind->isEmpty();
Tab R = Tab("zz", "rr","n");
wind->print();
wind->print();
Tab E = Tab("m", "xx","d");
wind->closeTab();
Tab I = Tab("m", "lll","ii");
wind->changeActiveTabTo(5);
Tab Y = Tab("kkk", "aaa","w");
wind->print();
Tab F = Tab("aa", "ll","f");
wind->changeActiveTabTo(0);
Tab S = Tab("dd", "nn","y");
wind->getActiveTab();
Tab V = Tab("qq", "o","ff");
wind->getActiveTab();
wind->newTab(E);
Tab X = Tab("uuu", "qqq","iii");
wind->getActiveTab();
wind->closeTab();
wind->moveActiveTabTo(0);
Tab G = Tab("ddd", "uuu","o");
wind->changeActiveTabTo(5);
wind->isEmpty();
wind->getActiveTab();
wind->isEmpty();
Tab P = Tab("yyy", "bb","ggg");
wind->closeTab();
wind->moveActiveTabTo(4);
wind->print();
wind->closeTab();
Tab B = Tab("n", "aa","g");
wind->isEmpty();
wind->getActiveTab();
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(1);
wind->closeTab();
wind->changeActiveTabTo(1);
Tab Q = Tab("uuu", "g","xx");
wind->newTab(B);
wind->newTab(F);
wind->getActiveTab();
wind->closeTab();
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->closeTab();
wind->print();
wind->print();
wind->moveActiveTabTo(4);
wind->isEmpty();
wind->print();
wind->print();
wind->moveActiveTabTo(2);
wind->newTab(G);
wind->moveActiveTabTo(0);
wind->newTab(H);
wind->isEmpty();
wind->closeTab();
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->print();
wind->closeTab();
wind->changeActiveTabTo(1);
wind->print();
wind->closeTab();
wind->print();
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(I);
wind->newTab(K);
Tab T = Tab("ss", "jjj","l");
wind->getActiveTab();
wind->newTab(L);
wind->closeTab();
wind->newTab(M);
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
wind->print();
wind->newTab(N);
Tab J = Tab("oo", "oo","dd");
wind->newTab(J);
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->print();
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(3);
wind->closeTab();
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->print();
wind->closeTab();
wind->newTab(O);
delete wind;
}
	return 0;
}