#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->moveActiveTabTo(5);
Tab Z = Tab("rrr", "eee","iii");
wind->newTab(Z);
Tab U = Tab("g", "zzz","ff");
wind->changeActiveTabTo(0);
wind->print();
Tab Y = Tab("bb", "bb","aaa");
wind->newTab(U);
wind->newTab(Y);
Tab X = Tab("zz", "hhh","cc");
wind->moveActiveTabTo(2);
wind->closeTab();
Tab T = Tab("yy", "ccc","kk");
wind->moveActiveTabTo(1);
Tab I = Tab("cc", "ss","ll");
wind->closeTab();
wind->closeTab();
Tab V = Tab("b", "vvv","tt");
wind->changeActiveTabTo(5);
Tab R = Tab("c", "uuu","f");
wind->closeTab();
Tab B = Tab("v", "j","eee");
wind->print();
Tab Q = Tab("sss", "nnn","gg");
wind->newTab(B);
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(2);
wind->isEmpty();
Tab D = Tab("ccc", "t","hh");
wind->newTab(D);
wind->print();
wind->changeActiveTabTo(5);
wind->closeTab();
Tab M = Tab("z", "uuu","a");
wind->isEmpty();
Tab N = Tab("sss", "ee","zz");
wind->moveActiveTabTo(2);
wind->print();
Tab K = Tab("qqq", "zzz","rrr");
wind->newTab(I);
Tab G = Tab("y", "g","o");
wind->isEmpty();
wind->print();
Tab F = Tab("q", "qqq","v");
wind->print();
Tab P = Tab("ggg", "f","ccc");
wind->getActiveTab();
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
wind->print();
wind->closeTab();
Tab C = Tab("uuu", "rr","g");
wind->newTab(C);
Tab E = Tab("b", "nnn","aa");
wind->print();
wind->newTab(E);
Tab W = Tab("cc", "yy","dd");
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(4);
wind->getActiveTab();
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
wind->newTab(F);
Tab J = Tab("yy", "vvv","uuu");
wind->isEmpty();
wind->print();
wind->newTab(G);
wind->closeTab();
wind->newTab(J);
wind->newTab(K);
wind->moveActiveTabTo(3);
wind->print();
Tab O = Tab("ii", "p","kk");
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->print();
Tab L = Tab("hh", "mm","k");
wind->moveActiveTabTo(0);
wind->print();
wind->isEmpty();
Tab S = Tab("zzz", "yy","xxx");
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(4);
wind->newTab(L);
wind->moveActiveTabTo(0);
wind->newTab(M);
wind->newTab(N);
wind->isEmpty();
wind->print();
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(3);
wind->newTab(O);
wind->newTab(P);
wind->newTab(Q);
wind->newTab(R);
wind->closeTab();
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->closeTab();
wind->moveActiveTabTo(1);
wind->getActiveTab();
Tab A = Tab("ee", "aaa","mm");
wind->newTab(A);
wind->newTab(S);
wind->moveActiveTabTo(2);
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(4);
wind->newTab(T);
wind->newTab(V);
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(5);
delete wind;
}
	return 0;
}