#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
Tab S = Tab("lll", "gg","ww");
wind->newTab(S);
Tab D = Tab("oo", "n","g");
wind->closeTab();
Tab T = Tab("vvv", "aaa","s");
wind->getActiveTab();
wind->moveActiveTabTo(3);
Tab I = Tab("hhh", "c","nn");
wind->print();
wind->getActiveTab();
Tab M = Tab("rrr", "fff","bbb");
wind->getActiveTab();
Tab L = Tab("sss", "zzz","xx");
wind->moveActiveTabTo(2);
Tab G = Tab("r", "mmm","hhh");
wind->newTab(D);
Tab V = Tab("nnn", "g","pp");
wind->print();
Tab W = Tab("h", "tt","ss");
wind->newTab(G);
wind->moveActiveTabTo(1);
wind->isEmpty();
Tab X = Tab("ggg", "ooo","kk");
wind->changeActiveTabTo(0);
Tab E = Tab("c", "aa","www");
wind->newTab(E);
Tab Z = Tab("ggg", "n","ww");
wind->closeTab();
Tab Y = Tab("qq", "ll","m");
wind->closeTab();
Tab A = Tab("jjj", "mm","x");
wind->changeActiveTabTo(2);
Tab N = Tab("mmm", "ccc","lll");
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->getActiveTab();
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(4);
wind->print();
Tab J = Tab("s", "ccc","ss");
wind->isEmpty();
Tab B = Tab("ii", "yy","ff");
wind->print();
Tab O = Tab("zzz", "n","jj");
wind->closeTab();
Tab Q = Tab("eee", "d","pp");
wind->moveActiveTabTo(2);
wind->newTab(A);
wind->changeActiveTabTo(1);
wind->print();
wind->changeActiveTabTo(1);
wind->isEmpty();
Tab P = Tab("q", "hh","o");
wind->isEmpty();
Tab U = Tab("rrr", "i","d");
wind->getActiveTab();
wind->newTab(B);
wind->getActiveTab();
wind->newTab(I);
wind->isEmpty();
wind->closeTab();
Tab H = Tab("nn", "v","www");
wind->isEmpty();
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(H);
wind->closeTab();
wind->changeActiveTabTo(3);
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->moveActiveTabTo(4);
wind->closeTab();
wind->newTab(J);
wind->changeActiveTabTo(0);
wind->print();
wind->isEmpty();
wind->closeTab();
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->print();
wind->newTab(L);
wind->moveActiveTabTo(4);
Tab K = Tab("k", "hh","fff");
wind->getActiveTab();
wind->print();
wind->isEmpty();
wind->closeTab();
Tab F = Tab("bb", "nnn","p");
wind->isEmpty();
wind->isEmpty();
Tab C = Tab("lll", "dd","uuu");
wind->getActiveTab();
wind->getActiveTab();
Tab R = Tab("vv", "gg","bbb");
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(1);
wind->print();
wind->changeActiveTabTo(2);
wind->newTab(C);
wind->newTab(F);
wind->moveActiveTabTo(5);
wind->newTab(K);
wind->moveActiveTabTo(5);
wind->newTab(M);
wind->getActiveTab();
wind->newTab(N);
wind->newTab(O);
wind->print();
wind->getActiveTab();
wind->isEmpty();
wind->newTab(P);
wind->print();
wind->moveActiveTabTo(1);
wind->print();
wind->changeActiveTabTo(2);
wind->closeTab();
wind->print();
wind->print();
wind->getActiveTab();
wind->newTab(Q);
wind->changeActiveTabTo(1);
delete wind;
}
	return 0;
}