#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->isEmpty();
Tab R = Tab("ggg", "aa","c");
wind->getActiveTab();
Tab N = Tab("g", "m","gg");
wind->closeTab();
Tab V = Tab("jjj", "ss","jj");
wind->newTab(N);
Tab M = Tab("bbb", "fff","q");
wind->changeActiveTabTo(0);
wind->getActiveTab();
Tab Z = Tab("ll", "d","jjj");
wind->closeTab();
Tab S = Tab("c", "m","jj");
wind->moveActiveTabTo(1);
Tab I = Tab("qqq", "ppp","e");
wind->getActiveTab();
Tab U = Tab("g", "kkk","ff");
wind->getActiveTab();
wind->changeActiveTabTo(4);
wind->getActiveTab();
wind->closeTab();
Tab J = Tab("cc", "fff","nnn");
wind->newTab(I);
Tab A = Tab("mm", "qq","z");
wind->print();
wind->changeActiveTabTo(1);
Tab W = Tab("ii", "ggg","vv");
wind->newTab(A);
wind->print();
wind->moveActiveTabTo(2);
Tab H = Tab("ii", "qq","r");
wind->print();
wind->moveActiveTabTo(3);
Tab O = Tab("uu", "xxx","pp");
wind->moveActiveTabTo(4);
Tab E = Tab("kk", "ff","t");
wind->getActiveTab();
Tab P = Tab("ooo", "kk","hh");
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(5);
Tab X = Tab("j", "ddd","www");
wind->print();
wind->moveActiveTabTo(5);
Tab G = Tab("d", "ss","aaa");
wind->isEmpty();
wind->isEmpty();
wind->getActiveTab();
wind->newTab(E);
wind->moveActiveTabTo(1);
wind->newTab(G);
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->changeActiveTabTo(2);
Tab Y = Tab("rrr", "z","r");
wind->isEmpty();
wind->moveActiveTabTo(5);
Tab Q = Tab("ii", "oo","oo");
wind->moveActiveTabTo(2);
Tab L = Tab("f", "i","bbb");
wind->changeActiveTabTo(4);
Tab C = Tab("xxx", "c","iii");
wind->print();
wind->closeTab();
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->print();
Tab T = Tab("p", "l","aaa");
wind->getActiveTab();
wind->isEmpty();
wind->getActiveTab();
wind->changeActiveTabTo(0);
wind->closeTab();
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->newTab(C);
wind->closeTab();
wind->isEmpty();
wind->closeTab();
wind->changeActiveTabTo(1);
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->closeTab();
wind->isEmpty();
wind->changeActiveTabTo(5);
Tab K = Tab("nnn", "xxx","o");
wind->isEmpty();
Tab F = Tab("zzz", "q","ff");
wind->closeTab();
wind->moveActiveTabTo(4);
Tab B = Tab("a", "ff","vvv");
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(1);
wind->print();
wind->getActiveTab();
Tab D = Tab("u", "yy","hhh");
wind->changeActiveTabTo(1);
wind->closeTab();
wind->newTab(B);
wind->getActiveTab();
wind->newTab(D);
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->closeTab();
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->print();
wind->closeTab();
wind->moveActiveTabTo(4);
wind->isEmpty();
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(1);
wind->closeTab();
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->print();
wind->isEmpty();
wind->isEmpty();
wind->print();
wind->moveActiveTabTo(5);
wind->isEmpty();
delete wind;
}
	return 0;
}