#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->getActiveTab();
Tab Y = Tab("iii", "aa","oo");
wind->newTab(Y);
Tab V = Tab("nnn", "a","jjj");
wind->print();
Tab A = Tab("c", "yy","ww");
wind->print();
wind->moveActiveTabTo(4);
Tab T = Tab("xx", "e","qqq");
wind->print();
Tab Z = Tab("n", "kkk","h");
wind->isEmpty();
Tab R = Tab("jj", "ggg","f");
wind->getActiveTab();
Tab N = Tab("www", "ss","gg");
wind->moveActiveTabTo(1);
Tab F = Tab("l", "hhh","qq");
wind->moveActiveTabTo(0);
Tab X = Tab("nn", "z","aaa");
wind->newTab(A);
Tab M = Tab("hhh", "hhh","i");
wind->newTab(F);
Tab K = Tab("v", "oo","j");
wind->changeActiveTabTo(3);
wind->newTab(K);
Tab L = Tab("b", "yy","xx");
wind->closeTab();
Tab O = Tab("aa", "i","ss");
wind->print();
wind->newTab(L);
Tab Q = Tab("kkk", "nnn","dd");
wind->isEmpty();
Tab C = Tab("kkk", "qq","ooo");
wind->moveActiveTabTo(0);
Tab I = Tab("c", "x","rrr");
wind->newTab(C);
Tab U = Tab("e", "i","s");
wind->print();
wind->changeActiveTabTo(5);
wind->print();
wind->newTab(I);
wind->changeActiveTabTo(4);
wind->newTab(M);
Tab E = Tab("gg", "j","g");
wind->changeActiveTabTo(0);
wind->closeTab();
wind->newTab(E);
wind->moveActiveTabTo(5);
wind->closeTab();
Tab D = Tab("u", "sss","yy");
wind->moveActiveTabTo(3);
wind->isEmpty();
wind->closeTab();
wind->newTab(D);
wind->moveActiveTabTo(0);
Tab W = Tab("s", "s","ss");
wind->newTab(N);
wind->closeTab();
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(3);
Tab B = Tab("ppp", "k","w");
wind->isEmpty();
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(3);
Tab S = Tab("nnn", "vv","m");
wind->moveActiveTabTo(3);
wind->isEmpty();
wind->moveActiveTabTo(2);
Tab H = Tab("ooo", "kkk","xxx");
wind->print();
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(4);
Tab P = Tab("zzz", "rr","gg");
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(5);
wind->closeTab();
wind->print();
wind->changeActiveTabTo(3);
wind->print();
Tab J = Tab("ff", "vv","eee");
wind->print();
wind->moveActiveTabTo(0);
wind->closeTab();
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(4);
wind->changeActiveTabTo(2);
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->print();
Tab G = Tab("nnn", "hhh","s");
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(3);
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(5);
wind->getActiveTab();
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->getActiveTab();
wind->closeTab();
wind->moveActiveTabTo(3);
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(4);
wind->isEmpty();
wind->newTab(B);
wind->print();
wind->closeTab();
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(1);
wind->getActiveTab();
wind->closeTab();
delete wind;
}
	return 0;
}