#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->closeTab();
Tab Q = Tab("jj", "c","r");
wind->closeTab();
Tab C = Tab("ff", "sss","ll");
wind->changeActiveTabTo(4);
Tab F = Tab("ggg", "p","kk");
wind->moveActiveTabTo(4);
Tab S = Tab("l", "rrr","qqq");
wind->getActiveTab();
Tab J = Tab("xxx", "i","h");
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(3);
Tab D = Tab("cc", "yyy","jj");
wind->print();
Tab N = Tab("y", "uu","cc");
wind->closeTab();
Tab X = Tab("r", "ppp","oo");
wind->changeActiveTabTo(4);
Tab M = Tab("g", "xx","ooo");
wind->newTab(C);
Tab V = Tab("t", "w","aaa");
wind->print();
wind->getActiveTab();
wind->closeTab();
wind->closeTab();
Tab P = Tab("f", "ff","rr");
wind->newTab(D);
Tab Y = Tab("ss", "hhh","tt");
wind->getActiveTab();
Tab Z = Tab("ll", "ooo","yy");
wind->print();
Tab W = Tab("x", "u","mmm");
wind->newTab(F);
wind->newTab(J);
Tab R = Tab("ppp", "yyy","zzz");
wind->newTab(M);
Tab E = Tab("d", "ccc","uuu");
wind->newTab(E);
wind->newTab(N);
wind->isEmpty();
Tab G = Tab("cc", "bb","ooo");
wind->changeActiveTabTo(0);
Tab I = Tab("xx", "a","mm");
wind->getActiveTab();
wind->isEmpty();
wind->getActiveTab();
wind->closeTab();
Tab K = Tab("i", "l","mmm");
wind->getActiveTab();
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(1);
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
wind->print();
wind->print();
wind->print();
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(0);
Tab L = Tab("xxx", "www","xxx");
wind->newTab(G);
wind->closeTab();
wind->moveActiveTabTo(1);
wind->getActiveTab();
Tab B = Tab("y", "r","aaa");
wind->moveActiveTabTo(5);
wind->print();
Tab A = Tab("e", "ll","d");
wind->print();
wind->closeTab();
wind->changeActiveTabTo(5);
wind->print();
wind->moveActiveTabTo(3);
wind->changeActiveTabTo(1);
Tab T = Tab("ee", "nnn","h");
wind->getActiveTab();
wind->newTab(A);
wind->closeTab();
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(3);
wind->newTab(B);
wind->print();
wind->closeTab();
wind->newTab(I);
wind->changeActiveTabTo(3);
wind->newTab(K);
wind->changeActiveTabTo(4);
Tab U = Tab("k", "xxx","eee");
wind->getActiveTab();
wind->getActiveTab();
wind->print();
wind->newTab(L);
wind->changeActiveTabTo(1);
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(0);
wind->closeTab();
wind->closeTab();
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(2);
wind->closeTab();
wind->moveActiveTabTo(4);
wind->isEmpty();
wind->isEmpty();
wind->newTab(P);
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->newTab(Q);
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->getActiveTab();
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->newTab(R);
wind->print();
wind->isEmpty();
wind->closeTab();
wind->newTab(S);
wind->changeActiveTabTo(1);
wind->print();
delete wind;
}
	return 0;
}