#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->closeTab();
Tab L = Tab("j", "k","sss");
wind->print();
Tab P = Tab("xxx", "c","rr");
wind->moveActiveTabTo(3);
Tab Y = Tab("uuu", "d","lll");
wind->print();
Tab H = Tab("bbb", "xx","tt");
wind->isEmpty();
Tab V = Tab("w", "yyy","zz");
wind->newTab(H);
Tab F = Tab("vvv", "i","mm");
wind->isEmpty();
wind->changeActiveTabTo(4);
Tab D = Tab("d", "dd","rr");
wind->isEmpty();
wind->print();
Tab R = Tab("ddd", "w","j");
wind->newTab(D);
wind->newTab(F);
wind->print();
Tab C = Tab("n", "kk","uuu");
wind->closeTab();
Tab E = Tab("ooo", "sss","ff");
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->newTab(C);
Tab J = Tab("rrr", "ss","cc");
wind->print();
Tab B = Tab("ee", "xx","aa");
wind->moveActiveTabTo(3);
Tab K = Tab("e", "ppp","qq");
wind->getActiveTab();
wind->isEmpty();
Tab O = Tab("i", "ww","w");
wind->newTab(B);
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(3);
Tab A = Tab("tt", "r","q");
wind->newTab(A);
Tab N = Tab("sss", "bb","z");
wind->moveActiveTabTo(0);
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
Tab U = Tab("jj", "vv","ccc");
wind->moveActiveTabTo(4);
Tab G = Tab("l", "bb","f");
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
Tab I = Tab("e", "w","hhh");
wind->changeActiveTabTo(1);
wind->newTab(E);
wind->print();
wind->closeTab();
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->changeActiveTabTo(5);
wind->print();
wind->closeTab();
wind->changeActiveTabTo(5);
wind->newTab(G);
wind->moveActiveTabTo(0);
wind->newTab(I);
wind->changeActiveTabTo(2);
wind->newTab(J);
Tab S = Tab("a", "fff","s");
wind->isEmpty();
Tab Q = Tab("p", "d","rr");
wind->print();
wind->newTab(K);
wind->newTab(L);
wind->moveActiveTabTo(0);
wind->newTab(N);
wind->getActiveTab();
wind->newTab(O);
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
wind->changeActiveTabTo(4);
Tab M = Tab("bbb", "ee","zz");
wind->changeActiveTabTo(2);
wind->moveActiveTabTo(1);
wind->moveActiveTabTo(2);
wind->getActiveTab();
wind->print();
wind->newTab(M);
wind->newTab(P);
wind->moveActiveTabTo(5);
wind->newTab(Q);
wind->changeActiveTabTo(3);
Tab T = Tab("hhh", "a","n");
wind->print();
wind->newTab(R);
wind->changeActiveTabTo(5);
wind->newTab(S);
wind->closeTab();
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
wind->closeTab();
wind->closeTab();
wind->newTab(T);
wind->newTab(U);
wind->closeTab();
wind->newTab(V);
wind->getActiveTab();
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->changeActiveTabTo(2);
Tab W = Tab("u", "vv","cc");
wind->closeTab();
wind->changeActiveTabTo(5);
wind->newTab(W);
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(0);
delete wind;
}
	return 0;
}