#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->print();
Tab Y = Tab("u", "ooo","rr");
wind->print();
Tab L = Tab("iii", "ttt","sss");
wind->getActiveTab();
Tab W = Tab("vv", "gg","qqq");
wind->newTab(L);
Tab T = Tab("uuu", "k","lll");
wind->newTab(T);
Tab P = Tab("p", "w","z");
wind->changeActiveTabTo(3);
Tab O = Tab("ee", "oo","g");
wind->newTab(O);
Tab U = Tab("www", "ppp","x");
wind->closeTab();
Tab J = Tab("qqq", "qq","jj");
wind->newTab(J);
Tab X = Tab("mmm", "eee","b");
wind->isEmpty();
Tab R = Tab("zz", "eee","p");
wind->print();
Tab M = Tab("z", "p","kkk");
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->moveActiveTabTo(1);
wind->getActiveTab();
Tab A = Tab("a", "t","eee");
wind->moveActiveTabTo(4);
wind->newTab(A);
Tab E = Tab("z", "cc","y");
wind->moveActiveTabTo(1);
Tab C = Tab("n", "ll","iii");
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(4);
wind->print();
wind->closeTab();
Tab G = Tab("gg", "r","uuu");
wind->newTab(C);
wind->getActiveTab();
wind->print();
wind->print();
wind->closeTab();
Tab Z = Tab("jjj", "ooo","aaa");
wind->isEmpty();
wind->print();
Tab V = Tab("ll", "aaa","mmm");
wind->print();
wind->moveActiveTabTo(3);
Tab D = Tab("l", "l","d");
wind->closeTab();
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(5);
Tab N = Tab("ddd", "xxx","jjj");
wind->changeActiveTabTo(3);
wind->closeTab();
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(4);
Tab K = Tab("nn", "ppp","gg");
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->closeTab();
wind->newTab(D);
wind->isEmpty();
Tab H = Tab("aa", "vv","hhh");
wind->isEmpty();
wind->print();
wind->print();
wind->getActiveTab();
Tab F = Tab("aaa", "uu","eee");
wind->getActiveTab();
wind->isEmpty();
wind->print();
wind->changeActiveTabTo(2);
wind->closeTab();
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->closeTab();
wind->moveActiveTabTo(1);
Tab B = Tab("h", "ttt","bb");
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
wind->newTab(B);
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->print();
wind->getActiveTab();
wind->isEmpty();
wind->newTab(E);
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->print();
wind->changeActiveTabTo(2);
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->moveActiveTabTo(2);
wind->moveActiveTabTo(5);
wind->newTab(F);
Tab Q = Tab("f", "rrr","ee");
wind->getActiveTab();
wind->newTab(G);
wind->isEmpty();
wind->print();
wind->print();
Tab I = Tab("ww", "bbb","xxx");
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->isEmpty();
wind->closeTab();
wind->getActiveTab();
wind->moveActiveTabTo(4);
wind->getActiveTab();
Tab S = Tab("t", "ss","ppp");
wind->moveActiveTabTo(2);
wind->getActiveTab();
wind->newTab(H);
wind->closeTab();
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(3);
wind->changeActiveTabTo(1);
wind->newTab(I);
wind->closeTab();
delete wind;
}
	return 0;
}