#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->getActiveTab();
Tab Q = Tab("w", "h","nn");
wind->isEmpty();
wind->isEmpty();
Tab J = Tab("o", "j","yy");
wind->moveActiveTabTo(2);
Tab Z = Tab("jjj", "r","ll");
wind->changeActiveTabTo(3);
Tab O = Tab("aaa", "h","ww");
wind->newTab(J);
Tab H = Tab("l", "zzz","p");
wind->changeActiveTabTo(2);
Tab D = Tab("hhh", "w","pp");
wind->changeActiveTabTo(1);
Tab K = Tab("lll", "mmm","bb");
wind->closeTab();
Tab L = Tab("vvv", "kk","www");
wind->newTab(D);
Tab M = Tab("t", "vv","rrr");
wind->moveActiveTabTo(3);
Tab I = Tab("h", "ee","nn");
wind->changeActiveTabTo(3);
Tab N = Tab("zzz", "nnn","xxx");
wind->isEmpty();
wind->changeActiveTabTo(1);
Tab P = Tab("rr", "aa","nn");
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
Tab C = Tab("nn", "bbb","o");
wind->moveActiveTabTo(3);
Tab F = Tab("w", "rr","o");
wind->print();
Tab B = Tab("t", "y","e");
wind->newTab(B);
Tab A = Tab("t", "ppp","qq");
wind->moveActiveTabTo(5);
wind->getActiveTab();
Tab V = Tab("ttt", "ss","ww");
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->print();
Tab W = Tab("m", "r","qq");
wind->print();
Tab E = Tab("eee", "mmm","mmm");
wind->newTab(A);
wind->changeActiveTabTo(5);
wind->isEmpty();
wind->isEmpty();
Tab U = Tab("jj", "lll","lll");
wind->newTab(C);
wind->print();
Tab G = Tab("z", "iii","fff");
wind->isEmpty();
wind->getActiveTab();
wind->closeTab();
Tab R = Tab("aa", "eee","n");
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(5);
wind->isEmpty();
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->newTab(E);
wind->closeTab();
wind->changeActiveTabTo(5);
wind->print();
wind->getActiveTab();
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
wind->changeActiveTabTo(2);
wind->closeTab();
wind->closeTab();
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->newTab(F);
wind->newTab(G);
wind->newTab(H);
wind->getActiveTab();
wind->getActiveTab();
Tab Y = Tab("f", "ggg","mm");
wind->print();
wind->getActiveTab();
Tab X = Tab("qqq", "a","j");
wind->changeActiveTabTo(4);
wind->newTab(I);
Tab S = Tab("ff", "iii","dd");
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(4);
wind->isEmpty();
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->newTab(K);
wind->newTab(L);
wind->print();
wind->moveActiveTabTo(1);
wind->print();
wind->newTab(M);
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(N);
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->print();
wind->changeActiveTabTo(2);
wind->print();
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(O);
wind->isEmpty();
wind->print();
delete wind;
}
	return 0;
}