#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->changeActiveTabTo(4);
Tab G = Tab("h", "xxx","r");
wind->moveActiveTabTo(5);
Tab U = Tab("e", "bb","qq");
wind->moveActiveTabTo(4);
Tab J = Tab("bb", "nnn","bbb");
wind->isEmpty();
wind->closeTab();
Tab A = Tab("a", "tt","ooo");
wind->isEmpty();
Tab X = Tab("u", "ll","nnn");
wind->changeActiveTabTo(4);
Tab C = Tab("r", "dd","ss");
wind->moveActiveTabTo(2);
Tab F = Tab("tt", "aa","uu");
wind->isEmpty();
Tab Q = Tab("w", "i","s");
wind->print();
Tab V = Tab("ggg", "xxx","ii");
wind->newTab(A);
Tab P = Tab("b", "vvv","vv");
wind->isEmpty();
Tab N = Tab("hhh", "uu","kkk");
wind->newTab(C);
Tab M = Tab("f", "kkk","s");
wind->moveActiveTabTo(3);
Tab K = Tab("vv", "fff","k");
wind->isEmpty();
Tab D = Tab("jj", "gg","g");
wind->closeTab();
wind->changeActiveTabTo(2);
Tab W = Tab("ddd", "f","nnn");
wind->changeActiveTabTo(2);
wind->print();
wind->isEmpty();
Tab O = Tab("kk", "i","xxx");
wind->moveActiveTabTo(0);
Tab B = Tab("q", "o","lll");
wind->newTab(B);
wind->print();
wind->isEmpty();
Tab L = Tab("jjj", "r","g");
wind->moveActiveTabTo(1);
wind->isEmpty();
Tab I = Tab("aa", "aaa","tt");
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->print();
Tab E = Tab("ttt", "oo","n");
wind->changeActiveTabTo(4);
wind->newTab(D);
Tab S = Tab("jjj", "yy","y");
wind->changeActiveTabTo(0);
Tab Y = Tab("sss", "aaa","ii");
wind->getActiveTab();
wind->closeTab();
wind->newTab(E);
wind->newTab(F);
wind->closeTab();
wind->changeActiveTabTo(1);
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->isEmpty();
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->print();
Tab T = Tab("pp", "rrr","ww");
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(0);
wind->print();
Tab Z = Tab("uu", "i","t");
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->changeActiveTabTo(2);
wind->print();
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->newTab(G);
wind->moveActiveTabTo(5);
wind->newTab(I);
wind->isEmpty();
wind->getActiveTab();
wind->moveActiveTabTo(1);
wind->closeTab();
wind->changeActiveTabTo(0);
wind->newTab(J);
wind->closeTab();
Tab R = Tab("pp", "qqq","m");
wind->print();
wind->newTab(K);
wind->print();
wind->closeTab();
wind->moveActiveTabTo(2);
wind->closeTab();
Tab H = Tab("lll", "aa","iii");
wind->isEmpty();
wind->changeActiveTabTo(2);
wind->closeTab();
wind->closeTab();
wind->closeTab();
wind->newTab(H);
wind->getActiveTab();
wind->isEmpty();
wind->print();
wind->newTab(L);
wind->closeTab();
wind->newTab(M);
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->moveActiveTabTo(4);
wind->print();
wind->closeTab();
wind->isEmpty();
wind->newTab(N);
wind->newTab(O);
wind->moveActiveTabTo(0);
wind->print();
wind->changeActiveTabTo(3);
wind->print();
wind->closeTab();
wind->getActiveTab();
delete wind;
}
	return 0;
}