#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->closeTab();
Tab S = Tab("ccc", "gg","hhh");
wind->moveActiveTabTo(0);
Tab U = Tab("a", "ss","kkk");
wind->closeTab();
Tab X = Tab("nn", "ccc","kk");
wind->closeTab();
Tab L = Tab("ww", "ss","t");
wind->print();
Tab R = Tab("mmm", "nn","jj");
wind->closeTab();
Tab B = Tab("oo", "w","vvv");
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
Tab J = Tab("pp", "a","ff");
wind->changeActiveTabTo(3);
Tab V = Tab("ll", "bbb","mm");
wind->newTab(B);
wind->isEmpty();
wind->isEmpty();
Tab C = Tab("g", "pp","x");
wind->moveActiveTabTo(1);
Tab M = Tab("iii", "uu","zzz");
wind->closeTab();
Tab G = Tab("ddd", "v","eee");
wind->getActiveTab();
Tab A = Tab("k", "q","f");
wind->changeActiveTabTo(3);
Tab D = Tab("k", "zz","nn");
wind->closeTab();
wind->changeActiveTabTo(1);
Tab Y = Tab("mmm", "h","s");
wind->closeTab();
Tab W = Tab("lll", "ll","oo");
wind->newTab(A);
wind->newTab(C);
wind->getActiveTab();
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->getActiveTab();
wind->isEmpty();
wind->getActiveTab();
Tab O = Tab("j", "h","cc");
wind->closeTab();
wind->print();
Tab H = Tab("ooo", "xxx","jj");
wind->moveActiveTabTo(0);
wind->newTab(D);
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
wind->newTab(G);
wind->closeTab();
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(2);
wind->newTab(H);
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->newTab(J);
wind->print();
wind->getActiveTab();
wind->print();
Tab F = Tab("h", "jj","rrr");
wind->getActiveTab();
wind->isEmpty();
wind->changeActiveTabTo(4);
wind->closeTab();
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(0);
Tab K = Tab("sss", "t","mm");
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(0);
Tab I = Tab("fff", "rr","f");
wind->newTab(F);
wind->isEmpty();
wind->newTab(I);
Tab Z = Tab("lll", "b","g");
wind->changeActiveTabTo(1);
wind->newTab(K);
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->newTab(L);
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(2);
wind->print();
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(3);
Tab P = Tab("nn", "a","qqq");
wind->closeTab();
wind->getActiveTab();
wind->newTab(M);
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(3);
wind->newTab(O);
wind->closeTab();
wind->isEmpty();
wind->closeTab();
Tab E = Tab("v", "ccc","eee");
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(2);
wind->print();
wind->newTab(E);
wind->moveActiveTabTo(3);
wind->closeTab();
wind->isEmpty();
Tab T = Tab("i", "ccc","l");
wind->changeActiveTabTo(1);
wind->isEmpty();
wind->changeActiveTabTo(2);
wind->getActiveTab();
delete wind;
}
	return 0;
}