#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->moveActiveTabTo(0);
Tab Z = Tab("pp", "nnn","k");
wind->closeTab();
Tab D = Tab("ddd", "t","yyy");
wind->print();
Tab W = Tab("b", "jj","j");
wind->closeTab();
Tab R = Tab("www", "g","ddd");
wind->isEmpty();
Tab O = Tab("lll", "ff","ccc");
wind->changeActiveTabTo(4);
Tab Q = Tab("kk", "ppp","ccc");
wind->changeActiveTabTo(5);
Tab Y = Tab("g", "tt","mmm");
wind->isEmpty();
Tab M = Tab("hhh", "l","o");
wind->closeTab();
Tab B = Tab("xx", "gg","w");
wind->newTab(B);
wind->closeTab();
wind->print();
Tab H = Tab("a", "yyy","hhh");
wind->moveActiveTabTo(5);
Tab L = Tab("yy", "ll","gg");
wind->print();
wind->closeTab();
Tab P = Tab("ee", "u","v");
wind->newTab(D);
wind->newTab(H);
wind->print();
wind->closeTab();
wind->closeTab();
Tab E = Tab("ll", "kkk","q");
wind->print();
Tab A = Tab("t", "e","uu");
wind->print();
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(2);
Tab X = Tab("p", "bbb","xxx");
wind->print();
wind->closeTab();
wind->isEmpty();
Tab T = Tab("o", "nnn","aa");
wind->getActiveTab();
wind->moveActiveTabTo(5);
Tab F = Tab("kkk", "f","oo");
wind->changeActiveTabTo(4);
wind->newTab(A);
Tab J = Tab("gg", "ff","yy");
wind->changeActiveTabTo(2);
wind->getActiveTab();
Tab C = Tab("p", "qq","ttt");
wind->moveActiveTabTo(3);
wind->newTab(C);
Tab S = Tab("c", "bb","ii");
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->changeActiveTabTo(4);
wind->print();
wind->print();
Tab G = Tab("eee", "uu","ooo");
wind->newTab(E);
wind->moveActiveTabTo(3);
wind->closeTab();
wind->moveActiveTabTo(3);
wind->changeActiveTabTo(0);
wind->print();
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->closeTab();
wind->moveActiveTabTo(3);
wind->closeTab();
Tab N = Tab("rrr", "fff","ccc");
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(0);
wind->closeTab();
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->newTab(F);
wind->newTab(G);
wind->changeActiveTabTo(2);
wind->print();
wind->isEmpty();
Tab U = Tab("v", "qqq","n");
wind->isEmpty();
wind->closeTab();
Tab V = Tab("xx", "aa","cc");
wind->getActiveTab();
wind->newTab(J);
wind->moveActiveTabTo(3);
wind->print();
wind->closeTab();
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(4);
wind->print();
wind->moveActiveTabTo(5);
wind->print();
wind->closeTab();
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(4);
Tab I = Tab("z", "yy","ff");
wind->newTab(I);
wind->moveActiveTabTo(5);
wind->getActiveTab();
Tab K = Tab("ppp", "ggg","ttt");
wind->closeTab();
wind->newTab(K);
wind->newTab(L);
wind->print();
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->print();
wind->isEmpty();
wind->newTab(M);
wind->closeTab();
wind->newTab(N);
wind->isEmpty();
delete wind;
}
	return 0;
}