#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->changeActiveTabTo(3);
Tab F = Tab("ss", "q","v");
wind->newTab(F);
Tab U = Tab("eee", "f","jj");
wind->getActiveTab();
Tab C = Tab("q", "dd","x");
wind->isEmpty();
wind->changeActiveTabTo(2);
Tab O = Tab("fff", "sss","z");
wind->newTab(C);
Tab L = Tab("vvv", "t","dd");
wind->changeActiveTabTo(2);
Tab K = Tab("c", "yyy","aa");
wind->moveActiveTabTo(4);
wind->getActiveTab();
Tab W = Tab("ddd", "b","p");
wind->closeTab();
Tab R = Tab("tt", "mm","ll");
wind->getActiveTab();
Tab E = Tab("bb", "ttt","bbb");
wind->print();
Tab N = Tab("bb", "xx","mm");
wind->changeActiveTabTo(1);
wind->print();
Tab M = Tab("sss", "ww","kk");
wind->print();
Tab H = Tab("z", "vvv","bb");
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->isEmpty();
Tab V = Tab("gg", "ggg","g");
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->changeActiveTabTo(3);
Tab B = Tab("mm", "ooo","ww");
wind->getActiveTab();
wind->changeActiveTabTo(4);
Tab T = Tab("ss", "u","f");
wind->isEmpty();
Tab Z = Tab("xxx", "t","a");
wind->moveActiveTabTo(4);
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(1);
wind->closeTab();
wind->print();
wind->print();
Tab A = Tab("u", "j","mm");
wind->closeTab();
Tab D = Tab("zz", "b","bbb");
wind->moveActiveTabTo(3);
wind->getActiveTab();
wind->print();
wind->print();
wind->print();
wind->changeActiveTabTo(4);
wind->print();
wind->changeActiveTabTo(5);
Tab J = Tab("bbb", "xx","qqq");
wind->print();
wind->getActiveTab();
wind->isEmpty();
Tab P = Tab("bb", "kk","j");
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->getActiveTab();
wind->print();
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(2);
wind->newTab(A);
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(1);
wind->print();
Tab I = Tab("nnn", "kkk","aa");
wind->isEmpty();
Tab Q = Tab("g", "u","f");
wind->moveActiveTabTo(0);
wind->newTab(B);
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->getActiveTab();
Tab Y = Tab("hh", "rr","ddd");
wind->print();
wind->print();
wind->isEmpty();
wind->print();
wind->getActiveTab();
Tab G = Tab("ff", "jj","ll");
wind->getActiveTab();
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(0);
wind->closeTab();
wind->getActiveTab();
wind->moveActiveTabTo(1);
wind->closeTab();
wind->getActiveTab();
wind->newTab(D);
Tab X = Tab("u", "i","xx");
wind->closeTab();
wind->isEmpty();
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->closeTab();
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->newTab(E);
Tab S = Tab("mm", "lll","jjj");
wind->newTab(G);
wind->newTab(H);
wind->moveActiveTabTo(4);
wind->closeTab();
wind->moveActiveTabTo(5);
wind->closeTab();
wind->print();
wind->isEmpty();
wind->closeTab();
wind->print();
wind->isEmpty();
wind->print();
wind->print();
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->isEmpty();
delete wind;
}
	return 0;
}