#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->closeTab();
Tab M = Tab("sss", "ww","a");
wind->changeActiveTabTo(1);
Tab S = Tab("ttt", "fff","l");
wind->newTab(M);
Tab L = Tab("gg", "xxx","lll");
wind->changeActiveTabTo(4);
Tab Q = Tab("r", "lll","fff");
wind->newTab(L);
Tab X = Tab("qq", "mm","rrr");
wind->moveActiveTabTo(0);
Tab W = Tab("vvv", "tt","aa");
wind->newTab(Q);
Tab C = Tab("s", "dd","mmm");
wind->closeTab();
Tab Z = Tab("jj", "ccc","p");
wind->isEmpty();
Tab Y = Tab("nn", "fff","ww");
wind->moveActiveTabTo(5);
Tab B = Tab("uu", "bb","g");
wind->moveActiveTabTo(5);
Tab R = Tab("oo", "c","mmm");
wind->getActiveTab();
Tab O = Tab("vv", "z","gg");
wind->isEmpty();
Tab I = Tab("r", "ii","mm");
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(3);
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(4);
wind->closeTab();
wind->print();
Tab G = Tab("y", "v","fff");
wind->print();
wind->isEmpty();
Tab E = Tab("n", "kk","aaa");
wind->print();
Tab U = Tab("ff", "iii","kk");
wind->isEmpty();
Tab T = Tab("w", "uuu","zzz");
wind->moveActiveTabTo(1);
wind->print();
Tab A = Tab("nn", "ccc","ooo");
wind->print();
Tab F = Tab("ttt", "hh","ddd");
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->moveActiveTabTo(3);
Tab P = Tab("m", "y","yyy");
wind->newTab(A);
wind->isEmpty();
Tab V = Tab("xx", "ff","bb");
wind->print();
Tab K = Tab("tt", "ff","vvv");
wind->getActiveTab();
wind->newTab(B);
wind->print();
wind->getActiveTab();
wind->isEmpty();
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
Tab J = Tab("n", "i","uu");
wind->print();
wind->isEmpty();
wind->closeTab();
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(3);
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(4);
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->newTab(C);
wind->newTab(E);
wind->changeActiveTabTo(3);
Tab H = Tab("bbb", "u","zz");
wind->print();
wind->getActiveTab();
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
wind->print();
Tab D = Tab("bbb", "l","ii");
wind->print();
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(2);
wind->getActiveTab();
wind->isEmpty();
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->moveActiveTabTo(4);
wind->print();
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(5);
wind->isEmpty();
wind->newTab(D);
wind->isEmpty();
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(4);
wind->isEmpty();
wind->isEmpty();
wind->newTab(F);
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->getActiveTab();
wind->isEmpty();
wind->print();
wind->getActiveTab();
wind->newTab(G);
wind->newTab(H);
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->getActiveTab();
wind->newTab(I);
delete wind;
}
	return 0;
}