#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->moveActiveTabTo(4);
Tab G = Tab("n", "uu","zzz");
wind->changeActiveTabTo(5);
wind->newTab(G);
Tab N = Tab("uuu", "mmm","j");
wind->closeTab();
Tab Z = Tab("mm", "y","xxx");
wind->print();
Tab H = Tab("uu", "sss","kk");
wind->newTab(H);
Tab K = Tab("bbb", "zz","o");
wind->changeActiveTabTo(5);
Tab F = Tab("nnn", "y","iii");
wind->isEmpty();
Tab I = Tab("aaa", "ee","vv");
wind->print();
Tab W = Tab("vv", "r","a");
wind->moveActiveTabTo(4);
Tab B = Tab("b", "f","ccc");
wind->moveActiveTabTo(4);
Tab D = Tab("yyy", "n","tt");
wind->closeTab();
wind->newTab(B);
Tab X = Tab("tt", "ee","ggg");
wind->isEmpty();
Tab O = Tab("jj", "ww","gg");
wind->newTab(D);
wind->newTab(F);
wind->newTab(I);
wind->print();
wind->getActiveTab();
Tab A = Tab("w", "vv","jjj");
wind->moveActiveTabTo(3);
Tab V = Tab("oo", "www","rr");
wind->print();
wind->changeActiveTabTo(0);
wind->closeTab();
Tab M = Tab("ppp", "rr","jjj");
wind->moveActiveTabTo(3);
wind->isEmpty();
Tab P = Tab("ii", "d","rr");
wind->changeActiveTabTo(4);
wind->closeTab();
wind->getActiveTab();
wind->moveActiveTabTo(0);
Tab Y = Tab("aaa", "e","u");
wind->getActiveTab();
wind->closeTab();
wind->getActiveTab();
wind->newTab(A);
wind->closeTab();
wind->getActiveTab();
wind->print();
Tab E = Tab("zzz", "e","b");
wind->changeActiveTabTo(2);
wind->newTab(E);
wind->newTab(K);
wind->isEmpty();
Tab Q = Tab("ttt", "nnn","k");
wind->print();
wind->getActiveTab();
Tab C = Tab("uuu", "y","dd");
wind->print();
Tab L = Tab("s", "e","x");
wind->changeActiveTabTo(4);
wind->changeActiveTabTo(5);
Tab S = Tab("tt", "mm","vv");
wind->closeTab();
wind->newTab(C);
Tab R = Tab("q", "hhh","v");
wind->moveActiveTabTo(3);
wind->print();
wind->print();
wind->newTab(L);
wind->getActiveTab();
wind->closeTab();
wind->print();
wind->moveActiveTabTo(2);
wind->getActiveTab();
wind->closeTab();
Tab J = Tab("ee", "l","aaa");
wind->closeTab();
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(4);
wind->newTab(J);
wind->closeTab();
wind->isEmpty();
Tab T = Tab("h", "ww","uu");
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(5);
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->newTab(M);
wind->isEmpty();
wind->isEmpty();
wind->newTab(N);
wind->print();
wind->getActiveTab();
wind->print();
wind->closeTab();
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(5);
wind->print();
wind->closeTab();
wind->isEmpty();
wind->closeTab();
wind->moveActiveTabTo(5);
wind->newTab(O);
wind->closeTab();
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(1);
wind->getActiveTab();
wind->newTab(P);
wind->changeActiveTabTo(5);
wind->closeTab();
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(2);
wind->closeTab();
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->print();
delete wind;
}
	return 0;
}