#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->getActiveTab();
Tab G = Tab("g", "o","vvv");
wind->print();
Tab K = Tab("aaa", "s","z");
wind->changeActiveTabTo(2);
Tab Y = Tab("hh", "hh","eee");
wind->print();
Tab J = Tab("bbb", "ttt","kk");
wind->isEmpty();
Tab N = Tab("ooo", "mm","rr");
wind->changeActiveTabTo(5);
Tab V = Tab("ppp", "uuu","vv");
wind->closeTab();
wind->moveActiveTabTo(4);
Tab O = Tab("g", "zz","ff");
wind->moveActiveTabTo(4);
Tab U = Tab("uu", "mmm","jjj");
wind->print();
Tab M = Tab("x", "p","bbb");
wind->getActiveTab();
Tab C = Tab("jjj", "k","bb");
wind->closeTab();
Tab T = Tab("ll", "yy","xx");
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
wind->getActiveTab();
Tab F = Tab("d", "cc","v");
wind->closeTab();
wind->closeTab();
Tab X = Tab("p", "w","b");
wind->print();
Tab E = Tab("ll", "tt","h");
wind->changeActiveTabTo(4);
Tab Q = Tab("ii", "n","ss");
wind->closeTab();
wind->print();
Tab W = Tab("x", "aa","n");
wind->moveActiveTabTo(4);
Tab A = Tab("sss", "aa","v");
wind->changeActiveTabTo(0);
Tab Z = Tab("yyy", "r","ooo");
wind->changeActiveTabTo(1);
wind->print();
wind->changeActiveTabTo(4);
Tab D = Tab("aaa", "jjj","g");
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(2);
Tab R = Tab("ll", "z","p");
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->print();
wind->newTab(A);
wind->getActiveTab();
wind->isEmpty();
wind->newTab(C);
wind->isEmpty();
wind->closeTab();
wind->closeTab();
wind->moveActiveTabTo(4);
Tab P = Tab("iii", "uuu","ee");
wind->newTab(D);
Tab H = Tab("bb", "hhh","ggg");
wind->changeActiveTabTo(0);
wind->newTab(E);
wind->getActiveTab();
wind->moveActiveTabTo(4);
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
wind->changeActiveTabTo(4);
wind->print();
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->newTab(F);
wind->print();
wind->changeActiveTabTo(1);
wind->print();
wind->moveActiveTabTo(1);
wind->newTab(G);
wind->newTab(H);
Tab L = Tab("mmm", "g","k");
wind->print();
wind->moveActiveTabTo(1);
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(1);
wind->getActiveTab();
wind->closeTab();
wind->closeTab();
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->newTab(J);
wind->newTab(K);
wind->newTab(L);
wind->closeTab();
wind->newTab(M);
Tab S = Tab("bbb", "g","l");
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->print();
wind->changeActiveTabTo(4);
wind->newTab(N);
wind->newTab(O);
wind->moveActiveTabTo(5);
wind->print();
wind->isEmpty();
wind->closeTab();
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->print();
wind->newTab(P);
wind->closeTab();
Tab B = Tab("xx", "mmm","rr");
wind->changeActiveTabTo(1);
wind->isEmpty();
wind->print();
wind->closeTab();
delete wind;
}
	return 0;
}