#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->getActiveTab();
Tab L = Tab("yyy", "ooo","ee");
wind->print();
Tab E = Tab("rr", "vv","ll");
wind->getActiveTab();
Tab P = Tab("yy", "gg","j");
wind->closeTab();
Tab A = Tab("kkk", "x","ddd");
wind->closeTab();
wind->newTab(A);
wind->print();
Tab U = Tab("ttt", "ww","z");
wind->print();
Tab K = Tab("jjj", "eee","ll");
wind->getActiveTab();
Tab W = Tab("t", "xx","b");
wind->isEmpty();
wind->isEmpty();
Tab D = Tab("dd", "yy","eee");
wind->print();
wind->newTab(D);
Tab Z = Tab("www", "ppp","jj");
wind->changeActiveTabTo(3);
wind->print();
Tab N = Tab("h", "ccc","o");
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(3);
Tab Y = Tab("cc", "yy","e");
wind->newTab(E);
Tab F = Tab("eee", "gg","xx");
wind->print();
Tab X = Tab("l", "ttt","b");
wind->moveActiveTabTo(5);
wind->newTab(F);
Tab J = Tab("hhh", "ww","u");
wind->moveActiveTabTo(0);
Tab M = Tab("dd", "kk","gg");
wind->moveActiveTabTo(1);
Tab C = Tab("ooo", "aaa","fff");
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->getActiveTab();
wind->isEmpty();
Tab I = Tab("gg", "j","eee");
wind->isEmpty();
wind->getActiveTab();
wind->print();
wind->newTab(C);
wind->print();
Tab S = Tab("aa", "a","i");
wind->closeTab();
wind->closeTab();
wind->closeTab();
wind->moveActiveTabTo(1);
wind->print();
wind->closeTab();
wind->isEmpty();
wind->newTab(I);
wind->changeActiveTabTo(1);
Tab H = Tab("ff", "t","oo");
wind->newTab(H);
wind->changeActiveTabTo(1);
wind->isEmpty();
wind->print();
Tab O = Tab("jjj", "v","zzz");
wind->closeTab();
wind->isEmpty();
Tab R = Tab("a", "zz","eee");
wind->getActiveTab();
Tab B = Tab("lll", "mm","mmm");
wind->changeActiveTabTo(2);
wind->moveActiveTabTo(5);
wind->newTab(B);
wind->newTab(J);
Tab V = Tab("f", "s","nn");
wind->newTab(K);
wind->closeTab();
wind->changeActiveTabTo(4);
wind->isEmpty();
wind->getActiveTab();
Tab G = Tab("s", "iii","e");
wind->changeActiveTabTo(2);
wind->moveActiveTabTo(5);
wind->newTab(G);
wind->newTab(L);
wind->closeTab();
Tab T = Tab("o", "bb","nnn");
wind->closeTab();
wind->getActiveTab();
wind->print();
wind->closeTab();
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(3);
wind->print();
wind->moveActiveTabTo(4);
wind->getActiveTab();
Tab Q = Tab("bb", "vvv","kkk");
wind->closeTab();
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->getActiveTab();
wind->print();
wind->moveActiveTabTo(3);
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(5);
wind->print();
wind->newTab(M);
wind->getActiveTab();
wind->getActiveTab();
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(4);
wind->newTab(N);
wind->changeActiveTabTo(3);
wind->newTab(O);
wind->isEmpty();
wind->isEmpty();
wind->getActiveTab();
wind->isEmpty();
wind->print();
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(2);
wind->print();
wind->print();
delete wind;
}
	return 0;
}