#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->isEmpty();
Tab F = Tab("xx", "k","yy");
wind->isEmpty();
Tab N = Tab("f", "qqq","vv");
wind->isEmpty();
Tab S = Tab("yy", "ooo","n");
wind->moveActiveTabTo(1);
Tab B = Tab("sss", "qqq","uu");
wind->getActiveTab();
Tab M = Tab("uu", "x","ll");
wind->changeActiveTabTo(4);
Tab L = Tab("jj", "xx","xx");
wind->newTab(B);
Tab G = Tab("ddd", "yy","x");
wind->print();
wind->closeTab();
Tab Z = Tab("k", "j","tt");
wind->isEmpty();
Tab I = Tab("l", "f","rr");
wind->closeTab();
Tab U = Tab("y", "zzz","z");
wind->print();
Tab A = Tab("f", "dd","j");
wind->closeTab();
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->getActiveTab();
wind->moveActiveTabTo(3);
Tab D = Tab("o", "u","rrr");
wind->moveActiveTabTo(2);
wind->closeTab();
wind->isEmpty();
wind->print();
Tab H = Tab("t", "xxx","oo");
wind->newTab(A);
Tab K = Tab("ss", "kkk","rr");
wind->isEmpty();
Tab Q = Tab("v", "kk","ccc");
wind->isEmpty();
wind->closeTab();
wind->closeTab();
wind->isEmpty();
Tab V = Tab("oo", "yyy","yy");
wind->isEmpty();
wind->newTab(D);
Tab P = Tab("m", "xxx","o");
wind->newTab(F);
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->isEmpty();
Tab C = Tab("yyy", "h","dd");
wind->print();
Tab O = Tab("nn", "qqq","o");
wind->changeActiveTabTo(2);
Tab W = Tab("m", "kkk","zzz");
wind->newTab(C);
Tab R = Tab("sss", "uuu","rrr");
wind->closeTab();
wind->newTab(G);
Tab E = Tab("x", "aa","yy");
wind->closeTab();
Tab T = Tab("n", "fff","qqq");
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
wind->newTab(E);
wind->closeTab();
wind->moveActiveTabTo(2);
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->closeTab();
wind->changeActiveTabTo(1);
wind->isEmpty();
wind->closeTab();
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->print();
Tab X = Tab("ggg", "uu","p");
wind->newTab(H);
wind->getActiveTab();
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(3);
wind->closeTab();
wind->closeTab();
wind->getActiveTab();
wind->newTab(I);
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
wind->print();
wind->print();
wind->closeTab();
wind->isEmpty();
Tab J = Tab("sss", "e","q");
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(0);
wind->getActiveTab();
Tab Y = Tab("gg", "zz","ii");
wind->print();
wind->print();
wind->print();
wind->moveActiveTabTo(3);
wind->moveActiveTabTo(2);
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(5);
wind->closeTab();
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(2);
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->print();
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(3);
wind->newTab(J);
wind->print();
wind->print();
delete wind;
}
	return 0;
}