#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->closeTab();
Tab I = Tab("qq", "cc","ggg");
wind->changeActiveTabTo(3);
Tab S = Tab("p", "v","iii");
wind->moveActiveTabTo(0);
Tab G = Tab("vvv", "jjj","k");
wind->getActiveTab();
Tab P = Tab("f", "h","ccc");
wind->print();
Tab X = Tab("p", "ggg","pp");
wind->print();
Tab C = Tab("t", "hh","kkk");
wind->moveActiveTabTo(0);
Tab A = Tab("ddd", "z","iii");
wind->isEmpty();
Tab B = Tab("ww", "t","t");
wind->moveActiveTabTo(5);
Tab L = Tab("v", "vvv","yy");
wind->getActiveTab();
Tab N = Tab("aaa", "xxx","jjj");
wind->getActiveTab();
wind->newTab(A);
Tab R = Tab("dd", "www","www");
wind->isEmpty();
Tab D = Tab("ff", "r","qqq");
wind->closeTab();
wind->changeActiveTabTo(2);
wind->print();
Tab T = Tab("jj", "dd","fff");
wind->getActiveTab();
Tab Q = Tab("ii", "f","s");
wind->changeActiveTabTo(1);
wind->print();
Tab O = Tab("a", "jj","nn");
wind->isEmpty();
wind->moveActiveTabTo(2);
Tab Y = Tab("j", "ddd","jjj");
wind->moveActiveTabTo(2);
Tab K = Tab("b", "d","zzz");
wind->closeTab();
wind->isEmpty();
wind->newTab(B);
wind->closeTab();
Tab W = Tab("hhh", "jjj","k");
wind->newTab(C);
wind->moveActiveTabTo(4);
Tab V = Tab("pp", "jj","g");
wind->moveActiveTabTo(4);
wind->changeActiveTabTo(2);
wind->getActiveTab();
Tab M = Tab("bb", "n","zz");
wind->newTab(D);
wind->newTab(G);
wind->getActiveTab();
wind->closeTab();
Tab J = Tab("ww", "ccc","dd");
wind->isEmpty();
Tab Z = Tab("ccc", "kkk","bbb");
wind->newTab(I);
wind->closeTab();
wind->newTab(J);
Tab H = Tab("zzz", "hh","bb");
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->getActiveTab();
wind->print();
wind->moveActiveTabTo(3);
wind->getActiveTab();
wind->print();
Tab F = Tab("y", "nnn","z");
wind->newTab(F);
wind->print();
wind->changeActiveTabTo(5);
wind->print();
wind->closeTab();
wind->moveActiveTabTo(0);
wind->newTab(H);
wind->closeTab();
wind->isEmpty();
wind->moveActiveTabTo(2);
Tab U = Tab("jjj", "ii","ff");
wind->moveActiveTabTo(3);
wind->getActiveTab();
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->print();
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->isEmpty();
wind->changeActiveTabTo(4);
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(2);
wind->moveActiveTabTo(5);
wind->closeTab();
wind->moveActiveTabTo(5);
wind->newTab(K);
wind->print();
wind->print();
wind->print();
wind->changeActiveTabTo(3);
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(4);
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->moveActiveTabTo(1);
wind->moveActiveTabTo(2);
wind->moveActiveTabTo(3);
wind->closeTab();
Tab E = Tab("g", "dd","c");
wind->print();
wind->newTab(E);
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->isEmpty();
wind->print();
wind->getActiveTab();
wind->closeTab();
wind->newTab(L);
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(2);
delete wind;
}
	return 0;
}