#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->isEmpty();
Tab R = Tab("i", "uuu","aa");
wind->changeActiveTabTo(5);
Tab V = Tab("gg", "r","vv");
wind->print();
Tab D = Tab("m", "t","ll");
wind->changeActiveTabTo(3);
Tab Q = Tab("yyy", "oo","k");
wind->moveActiveTabTo(4);
Tab K = Tab("www", "v","hh");
wind->changeActiveTabTo(3);
Tab A = Tab("ll", "kk","uu");
wind->moveActiveTabTo(2);
wind->getActiveTab();
Tab Y = Tab("kkk", "f","xx");
wind->isEmpty();
Tab B = Tab("sss", "ff","qqq");
wind->newTab(A);
Tab W = Tab("lll", "rrr","jj");
wind->changeActiveTabTo(1);
Tab U = Tab("mm", "eee","q");
wind->isEmpty();
Tab X = Tab("rr", "qq","kk");
wind->isEmpty();
Tab O = Tab("x", "zzz","i");
wind->moveActiveTabTo(4);
wind->print();
Tab C = Tab("ggg", "nnn","o");
wind->moveActiveTabTo(1);
Tab S = Tab("jj", "zz","q");
wind->getActiveTab();
Tab L = Tab("ddd", "h","gg");
wind->closeTab();
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(5);
Tab F = Tab("nnn", "www","s");
wind->closeTab();
wind->changeActiveTabTo(5);
wind->getActiveTab();
wind->moveActiveTabTo(4);
Tab P = Tab("g", "q","gg");
wind->closeTab();
wind->getActiveTab();
Tab H = Tab("vvv", "cc","o");
wind->closeTab();
Tab Z = Tab("yy", "zz","g");
wind->print();
wind->changeActiveTabTo(4);
Tab G = Tab("mmm", "qq","b");
wind->closeTab();
wind->isEmpty();
Tab J = Tab("pp", "d","vvv");
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->closeTab();
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(1);
wind->newTab(B);
wind->newTab(C);
Tab I = Tab("z", "x","c");
wind->getActiveTab();
wind->isEmpty();
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(3);
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->newTab(D);
wind->isEmpty();
wind->isEmpty();
wind->newTab(F);
wind->print();
wind->changeActiveTabTo(4);
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(0);
wind->newTab(G);
Tab M = Tab("xx", "kkk","q");
wind->closeTab();
wind->changeActiveTabTo(1);
wind->newTab(H);
wind->print();
Tab T = Tab("zzz", "sss","v");
wind->moveActiveTabTo(4);
wind->newTab(I);
Tab N = Tab("qq", "ttt","xxx");
wind->print();
wind->closeTab();
wind->newTab(J);
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->changeActiveTabTo(4);
wind->newTab(K);
wind->closeTab();
wind->newTab(L);
wind->getActiveTab();
wind->isEmpty();
wind->getActiveTab();
wind->closeTab();
wind->print();
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(2);
wind->closeTab();
wind->print();
wind->closeTab();
wind->moveActiveTabTo(4);
wind->changeActiveTabTo(1);
wind->closeTab();
wind->closeTab();
wind->changeActiveTabTo(4);
wind->newTab(M);
wind->changeActiveTabTo(5);
wind->newTab(N);
wind->getActiveTab();
wind->changeActiveTabTo(5);
Tab E = Tab("d", "c","x");
wind->print();
wind->newTab(E);
wind->print();
wind->moveActiveTabTo(0);
delete wind;
}
	return 0;
}