#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->print();
Tab E = Tab("hhh", "ddd","s");
wind->isEmpty();
Tab C = Tab("gg", "mmm","fff");
wind->closeTab();
Tab O = Tab("yy", "lll","fff");
wind->closeTab();
wind->newTab(C);
wind->newTab(E);
Tab V = Tab("yyy", "p","jjj");
wind->closeTab();
wind->moveActiveTabTo(2);
wind->newTab(O);
Tab J = Tab("kk", "w","www");
wind->changeActiveTabTo(5);
Tab M = Tab("aaa", "jjj","mm");
wind->print();
wind->closeTab();
Tab I = Tab("j", "ll","s");
wind->print();
Tab A = Tab("qq", "zzz","uuu");
wind->newTab(A);
Tab N = Tab("uuu", "nnn","ww");
wind->changeActiveTabTo(4);
wind->isEmpty();
Tab X = Tab("ee", "f","v");
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->print();
wind->changeActiveTabTo(5);
wind->closeTab();
Tab Q = Tab("eee", "k","s");
wind->newTab(I);
wind->print();
Tab H = Tab("e", "ff","m");
wind->changeActiveTabTo(2);
wind->print();
Tab B = Tab("iii", "jj","ddd");
wind->newTab(B);
wind->closeTab();
wind->moveActiveTabTo(1);
wind->closeTab();
wind->isEmpty();
wind->newTab(H);
wind->print();
Tab Y = Tab("e", "jj","r");
wind->isEmpty();
wind->getActiveTab();
Tab R = Tab("jj", "e","qq");
wind->newTab(J);
Tab L = Tab("kk", "ttt","n");
wind->isEmpty();
wind->closeTab();
wind->moveActiveTabTo(1);
wind->closeTab();
wind->getActiveTab();
Tab T = Tab("y", "xxx","ggg");
wind->isEmpty();
Tab P = Tab("n", "qqq","bbb");
wind->newTab(L);
wind->newTab(M);
wind->print();
wind->getActiveTab();
wind->changeActiveTabTo(0);
wind->print();
wind->isEmpty();
wind->newTab(N);
wind->changeActiveTabTo(4);
wind->getActiveTab();
wind->newTab(P);
wind->moveActiveTabTo(5);
wind->print();
wind->print();
wind->closeTab();
Tab S = Tab("u", "p","ee");
wind->closeTab();
wind->newTab(Q);
Tab W = Tab("ccc", "uuu","t");
wind->moveActiveTabTo(3);
Tab F = Tab("mm", "s","jj");
wind->print();
Tab G = Tab("aa", "xx","hhh");
wind->print();
wind->closeTab();
Tab Z = Tab("ss", "bb","qq");
wind->newTab(F);
wind->getActiveTab();
wind->moveActiveTabTo(2);
wind->print();
Tab D = Tab("ss", "a","k");
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(3);
wind->getActiveTab();
wind->isEmpty();
wind->print();
wind->isEmpty();
wind->newTab(D);
wind->print();
wind->isEmpty();
Tab U = Tab("iii", "d","r");
wind->print();
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->print();
wind->newTab(G);
wind->isEmpty();
Tab K = Tab("f", "ccc","oo");
wind->newTab(K);
wind->moveActiveTabTo(0);
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->closeTab();
wind->moveActiveTabTo(1);
wind->moveActiveTabTo(2);
wind->newTab(R);
wind->getActiveTab();
wind->closeTab();
wind->newTab(S);
wind->moveActiveTabTo(4);
wind->closeTab();
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->getActiveTab();
delete wind;
}
	return 0;
}