#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
Tab C = Tab("gg", "oo","qqq");
wind->print();
Tab B = Tab("zz", "rrr","o");
wind->getActiveTab();
Tab G = Tab("k", "ee","ggg");
wind->closeTab();
Tab S = Tab("u", "hh","vv");
wind->changeActiveTabTo(5);
Tab Z = Tab("ss", "xx","dd");
wind->closeTab();
Tab V = Tab("p", "ii","rr");
wind->print();
Tab U = Tab("k", "bbb","oo");
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->changeActiveTabTo(1);
Tab Q = Tab("bb", "a","aaa");
wind->print();
Tab A = Tab("bb", "rr","kk");
wind->print();
wind->changeActiveTabTo(2);
Tab L = Tab("s", "h","aa");
wind->isEmpty();
Tab X = Tab("hh", "cc","z");
wind->print();
Tab K = Tab("u", "rr","mm");
wind->changeActiveTabTo(4);
Tab E = Tab("ii", "f","ee");
wind->isEmpty();
Tab Y = Tab("i", "l","b");
wind->changeActiveTabTo(1);
Tab N = Tab("mm", "hh","b");
wind->isEmpty();
wind->getActiveTab();
wind->print();
wind->print();
Tab R = Tab("vv", "mm","kkk");
wind->newTab(A);
wind->newTab(B);
wind->getActiveTab();
wind->newTab(C);
Tab M = Tab("v", "s","eee");
wind->newTab(E);
Tab T = Tab("i", "tt","aa");
wind->isEmpty();
wind->print();
wind->newTab(G);
wind->closeTab();
wind->newTab(K);
wind->changeActiveTabTo(1);
Tab O = Tab("iii", "ee","fff");
wind->newTab(L);
wind->print();
wind->isEmpty();
wind->isEmpty();
Tab H = Tab("oo", "pp","t");
wind->newTab(H);
wind->print();
wind->isEmpty();
wind->newTab(M);
wind->closeTab();
wind->getActiveTab();
wind->print();
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->newTab(N);
wind->closeTab();
wind->isEmpty();
Tab J = Tab("xx", "w","d");
wind->closeTab();
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->changeActiveTabTo(5);
Tab D = Tab("ss", "e","eee");
wind->getActiveTab();
wind->newTab(D);
wind->print();
wind->newTab(J);
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
wind->newTab(O);
wind->moveActiveTabTo(5);
Tab I = Tab("i", "v","iii");
wind->closeTab();
Tab P = Tab("ooo", "nn","bbb");
wind->moveActiveTabTo(2);
wind->print();
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(3);
wind->changeActiveTabTo(2);
wind->closeTab();
wind->isEmpty();
wind->print();
wind->changeActiveTabTo(5);
wind->print();
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
wind->newTab(I);
wind->isEmpty();
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->closeTab();
wind->closeTab();
wind->moveActiveTabTo(4);
wind->newTab(P);
wind->moveActiveTabTo(0);
wind->print();
wind->newTab(Q);
wind->changeActiveTabTo(2);
wind->closeTab();
wind->print();
wind->newTab(R);
Tab W = Tab("mm", "d","iii");
wind->getActiveTab();
wind->isEmpty();
wind->print();
wind->newTab(S);
wind->isEmpty();
wind->changeActiveTabTo(4);
wind->changeActiveTabTo(4);
wind->print();
delete wind;
}
	return 0;
}