#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
Tab A = Tab("j", "hh","qqq");
wind->getActiveTab();
Tab B = Tab("zz", "q","v");
wind->newTab(A);
Tab G = Tab("nn", "ooo","nnn");
wind->newTab(B);
wind->changeActiveTabTo(0);
Tab M = Tab("ooo", "z","dd");
wind->changeActiveTabTo(0);
wind->closeTab();
Tab U = Tab("e", "hhh","sss");
wind->print();
wind->getActiveTab();
Tab T = Tab("xxx", "oo","bb");
wind->closeTab();
Tab Z = Tab("kkk", "qqq","n");
wind->closeTab();
wind->getActiveTab();
Tab V = Tab("kk", "zz","jjj");
wind->closeTab();
Tab E = Tab("b", "u","qqq");
wind->isEmpty();
Tab O = Tab("ppp", "iii","a");
wind->changeActiveTabTo(0);
wind->getActiveTab();
Tab P = Tab("xxx", "z","yyy");
wind->isEmpty();
wind->newTab(E);
wind->print();
Tab Q = Tab("kk", "jj","l");
wind->closeTab();
Tab S = Tab("uuu", "uuu","rrr");
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(4);
Tab Y = Tab("iii", "a","hhh");
wind->isEmpty();
Tab X = Tab("l", "pp","v");
wind->moveActiveTabTo(0);
Tab W = Tab("v", "ooo","u");
wind->closeTab();
wind->closeTab();
wind->moveActiveTabTo(5);
Tab J = Tab("lll", "uu","gg");
wind->print();
wind->changeActiveTabTo(0);
Tab H = Tab("hh", "s","vvv");
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->closeTab();
Tab I = Tab("qqq", "vvv","gg");
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(5);
Tab K = Tab("q", "rr","k");
wind->newTab(G);
wind->newTab(H);
wind->newTab(I);
wind->print();
wind->moveActiveTabTo(0);
Tab C = Tab("www", "v","ii");
wind->print();
Tab R = Tab("l", "i","k");
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(2);
wind->closeTab();
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->newTab(C);
Tab F = Tab("f", "b","vvv");
wind->print();
wind->newTab(F);
wind->closeTab();
wind->isEmpty();
wind->print();
wind->isEmpty();
wind->newTab(J);
wind->moveActiveTabTo(5);
wind->closeTab();
wind->changeActiveTabTo(1);
wind->print();
wind->closeTab();
Tab L = Tab("m", "vvv","yyy");
wind->getActiveTab();
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(1);
wind->getActiveTab();
wind->moveActiveTabTo(4);
wind->closeTab();
wind->moveActiveTabTo(1);
wind->moveActiveTabTo(1);
wind->closeTab();
wind->newTab(K);
wind->moveActiveTabTo(2);
wind->closeTab();
wind->changeActiveTabTo(3);
wind->print();
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->newTab(L);
wind->moveActiveTabTo(4);
wind->isEmpty();
wind->closeTab();
wind->moveActiveTabTo(3);
Tab D = Tab("aa", "bb","c");
wind->moveActiveTabTo(2);
wind->getActiveTab();
wind->closeTab();
wind->moveActiveTabTo(5);
wind->closeTab();
wind->print();
wind->moveActiveTabTo(1);
wind->newTab(D);
wind->closeTab();
Tab N = Tab("aaa", "ccc","i");
wind->print();
wind->moveActiveTabTo(1);
wind->closeTab();
wind->isEmpty();
delete wind;
}
	return 0;
}