#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->isEmpty();
Tab S = Tab("uuu", "kk","nn");
wind->moveActiveTabTo(3);
Tab V = Tab("ii", "mmm","hhh");
wind->newTab(S);
Tab G = Tab("vv", "dd","ww");
wind->changeActiveTabTo(4);
Tab N = Tab("kk", "www","xx");
wind->moveActiveTabTo(3);
Tab F = Tab("a", "gg","jjj");
wind->isEmpty();
Tab I = Tab("b", "x","n");
wind->getActiveTab();
Tab B = Tab("dd", "vv","t");
wind->print();
wind->print();
wind->print();
Tab W = Tab("bb", "qqq","qq");
wind->newTab(B);
Tab L = Tab("m", "yy","eee");
wind->getActiveTab();
Tab U = Tab("jjj", "s","v");
wind->moveActiveTabTo(4);
Tab D = Tab("dd", "dd","j");
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->changeActiveTabTo(2);
Tab C = Tab("t", "lll","ppp");
wind->changeActiveTabTo(4);
wind->isEmpty();
Tab R = Tab("ggg", "fff","w");
wind->print();
wind->newTab(C);
wind->closeTab();
Tab J = Tab("ddd", "sss","oo");
wind->newTab(D);
Tab X = Tab("o", "rr","dd");
wind->isEmpty();
Tab H = Tab("uu", "oo","mm");
wind->newTab(F);
Tab Z = Tab("p", "hhh","nn");
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->isEmpty();
Tab E = Tab("v", "uu","ccc");
wind->closeTab();
Tab A = Tab("e", "aa","vvv");
wind->moveActiveTabTo(4);
wind->changeActiveTabTo(5);
Tab P = Tab("tt", "w","kk");
wind->getActiveTab();
wind->isEmpty();
wind->closeTab();
wind->closeTab();
wind->changeActiveTabTo(4);
Tab M = Tab("t", "j","ss");
wind->newTab(A);
wind->getActiveTab();
wind->print();
wind->print();
wind->isEmpty();
Tab O = Tab("ddd", "tt","ttt");
wind->print();
wind->print();
wind->isEmpty();
Tab T = Tab("c", "rrr","r");
wind->isEmpty();
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->moveActiveTabTo(2);
Tab Q = Tab("nn", "dd","ttt");
wind->print();
wind->print();
wind->newTab(E);
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->newTab(G);
wind->print();
wind->moveActiveTabTo(0);
Tab Y = Tab("ff", "jj","uuu");
wind->changeActiveTabTo(3);
wind->print();
wind->print();
wind->closeTab();
wind->changeActiveTabTo(1);
wind->isEmpty();
wind->getActiveTab();
wind->newTab(H);
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
wind->getActiveTab();
wind->closeTab();
wind->moveActiveTabTo(2);
wind->closeTab();
wind->newTab(I);
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(5);
wind->closeTab();
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->isEmpty();
wind->closeTab();
wind->moveActiveTabTo(1);
wind->newTab(J);
Tab K = Tab("zzz", "www","i");
wind->closeTab();
wind->isEmpty();
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(3);
wind->closeTab();
wind->closeTab();
wind->changeActiveTabTo(4);
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(K);
wind->closeTab();
wind->changeActiveTabTo(3);
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->newTab(L);
delete wind;
}
	return 0;
}