#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
Tab U = Tab("hh", "rrr","c");
wind->closeTab();
Tab E = Tab("yy", "hh","aaa");
wind->isEmpty();
Tab P = Tab("jjj", "sss","kk");
wind->newTab(E);
Tab A = Tab("ttt", "lll","ppp");
wind->print();
Tab C = Tab("jjj", "zz","g");
wind->print();
Tab K = Tab("mmm", "jj","zz");
wind->closeTab();
Tab X = Tab("h", "ss","dd");
wind->changeActiveTabTo(0);
Tab D = Tab("ii", "z","iii");
wind->print();
Tab H = Tab("x", "aa","j");
wind->changeActiveTabTo(0);
Tab G = Tab("mmm", "ii","xxx");
wind->newTab(A);
Tab V = Tab("y", "tt","sss");
wind->isEmpty();
Tab B = Tab("vv", "nnn","iii");
wind->print();
wind->print();
wind->print();
Tab O = Tab("fff", "l","ppp");
wind->print();
Tab N = Tab("l", "l","x");
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->isEmpty();
wind->getActiveTab();
Tab J = Tab("v", "x","ttt");
wind->newTab(B);
wind->print();
wind->print();
Tab T = Tab("ll", "ff","xx");
wind->print();
wind->moveActiveTabTo(4);
Tab I = Tab("zz", "m","uu");
wind->getActiveTab();
wind->print();
wind->closeTab();
wind->print();
Tab S = Tab("g", "yyy","uuu");
wind->isEmpty();
Tab Q = Tab("ooo", "kkk","ff");
wind->print();
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(2);
wind->moveActiveTabTo(5);
wind->print();
wind->print();
Tab M = Tab("z", "qqq","bb");
wind->print();
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->closeTab();
wind->newTab(C);
wind->closeTab();
wind->print();
wind->closeTab();
wind->newTab(D);
wind->isEmpty();
wind->newTab(G);
Tab Z = Tab("lll", "ooo","kk");
wind->isEmpty();
Tab F = Tab("n", "ppp","e");
wind->moveActiveTabTo(0);
wind->isEmpty();
wind->isEmpty();
wind->getActiveTab();
wind->moveActiveTabTo(2);
Tab L = Tab("rr", "f","j");
wind->print();
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(4);
wind->closeTab();
wind->newTab(F);
wind->changeActiveTabTo(5);
wind->newTab(H);
wind->print();
wind->changeActiveTabTo(5);
wind->print();
wind->moveActiveTabTo(0);
wind->newTab(I);
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->print();
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(3);
Tab R = Tab("v", "eee","xxx");
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->getActiveTab();
wind->closeTab();
wind->getActiveTab();
Tab W = Tab("hh", "n","t");
wind->closeTab();
wind->closeTab();
wind->closeTab();
wind->closeTab();
wind->changeActiveTabTo(2);
wind->closeTab();
wind->moveActiveTabTo(3);
wind->closeTab();
wind->closeTab();
wind->getActiveTab();
wind->newTab(J);
Tab Y = Tab("ww", "vvv","bbb");
wind->print();
wind->isEmpty();
wind->newTab(K);
wind->moveActiveTabTo(3);
wind->closeTab();
wind->newTab(L);
wind->changeActiveTabTo(0);
delete wind;
}
	return 0;
}