#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
Tab R = Tab("vvv", "cc","t");
wind->isEmpty();
Tab Q = Tab("zz", "fff","h");
wind->newTab(Q);
Tab A = Tab("xx", "z","kkk");
wind->print();
Tab F = Tab("ooo", "q","nn");
wind->getActiveTab();
wind->print();
wind->moveActiveTabTo(1);
Tab W = Tab("b", "qq","vv");
wind->newTab(A);
Tab P = Tab("s", "eee","x");
wind->getActiveTab();
Tab X = Tab("jjj", "d","ooo");
wind->closeTab();
Tab B = Tab("xx", "l","hhh");
wind->newTab(B);
Tab C = Tab("iii", "z","ss");
wind->isEmpty();
Tab H = Tab("v", "z","vv");
wind->isEmpty();
wind->getActiveTab();
Tab V = Tab("rr", "oo","o");
wind->print();
Tab J = Tab("bb", "fff","sss");
wind->isEmpty();
Tab G = Tab("g", "c","j");
wind->newTab(C);
wind->isEmpty();
Tab D = Tab("ll", "cc","e");
wind->closeTab();
wind->print();
wind->isEmpty();
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
Tab T = Tab("h", "c","r");
wind->newTab(D);
Tab L = Tab("hhh", "ddd","mmm");
wind->newTab(F);
wind->changeActiveTabTo(3);
wind->print();
Tab K = Tab("rr", "w","hhh");
wind->print();
Tab E = Tab("t", "m","xxx");
wind->isEmpty();
wind->print();
wind->print();
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(4);
Tab Z = Tab("g", "qqq","rrr");
wind->moveActiveTabTo(4);
wind->closeTab();
Tab M = Tab("dd", "ddd","v");
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->newTab(E);
wind->closeTab();
Tab O = Tab("y", "k","u");
wind->getActiveTab();
Tab N = Tab("qqq", "sss","www");
wind->closeTab();
wind->moveActiveTabTo(5);
Tab S = Tab("c", "q","ss");
wind->print();
wind->getActiveTab();
wind->closeTab();
wind->moveActiveTabTo(3);
Tab I = Tab("t", "hhh","m");
wind->newTab(G);
wind->changeActiveTabTo(5);
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->print();
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
wind->newTab(H);
Tab U = Tab("nn", "aaa","nn");
wind->changeActiveTabTo(2);
wind->moveActiveTabTo(5);
wind->print();
wind->newTab(I);
wind->getActiveTab();
wind->newTab(J);
wind->closeTab();
wind->print();
wind->print();
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->changeActiveTabTo(4);
wind->getActiveTab();
wind->changeActiveTabTo(4);
wind->isEmpty();
wind->print();
wind->closeTab();
wind->getActiveTab();
Tab Y = Tab("aa", "kkk","dd");
wind->changeActiveTabTo(1);
wind->print();
wind->changeActiveTabTo(1);
wind->newTab(K);
wind->closeTab();
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(5);
wind->print();
wind->isEmpty();
wind->closeTab();
wind->print();
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->newTab(L);
wind->newTab(M);
wind->print();
wind->closeTab();
wind->closeTab();
wind->closeTab();
wind->getActiveTab();
delete wind;
}
	return 0;
}