#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->changeActiveTabTo(1);
Tab I = Tab("rrr", "ww","xxx");
wind->closeTab();
Tab W = Tab("xx", "yy","ccc");
wind->isEmpty();
Tab Q = Tab("mm", "yy","jjj");
wind->moveActiveTabTo(5);
Tab D = Tab("ttt", "sss","bbb");
wind->getActiveTab();
Tab U = Tab("v", "hhh","z");
wind->print();
Tab K = Tab("qq", "fff","q");
wind->moveActiveTabTo(5);
Tab V = Tab("jj", "k","o");
wind->isEmpty();
Tab B = Tab("w", "www","ss");
wind->newTab(B);
wind->closeTab();
Tab J = Tab("dd", "eee","aa");
wind->newTab(D);
wind->isEmpty();
wind->closeTab();
Tab S = Tab("rr", "w","f");
wind->getActiveTab();
Tab A = Tab("ppp", "hhh","ddd");
wind->changeActiveTabTo(2);
Tab M = Tab("c", "zz","qqq");
wind->isEmpty();
Tab O = Tab("www", "ll","a");
wind->getActiveTab();
Tab F = Tab("xx", "s","sss");
wind->moveActiveTabTo(1);
wind->print();
Tab E = Tab("p", "ppp","uu");
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(2);
wind->print();
wind->newTab(A);
Tab Z = Tab("yyy", "nn","sss");
wind->print();
Tab Y = Tab("aaa", "m","rr");
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(4);
wind->print();
wind->getActiveTab();
Tab P = Tab("zz", "bb","t");
wind->getActiveTab();
Tab X = Tab("oo", "bbb","j");
wind->print();
Tab H = Tab("zzz", "zz","nnn");
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(4);
wind->closeTab();
wind->newTab(E);
wind->getActiveTab();
Tab T = Tab("rr", "p","qqq");
wind->closeTab();
wind->moveActiveTabTo(4);
wind->newTab(F);
wind->closeTab();
Tab L = Tab("dd", "jj","c");
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->print();
wind->newTab(H);
wind->moveActiveTabTo(4);
Tab C = Tab("o", "vv","oo");
wind->print();
wind->moveActiveTabTo(1);
Tab R = Tab("rrr", "x","ww");
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(5);
wind->print();
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->newTab(C);
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(1);
wind->newTab(I);
wind->newTab(J);
Tab N = Tab("hh", "x","mmm");
wind->newTab(K);
wind->print();
wind->moveActiveTabTo(1);
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->changeActiveTabTo(4);
wind->newTab(L);
wind->print();
wind->newTab(M);
wind->closeTab();
wind->getActiveTab();
wind->changeActiveTabTo(4);
wind->isEmpty();
wind->newTab(N);
wind->print();
wind->changeActiveTabTo(1);
wind->newTab(O);
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->newTab(P);
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(2);
wind->print();
Tab G = Tab("ee", "x","e");
wind->getActiveTab();
wind->closeTab();
wind->print();
wind->print();
wind->closeTab();
wind->print();
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->print();
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(0);
delete wind;
}
	return 0;
}