#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->closeTab();
Tab P = Tab("ttt", "www","c");
wind->isEmpty();
wind->newTab(P);
Tab R = Tab("d", "ooo","bb");
wind->closeTab();
Tab K = Tab("zzz", "ww","ff");
wind->newTab(K);
Tab A = Tab("jj", "ggg","t");
wind->isEmpty();
Tab F = Tab("r", "ff","fff");
wind->getActiveTab();
Tab E = Tab("j", "v","iii");
wind->isEmpty();
wind->newTab(A);
Tab Z = Tab("xx", "ppp","jjj");
wind->newTab(E);
Tab W = Tab("iii", "eee","ww");
wind->closeTab();
Tab B = Tab("ooo", "i","rrr");
wind->closeTab();
wind->isEmpty();
Tab X = Tab("d", "xxx","eee");
wind->isEmpty();
wind->newTab(B);
Tab H = Tab("mm", "ii","www");
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(5);
Tab Q = Tab("p", "pp","pp");
wind->getActiveTab();
wind->isEmpty();
Tab D = Tab("www", "ww","kkk");
wind->changeActiveTabTo(3);
Tab G = Tab("eee", "hhh","rrr");
wind->getActiveTab();
wind->changeActiveTabTo(1);
Tab V = Tab("xxx", "nn","tt");
wind->getActiveTab();
Tab T = Tab("iii", "gg","uuu");
wind->changeActiveTabTo(1);
wind->newTab(D);
Tab O = Tab("n", "ccc","mmm");
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->print();
wind->getActiveTab();
Tab I = Tab("z", "u","q");
wind->print();
Tab C = Tab("r", "bbb","ww");
wind->newTab(C);
wind->changeActiveTabTo(3);
wind->closeTab();
wind->isEmpty();
wind->newTab(F);
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->changeActiveTabTo(4);
wind->isEmpty();
wind->getActiveTab();
wind->isEmpty();
Tab U = Tab("ccc", "yyy","ppp");
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->getActiveTab();
wind->moveActiveTabTo(4);
wind->newTab(G);
Tab S = Tab("o", "m","p");
wind->getActiveTab();
wind->closeTab();
Tab J = Tab("mmm", "t","g");
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(4);
wind->print();
Tab M = Tab("n", "ii","dd");
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(3);
wind->print();
wind->newTab(H);
wind->isEmpty();
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->print();
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->isEmpty();
wind->newTab(I);
wind->getActiveTab();
wind->closeTab();
Tab Y = Tab("bbb", "o","ee");
wind->moveActiveTabTo(3);
wind->print();
wind->getActiveTab();
Tab N = Tab("uu", "t","ss");
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(1);
wind->print();
wind->newTab(J);
wind->changeActiveTabTo(4);
wind->closeTab();
wind->isEmpty();
wind->print();
wind->moveActiveTabTo(2);
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->isEmpty();
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(3);
wind->getActiveTab();
wind->moveActiveTabTo(4);
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
wind->newTab(M);
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->isEmpty();
Tab L = Tab("ddd", "y","t");
delete wind;
}
	return 0;
};

