#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->closeTab();
Tab V = Tab("ll", "ww","xx");
wind->closeTab();
Tab K = Tab("s", "dd","qq");
wind->getActiveTab();
Tab Q = Tab("b", "z","ww");
wind->isEmpty();
Tab G = Tab("x", "zz","k");
wind->moveActiveTabTo(0);
Tab W = Tab("b", "sss","nn");
wind->moveActiveTabTo(1);
wind->isEmpty();
Tab D = Tab("www", "ccc","ss");
wind->print();
Tab S = Tab("hh", "uu","ccc");
wind->print();
Tab F = Tab("cc", "b","dd");
wind->closeTab();
Tab R = Tab("ff", "fff","ee");
wind->closeTab();
Tab X = Tab("u", "hhh","fff");
wind->newTab(D);
Tab Y = Tab("fff", "f","f");
wind->print();
Tab U = Tab("o", "m","q");
wind->print();
wind->getActiveTab();
wind->isEmpty();
wind->closeTab();
Tab C = Tab("e", "i","qqq");
wind->isEmpty();
Tab M = Tab("w", "cc","ooo");
wind->moveActiveTabTo(5);
Tab I = Tab("cc", "t","cc");
wind->moveActiveTabTo(5);
wind->closeTab();
wind->newTab(C);
wind->newTab(F);
Tab O = Tab("n", "v","bbb");
wind->closeTab();
wind->print();
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
Tab E = Tab("w", "x","ww");
wind->closeTab();
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(1);
Tab Z = Tab("mm", "u","f");
wind->print();
Tab A = Tab("ww", "dd","vv");
wind->closeTab();
Tab L = Tab("dd", "vvv","ooo");
wind->changeActiveTabTo(0);
wind->closeTab();
wind->print();
Tab B = Tab("b", "xxx","hhh");
wind->getActiveTab();
Tab H = Tab("e", "p","h");
wind->closeTab();
wind->print();
Tab P = Tab("ll", "n","nn");
wind->closeTab();
wind->moveActiveTabTo(0);
wind->closeTab();
wind->moveActiveTabTo(1);
wind->closeTab();
wind->print();
wind->print();
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(0);
wind->print();
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(4);
wind->changeActiveTabTo(2);
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(4);
wind->closeTab();
wind->print();
wind->changeActiveTabTo(0);
wind->newTab(A);
Tab J = Tab("lll", "uu","ddd");
wind->newTab(B);
Tab T = Tab("mmm", "iii","ee");
wind->getActiveTab();
wind->newTab(E);
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
wind->moveActiveTabTo(5);
wind->closeTab();
wind->moveActiveTabTo(1);
wind->print();
wind->getActiveTab();
wind->closeTab();
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->print();
wind->getActiveTab();
wind->newTab(G);
wind->newTab(H);
wind->changeActiveTabTo(2);
wind->closeTab();
wind->closeTab();
wind->getActiveTab();
wind->isEmpty();
wind->getActiveTab();
wind->newTab(I);
wind->closeTab();
wind->print();
wind->isEmpty();
wind->newTab(J);
wind->print();
wind->isEmpty();
delete wind;
}
	return 0;
}