#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->changeActiveTabTo(5);
Tab K = Tab("t", "cc","sss");
wind->getActiveTab();
Tab Q = Tab("h", "ddd","c");
wind->getActiveTab();
Tab S = Tab("rrr", "eee","kk");
wind->print();
Tab F = Tab("f", "rr","kk");
wind->closeTab();
Tab R = Tab("f", "hhh","v");
wind->changeActiveTabTo(0);
Tab I = Tab("b", "ii","dd");
wind->closeTab();
Tab W = Tab("vv", "z","b");
wind->getActiveTab();
Tab G = Tab("kk", "qq","qqq");
wind->changeActiveTabTo(4);
wind->changeActiveTabTo(4);
Tab U = Tab("ff", "m","qq");
wind->closeTab();
Tab T = Tab("ss", "rrr","y");
wind->closeTab();
Tab N = Tab("y", "p","iii");
wind->print();
Tab Y = Tab("u", "rr","jj");
wind->moveActiveTabTo(5);
Tab J = Tab("p", "r","ee");
wind->isEmpty();
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(0);
wind->newTab(F);
wind->getActiveTab();
Tab H = Tab("s", "dd","hh");
wind->closeTab();
Tab E = Tab("nnn", "ooo","mmm");
wind->isEmpty();
Tab A = Tab("ss", "xxx","tt");
wind->isEmpty();
wind->newTab(A);
Tab C = Tab("oo", "vvv","pp");
wind->print();
wind->isEmpty();
Tab D = Tab("l", "ff","vv");
wind->isEmpty();
wind->print();
wind->changeActiveTabTo(3);
wind->isEmpty();
Tab B = Tab("oo", "j","fff");
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
Tab P = Tab("s", "s","jj");
wind->closeTab();
Tab V = Tab("xx", "uuu","sss");
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->closeTab();
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->isEmpty();
wind->closeTab();
wind->closeTab();
wind->changeActiveTabTo(3);
wind->newTab(B);
Tab X = Tab("jjj", "ll","g");
wind->getActiveTab();
Tab M = Tab("i", "cc","j");
wind->changeActiveTabTo(1);
wind->print();
wind->print();
wind->getActiveTab();
wind->newTab(C);
wind->newTab(D);
wind->newTab(E);
wind->changeActiveTabTo(5);
wind->getActiveTab();
wind->closeTab();
Tab Z = Tab("bb", "cc","g");
wind->isEmpty();
wind->print();
wind->getActiveTab();
wind->print();
wind->isEmpty();
wind->closeTab();
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->closeTab();
wind->getActiveTab();
Tab O = Tab("s", "ww","ii");
wind->newTab(G);
wind->getActiveTab();
wind->isEmpty();
wind->print();
wind->print();
wind->closeTab();
wind->newTab(H);
wind->getActiveTab();
wind->print();
wind->print();
wind->changeActiveTabTo(3);
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->newTab(I);
wind->closeTab();
wind->getActiveTab();
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->getActiveTab();
wind->isEmpty();
wind->newTab(J);
wind->closeTab();
wind->print();
wind->print();
wind->changeActiveTabTo(4);
wind->closeTab();
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->print();
wind->getActiveTab();
delete wind;
}
	return 0;
}