#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->isEmpty();
Tab R = Tab("ooo", "f","hh");
wind->newTab(R);
Tab G = Tab("jjj", "xx","bbb");
wind->isEmpty();
Tab U = Tab("g", "vvv","ddd");
wind->isEmpty();
Tab M = Tab("hh", "e","jjj");
wind->print();
Tab W = Tab("ii", "ttt","ff");
wind->newTab(G);
Tab J = Tab("uuu", "xx","ggg");
wind->changeActiveTabTo(4);
Tab I = Tab("cc", "eee","qqq");
wind->closeTab();
wind->getActiveTab();
Tab E = Tab("g", "qq","rr");
wind->getActiveTab();
wind->getActiveTab();
Tab L = Tab("kk", "oo","nnn");
wind->getActiveTab();
Tab N = Tab("ppp", "ll","x");
wind->moveActiveTabTo(1);
Tab Y = Tab("h", "g","kk");
wind->newTab(E);
wind->closeTab();
wind->print();
Tab O = Tab("c", "nn","b");
wind->closeTab();
Tab S = Tab("mm", "pp","i");
wind->isEmpty();
wind->newTab(I);
wind->print();
wind->isEmpty();
Tab B = Tab("dd", "mm","nnn");
wind->getActiveTab();
wind->print();
wind->isEmpty();
Tab C = Tab("cc", "ppp","eee");
wind->newTab(B);
wind->isEmpty();
wind->getActiveTab();
wind->isEmpty();
wind->print();
Tab H = Tab("yy", "kkk","ff");
wind->print();
Tab A = Tab("v", "ooo","qqq");
wind->isEmpty();
wind->print();
wind->isEmpty();
wind->closeTab();
wind->getActiveTab();
Tab D = Tab("q", "sss","rrr");
wind->getActiveTab();
wind->isEmpty();
Tab P = Tab("s", "vvv","nn");
wind->isEmpty();
Tab V = Tab("yyy", "ss","gg");
wind->print();
Tab K = Tab("r", "ccc","z");
wind->closeTab();
wind->changeActiveTabTo(5);
wind->getActiveTab();
wind->newTab(A);
Tab Z = Tab("c", "jj","m");
wind->closeTab();
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->newTab(C);
wind->isEmpty();
wind->closeTab();
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->print();
Tab Q = Tab("l", "aa","eee");
wind->getActiveTab();
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(1);
wind->print();
wind->changeActiveTabTo(1);
wind->print();
wind->print();
wind->newTab(D);
wind->getActiveTab();
wind->closeTab();
wind->newTab(H);
wind->newTab(J);
wind->newTab(K);
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(1);
wind->closeTab();
wind->newTab(L);
wind->moveActiveTabTo(3);
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
Tab T = Tab("ss", "iii","v");
wind->print();
Tab F = Tab("k", "uu","s");
wind->newTab(F);
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(5);
wind->print();
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->newTab(M);
wind->print();
wind->closeTab();
wind->print();
wind->closeTab();
wind->print();
wind->print();
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(2);
wind->newTab(N);
wind->newTab(O);
wind->isEmpty();
wind->moveActiveTabTo(4);
wind->closeTab();
delete wind;
}
	return 0;
}