#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
Tab Y = Tab("vvv", "hh","w");
wind->isEmpty();
Tab W = Tab("ccc", "u","w");
wind->isEmpty();
Tab I = Tab("rrr", "s","zzz");
wind->newTab(I);
Tab M = Tab("vvv", "xx","g");
wind->isEmpty();
Tab V = Tab("z", "ss","ss");
wind->changeActiveTabTo(3);
Tab L = Tab("vv", "nnn","oo");
wind->changeActiveTabTo(5);
Tab C = Tab("rr", "x","tt");
wind->isEmpty();
Tab E = Tab("o", "w","sss");
wind->isEmpty();
Tab N = Tab("iii", "kkk","t");
wind->print();
wind->newTab(C);
Tab G = Tab("ll", "ii","k");
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->newTab(E);
Tab Q = Tab("lll", "yyy","qq");
wind->closeTab();
Tab K = Tab("rrr", "iii","vv");
wind->isEmpty();
wind->moveActiveTabTo(4);
wind->isEmpty();
wind->newTab(G);
wind->newTab(K);
wind->moveActiveTabTo(1);
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(2);
wind->moveActiveTabTo(5);
Tab Z = Tab("ee", "ww","oo");
wind->isEmpty();
Tab R = Tab("uu", "h","ii");
wind->isEmpty();
wind->print();
wind->newTab(L);
wind->getActiveTab();
wind->print();
wind->moveActiveTabTo(3);
Tab D = Tab("hh", "qqq","y");
wind->closeTab();
Tab P = Tab("j", "i","m");
wind->closeTab();
wind->newTab(D);
Tab J = Tab("ww", "uuu","ee");
wind->moveActiveTabTo(2);
Tab S = Tab("mm", "nn","qqq");
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->print();
Tab A = Tab("xx", "uuu","x");
wind->closeTab();
wind->print();
wind->changeActiveTabTo(5);
wind->print();
wind->isEmpty();
wind->isEmpty();
Tab T = Tab("qqq", "oo","ccc");
wind->isEmpty();
Tab X = Tab("c", "uu","mmm");
wind->closeTab();
wind->newTab(A);
wind->newTab(J);
wind->isEmpty();
Tab U = Tab("jjj", "rrr","s");
wind->isEmpty();
wind->print();
wind->print();
wind->newTab(M);
wind->newTab(N);
wind->changeActiveTabTo(0);
wind->closeTab();
wind->moveActiveTabTo(5);
Tab B = Tab("dd", "s","b");
wind->print();
wind->getActiveTab();
wind->changeActiveTabTo(5);
wind->closeTab();
wind->print();
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->getActiveTab();
wind->closeTab();
wind->newTab(B);
wind->isEmpty();
Tab F = Tab("p", "mmm","cc");
wind->isEmpty();
Tab O = Tab("yyy", "qq","s");
wind->closeTab();
Tab H = Tab("bb", "gg","u");
wind->moveActiveTabTo(4);
wind->isEmpty();
wind->isEmpty();
wind->print();
wind->moveActiveTabTo(1);
wind->getActiveTab();
wind->closeTab();
wind->moveActiveTabTo(4);
wind->print();
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->print();
wind->newTab(F);
wind->newTab(H);
wind->isEmpty();
wind->getActiveTab();
wind->closeTab();
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->newTab(O);
wind->getActiveTab();
wind->isEmpty();
wind->print();
wind->changeActiveTabTo(5);
delete wind;
}
	return 0;
}