#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->getActiveTab();
Tab C = Tab("jjj", "ppp","kkk");
wind->print();
Tab Y = Tab("www", "ll","o");
wind->closeTab();
Tab V = Tab("ss", "lll","hhh");
wind->changeActiveTabTo(3);
Tab X = Tab("ttt", "pp","www");
wind->print();
Tab H = Tab("ccc", "u","bbb");
wind->changeActiveTabTo(4);
Tab B = Tab("ee", "s","ll");
wind->getActiveTab();
Tab D = Tab("ttt", "y","c");
wind->moveActiveTabTo(5);
Tab T = Tab("aaa", "ddd","ff");
wind->isEmpty();
wind->getActiveTab();
Tab W = Tab("t", "d","rr");
wind->changeActiveTabTo(4);
Tab E = Tab("www", "gg","oo");
wind->getActiveTab();
Tab R = Tab("i", "ee","mmm");
wind->closeTab();
Tab Q = Tab("yyy", "gg","xxx");
wind->closeTab();
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(4);
Tab I = Tab("y", "p","e");
wind->getActiveTab();
wind->print();
Tab K = Tab("zzz", "aaa","ii");
wind->getActiveTab();
wind->isEmpty();
Tab M = Tab("fff", "mm","zzz");
wind->print();
Tab N = Tab("ff", "w","jj");
wind->changeActiveTabTo(3);
Tab U = Tab("xx", "kkk","e");
wind->print();
wind->changeActiveTabTo(1);
Tab J = Tab("rrr", "dd","z");
wind->newTab(B);
wind->changeActiveTabTo(0);
wind->print();
wind->changeActiveTabTo(1);
Tab S = Tab("vvv", "qqq","ii");
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->isEmpty();
wind->newTab(C);
wind->newTab(D);
wind->moveActiveTabTo(3);
wind->getActiveTab();
Tab L = Tab("yy", "ooo","z");
wind->newTab(E);
wind->getActiveTab();
wind->isEmpty();
Tab Z = Tab("yy", "sss","g");
wind->closeTab();
Tab P = Tab("o", "ccc","uuu");
wind->changeActiveTabTo(3);
wind->print();
wind->getActiveTab();
Tab F = Tab("zzz", "v","ss");
wind->closeTab();
wind->closeTab();
wind->closeTab();
wind->changeActiveTabTo(2);
Tab A = Tab("l", "t","tt");
wind->newTab(A);
wind->print();
wind->print();
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->closeTab();
wind->closeTab();
wind->newTab(F);
Tab O = Tab("yy", "ddd","sss");
wind->changeActiveTabTo(1);
Tab G = Tab("ttt", "aa","m");
wind->isEmpty();
wind->newTab(G);
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->newTab(H);
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(1);
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->print();
wind->getActiveTab();
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->newTab(I);
wind->changeActiveTabTo(4);
wind->closeTab();
wind->getActiveTab();
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->getActiveTab();
wind->closeTab();
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(2);
wind->closeTab();
wind->newTab(J);
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(3);
wind->isEmpty();
delete wind;
}
	return 0;
}