#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->print();
Tab A = Tab("ii", "m","y");
wind->print();
wind->closeTab();
Tab G = Tab("u", "q","l");
wind->getActiveTab();
Tab F = Tab("s", "ii","vvv");
wind->isEmpty();
Tab P = Tab("f", "yy","uu");
wind->changeActiveTabTo(3);
Tab I = Tab("oo", "i","iii");
wind->closeTab();
Tab W = Tab("nn", "rrr","ee");
wind->changeActiveTabTo(2);
Tab R = Tab("zz", "pp","pp");
wind->print();
Tab J = Tab("r", "zz","qqq");
wind->closeTab();
Tab Q = Tab("nn", "u","cc");
wind->moveActiveTabTo(2);
Tab H = Tab("x", "q","tt");
wind->closeTab();
Tab M = Tab("uuu", "y","ooo");
wind->getActiveTab();
Tab B = Tab("t", "nnn","kk");
wind->closeTab();
wind->moveActiveTabTo(1);
wind->newTab(A);
wind->print();
wind->changeActiveTabTo(2);
wind->closeTab();
Tab V = Tab("l", "y","b");
wind->print();
Tab K = Tab("d", "aaa","iii");
wind->changeActiveTabTo(4);
wind->print();
Tab T = Tab("i", "m","aaa");
wind->closeTab();
wind->print();
wind->closeTab();
wind->moveActiveTabTo(5);
Tab O = Tab("aa", "i","l");
wind->closeTab();
Tab S = Tab("bb", "mmm","dd");
wind->print();
wind->closeTab();
wind->changeActiveTabTo(2);
Tab U = Tab("ddd", "d","sss");
wind->changeActiveTabTo(2);
wind->newTab(B);
wind->moveActiveTabTo(5);
wind->print();
wind->closeTab();
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->closeTab();
Tab L = Tab("dd", "sss","ddd");
wind->getActiveTab();
Tab C = Tab("y", "w","h");
wind->closeTab();
wind->isEmpty();
wind->moveActiveTabTo(0);
Tab N = Tab("ppp", "p","pp");
wind->isEmpty();
wind->newTab(C);
wind->print();
wind->closeTab();
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->print();
wind->changeActiveTabTo(5);
Tab Y = Tab("ff", "l","s");
wind->closeTab();
wind->getActiveTab();
Tab Z = Tab("h", "xxx","yy");
wind->print();
Tab X = Tab("rrr", "dd","nnn");
wind->changeActiveTabTo(0);
wind->closeTab();
wind->newTab(F);
wind->changeActiveTabTo(1);
wind->print();
wind->print();
wind->getActiveTab();
wind->closeTab();
wind->getActiveTab();
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->newTab(G);
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(1);
wind->print();
wind->print();
wind->newTab(H);
wind->changeActiveTabTo(0);
wind->newTab(I);
wind->changeActiveTabTo(0);
Tab D = Tab("hhh", "lll","u");
wind->print();
wind->closeTab();
wind->newTab(D);
wind->changeActiveTabTo(0);
wind->newTab(J);
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(2);
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->print();
wind->newTab(K);
wind->moveActiveTabTo(0);
wind->print();
wind->closeTab();
wind->moveActiveTabTo(0);
delete wind;
}
	return 0;
}