#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->moveActiveTabTo(4);
Tab O = Tab("fff", "o","ss");
wind->changeActiveTabTo(4);
Tab L = Tab("z", "ggg","w");
wind->print();
Tab T = Tab("z", "qq","ee");
wind->changeActiveTabTo(5);
Tab W = Tab("nn", "pp","u");
wind->isEmpty();
Tab C = Tab("p", "hhh","vvv");
wind->closeTab();
Tab F = Tab("k", "bbb","aaa");
wind->print();
Tab B = Tab("t", "vvv","q");
wind->newTab(B);
wind->print();
Tab N = Tab("n", "oo","z");
wind->moveActiveTabTo(3);
wind->newTab(C);
Tab I = Tab("qq", "rrr","x");
wind->changeActiveTabTo(4);
Tab J = Tab("x", "aaa","mm");
wind->isEmpty();
wind->newTab(F);
Tab E = Tab("z", "l","r");
wind->getActiveTab();
Tab P = Tab("rr", "ee","ttt");
wind->moveActiveTabTo(0);
Tab Y = Tab("v", "o","oo");
wind->newTab(E);
wind->moveActiveTabTo(1);
wind->getActiveTab();
Tab X = Tab("k", "sss","ddd");
wind->newTab(I);
Tab R = Tab("w", "i","uuu");
wind->moveActiveTabTo(4);
wind->closeTab();
Tab A = Tab("j", "xxx","rr");
wind->closeTab();
wind->print();
Tab V = Tab("bb", "v","u");
wind->changeActiveTabTo(2);
Tab K = Tab("yy", "rrr","k");
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->newTab(A);
wind->getActiveTab();
Tab M = Tab("x", "xx","nnn");
wind->moveActiveTabTo(5);
Tab S = Tab("b", "gg","q");
wind->getActiveTab();
wind->newTab(J);
wind->changeActiveTabTo(0);
wind->getActiveTab();
Tab Z = Tab("cc", "c","t");
wind->isEmpty();
wind->newTab(K);
wind->print();
wind->getActiveTab();
wind->print();
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(0);
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->newTab(L);
wind->moveActiveTabTo(5);
Tab Q = Tab("kk", "o","xx");
wind->newTab(M);
wind->print();
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(3);
wind->newTab(N);
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(3);
wind->isEmpty();
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->print();
wind->getActiveTab();
wind->newTab(O);
wind->print();
wind->print();
wind->changeActiveTabTo(0);
wind->closeTab();
Tab G = Tab("nnn", "pp","uuu");
wind->isEmpty();
wind->getActiveTab();
Tab H = Tab("yyy", "yyy","jj");
wind->moveActiveTabTo(2);
wind->closeTab();
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->getActiveTab();
wind->closeTab();
Tab U = Tab("ttt", "nnn","tt");
wind->isEmpty();
wind->getActiveTab();
wind->newTab(G);
wind->isEmpty();
wind->getActiveTab();
wind->newTab(H);
wind->isEmpty();
wind->newTab(P);
wind->changeActiveTabTo(2);
wind->print();
wind->isEmpty();
wind->print();
wind->closeTab();
wind->moveActiveTabTo(2);
wind->newTab(Q);
wind->changeActiveTabTo(4);
wind->print();
wind->changeActiveTabTo(2);
wind->print();
Tab D = Tab("sss", "xxx","vv");
wind->isEmpty();
wind->print();
wind->closeTab();
wind->newTab(D);
wind->changeActiveTabTo(2);
wind->closeTab();
wind->closeTab();
delete wind;
}
	return 0;
}