#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->print();
Tab O = Tab("r", "b","z");
wind->closeTab();
Tab B = Tab("ggg", "zz","c");
wind->print();
Tab D = Tab("ss", "qqq","m");
wind->changeActiveTabTo(4);
Tab W = Tab("nnn", "uuu","b");
wind->newTab(B);
Tab R = Tab("n", "aa","rr");
wind->isEmpty();
Tab Z = Tab("qqq", "uuu","ll");
wind->newTab(D);
Tab Y = Tab("ww", "iii","u");
wind->moveActiveTabTo(3);
Tab X = Tab("mmm", "n","vv");
wind->getActiveTab();
Tab N = Tab("qq", "jj","nn");
wind->newTab(N);
wind->isEmpty();
Tab V = Tab("tt", "ggg","rr");
wind->getActiveTab();
Tab S = Tab("m", "g","ppp");
wind->moveActiveTabTo(3);
Tab K = Tab("yyy", "e","zzz");
wind->changeActiveTabTo(3);
wind->print();
Tab H = Tab("ttt", "ii","uuu");
wind->getActiveTab();
wind->print();
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->print();
wind->getActiveTab();
Tab J = Tab("xxx", "s","oo");
wind->changeActiveTabTo(2);
wind->newTab(H);
wind->closeTab();
Tab I = Tab("k", "ccc","yy");
wind->changeActiveTabTo(0);
Tab F = Tab("ppp", "qq","f");
wind->changeActiveTabTo(1);
wind->newTab(F);
wind->print();
Tab A = Tab("f", "rr","ii");
wind->moveActiveTabTo(0);
Tab L = Tab("ooo", "v","e");
wind->getActiveTab();
Tab U = Tab("vv", "s","mmm");
wind->getActiveTab();
Tab E = Tab("r", "ttt","g");
wind->getActiveTab();
wind->print();
Tab C = Tab("uuu", "ddd","mmm");
wind->getActiveTab();
wind->newTab(A);
wind->closeTab();
wind->changeActiveTabTo(0);
Tab P = Tab("kkk", "ff","oo");
wind->newTab(C);
wind->moveActiveTabTo(4);
wind->print();
wind->isEmpty();
wind->isEmpty();
wind->changeActiveTabTo(4);
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->print();
Tab G = Tab("l", "sss","aaa");
wind->print();
Tab Q = Tab("iii", "nnn","tt");
wind->newTab(E);
wind->getActiveTab();
wind->newTab(G);
wind->getActiveTab();
Tab T = Tab("rrr", "bb","xxx");
wind->isEmpty();
wind->getActiveTab();
wind->newTab(I);
wind->print();
wind->closeTab();
wind->print();
wind->moveActiveTabTo(5);
wind->closeTab();
wind->closeTab();
wind->isEmpty();
wind->closeTab();
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->print();
Tab M = Tab("l", "eee","l");
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->isEmpty();
wind->changeActiveTabTo(4);
wind->changeActiveTabTo(1);
wind->newTab(J);
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->moveActiveTabTo(1);
wind->newTab(K);
wind->getActiveTab();
wind->newTab(L);
wind->changeActiveTabTo(2);
wind->newTab(M);
wind->moveActiveTabTo(1);
wind->moveActiveTabTo(1);
wind->getActiveTab();
wind->print();
wind->closeTab();
wind->isEmpty();
wind->closeTab();
wind->newTab(O);
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(1);
wind->closeTab();
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
delete wind;
}
	return 0;
}