#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->moveActiveTabTo(5);
Tab D = Tab("vv", "ii","cc");
wind->isEmpty();
Tab W = Tab("h", "d","bb");
wind->changeActiveTabTo(4);
Tab Q = Tab("dd", "s","qqq");
wind->newTab(D);
Tab Z = Tab("aaa", "ppp","ff");
wind->closeTab();
Tab R = Tab("kk", "d","hhh");
wind->isEmpty();
Tab L = Tab("l", "ee","bb");
wind->isEmpty();
Tab O = Tab("m", "nnn","r");
wind->newTab(L);
Tab V = Tab("c", "n","i");
wind->moveActiveTabTo(5);
Tab B = Tab("aa", "eee","x");
wind->getActiveTab();
Tab X = Tab("ddd", "i","g");
wind->print();
wind->getActiveTab();
Tab U = Tab("jj", "vvv","j");
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->print();
wind->moveActiveTabTo(3);
Tab Y = Tab("yyy", "lll","tt");
wind->isEmpty();
Tab H = Tab("s", "zzz","r");
wind->moveActiveTabTo(4);
Tab M = Tab("xxx", "nn","nnn");
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->getActiveTab();
wind->getActiveTab();
Tab J = Tab("cc", "qq","bbb");
wind->print();
wind->getActiveTab();
wind->getActiveTab();
Tab C = Tab("pp", "n","nnn");
wind->getActiveTab();
wind->closeTab();
Tab A = Tab("cc", "ll","qqq");
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
wind->changeActiveTabTo(4);
wind->print();
Tab S = Tab("ooo", "ddd","h");
wind->isEmpty();
Tab F = Tab("ggg", "h","q");
wind->print();
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->moveActiveTabTo(4);
Tab I = Tab("z", "ttt","t");
wind->print();
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->getActiveTab();
Tab K = Tab("h", "c","x");
wind->isEmpty();
Tab N = Tab("tt", "z","gg");
wind->getActiveTab();
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
wind->closeTab();
wind->isEmpty();
Tab P = Tab("ggg", "uu","r");
wind->newTab(A);
wind->closeTab();
Tab E = Tab("h", "z","i");
wind->print();
wind->getActiveTab();
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->isEmpty();
Tab T = Tab("oo", "z","mm");
wind->getActiveTab();
wind->moveActiveTabTo(5);
Tab G = Tab("yyy", "mm","o");
wind->changeActiveTabTo(4);
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(4);
wind->changeActiveTabTo(2);
wind->closeTab();
wind->getActiveTab();
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->print();
wind->newTab(B);
wind->newTab(C);
wind->moveActiveTabTo(3);
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->isEmpty();
wind->closeTab();
wind->moveActiveTabTo(3);
wind->isEmpty();
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->newTab(E);
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(3);
wind->closeTab();
wind->changeActiveTabTo(5);
wind->closeTab();
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(0);
wind->print();
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->getActiveTab();
wind->moveActiveTabTo(4);
wind->getActiveTab();
delete wind;
}
	return 0;
}