#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
Tab K = Tab("q", "ooo","gg");
wind->moveActiveTabTo(2);
Tab Q = Tab("j", "s","ddd");
wind->getActiveTab();
Tab S = Tab("zzz", "eee","v");
wind->isEmpty();
Tab T = Tab("www", "t","s");
wind->isEmpty();
Tab D = Tab("vv", "i","kkk");
wind->changeActiveTabTo(5);
Tab J = Tab("yy", "z","zz");
wind->print();
Tab Z = Tab("iii", "qq","oo");
wind->changeActiveTabTo(5);
wind->newTab(D);
Tab H = Tab("u", "cc","ww");
wind->changeActiveTabTo(1);
Tab N = Tab("hh", "lll","g");
wind->print();
wind->closeTab();
wind->changeActiveTabTo(4);
Tab R = Tab("k", "aa","lll");
wind->closeTab();
wind->closeTab();
Tab Y = Tab("w", "zz","n");
wind->getActiveTab();
Tab L = Tab("h", "ppp","ff");
wind->closeTab();
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(5);
wind->isEmpty();
Tab B = Tab("ll", "m","nnn");
wind->changeActiveTabTo(0);
Tab M = Tab("b", "a","hhh");
wind->newTab(B);
Tab A = Tab("nnn", "zzz","j");
wind->moveActiveTabTo(1);
wind->print();
wind->newTab(A);
wind->closeTab();
wind->isEmpty();
Tab X = Tab("v", "eee","hh");
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->getActiveTab();
Tab G = Tab("qqq", "ff","r");
wind->newTab(G);
wind->isEmpty();
Tab W = Tab("ii", "vvv","jjj");
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
Tab C = Tab("l", "rr","i");
wind->isEmpty();
wind->closeTab();
Tab O = Tab("ooo", "ttt","w");
wind->newTab(C);
Tab E = Tab("p", "ii","pp");
wind->changeActiveTabTo(2);
wind->isEmpty();
Tab P = Tab("ss", "mm","cc");
wind->isEmpty();
Tab I = Tab("ccc", "qqq","ggg");
wind->moveActiveTabTo(2);
Tab U = Tab("ww", "kk","lll");
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(E);
wind->newTab(H);
wind->print();
Tab F = Tab("zz", "z","zzz");
wind->closeTab();
wind->print();
wind->closeTab();
wind->print();
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->closeTab();
wind->print();
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
wind->print();
wind->isEmpty();
Tab V = Tab("www", "hhh","nnn");
wind->getActiveTab();
wind->newTab(F);
wind->newTab(I);
wind->changeActiveTabTo(5);
wind->print();
wind->newTab(J);
wind->getActiveTab();
wind->getActiveTab();
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->changeActiveTabTo(5);
wind->newTab(K);
wind->newTab(L);
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->isEmpty();
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->closeTab();
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->print();
wind->print();
wind->newTab(M);
wind->print();
wind->changeActiveTabTo(4);
wind->newTab(N);
wind->print();
wind->print();
wind->changeActiveTabTo(1);
wind->isEmpty();
wind->moveActiveTabTo(2);
delete wind;
}
	return 0;
}