#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->moveActiveTabTo(3);
Tab P = Tab("i", "jj","x");
wind->changeActiveTabTo(5);
Tab H = Tab("zz", "yyy","d");
wind->getActiveTab();
Tab V = Tab("p", "ww","w");
wind->closeTab();
Tab Q = Tab("nnn", "ddd","y");
wind->isEmpty();
Tab N = Tab("oo", "i","qq");
wind->closeTab();
Tab B = Tab("bbb", "uuu","ss");
wind->getActiveTab();
Tab W = Tab("zz", "xxx","qqq");
wind->changeActiveTabTo(0);
wind->closeTab();
wind->newTab(B);
Tab S = Tab("pp", "bbb","bb");
wind->getActiveTab();
Tab Z = Tab("p", "rrr","tt");
wind->closeTab();
Tab G = Tab("j", "l","rrr");
wind->changeActiveTabTo(4);
Tab E = Tab("qqq", "jjj","m");
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->moveActiveTabTo(4);
Tab M = Tab("m", "uu","kk");
wind->moveActiveTabTo(1);
Tab I = Tab("e", "ttt","lll");
wind->newTab(E);
Tab D = Tab("gg", "bbb","aaa");
wind->getActiveTab();
Tab T = Tab("jjj", "cc","eee");
wind->closeTab();
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(5);
Tab U = Tab("z", "qqq","ee");
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->changeActiveTabTo(4);
Tab F = Tab("kk", "fff","rr");
wind->isEmpty();
wind->newTab(D);
Tab K = Tab("nnn", "xx","lll");
wind->print();
wind->newTab(F);
wind->changeActiveTabTo(3);
Tab Y = Tab("jj", "q","lll");
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->getActiveTab();
Tab O = Tab("ss", "jj","lll");
wind->newTab(G);
Tab X = Tab("q", "n","ttt");
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
wind->closeTab();
wind->newTab(H);
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(4);
wind->print();
wind->isEmpty();
Tab C = Tab("y", "qq","c");
wind->changeActiveTabTo(0);
wind->newTab(C);
wind->isEmpty();
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->print();
wind->newTab(I);
Tab R = Tab("xx", "oo","rrr");
wind->changeActiveTabTo(2);
Tab A = Tab("zzz", "p","d");
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
wind->moveActiveTabTo(2);
wind->moveActiveTabTo(3);
wind->closeTab();
wind->isEmpty();
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(0);
wind->closeTab();
wind->moveActiveTabTo(3);
wind->newTab(A);
wind->getActiveTab();
wind->newTab(K);
wind->moveActiveTabTo(5);
Tab L = Tab("b", "q","zz");
wind->closeTab();
wind->newTab(L);
wind->closeTab();
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(0);
wind->newTab(M);
wind->closeTab();
Tab J = Tab("mm", "o","ii");
wind->moveActiveTabTo(1);
wind->moveActiveTabTo(1);
wind->print();
wind->getActiveTab();
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->newTab(J);
wind->print();
wind->newTab(N);
wind->closeTab();
wind->newTab(O);
wind->closeTab();
wind->closeTab();
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->newTab(P);
wind->moveActiveTabTo(5);
wind->print();
wind->isEmpty();
wind->isEmpty();
delete wind;
}
	return 0;
}