#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->isEmpty();
Tab X = Tab("i", "c","zzz");
wind->getActiveTab();
Tab U = Tab("gg", "nn","vv");
wind->isEmpty();
Tab C = Tab("lll", "aaa","a");
wind->print();
Tab H = Tab("mm", "b","ddd");
wind->newTab(C);
Tab W = Tab("d", "ppp","ww");
wind->moveActiveTabTo(3);
Tab N = Tab("yyy", "eee","zz");
wind->changeActiveTabTo(2);
wind->print();
Tab J = Tab("ccc", "ttt","ttt");
wind->isEmpty();
Tab S = Tab("dd", "yy","ii");
wind->isEmpty();
Tab R = Tab("yy", "mm","gg");
wind->closeTab();
Tab Z = Tab("tt", "hhh","b");
wind->newTab(H);
wind->changeActiveTabTo(0);
Tab V = Tab("z", "mm","kk");
wind->closeTab();
wind->changeActiveTabTo(4);
Tab G = Tab("yy", "z","bbb");
wind->print();
Tab M = Tab("xx", "mmm","zz");
wind->changeActiveTabTo(4);
wind->newTab(G);
Tab T = Tab("rr", "d","yyy");
wind->changeActiveTabTo(3);
wind->isEmpty();
Tab A = Tab("l", "nn","fff");
wind->moveActiveTabTo(2);
Tab E = Tab("yy", "y","ttt");
wind->closeTab();
wind->print();
wind->newTab(A);
wind->closeTab();
Tab P = Tab("dd", "www","zz");
wind->changeActiveTabTo(2);
wind->closeTab();
wind->getActiveTab();
Tab F = Tab("kkk", "qq","iii");
wind->newTab(E);
wind->moveActiveTabTo(3);
wind->print();
wind->isEmpty();
wind->closeTab();
wind->getActiveTab();
wind->moveActiveTabTo(3);
Tab K = Tab("vvv", "vv","kk");
wind->changeActiveTabTo(3);
wind->closeTab();
Tab L = Tab("ff", "e","vvv");
wind->newTab(F);
Tab O = Tab("tt", "tt","jj");
wind->closeTab();
wind->print();
wind->moveActiveTabTo(4);
wind->closeTab();
wind->closeTab();
wind->newTab(J);
wind->newTab(K);
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
Tab Y = Tab("mmm", "rr","iii");
wind->closeTab();
wind->moveActiveTabTo(1);
wind->getActiveTab();
wind->closeTab();
wind->newTab(L);
wind->print();
wind->isEmpty();
wind->closeTab();
wind->closeTab();
wind->print();
wind->closeTab();
Tab Q = Tab("mmm", "nn","j");
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
wind->print();
wind->newTab(M);
wind->print();
wind->moveActiveTabTo(1);
wind->closeTab();
Tab I = Tab("a", "zzz","eee");
wind->moveActiveTabTo(0);
wind->isEmpty();
wind->print();
wind->newTab(I);
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->print();
wind->moveActiveTabTo(2);
wind->moveActiveTabTo(0);
Tab D = Tab("nn", "ggg","s");
wind->print();
wind->closeTab();
wind->newTab(D);
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(3);
wind->print();
wind->getActiveTab();
Tab B = Tab("h", "hhh","ss");
wind->isEmpty();
wind->moveActiveTabTo(4);
wind->changeActiveTabTo(5);
wind->newTab(B);
wind->print();
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->moveActiveTabTo(1);
delete wind;
}
	return 0;
}