#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->isEmpty();
Tab J = Tab("a", "e","jjj");
wind->moveActiveTabTo(4);
Tab W = Tab("iii", "www","k");
wind->isEmpty();
Tab R = Tab("ttt", "m","www");
wind->getActiveTab();
Tab G = Tab("zzz", "t","cc");
wind->getActiveTab();
Tab O = Tab("iii", "yyy","ttt");
wind->closeTab();
Tab D = Tab("q", "jjj","rr");
wind->newTab(D);
wind->isEmpty();
Tab B = Tab("e", "y","vv");
wind->newTab(B);
Tab M = Tab("yyy", "b","mm");
wind->getActiveTab();
Tab H = Tab("ggg", "ccc","f");
wind->newTab(G);
wind->changeActiveTabTo(0);
Tab I = Tab("aa", "aaa","rrr");
wind->print();
Tab A = Tab("ss", "zz","jj");
wind->changeActiveTabTo(2);
Tab N = Tab("rrr", "h","mm");
wind->closeTab();
wind->changeActiveTabTo(0);
wind->getActiveTab();
Tab V = Tab("sss", "g","fff");
wind->isEmpty();
wind->closeTab();
Tab X = Tab("ooo", "ss","hh");
wind->getActiveTab();
wind->moveActiveTabTo(4);
Tab E = Tab("n", "vv","xxx");
wind->isEmpty();
wind->closeTab();
Tab S = Tab("qq", "gg","cc");
wind->print();
Tab L = Tab("uu", "qqq","jj");
wind->closeTab();
wind->closeTab();
wind->moveActiveTabTo(1);
wind->getActiveTab();
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->print();
Tab Y = Tab("z", "vvv","b");
wind->changeActiveTabTo(5);
wind->newTab(A);
wind->getActiveTab();
Tab F = Tab("d", "i","w");
wind->moveActiveTabTo(2);
wind->getActiveTab();
wind->print();
wind->print();
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
Tab Q = Tab("ttt", "l","hh");
wind->changeActiveTabTo(4);
Tab K = Tab("qqq", "t","ff");
wind->newTab(E);
wind->changeActiveTabTo(4);
wind->print();
wind->print();
wind->newTab(F);
wind->closeTab();
Tab T = Tab("nnn", "vvv","w");
wind->getActiveTab();
wind->newTab(H);
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->closeTab();
wind->newTab(I);
Tab Z = Tab("cc", "ee","aaa");
wind->isEmpty();
wind->closeTab();
Tab U = Tab("r", "ll","zzz");
wind->print();
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(0);
wind->closeTab();
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->print();
wind->moveActiveTabTo(1);
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->isEmpty();
wind->print();
wind->closeTab();
wind->getActiveTab();
Tab C = Tab("iii", "kkk","bb");
wind->moveActiveTabTo(0);
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
Tab P = Tab("f", "w","h");
wind->closeTab();
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(C);
wind->newTab(J);
wind->print();
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(K);
wind->newTab(L);
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(4);
wind->getActiveTab();
delete wind;
}
	return 0;
}