#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->closeTab();
Tab L = Tab("ttt", "u","aa");
wind->print();
Tab P = Tab("cc", "bb","bbb");
wind->changeActiveTabTo(4);
Tab K = Tab("yy", "gg","s");
wind->closeTab();
Tab T = Tab("nnn", "r","s");
wind->getActiveTab();
Tab Z = Tab("xx", "f","c");
wind->print();
Tab I = Tab("pp", "ccc","p");
wind->moveActiveTabTo(4);
Tab V = Tab("w", "bbb","vvv");
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
Tab B = Tab("fff", "xxx","nn");
wind->isEmpty();
wind->print();
Tab A = Tab("l", "ppp","d");
wind->getActiveTab();
wind->isEmpty();
Tab O = Tab("ee", "nnn","ccc");
wind->moveActiveTabTo(1);
Tab C = Tab("a", "xx","y");
wind->newTab(A);
wind->getActiveTab();
Tab N = Tab("m", "o","k");
wind->moveActiveTabTo(2);
Tab D = Tab("a", "rr","p");
wind->moveActiveTabTo(3);
wind->print();
wind->newTab(B);
Tab E = Tab("mm", "qqq","hh");
wind->closeTab();
wind->newTab(C);
wind->moveActiveTabTo(3);
Tab M = Tab("ff", "a","cc");
wind->print();
Tab H = Tab("kk", "xxx","kkk");
wind->getActiveTab();
wind->moveActiveTabTo(4);
Tab X = Tab("d", "y","t");
wind->moveActiveTabTo(5);
wind->newTab(D);
Tab F = Tab("bbb", "uu","qq");
wind->print();
Tab W = Tab("aa", "hh","ccc");
wind->changeActiveTabTo(4);
wind->changeActiveTabTo(0);
Tab Q = Tab("jjj", "xx","d");
wind->print();
wind->moveActiveTabTo(3);
wind->isEmpty();
Tab U = Tab("zz", "uuu","aa");
wind->closeTab();
wind->closeTab();
wind->getActiveTab();
Tab R = Tab("x", "mm","l");
wind->getActiveTab();
wind->closeTab();
wind->newTab(E);
wind->isEmpty();
wind->newTab(F);
Tab S = Tab("aa", "gg","xxx");
wind->changeActiveTabTo(3);
wind->newTab(H);
wind->isEmpty();
wind->isEmpty();
wind->print();
wind->newTab(I);
wind->newTab(K);
wind->isEmpty();
wind->print();
Tab G = Tab("gg", "ii","ff");
wind->newTab(G);
wind->closeTab();
wind->print();
wind->closeTab();
wind->print();
wind->newTab(L);
wind->closeTab();
wind->newTab(M);
wind->newTab(N);
Tab Y = Tab("y", "ddd","a");
wind->closeTab();
wind->print();
wind->moveActiveTabTo(4);
wind->newTab(O);
wind->changeActiveTabTo(4);
wind->newTab(P);
wind->getActiveTab();
wind->print();
wind->newTab(Q);
wind->getActiveTab();
wind->isEmpty();
wind->closeTab();
Tab J = Tab("mm", "eee","m");
wind->newTab(J);
wind->print();
wind->changeActiveTabTo(2);
wind->moveActiveTabTo(4);
wind->closeTab();
wind->changeActiveTabTo(2);
wind->moveActiveTabTo(2);
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->print();
wind->closeTab();
wind->print();
wind->changeActiveTabTo(2);
wind->newTab(R);
wind->isEmpty();
wind->closeTab();
wind->print();
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->newTab(S);
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->print();
delete wind;
}
	return 0;
}