#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->isEmpty();
Tab E = Tab("z", "qqq","w");
wind->closeTab();
Tab S = Tab("aaa", "uuu","nnn");
wind->getActiveTab();
Tab K = Tab("c", "ddd","bbb");
wind->moveActiveTabTo(5);
Tab C = Tab("aa", "cc","y");
wind->moveActiveTabTo(3);
Tab N = Tab("bbb", "a","f");
wind->moveActiveTabTo(5);
Tab F = Tab("rrr", "d","vv");
wind->print();
Tab G = Tab("kkk", "xx","ooo");
wind->newTab(C);
Tab Q = Tab("q", "ww","a");
wind->changeActiveTabTo(2);
Tab X = Tab("iii", "x","k");
wind->newTab(E);
Tab U = Tab("mmm", "y","c");
wind->moveActiveTabTo(1);
wind->print();
Tab B = Tab("vv", "fff","g");
wind->moveActiveTabTo(4);
Tab I = Tab("ee", "a","rr");
wind->isEmpty();
Tab M = Tab("ff", "lll","yyy");
wind->changeActiveTabTo(4);
Tab P = Tab("ttt", "m","v");
wind->newTab(B);
Tab Z = Tab("ccc", "w","ww");
wind->print();
Tab J = Tab("lll", "u","q");
wind->newTab(F);
Tab V = Tab("a", "eee","zz");
wind->closeTab();
Tab L = Tab("hh", "aa","bb");
wind->print();
wind->moveActiveTabTo(5);
wind->isEmpty();
Tab W = Tab("ss", "mm","cc");
wind->getActiveTab();
wind->isEmpty();
wind->isEmpty();
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(0);
Tab A = Tab("qq", "r","v");
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(3);
Tab Y = Tab("ww", "vvv","yy");
wind->print();
wind->moveActiveTabTo(5);
Tab T = Tab("q", "ss","rrr");
wind->changeActiveTabTo(5);
wind->isEmpty();
wind->moveActiveTabTo(4);
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
wind->getActiveTab();
Tab H = Tab("mmm", "ss","lll");
wind->newTab(A);
wind->getActiveTab();
wind->newTab(G);
Tab R = Tab("ccc", "eee","c");
wind->closeTab();
wind->print();
wind->print();
wind->changeActiveTabTo(2);
wind->closeTab();
wind->print();
wind->print();
wind->newTab(H);
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(I);
wind->isEmpty();
wind->closeTab();
wind->newTab(J);
wind->closeTab();
wind->newTab(K);
wind->moveActiveTabTo(3);
wind->moveActiveTabTo(4);
wind->newTab(L);
wind->newTab(M);
Tab O = Tab("xxx", "iii","yyy");
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
wind->newTab(N);
wind->closeTab();
wind->getActiveTab();
wind->getActiveTab();
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->closeTab();
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(O);
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->isEmpty();
wind->print();
wind->closeTab();
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->closeTab();
wind->closeTab();
wind->isEmpty();
wind->newTab(P);
wind->newTab(Q);
Tab D = Tab("dd", "rrr","q");
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(1);
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(5);
delete wind;
}
	return 0;
}