#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->getActiveTab();
Tab J = Tab("n", "ooo","i");
wind->changeActiveTabTo(3);
Tab B = Tab("dd", "ll","lll");
wind->getActiveTab();
Tab E = Tab("ggg", "nnn","w");
wind->print();
Tab G = Tab("ooo", "rrr","ggg");
wind->newTab(B);
wind->closeTab();
Tab T = Tab("zz", "zz","m");
wind->closeTab();
Tab Q = Tab("zzz", "ggg","uu");
wind->changeActiveTabTo(4);
Tab W = Tab("s", "yyy","e");
wind->getActiveTab();
Tab Z = Tab("v", "h","a");
wind->isEmpty();
Tab D = Tab("nn", "ww","n");
wind->isEmpty();
Tab Y = Tab("eee", "vvv","y");
wind->isEmpty();
Tab M = Tab("www", "e","vvv");
wind->isEmpty();
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(4);
Tab R = Tab("ww", "j","zz");
wind->isEmpty();
Tab N = Tab("h", "uu","ff");
wind->changeActiveTabTo(2);
wind->closeTab();
wind->isEmpty();
Tab H = Tab("uu", "t","m");
wind->moveActiveTabTo(2);
wind->closeTab();
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(1);
wind->closeTab();
wind->newTab(D);
wind->newTab(E);
Tab L = Tab("bbb", "ccc","jjj");
wind->moveActiveTabTo(3);
wind->print();
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(3);
Tab F = Tab("ss", "ggg","w");
wind->closeTab();
Tab K = Tab("www", "www","m");
wind->closeTab();
wind->getActiveTab();
Tab X = Tab("f", "zz","q");
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->getActiveTab();
Tab P = Tab("ddd", "j","p");
wind->changeActiveTabTo(2);
Tab O = Tab("jj", "xxx","q");
wind->changeActiveTabTo(4);
wind->print();
wind->isEmpty();
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->isEmpty();
wind->closeTab();
Tab C = Tab("hh", "kkk","yy");
wind->moveActiveTabTo(4);
Tab V = Tab("ppp", "m","ttt");
wind->getActiveTab();
Tab I = Tab("ss", "ii","uu");
wind->changeActiveTabTo(5);
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(4);
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(5);
wind->print();
wind->newTab(C);
wind->changeActiveTabTo(5);
Tab S = Tab("d", "v","dd");
wind->changeActiveTabTo(0);
wind->closeTab();
wind->changeActiveTabTo(3);
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->changeActiveTabTo(0);
wind->closeTab();
wind->closeTab();
wind->changeActiveTabTo(1);
wind->newTab(F);
wind->print();
wind->newTab(G);
wind->print();
wind->isEmpty();
wind->print();
wind->getActiveTab();
Tab U = Tab("aaa", "aa","e");
wind->changeActiveTabTo(1);
wind->newTab(H);
wind->getActiveTab();
wind->closeTab();
wind->newTab(I);
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->print();
wind->newTab(J);
wind->closeTab();
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(0);
Tab A = Tab("rr", "zzz","q");
wind->isEmpty();
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->closeTab();
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->getActiveTab();
wind->moveActiveTabTo(2);
wind->moveActiveTabTo(0);
delete wind;
}
	return 0;
}