#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->print();
Tab F = Tab("rr", "www","w");
wind->newTab(F);
wind->print();
wind->getActiveTab();
Tab B = Tab("j", "jjj","i");
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(0);
wind->closeTab();
Tab U = Tab("t", "gg","uu");
wind->changeActiveTabTo(2);
wind->getActiveTab();
Tab Z = Tab("cc", "q","c");
wind->newTab(B);
Tab W = Tab("vvv", "x","k");
wind->closeTab();
Tab S = Tab("gg", "www","ll");
wind->isEmpty();
Tab P = Tab("j", "xxx","qq");
wind->moveActiveTabTo(3);
wind->isEmpty();
Tab Y = Tab("vv", "ii","zz");
wind->newTab(P);
Tab Q = Tab("e", "tt","zzz");
wind->print();
wind->newTab(Q);
wind->changeActiveTabTo(0);
Tab V = Tab("pp", "bbb","ppp");
wind->moveActiveTabTo(4);
Tab T = Tab("p", "xxx","l");
wind->isEmpty();
wind->newTab(S);
Tab L = Tab("k", "rrr","ggg");
wind->newTab(L);
Tab X = Tab("sss", "j","pp");
wind->moveActiveTabTo(5);
wind->newTab(T);
wind->print();
wind->moveActiveTabTo(5);
wind->newTab(U);
wind->print();
wind->changeActiveTabTo(2);
Tab G = Tab("x", "www","ff");
wind->closeTab();
wind->closeTab();
wind->newTab(G);
Tab H = Tab("ii", "l","rr");
wind->changeActiveTabTo(1);
wind->print();
wind->changeActiveTabTo(4);
wind->getActiveTab();
Tab O = Tab("tt", "nnn","pp");
wind->closeTab();
wind->changeActiveTabTo(4);
wind->isEmpty();
Tab N = Tab("ii", "f","ff");
wind->print();
wind->moveActiveTabTo(4);
wind->newTab(H);
Tab I = Tab("sss", "mm","ww");
wind->getActiveTab();
wind->changeActiveTabTo(1);
Tab M = Tab("ooo", "n","p");
wind->newTab(I);
Tab K = Tab("l", "n","g");
wind->isEmpty();
Tab R = Tab("p", "ooo","uuu");
wind->closeTab();
wind->newTab(K);
wind->closeTab();
wind->print();
Tab J = Tab("i", "ii","v");
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->closeTab();
Tab C = Tab("d", "hhh","eee");
wind->closeTab();
Tab A = Tab("nn", "kkk","bb");
wind->isEmpty();
wind->getActiveTab();
wind->isEmpty();
wind->closeTab();
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(4);
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(1);
Tab D = Tab("gg", "a","iii");
wind->getActiveTab();
wind->print();
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(5);
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
wind->print();
wind->getActiveTab();
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
wind->print();
wind->print();
wind->closeTab();
wind->print();
wind->moveActiveTabTo(0);
wind->isEmpty();
wind->print();
wind->print();
wind->print();
wind->getActiveTab();
wind->print();
wind->newTab(A);
wind->newTab(C);
wind->newTab(D);
wind->changeActiveTabTo(4);
wind->isEmpty();
wind->closeTab();
wind->changeActiveTabTo(0);
wind->closeTab();
wind->newTab(J);
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->isEmpty();
delete wind;
}
	return 0;
}