#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->getActiveTab();
Tab R = Tab("z", "i","lll");
wind->changeActiveTabTo(1);
Tab Z = Tab("jjj", "p","hh");
wind->closeTab();
Tab V = Tab("n", "y","lll");
wind->print();
Tab M = Tab("s", "w","rrr");
wind->moveActiveTabTo(2);
Tab N = Tab("ii", "zzz","nn");
wind->isEmpty();
wind->print();
Tab O = Tab("xx", "hhh","mmm");
wind->changeActiveTabTo(3);
Tab E = Tab("ll", "ww","gg");
wind->changeActiveTabTo(1);
Tab C = Tab("j", "ooo","dd");
wind->moveActiveTabTo(2);
Tab U = Tab("ppp", "dd","g");
wind->changeActiveTabTo(3);
Tab D = Tab("jj", "xx","sss");
wind->changeActiveTabTo(4);
Tab J = Tab("eee", "ii","mm");
wind->changeActiveTabTo(4);
Tab L = Tab("ss", "rr","qqq");
wind->moveActiveTabTo(4);
Tab F = Tab("nn", "ff","vvv");
wind->changeActiveTabTo(3);
wind->newTab(C);
wind->closeTab();
wind->moveActiveTabTo(5);
Tab K = Tab("ccc", "ddd","kk");
wind->isEmpty();
Tab W = Tab("aaa", "ee","s");
wind->closeTab();
wind->print();
Tab B = Tab("xx", "nnn","ll");
wind->newTab(B);
wind->isEmpty();
Tab G = Tab("hhh", "ooo","ll");
wind->closeTab();
Tab I = Tab("tt", "kk","s");
wind->closeTab();
wind->closeTab();
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->getActiveTab();
Tab T = Tab("rr", "b","xx");
wind->moveActiveTabTo(2);
Tab H = Tab("d", "b","ee");
wind->print();
Tab Q = Tab("d", "xx","ll");
wind->closeTab();
wind->print();
Tab X = Tab("tt", "mmm","b");
wind->getActiveTab();
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(2);
wind->getActiveTab();
Tab A = Tab("oo", "xx","lll");
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(0);
wind->newTab(A);
wind->moveActiveTabTo(1);
wind->closeTab();
Tab Y = Tab("pp", "aa","uuu");
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->isEmpty();
wind->changeActiveTabTo(0);
Tab S = Tab("rr", "ccc","rr");
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(1);
wind->newTab(D);
wind->print();
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->getActiveTab();
Tab P = Tab("jjj", "yy","yyy");
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(3);
wind->print();
wind->closeTab();
wind->closeTab();
wind->getActiveTab();
wind->isEmpty();
wind->changeActiveTabTo(0);
wind->newTab(E);
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(2);
wind->closeTab();
wind->newTab(F);
wind->getActiveTab();
wind->isEmpty();
wind->isEmpty();
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(4);
wind->print();
wind->closeTab();
wind->moveActiveTabTo(2);
wind->print();
wind->isEmpty();
wind->print();
wind->isEmpty();
wind->print();
wind->moveActiveTabTo(3);
wind->getActiveTab();
wind->print();
wind->print();
wind->isEmpty();
wind->newTab(G);
wind->changeActiveTabTo(5);
wind->newTab(H);
wind->closeTab();
delete wind;
}
	return 0;
}