#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->print();
Tab R = Tab("ddd", "www","b");
wind->closeTab();
Tab X = Tab("zz", "ttt","ddd");
wind->changeActiveTabTo(4);
Tab D = Tab("jj", "e","yyy");
wind->newTab(D);
Tab T = Tab("ww", "p","sss");
wind->newTab(R);
Tab O = Tab("aaa", "i","ooo");
wind->isEmpty();
Tab U = Tab("o", "u","iii");
wind->moveActiveTabTo(5);
Tab Q = Tab("nn", "uu","cc");
wind->print();
Tab M = Tab("t", "gg","xxx");
wind->print();
Tab L = Tab("ooo", "rrr","ddd");
wind->getActiveTab();
Tab B = Tab("jjj", "jj","l");
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->print();
wind->getActiveTab();
Tab S = Tab("j", "f","u");
wind->changeActiveTabTo(0);
Tab K = Tab("aa", "oo","sss");
wind->moveActiveTabTo(5);
Tab G = Tab("kk", "ll","mmm");
wind->closeTab();
Tab I = Tab("r", "iii","tt");
wind->moveActiveTabTo(5);
wind->closeTab();
wind->changeActiveTabTo(1);
wind->newTab(B);
wind->getActiveTab();
Tab W = Tab("bbb", "ooo","zz");
wind->changeActiveTabTo(1);
Tab Z = Tab("ppp", "o","aa");
wind->print();
wind->print();
wind->moveActiveTabTo(1);
wind->closeTab();
Tab E = Tab("r", "g","q");
wind->getActiveTab();
Tab J = Tab("c", "ff","uuu");
wind->getActiveTab();
Tab F = Tab("zz", "b","e");
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->moveActiveTabTo(1);
Tab A = Tab("hh", "kk","k");
wind->moveActiveTabTo(4);
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->closeTab();
wind->newTab(A);
wind->isEmpty();
wind->moveActiveTabTo(5);
Tab Y = Tab("zz", "c","yyy");
wind->newTab(E);
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(3);
wind->print();
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->print();
wind->moveActiveTabTo(4);
wind->print();
wind->moveActiveTabTo(4);
Tab H = Tab("ppp", "a","kkk");
wind->changeActiveTabTo(4);
wind->newTab(F);
wind->moveActiveTabTo(2);
wind->newTab(G);
wind->print();
wind->print();
wind->newTab(H);
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(2);
wind->newTab(I);
wind->changeActiveTabTo(0);
wind->newTab(J);
wind->getActiveTab();
wind->print();
wind->print();
wind->newTab(K);
wind->getActiveTab();
Tab V = Tab("w", "iii","mmm");
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(L);
Tab C = Tab("hh", "m","r");
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->closeTab();
wind->closeTab();
wind->print();
wind->print();
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(4);
wind->newTab(C);
wind->closeTab();
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->isEmpty();
wind->moveActiveTabTo(4);
wind->closeTab();
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->closeTab();
wind->changeActiveTabTo(1);
wind->closeTab();
wind->print();
wind->newTab(M);
wind->moveActiveTabTo(1);
wind->isEmpty();
delete wind;
}
	return 0;
}