#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->print();
Tab P = Tab("n", "tt","o");
wind->closeTab();
Tab U = Tab("t", "jjj","oo");
wind->isEmpty();
Tab B = Tab("rr", "ss","n");
wind->changeActiveTabTo(5);
Tab J = Tab("rrr", "rr","mmm");
wind->moveActiveTabTo(5);
Tab R = Tab("ttt", "p","qq");
wind->getActiveTab();
Tab A = Tab("bb", "mmm","l");
wind->closeTab();
Tab W = Tab("t", "e","w");
wind->closeTab();
Tab Y = Tab("hh", "d","zzz");
wind->newTab(A);
Tab M = Tab("lll", "yyy","l");
wind->print();
Tab H = Tab("hhh", "sss","xxx");
wind->changeActiveTabTo(1);
Tab I = Tab("uu", "ddd","zz");
wind->isEmpty();
wind->print();
Tab S = Tab("n", "d","i");
wind->isEmpty();
wind->newTab(B);
Tab T = Tab("ii", "k","bbb");
wind->newTab(H);
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->getActiveTab();
wind->isEmpty();
Tab E = Tab("kk", "xxx","ee");
wind->newTab(E);
wind->moveActiveTabTo(4);
Tab N = Tab("qqq", "z","b");
wind->moveActiveTabTo(3);
wind->print();
wind->changeActiveTabTo(0);
Tab X = Tab("n", "n","ppp");
wind->print();
Tab F = Tab("xx", "lll","qqq");
wind->closeTab();
Tab Q = Tab("b", "aa","x");
wind->closeTab();
wind->isEmpty();
Tab K = Tab("nnn", "rr","iii");
wind->newTab(F);
Tab L = Tab("g", "j","lll");
wind->newTab(I);
wind->changeActiveTabTo(1);
wind->newTab(J);
Tab O = Tab("ggg", "k","s");
wind->getActiveTab();
Tab Z = Tab("vv", "mmm","ll");
wind->isEmpty();
wind->moveActiveTabTo(4);
wind->isEmpty();
wind->newTab(K);
wind->newTab(L);
Tab D = Tab("nn", "x","f");
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->getActiveTab();
wind->newTab(D);
wind->getActiveTab();
Tab G = Tab("g", "hh","l");
wind->closeTab();
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->newTab(G);
wind->closeTab();
wind->getActiveTab();
wind->getActiveTab();
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->newTab(M);
wind->getActiveTab();
wind->isEmpty();
wind->print();
wind->closeTab();
wind->closeTab();
wind->closeTab();
wind->newTab(N);
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(1);
Tab V = Tab("ww", "r","ggg");
wind->newTab(O);
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->closeTab();
wind->print();
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->print();
wind->print();
wind->moveActiveTabTo(1);
wind->newTab(P);
wind->isEmpty();
wind->newTab(Q);
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->print();
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->changeActiveTabTo(0);
wind->print();
wind->closeTab();
wind->moveActiveTabTo(3);
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->isEmpty();
wind->newTab(R);
wind->newTab(S);
wind->newTab(T);
delete wind;
}
	return 0;
}