#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->isEmpty();
Tab Y = Tab("vvv", "nnn","dd");
wind->isEmpty();
wind->print();
Tab Z = Tab("vvv", "nn","lll");
wind->getActiveTab();
wind->getActiveTab();
Tab U = Tab("w", "xxx","bb");
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->closeTab();
wind->isEmpty();
Tab S = Tab("zzz", "eee","b");
wind->isEmpty();
Tab A = Tab("www", "uuu","i");
wind->changeActiveTabTo(3);
Tab E = Tab("x", "s","tt");
wind->print();
Tab G = Tab("h", "jjj","jjj");
wind->newTab(A);
Tab N = Tab("sss", "f","qq");
wind->isEmpty();
wind->getActiveTab();
Tab X = Tab("mm", "nnn","hhh");
wind->isEmpty();
Tab C = Tab("f", "o","vv");
wind->newTab(C);
Tab B = Tab("sss", "vvv","ooo");
wind->getActiveTab();
Tab H = Tab("d", "c","bbb");
wind->getActiveTab();
wind->print();
wind->moveActiveTabTo(3);
Tab D = Tab("ccc", "x","qq");
wind->print();
wind->moveActiveTabTo(5);
wind->isEmpty();
Tab O = Tab("z", "dd","ppp");
wind->print();
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(1);
Tab Q = Tab("g", "lll","s");
wind->newTab(B);
wind->getActiveTab();
Tab L = Tab("vvv", "n","ttt");
wind->moveActiveTabTo(0);
Tab K = Tab("ttt", "jjj","v");
wind->moveActiveTabTo(1);
Tab R = Tab("z", "mm","bbb");
wind->getActiveTab();
Tab P = Tab("ccc", "ee","ttt");
wind->moveActiveTabTo(0);
wind->print();
wind->print();
Tab V = Tab("xxx", "ccc","g");
wind->isEmpty();
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->newTab(D);
wind->closeTab();
wind->getActiveTab();
Tab J = Tab("uuu", "j","kk");
wind->closeTab();
wind->moveActiveTabTo(0);
wind->closeTab();
Tab W = Tab("hh", "w","kk");
wind->newTab(E);
Tab M = Tab("ooo", "ddd","uuu");
wind->changeActiveTabTo(0);
wind->newTab(G);
wind->isEmpty();
wind->newTab(H);
wind->getActiveTab();
wind->closeTab();
Tab I = Tab("ff", "sss","qqq");
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(I);
wind->moveActiveTabTo(3);
wind->closeTab();
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->closeTab();
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(5);
wind->print();
wind->changeActiveTabTo(2);
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(0);
Tab F = Tab("lll", "h","ee");
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(3);
wind->closeTab();
wind->print();
wind->moveActiveTabTo(3);
wind->newTab(F);
wind->newTab(J);
wind->print();
wind->isEmpty();
wind->print();
wind->print();
wind->newTab(K);
wind->getActiveTab();
wind->print();
wind->moveActiveTabTo(2);
wind->print();
wind->print();
wind->getActiveTab();
wind->closeTab();
wind->closeTab();
Tab T = Tab("d", "aaa","ii");
wind->print();
wind->changeActiveTabTo(3);
wind->newTab(L);
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(3);
wind->closeTab();
wind->newTab(M);
wind->isEmpty();
wind->getActiveTab();
wind->print();
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(0);
delete wind;
}
	return 0;
}