#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->closeTab();
Tab N = Tab("ggg", "g","dd");
wind->isEmpty();
Tab M = Tab("rr", "ttt","z");
wind->changeActiveTabTo(3);
Tab P = Tab("uuu", "d","mmm");
wind->closeTab();
Tab V = Tab("bb", "gg","oo");
wind->isEmpty();
Tab I = Tab("ppp", "m","ddd");
wind->isEmpty();
Tab A = Tab("qq", "i","f");
wind->moveActiveTabTo(5);
Tab T = Tab("w", "gg","ttt");
wind->newTab(A);
wind->closeTab();
Tab Y = Tab("a", "w","kkk");
wind->moveActiveTabTo(5);
Tab U = Tab("ppp", "c","rrr");
wind->getActiveTab();
wind->newTab(I);
Tab S = Tab("lll", "c","aaa");
wind->newTab(M);
Tab J = Tab("y", "d","jjj");
wind->newTab(J);
Tab D = Tab("oo", "s","dd");
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
Tab O = Tab("e", "yyy","l");
wind->changeActiveTabTo(4);
wind->closeTab();
wind->moveActiveTabTo(2);
wind->newTab(D);
Tab B = Tab("x", "gg","pp");
wind->isEmpty();
Tab W = Tab("g", "y","xxx");
wind->newTab(B);
Tab K = Tab("uuu", "bbb","ii");
wind->newTab(K);
Tab X = Tab("zz", "uu","r");
wind->isEmpty();
Tab H = Tab("fff", "ddd","z");
wind->print();
wind->getActiveTab();
wind->print();
wind->print();
Tab F = Tab("cc", "fff","s");
wind->print();
wind->closeTab();
wind->moveActiveTabTo(4);
wind->closeTab();
Tab R = Tab("bb", "x","ss");
wind->closeTab();
Tab G = Tab("e", "www","w");
wind->closeTab();
wind->isEmpty();
Tab L = Tab("kk", "vv","pp");
wind->print();
wind->print();
wind->moveActiveTabTo(1);
wind->newTab(F);
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->print();
wind->isEmpty();
wind->closeTab();
wind->newTab(G);
Tab E = Tab("dd", "b","zz");
wind->getActiveTab();
wind->moveActiveTabTo(2);
wind->print();
wind->closeTab();
wind->closeTab();
wind->newTab(E);
Tab Q = Tab("zz", "aa","ggg");
wind->changeActiveTabTo(5);
wind->isEmpty();
wind->getActiveTab();
wind->newTab(H);
wind->moveActiveTabTo(0);
wind->newTab(L);
wind->changeActiveTabTo(0);
wind->newTab(N);
wind->isEmpty();
Tab C = Tab("aaa", "ss","h");
wind->moveActiveTabTo(3);
wind->print();
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
wind->newTab(C);
Tab Z = Tab("r", "ee","w");
wind->closeTab();
wind->closeTab();
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(1);
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->print();
wind->print();
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->newTab(O);
wind->moveActiveTabTo(3);
wind->getActiveTab();
wind->print();
wind->closeTab();
wind->print();
wind->changeActiveTabTo(0);
wind->closeTab();
wind->print();
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(1);
wind->closeTab();
wind->getActiveTab();
wind->newTab(P);
wind->newTab(Q);
delete wind;
}
	return 0;
}