#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->isEmpty();
Tab N = Tab("j", "vv","g");
wind->isEmpty();
Tab O = Tab("f", "mmm","aaa");
wind->changeActiveTabTo(3);
Tab Z = Tab("g", "j","aaa");
wind->newTab(N);
Tab J = Tab("ttt", "cc","ee");
wind->closeTab();
Tab C = Tab("mmm", "qq","c");
wind->moveActiveTabTo(5);
Tab Q = Tab("yyy", "c","sss");
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(2);
wind->newTab(C);
Tab B = Tab("sss", "o","rrr");
wind->getActiveTab();
wind->moveActiveTabTo(5);
Tab U = Tab("w", "tt","kkk");
wind->newTab(B);
Tab Y = Tab("cc", "a","hhh");
wind->changeActiveTabTo(0);
wind->closeTab();
wind->newTab(J);
wind->closeTab();
Tab M = Tab("zzz", "ii","ppp");
wind->print();
Tab S = Tab("h", "oo","uuu");
wind->newTab(M);
Tab X = Tab("r", "rr","uuu");
wind->closeTab();
wind->changeActiveTabTo(1);
wind->print();
Tab I = Tab("x", "n","ppp");
wind->print();
wind->getActiveTab();
wind->closeTab();
Tab K = Tab("j", "cc","iii");
wind->getActiveTab();
Tab V = Tab("vv", "bbb","a");
wind->getActiveTab();
wind->moveActiveTabTo(5);
Tab T = Tab("iii", "jjj","ggg");
wind->closeTab();
wind->moveActiveTabTo(2);
wind->getActiveTab();
Tab F = Tab("eee", "g","nnn");
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
Tab G = Tab("ll", "s","vv");
wind->isEmpty();
Tab W = Tab("xxx", "uu","k");
wind->print();
Tab E = Tab("vvv", "tt","ooo");
wind->isEmpty();
wind->newTab(E);
Tab R = Tab("ss", "bb","aaa");
wind->isEmpty();
wind->closeTab();
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->newTab(F);
wind->changeActiveTabTo(2);
wind->print();
wind->newTab(G);
wind->moveActiveTabTo(2);
Tab A = Tab("m", "iii","t");
wind->closeTab();
Tab D = Tab("i", "z","rrr");
wind->newTab(A);
wind->closeTab();
wind->moveActiveTabTo(0);
wind->closeTab();
wind->moveActiveTabTo(2);
wind->closeTab();
wind->closeTab();
wind->moveActiveTabTo(3);
wind->print();
Tab L = Tab("r", "ff","yy");
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(5);
wind->print();
wind->print();
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(2);
Tab P = Tab("ppp", "ii","yyy");
wind->isEmpty();
wind->changeActiveTabTo(4);
wind->print();
wind->isEmpty();
wind->print();
wind->changeActiveTabTo(4);
wind->getActiveTab();
wind->isEmpty();
Tab H = Tab("aaa", "o","jj");
wind->closeTab();
wind->closeTab();
wind->isEmpty();
wind->closeTab();
wind->moveActiveTabTo(5);
wind->print();
wind->newTab(D);
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
wind->closeTab();
wind->newTab(H);
wind->newTab(I);
wind->changeActiveTabTo(0);
wind->newTab(K);
wind->closeTab();
wind->getActiveTab();
wind->newTab(L);
wind->print();
wind->newTab(O);
wind->moveActiveTabTo(3);
wind->print();
wind->changeActiveTabTo(1);
wind->newTab(P);
wind->getActiveTab();
delete wind;
}
	return 0;
}