#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->closeTab();
Tab E = Tab("f", "rr","y");
wind->isEmpty();
Tab U = Tab("nnn", "e","mmm");
wind->print();
Tab Z = Tab("xx", "iii","cc");
wind->print();
Tab X = Tab("eee", "p","ee");
wind->moveActiveTabTo(0);
Tab T = Tab("l", "lll","kkk");
wind->newTab(E);
Tab F = Tab("vv", "p","ww");
wind->isEmpty();
Tab B = Tab("w", "ccc","ccc");
wind->print();
Tab S = Tab("qq", "v","i");
wind->print();
wind->closeTab();
wind->print();
Tab A = Tab("sss", "i","zz");
wind->changeActiveTabTo(1);
Tab Q = Tab("u", "g","n");
wind->getActiveTab();
Tab P = Tab("bb", "ddd","ooo");
wind->moveActiveTabTo(3);
Tab R = Tab("jj", "sss","lll");
wind->isEmpty();
wind->moveActiveTabTo(3);
Tab H = Tab("ddd", "ee","cc");
wind->changeActiveTabTo(3);
wind->isEmpty();
Tab I = Tab("z", "i","bb");
wind->newTab(A);
Tab K = Tab("n", "www","yyy");
wind->newTab(B);
wind->getActiveTab();
wind->moveActiveTabTo(4);
Tab M = Tab("nnn", "pp","t");
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->isEmpty();
Tab D = Tab("uu", "n","aaa");
wind->closeTab();
Tab W = Tab("k", "zzz","uuu");
wind->getActiveTab();
wind->changeActiveTabTo(5);
wind->getActiveTab();
Tab Y = Tab("c", "fff","bbb");
wind->isEmpty();
Tab C = Tab("p", "aa","z");
wind->getActiveTab();
wind->moveActiveTabTo(2);
wind->moveActiveTabTo(0);
wind->getActiveTab();
Tab J = Tab("c", "gg","hhh");
wind->newTab(C);
wind->print();
wind->changeActiveTabTo(3);
wind->getActiveTab();
Tab N = Tab("v", "gg","ddd");
wind->changeActiveTabTo(5);
wind->closeTab();
Tab L = Tab("a", "cc","pp");
wind->getActiveTab();
wind->print();
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->getActiveTab();
Tab O = Tab("f", "l","ddd");
wind->getActiveTab();
wind->moveActiveTabTo(2);
wind->closeTab();
wind->moveActiveTabTo(0);
wind->isEmpty();
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->newTab(D);
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
Tab G = Tab("zz", "ggg","xx");
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->newTab(F);
wind->newTab(G);
wind->print();
wind->isEmpty();
wind->newTab(H);
wind->closeTab();
wind->changeActiveTabTo(2);
wind->newTab(I);
wind->isEmpty();
wind->newTab(J);
wind->getActiveTab();
wind->newTab(K);
wind->getActiveTab();
wind->newTab(L);
wind->print();
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(4);
Tab V = Tab("rrr", "nnn","cc");
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(4);
wind->newTab(M);
wind->print();
wind->closeTab();
wind->moveActiveTabTo(5);
wind->print();
wind->print();
wind->newTab(N);
wind->isEmpty();
wind->getActiveTab();
wind->newTab(O);
wind->print();
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->print();
wind->closeTab();
delete wind;
}
	return 0;
}