#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->moveActiveTabTo(5);
Tab L = Tab("c", "cc","ccc");
wind->isEmpty();
Tab C = Tab("ccc", "y","pp");
wind->closeTab();
Tab F = Tab("rrr", "z","eee");
wind->moveActiveTabTo(4);
Tab G = Tab("aa", "oo","t");
wind->closeTab();
Tab M = Tab("zz", "ee","uuu");
wind->getActiveTab();
wind->closeTab();
Tab D = Tab("ff", "ttt","bb");
wind->newTab(C);
Tab V = Tab("a", "p","iii");
wind->isEmpty();
Tab S = Tab("hhh", "v","ppp");
wind->changeActiveTabTo(5);
Tab W = Tab("ff", "kkk","pp");
wind->isEmpty();
wind->isEmpty();
Tab A = Tab("ggg", "a","ggg");
wind->print();
Tab K = Tab("vvv", "ll","xx");
wind->moveActiveTabTo(2);
Tab U = Tab("zzz", "gg","q");
wind->closeTab();
Tab N = Tab("dd", "aa","bb");
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(3);
Tab J = Tab("e", "i","d");
wind->isEmpty();
Tab Y = Tab("xxx", "hhh","hh");
wind->isEmpty();
wind->print();
wind->print();
Tab Z = Tab("kkk", "jj","hhh");
wind->newTab(A);
wind->print();
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->newTab(D);
wind->getActiveTab();
wind->changeActiveTabTo(1);
Tab H = Tab("ff", "aaa","p");
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(3);
Tab B = Tab("h", "mm","ii");
wind->print();
wind->closeTab();
Tab O = Tab("q", "k","ww");
wind->changeActiveTabTo(4);
Tab P = Tab("f", "uu","u");
wind->closeTab();
Tab E = Tab("h", "fff","yyy");
wind->moveActiveTabTo(4);
wind->changeActiveTabTo(5);
Tab Q = Tab("lll", "g","ww");
wind->closeTab();
wind->newTab(B);
wind->closeTab();
Tab T = Tab("c", "nn","g");
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->print();
wind->closeTab();
wind->changeActiveTabTo(1);
wind->closeTab();
wind->print();
wind->isEmpty();
wind->newTab(E);
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(2);
wind->newTab(F);
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(5);
wind->isEmpty();
wind->newTab(G);
Tab X = Tab("qqq", "c","ii");
wind->closeTab();
wind->closeTab();
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->newTab(H);
wind->newTab(J);
wind->getActiveTab();
Tab R = Tab("r", "mmm","rrr");
wind->newTab(K);
wind->print();
wind->closeTab();
wind->changeActiveTabTo(1);
wind->print();
wind->closeTab();
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(4);
wind->newTab(L);
wind->isEmpty();
wind->closeTab();
wind->changeActiveTabTo(1);
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->newTab(M);
wind->newTab(N);
wind->closeTab();
wind->newTab(O);
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(4);
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->newTab(P);
wind->moveActiveTabTo(1);
wind->print();
wind->getActiveTab();
wind->isEmpty();
wind->print();
Tab I = Tab("nn", "g","ttt");
wind->moveActiveTabTo(5);
delete wind;
}
	return 0;
}