#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->moveActiveTabTo(3);
Tab E = Tab("ggg", "cc","k");
wind->closeTab();
Tab S = Tab("o", "ll","s");
wind->changeActiveTabTo(0);
Tab D = Tab("ll", "hh","iii");
wind->isEmpty();
Tab B = Tab("jj", "ggg","r");
wind->getActiveTab();
Tab H = Tab("r", "ppp","rr");
wind->isEmpty();
Tab P = Tab("aaa", "z","lll");
wind->isEmpty();
Tab J = Tab("j", "ww","ggg");
wind->closeTab();
wind->newTab(B);
Tab G = Tab("aaa", "d","nn");
wind->closeTab();
wind->getActiveTab();
Tab F = Tab("pp", "www","xx");
wind->changeActiveTabTo(5);
wind->newTab(D);
Tab L = Tab("l", "y","rrr");
wind->print();
wind->moveActiveTabTo(4);
wind->print();
wind->getActiveTab();
wind->isEmpty();
Tab N = Tab("fff", "nn","ss");
wind->getActiveTab();
Tab T = Tab("uuu", "d","xx");
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(3);
Tab W = Tab("ppp", "p","h");
wind->newTab(E);
Tab Z = Tab("aa", "eee","mm");
wind->changeActiveTabTo(4);
Tab O = Tab("fff", "d","b");
wind->moveActiveTabTo(1);
wind->closeTab();
wind->isEmpty();
Tab Q = Tab("pp", "tt","ggg");
wind->moveActiveTabTo(5);
wind->closeTab();
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->print();
wind->isEmpty();
Tab I = Tab("ss", "aa","ii");
wind->newTab(F);
Tab U = Tab("r", "c","z");
wind->closeTab();
Tab A = Tab("gg", "ll","qqq");
wind->getActiveTab();
wind->changeActiveTabTo(4);
wind->isEmpty();
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
Tab X = Tab("yyy", "cc","iii");
wind->newTab(A);
wind->closeTab();
wind->newTab(G);
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(0);
wind->newTab(H);
Tab V = Tab("s", "oo","c");
wind->changeActiveTabTo(3);
wind->getActiveTab();
Tab C = Tab("aa", "x","rrr");
wind->moveActiveTabTo(3);
wind->newTab(C);
wind->isEmpty();
wind->newTab(I);
wind->closeTab();
wind->moveActiveTabTo(4);
wind->closeTab();
Tab M = Tab("aa", "d","s");
wind->getActiveTab();
wind->getActiveTab();
wind->isEmpty();
wind->isEmpty();
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->isEmpty();
wind->print();
wind->newTab(J);
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(1);
wind->newTab(L);
wind->print();
wind->getActiveTab();
wind->changeActiveTabTo(5);
wind->newTab(M);
wind->print();
wind->print();
wind->getActiveTab();
wind->newTab(N);
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(0);
wind->print();
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->print();
wind->newTab(O);
wind->newTab(P);
wind->moveActiveTabTo(0);
wind->closeTab();
wind->isEmpty();
wind->closeTab();
Tab R = Tab("b", "zzz","a");
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->print();
wind->print();
wind->changeActiveTabTo(4);
wind->getActiveTab();
wind->isEmpty();
delete wind;
}
	return 0;
}