#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->closeTab();
Tab A = Tab("e", "vvv","www");
wind->changeActiveTabTo(2);
Tab J = Tab("lll", "j","zz");
wind->moveActiveTabTo(0);
Tab F = Tab("ww", "xxx","www");
wind->getActiveTab();
Tab R = Tab("pp", "a","rrr");
wind->moveActiveTabTo(3);
Tab M = Tab("jj", "r","f");
wind->getActiveTab();
Tab Y = Tab("k", "ttt","kk");
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->newTab(A);
Tab T = Tab("b", "jj","ddd");
wind->moveActiveTabTo(0);
Tab D = Tab("c", "m","b");
wind->print();
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(1);
Tab P = Tab("yy", "pp","vvv");
wind->newTab(D);
wind->print();
Tab I = Tab("m", "yyy","c");
wind->changeActiveTabTo(2);
wind->isEmpty();
Tab B = Tab("h", "vv","hh");
wind->changeActiveTabTo(1);
wind->isEmpty();
Tab C = Tab("hhh", "s","www");
wind->moveActiveTabTo(4);
Tab X = Tab("d", "zzz","iii");
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(4);
Tab O = Tab("sss", "rrr","ll");
wind->newTab(B);
Tab V = Tab("ee", "a","ccc");
wind->isEmpty();
wind->getActiveTab();
Tab U = Tab("ww", "y","uu");
wind->isEmpty();
wind->closeTab();
wind->print();
Tab Q = Tab("nnn", "ww","ll");
wind->closeTab();
Tab G = Tab("ww", "s","j");
wind->isEmpty();
wind->isEmpty();
Tab N = Tab("uu", "ooo","ww");
wind->newTab(C);
wind->closeTab();
Tab L = Tab("c", "yy","ww");
wind->newTab(F);
wind->changeActiveTabTo(5);
wind->getActiveTab();
Tab Z = Tab("h", "ooo","oo");
wind->print();
wind->closeTab();
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->closeTab();
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
Tab H = Tab("x", "x","jj");
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(3);
wind->newTab(G);
wind->isEmpty();
wind->print();
Tab E = Tab("hh", "fff","ww");
wind->print();
wind->getActiveTab();
Tab S = Tab("cc", "l","ggg");
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(3);
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->newTab(E);
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(0);
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
wind->closeTab();
wind->closeTab();
wind->closeTab();
wind->print();
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(5);
wind->closeTab();
wind->isEmpty();
wind->newTab(H);
wind->getActiveTab();
wind->closeTab();
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(2);
Tab W = Tab("l", "lll","ss");
wind->getActiveTab();
wind->print();
wind->print();
wind->getActiveTab();
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->print();
wind->isEmpty();
wind->print();
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(0);
wind->newTab(I);
wind->getActiveTab();
wind->print();
wind->closeTab();
delete wind;
}
	return 0;
}