#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->isEmpty();
Tab S = Tab("l", "uuu","j");
wind->changeActiveTabTo(2);
Tab Z = Tab("l", "i","o");
wind->isEmpty();
Tab O = Tab("kk", "zzz","l");
wind->changeActiveTabTo(2);
Tab J = Tab("j", "ppp","y");
wind->closeTab();
Tab H = Tab("bb", "o","eee");
wind->closeTab();
wind->changeActiveTabTo(4);
Tab K = Tab("x", "w","rr");
wind->getActiveTab();
Tab D = Tab("oo", "ooo","ppp");
wind->newTab(D);
Tab T = Tab("m", "aaa","rrr");
wind->moveActiveTabTo(1);
Tab P = Tab("aa", "uu","mmm");
wind->isEmpty();
wind->getActiveTab();
Tab X = Tab("qq", "vvv","ss");
wind->changeActiveTabTo(2);
Tab R = Tab("www", "r","ppp");
wind->changeActiveTabTo(3);
wind->closeTab();
Tab A = Tab("v", "i","l");
wind->changeActiveTabTo(1);
Tab Q = Tab("h", "z","ccc");
wind->newTab(A);
wind->changeActiveTabTo(3);
Tab B = Tab("q", "k","g");
wind->isEmpty();
Tab I = Tab("oo", "ttt","yyy");
wind->changeActiveTabTo(3);
Tab E = Tab("xx", "s","n");
wind->moveActiveTabTo(5);
wind->closeTab();
wind->closeTab();
wind->isEmpty();
Tab Y = Tab("w", "c","mmm");
wind->getActiveTab();
wind->isEmpty();
wind->isEmpty();
wind->newTab(B);
Tab U = Tab("ooo", "ss","ff");
wind->changeActiveTabTo(0);
Tab L = Tab("eee", "a","xx");
wind->print();
wind->newTab(E);
wind->getActiveTab();
wind->newTab(H);
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
wind->closeTab();
Tab N = Tab("uu", "ttt","fff");
wind->closeTab();
wind->moveActiveTabTo(4);
wind->isEmpty();
wind->print();
wind->moveActiveTabTo(4);
wind->closeTab();
wind->newTab(I);
wind->closeTab();
wind->newTab(J);
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(3);
Tab F = Tab("ttt", "l","aaa");
wind->closeTab();
Tab V = Tab("aa", "ww","ff");
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->newTab(F);
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(4);
wind->print();
wind->changeActiveTabTo(3);
wind->closeTab();
wind->newTab(K);
wind->isEmpty();
wind->print();
wind->print();
wind->print();
wind->moveActiveTabTo(1);
wind->print();
wind->newTab(L);
wind->moveActiveTabTo(1);
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
Tab G = Tab("rrr", "kk","ttt");
wind->print();
wind->newTab(G);
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->closeTab();
wind->newTab(N);
Tab W = Tab("qqq", "uu","p");
wind->getActiveTab();
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->isEmpty();
wind->newTab(O);
wind->closeTab();
Tab C = Tab("e", "oo","gg");
wind->newTab(C);
wind->changeActiveTabTo(4);
wind->getActiveTab();
delete wind;
}
	return 0;
}