#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->changeActiveTabTo(1);
Tab Q = Tab("qqq", "jj","ccc");
wind->isEmpty();
Tab B = Tab("lll", "o","aaa");
wind->print();
Tab F = Tab("ww", "ttt","jj");
wind->newTab(B);
Tab Z = Tab("k", "ee","bbb");
wind->newTab(F);
Tab Y = Tab("o", "c","v");
wind->print();
Tab R = Tab("hh", "qqq","qq");
wind->getActiveTab();
Tab M = Tab("rrr", "a","ddd");
wind->moveActiveTabTo(3);
Tab P = Tab("a", "kk","cc");
wind->closeTab();
Tab N = Tab("sss", "n","ee");
wind->closeTab();
wind->getActiveTab();
Tab O = Tab("qqq", "nnn","xx");
wind->getActiveTab();
wind->newTab(M);
Tab I = Tab("www", "uu","gg");
wind->closeTab();
Tab U = Tab("kkk", "sss","yyy");
wind->getActiveTab();
wind->isEmpty();
Tab X = Tab("tt", "yyy","ww");
wind->getActiveTab();
wind->isEmpty();
wind->getActiveTab();
wind->newTab(I);
Tab T = Tab("nnn", "ttt","xx");
wind->newTab(N);
wind->print();
wind->newTab(O);
Tab S = Tab("www", "jjj","xxx");
wind->changeActiveTabTo(5);
wind->print();
wind->getActiveTab();
wind->print();
Tab A = Tab("jjj", "ii","eee");
wind->newTab(A);
Tab K = Tab("ff", "ff","e");
wind->getActiveTab();
Tab D = Tab("gg", "n","nnn");
wind->moveActiveTabTo(2);
Tab C = Tab("n", "l","gg");
wind->newTab(C);
wind->isEmpty();
Tab E = Tab("dd", "aa","iii");
wind->changeActiveTabTo(3);
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(2);
Tab W = Tab("fff", "uuu","r");
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
Tab H = Tab("hh", "eee","y");
wind->print();
wind->moveActiveTabTo(0);
wind->print();
wind->moveActiveTabTo(3);
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(4);
wind->isEmpty();
Tab J = Tab("t", "eee","t");
wind->closeTab();
wind->getActiveTab();
Tab V = Tab("yy", "ss","ppp");
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->isEmpty();
wind->print();
wind->isEmpty();
wind->newTab(D);
wind->closeTab();
wind->isEmpty();
wind->print();
wind->moveActiveTabTo(3);
wind->print();
wind->changeActiveTabTo(2);
wind->print();
wind->newTab(E);
wind->getActiveTab();
wind->print();
wind->isEmpty();
wind->print();
wind->closeTab();
wind->print();
wind->getActiveTab();
wind->closeTab();
wind->closeTab();
wind->newTab(H);
wind->closeTab();
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
Tab L = Tab("hhh", "eee","aaa");
wind->closeTab();
wind->newTab(J);
wind->print();
wind->isEmpty();
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(K);
wind->print();
wind->newTab(L);
wind->isEmpty();
wind->newTab(P);
wind->changeActiveTabTo(3);
wind->print();
wind->print();
wind->isEmpty();
wind->newTab(Q);
wind->print();
wind->newTab(R);
wind->getActiveTab();
delete wind;
}
	return 0;
}