#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->isEmpty();
Tab B = Tab("v", "fff","d");
wind->print();
Tab U = Tab("uuu", "y","tt");
wind->getActiveTab();
Tab S = Tab("dd", "zz","u");
wind->print();
Tab G = Tab("pp", "x","hh");
wind->newTab(B);
Tab J = Tab("l", "x","ddd");
wind->newTab(G);
wind->closeTab();
Tab L = Tab("z", "ii","fff");
wind->getActiveTab();
Tab O = Tab("nn", "s","gg");
wind->changeActiveTabTo(4);
Tab I = Tab("ll", "h","b");
wind->print();
Tab Y = Tab("yyy", "s","o");
wind->closeTab();
Tab Q = Tab("zzz", "s","v");
wind->closeTab();
wind->changeActiveTabTo(4);
wind->print();
Tab M = Tab("ccc", "q","zz");
wind->newTab(I);
wind->isEmpty();
wind->closeTab();
Tab H = Tab("bbb", "mmm","jj");
wind->moveActiveTabTo(2);
Tab F = Tab("ww", "b","o");
wind->changeActiveTabTo(3);
wind->getActiveTab();
wind->isEmpty();
wind->moveActiveTabTo(4);
wind->closeTab();
wind->moveActiveTabTo(4);
Tab C = Tab("w", "ee","vvv");
wind->newTab(C);
wind->print();
Tab E = Tab("pp", "ttt","d");
wind->moveActiveTabTo(2);
wind->getActiveTab();
wind->isEmpty();
wind->moveActiveTabTo(4);
Tab Z = Tab("cc", "dd","cc");
wind->isEmpty();
wind->changeActiveTabTo(0);
wind->newTab(E);
wind->isEmpty();
wind->moveActiveTabTo(4);
Tab W = Tab("kk", "fff","c");
wind->closeTab();
wind->moveActiveTabTo(0);
Tab P = Tab("ooo", "ppp","qqq");
wind->changeActiveTabTo(1);
Tab A = Tab("c", "zzz","mm");
wind->newTab(A);
wind->newTab(F);
wind->isEmpty();
wind->print();
Tab D = Tab("kk", "ii","uu");
wind->moveActiveTabTo(1);
wind->isEmpty();
Tab X = Tab("cc", "qqq","iii");
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(4);
wind->print();
wind->isEmpty();
wind->isEmpty();
wind->newTab(D);
wind->newTab(H);
Tab N = Tab("eee", "n","g");
wind->newTab(J);
wind->isEmpty();
wind->getActiveTab();
wind->changeActiveTabTo(4);
Tab R = Tab("kkk", "vvv","ii");
wind->closeTab();
wind->print();
wind->newTab(L);
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(1);
wind->moveActiveTabTo(5);
wind->newTab(M);
wind->moveActiveTabTo(2);
wind->getActiveTab();
wind->print();
wind->isEmpty();
wind->newTab(N);
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->closeTab();
wind->newTab(O);
Tab T = Tab("f", "aaa","vv");
wind->isEmpty();
wind->newTab(P);
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->print();
wind->closeTab();
wind->newTab(Q);
wind->isEmpty();
wind->newTab(R);
wind->changeActiveTabTo(1);
wind->print();
Tab K = Tab("d", "vvv","ee");
wind->changeActiveTabTo(0);
wind->newTab(K);
wind->newTab(S);
wind->print();
wind->isEmpty();
wind->newTab(T);
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->newTab(U);
wind->changeActiveTabTo(4);
wind->getActiveTab();
wind->print();
delete wind;
}
	return 0;
}