#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->moveActiveTabTo(3);
Tab H = Tab("qqq", "cc","kk");
wind->isEmpty();
Tab D = Tab("aa", "ll","j");
wind->closeTab();
Tab C = Tab("dd", "e","kkk");
wind->closeTab();
Tab V = Tab("uuu", "vvv","bbb");
wind->getActiveTab();
Tab N = Tab("ooo", "bbb","xxx");
wind->getActiveTab();
Tab P = Tab("vvv", "vv","y");
wind->changeActiveTabTo(4);
Tab Q = Tab("ww", "fff","rrr");
wind->isEmpty();
Tab A = Tab("yyy", "rrr","gg");
wind->changeActiveTabTo(1);
Tab X = Tab("yyy", "uuu","m");
wind->moveActiveTabTo(4);
wind->getActiveTab();
Tab B = Tab("h", "kkk","ddd");
wind->moveActiveTabTo(1);
Tab I = Tab("ii", "www","oo");
wind->isEmpty();
Tab J = Tab("h", "vvv","e");
wind->closeTab();
Tab T = Tab("r", "zz","nnn");
wind->changeActiveTabTo(4);
wind->newTab(A);
wind->changeActiveTabTo(2);
Tab L = Tab("ee", "k","ww");
wind->isEmpty();
Tab Z = Tab("iii", "vv","x");
wind->closeTab();
wind->changeActiveTabTo(4);
Tab W = Tab("lll", "h","ooo");
wind->isEmpty();
Tab Y = Tab("ii", "hhh","uuu");
wind->moveActiveTabTo(0);
Tab K = Tab("w", "n","yyy");
wind->changeActiveTabTo(3);
Tab O = Tab("c", "bbb","zzz");
wind->newTab(B);
wind->closeTab();
Tab R = Tab("ee", "d","uu");
wind->getActiveTab();
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(4);
wind->newTab(C);
wind->print();
wind->print();
wind->newTab(D);
Tab U = Tab("nn", "y","zz");
wind->newTab(H);
wind->changeActiveTabTo(3);
Tab S = Tab("ii", "jj","hhh");
wind->isEmpty();
wind->getActiveTab();
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
wind->newTab(I);
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(2);
wind->moveActiveTabTo(2);
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->closeTab();
wind->changeActiveTabTo(3);
Tab F = Tab("ff", "aaa","v");
wind->isEmpty();
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->newTab(F);
wind->moveActiveTabTo(3);
wind->closeTab();
wind->closeTab();
Tab G = Tab("e", "i","a");
wind->changeActiveTabTo(3);
wind->getActiveTab();
wind->isEmpty();
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->print();
wind->closeTab();
wind->closeTab();
wind->newTab(G);
Tab M = Tab("yyy", "gg","x");
wind->print();
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->newTab(J);
wind->moveActiveTabTo(1);
wind->newTab(K);
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->print();
wind->newTab(L);
wind->closeTab();
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(1);
wind->print();
wind->isEmpty();
wind->print();
wind->newTab(M);
wind->isEmpty();
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(N);
delete wind;
}
	return 0;
}