#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->changeActiveTabTo(4);
Tab C = Tab("lll", "u","vvv");
wind->moveActiveTabTo(1);
wind->closeTab();
wind->isEmpty();
Tab X = Tab("ccc", "zzz","n");
wind->changeActiveTabTo(0);
Tab H = Tab("mm", "qq","ccc");
wind->print();
Tab B = Tab("cc", "t","nn");
wind->moveActiveTabTo(2);
Tab V = Tab("pp", "z","a");
wind->moveActiveTabTo(1);
Tab M = Tab("m", "bbb","nnn");
wind->closeTab();
Tab G = Tab("ww", "zz","y");
wind->getActiveTab();
wind->getActiveTab();
Tab Z = Tab("ee", "g","cc");
wind->isEmpty();
Tab A = Tab("vv", "bb","oo");
wind->print();
Tab W = Tab("uuu", "zzz","iii");
wind->closeTab();
Tab N = Tab("xxx", "uuu","dd");
wind->isEmpty();
wind->closeTab();
Tab Q = Tab("yy", "p","h");
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(2);
wind->newTab(A);
wind->getActiveTab();
Tab P = Tab("eee", "ee","ff");
wind->moveActiveTabTo(0);
Tab F = Tab("ee", "q","i");
wind->newTab(B);
wind->getActiveTab();
wind->print();
Tab I = Tab("gg", "gg","y");
wind->changeActiveTabTo(0);
wind->closeTab();
wind->moveActiveTabTo(1);
Tab U = Tab("ppp", "nnn","c");
wind->changeActiveTabTo(3);
wind->getActiveTab();
Tab D = Tab("ee", "ddd","dd");
wind->print();
Tab S = Tab("tt", "pp","cc");
wind->isEmpty();
wind->getActiveTab();
wind->newTab(C);
wind->print();
wind->getActiveTab();
wind->changeActiveTabTo(0);
wind->newTab(D);
wind->isEmpty();
wind->print();
wind->changeActiveTabTo(5);
Tab K = Tab("y", "mm","xx");
wind->getActiveTab();
Tab T = Tab("p", "aaa","mmm");
wind->newTab(F);
wind->newTab(G);
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->getActiveTab();
wind->print();
wind->newTab(H);
wind->isEmpty();
wind->print();
wind->closeTab();
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->newTab(I);
wind->getActiveTab();
Tab L = Tab("p", "qq","qq");
wind->isEmpty();
wind->isEmpty();
wind->print();
Tab O = Tab("sss", "yy","l");
wind->newTab(K);
Tab R = Tab("o", "vv","zzz");
wind->moveActiveTabTo(5);
Tab J = Tab("b", "nnn","b");
wind->newTab(J);
Tab E = Tab("bbb", "pp","www");
wind->print();
wind->moveActiveTabTo(0);
wind->newTab(E);
wind->moveActiveTabTo(2);
wind->getActiveTab();
wind->closeTab();
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(2);
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(4);
wind->isEmpty();
wind->closeTab();
wind->moveActiveTabTo(4);
wind->closeTab();
wind->newTab(L);
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(1);
wind->closeTab();
wind->newTab(M);
wind->isEmpty();
wind->closeTab();
wind->closeTab();
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(N);
wind->newTab(O);
wind->newTab(P);
delete wind;
}
	return 0;
}