#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->print();
Tab G = Tab("vv", "i","vvv");
wind->newTab(G);
Tab E = Tab("q", "b","g");
wind->isEmpty();
wind->print();
Tab J = Tab("i", "dd","dd");
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(2);
wind->print();
wind->isEmpty();
Tab C = Tab("rr", "hh","ddd");
wind->changeActiveTabTo(5);
wind->isEmpty();
Tab K = Tab("yy", "yy","q");
wind->newTab(C);
Tab Q = Tab("xxx", "uuu","f");
wind->isEmpty();
Tab Y = Tab("ww", "bbb","g");
wind->getActiveTab();
wind->newTab(E);
Tab T = Tab("ppp", "ss","hh");
wind->isEmpty();
wind->closeTab();
Tab V = Tab("tt", "w","ooo");
wind->getActiveTab();
Tab S = Tab("t", "kk","w");
wind->isEmpty();
Tab I = Tab("m", "e","vv");
wind->isEmpty();
Tab L = Tab("xx", "ss","m");
wind->moveActiveTabTo(1);
Tab N = Tab("iii", "iii","l");
wind->newTab(I);
wind->newTab(J);
Tab Z = Tab("sss", "sss","k");
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->closeTab();
Tab M = Tab("cc", "jjj","bb");
wind->changeActiveTabTo(3);
Tab B = Tab("u", "jjj","x");
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->print();
wind->getActiveTab();
Tab R = Tab("uu", "e","fff");
wind->print();
wind->changeActiveTabTo(2);
Tab F = Tab("cc", "uu","eee");
wind->print();
wind->changeActiveTabTo(0);
Tab U = Tab("nnn", "o","zzz");
wind->isEmpty();
wind->newTab(B);
wind->newTab(F);
Tab H = Tab("z", "ff","dd");
wind->moveActiveTabTo(1);
Tab D = Tab("zzz", "zzz","ee");
wind->isEmpty();
wind->closeTab();
wind->changeActiveTabTo(5);
Tab P = Tab("hh", "xx","lll");
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->print();
Tab O = Tab("ddd", "r","x");
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(0);
wind->newTab(D);
wind->newTab(H);
wind->getActiveTab();
wind->getActiveTab();
Tab W = Tab("yyy", "v","ooo");
wind->changeActiveTabTo(1);
Tab A = Tab("ii", "eee","zz");
wind->isEmpty();
wind->print();
wind->closeTab();
wind->newTab(A);
wind->moveActiveTabTo(3);
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
wind->closeTab();
wind->print();
wind->newTab(K);
wind->newTab(L);
wind->closeTab();
wind->getActiveTab();
wind->moveActiveTabTo(3);
Tab X = Tab("ppp", "pp","m");
wind->isEmpty();
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->print();
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(2);
wind->closeTab();
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->isEmpty();
wind->newTab(M);
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->print();
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->print();
wind->newTab(N);
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->closeTab();
wind->getActiveTab();
wind->print();
wind->closeTab();
wind->moveActiveTabTo(1);
wind->newTab(O);
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(3);
delete wind;
}
	return 0;
}