#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->changeActiveTabTo(5);
Tab Q = Tab("nnn", "yyy","qqq");
wind->moveActiveTabTo(2);
wind->print();
Tab E = Tab("kkk", "a","jj");
wind->changeActiveTabTo(5);
Tab O = Tab("yy", "tt","o");
wind->newTab(E);
Tab H = Tab("ggg", "ooo","h");
wind->newTab(H);
wind->print();
Tab B = Tab("ggg", "aaa","vv");
wind->changeActiveTabTo(1);
Tab W = Tab("yyy", "nnn","qq");
wind->closeTab();
Tab U = Tab("bbb", "yyy","rrr");
wind->moveActiveTabTo(5);
Tab C = Tab("p", "ii","eee");
wind->getActiveTab();
Tab F = Tab("qqq", "w","a");
wind->newTab(B);
Tab J = Tab("sss", "qq","i");
wind->getActiveTab();
wind->closeTab();
wind->getActiveTab();
Tab A = Tab("v", "oo","iii");
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->newTab(A);
Tab K = Tab("tt", "zz","yy");
wind->getActiveTab();
Tab S = Tab("y", "vv","ll");
wind->moveActiveTabTo(5);
Tab Y = Tab("kk", "q","w");
wind->isEmpty();
Tab M = Tab("b", "uu","y");
wind->getActiveTab();
Tab L = Tab("gg", "kkk","www");
wind->getActiveTab();
Tab X = Tab("ww", "v","f");
wind->newTab(C);
wind->newTab(F);
wind->closeTab();
wind->newTab(J);
Tab G = Tab("tt", "bb","gg");
wind->newTab(G);
Tab Z = Tab("lll", "qq","lll");
wind->getActiveTab();
Tab R = Tab("y", "cc","ooo");
wind->closeTab();
wind->moveActiveTabTo(3);
wind->print();
wind->moveActiveTabTo(4);
Tab T = Tab("rr", "ee","yyy");
wind->print();
Tab V = Tab("ooo", "ppp","nnn");
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->print();
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(2);
wind->getActiveTab();
wind->isEmpty();
Tab P = Tab("www", "hhh","h");
wind->moveActiveTabTo(2);
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
wind->newTab(K);
wind->newTab(L);
wind->newTab(M);
wind->isEmpty();
wind->newTab(O);
wind->newTab(P);
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
Tab I = Tab("iii", "yyy","w");
wind->print();
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(1);
Tab D = Tab("s", "b","hh");
wind->changeActiveTabTo(1);
wind->closeTab();
wind->closeTab();
Tab N = Tab("h", "ccc","aa");
wind->print();
wind->newTab(D);
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
wind->closeTab();
wind->print();
wind->closeTab();
wind->newTab(I);
wind->closeTab();
wind->changeActiveTabTo(4);
wind->print();
wind->print();
wind->closeTab();
wind->newTab(N);
wind->changeActiveTabTo(4);
wind->closeTab();
wind->getActiveTab();
wind->print();
wind->newTab(Q);
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(3);
wind->getActiveTab();
wind->closeTab();
wind->newTab(R);
wind->newTab(S);
wind->newTab(T);
wind->print();
wind->moveActiveTabTo(5);
delete wind;
}
	return 0;
}