#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->getActiveTab();
Tab S = Tab("v", "qq","rrr");
wind->newTab(S);
Tab L = Tab("x", "zzz","f");
wind->moveActiveTabTo(3);
Tab W = Tab("bb", "kk","uuu");
wind->changeActiveTabTo(4);
Tab T = Tab("ooo", "q","ee");
wind->closeTab();
Tab K = Tab("s", "aaa","iii");
wind->moveActiveTabTo(2);
Tab A = Tab("h", "xx","g");
wind->newTab(A);
Tab F = Tab("ppp", "q","h");
wind->changeActiveTabTo(1);
Tab U = Tab("ccc", "k","ss");
wind->moveActiveTabTo(5);
Tab N = Tab("aa", "hhh","cc");
wind->moveActiveTabTo(2);
wind->isEmpty();
Tab M = Tab("xx", "www","mmm");
wind->print();
Tab D = Tab("yyy", "tt","d");
wind->newTab(D);
Tab R = Tab("www", "g","ss");
wind->changeActiveTabTo(1);
Tab V = Tab("r", "xx","n");
wind->changeActiveTabTo(0);
Tab H = Tab("ww", "rrr","fff");
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(F);
Tab Y = Tab("jjj", "j","z");
wind->moveActiveTabTo(0);
Tab Q = Tab("xx", "jjj","www");
wind->getActiveTab();
wind->newTab(H);
wind->newTab(K);
Tab B = Tab("dd", "ccc","nnn");
wind->closeTab();
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(5);
wind->isEmpty();
wind->isEmpty();
wind->moveActiveTabTo(1);
Tab I = Tab("k", "qqq","gg");
wind->print();
wind->getActiveTab();
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->print();
Tab J = Tab("q", "uu","hh");
wind->newTab(B);
wind->changeActiveTabTo(5);
wind->isEmpty();
Tab P = Tab("z", "xxx","nn");
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(5);
wind->closeTab();
wind->print();
wind->print();
wind->moveActiveTabTo(1);
wind->newTab(I);
Tab X = Tab("hh", "oo","m");
wind->print();
wind->closeTab();
Tab C = Tab("p", "ff","ccc");
wind->newTab(C);
wind->newTab(J);
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(0);
wind->newTab(L);
wind->newTab(M);
wind->newTab(N);
wind->getActiveTab();
wind->closeTab();
wind->newTab(P);
wind->isEmpty();
wind->closeTab();
wind->newTab(Q);
wind->print();
wind->print();
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->print();
Tab Z = Tab("hhh", "nnn","d");
wind->changeActiveTabTo(4);
wind->isEmpty();
Tab O = Tab("rr", "j","u");
wind->getActiveTab();
wind->isEmpty();
wind->print();
wind->closeTab();
wind->print();
Tab E = Tab("gg", "mmm","ddd");
wind->getActiveTab();
wind->isEmpty();
wind->isEmpty();
wind->moveActiveTabTo(1);
Tab G = Tab("jjj", "ggg","b");
wind->newTab(E);
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->newTab(G);
wind->moveActiveTabTo(4);
wind->newTab(O);
wind->changeActiveTabTo(4);
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
wind->print();
wind->print();
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(2);
delete wind;
}
	return 0;
}