#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
Tab K = Tab("bb", "uuu","kkk");
wind->print();
Tab U = Tab("nnn", "p","y");
wind->isEmpty();
Tab C = Tab("sss", "eee","xx");
wind->closeTab();
Tab Q = Tab("rr", "n","oo");
wind->isEmpty();
Tab F = Tab("ooo", "j","ooo");
wind->isEmpty();
Tab J = Tab("zz", "hhh","o");
wind->getActiveTab();
Tab O = Tab("oo", "ddd","vv");
wind->changeActiveTabTo(1);
Tab V = Tab("d", "pp","h");
wind->print();
wind->newTab(C);
wind->closeTab();
Tab E = Tab("ll", "ooo","ww");
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(5);
wind->getActiveTab();
Tab G = Tab("ll", "sss","kkk");
wind->isEmpty();
Tab Y = Tab("r", "oo","q");
wind->print();
wind->changeActiveTabTo(0);
Tab P = Tab("ppp", "w","xxx");
wind->print();
wind->newTab(E);
Tab T = Tab("k", "w","ff");
wind->print();
Tab N = Tab("ppp", "ooo","f");
wind->moveActiveTabTo(3);
wind->changeActiveTabTo(2);
Tab A = Tab("hh", "zz","yy");
wind->getActiveTab();
wind->closeTab();
Tab S = Tab("p", "ggg","z");
wind->newTab(A);
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(F);
Tab M = Tab("u", "h","pp");
wind->isEmpty();
wind->closeTab();
wind->newTab(G);
wind->getActiveTab();
Tab B = Tab("ss", "pp","zzz");
wind->newTab(B);
wind->print();
wind->getActiveTab();
wind->changeActiveTabTo(0);
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(3);
Tab D = Tab("ddd", "aaa","cc");
wind->changeActiveTabTo(0);
wind->getActiveTab();
Tab I = Tab("ppp", "nnn","ccc");
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(0);
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->getActiveTab();
Tab H = Tab("xxx", "mmm","ddd");
wind->changeActiveTabTo(4);
wind->print();
wind->print();
wind->changeActiveTabTo(4);
wind->closeTab();
Tab X = Tab("y", "www","rr");
wind->getActiveTab();
wind->newTab(D);
wind->closeTab();
wind->newTab(H);
wind->newTab(I);
wind->closeTab();
wind->changeActiveTabTo(5);
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(5);
wind->isEmpty();
wind->getActiveTab();
Tab R = Tab("mmm", "r","ww");
wind->newTab(J);
wind->getActiveTab();
wind->closeTab();
wind->moveActiveTabTo(5);
wind->closeTab();
Tab W = Tab("kkk", "yy","ii");
wind->newTab(K);
Tab L = Tab("k", "e","yyy");
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->moveActiveTabTo(4);
wind->newTab(L);
Tab Z = Tab("b", "f","t");
wind->closeTab();
wind->print();
wind->getActiveTab();
wind->print();
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->newTab(M);
wind->getActiveTab();
wind->closeTab();
wind->moveActiveTabTo(1);
wind->print();
wind->closeTab();
wind->print();
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->newTab(N);
wind->isEmpty();
wind->closeTab();
wind->closeTab();
wind->moveActiveTabTo(4);
wind->changeActiveTabTo(1);
wind->closeTab();
wind->isEmpty();
wind->newTab(O);
delete wind;
}
	return 0;
}