#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->print();
Tab J = Tab("dd", "i","vv");
wind->closeTab();
Tab Z = Tab("cc", "ee","kkk");
wind->changeActiveTabTo(2);
Tab K = Tab("ee", "ee","vv");
wind->closeTab();
Tab Q = Tab("yyy", "r","zzz");
wind->print();
Tab U = Tab("a", "ii","sss");
wind->newTab(J);
Tab X = Tab("ooo", "r","ee");
wind->getActiveTab();
wind->moveActiveTabTo(5);
Tab A = Tab("q", "rr","jjj");
wind->closeTab();
wind->closeTab();
Tab O = Tab("zz", "mm","i");
wind->closeTab();
Tab P = Tab("qqq", "www","g");
wind->newTab(A);
Tab N = Tab("h", "jjj","kk");
wind->changeActiveTabTo(3);
Tab D = Tab("j", "nn","xxx");
wind->print();
Tab I = Tab("xx", "d","ll");
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->newTab(D);
Tab S = Tab("zzz", "ee","w");
wind->closeTab();
Tab T = Tab("ff", "rr","r");
wind->getActiveTab();
wind->print();
Tab Y = Tab("jj", "c","nnn");
wind->newTab(I);
Tab E = Tab("jj", "eee","ii");
wind->changeActiveTabTo(5);
wind->print();
wind->closeTab();
wind->newTab(E);
wind->getActiveTab();
wind->newTab(K);
wind->isEmpty();
Tab H = Tab("a", "s","i");
wind->getActiveTab();
wind->newTab(H);
Tab R = Tab("eee", "kk","s");
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->moveActiveTabTo(1);
wind->newTab(N);
wind->newTab(O);
Tab M = Tab("lll", "h","h");
wind->getActiveTab();
wind->print();
wind->isEmpty();
wind->newTab(M);
wind->moveActiveTabTo(0);
wind->newTab(P);
Tab W = Tab("zz", "d","ee");
wind->isEmpty();
wind->newTab(Q);
wind->changeActiveTabTo(0);
wind->closeTab();
wind->moveActiveTabTo(4);
wind->newTab(R);
wind->getActiveTab();
wind->closeTab();
wind->getActiveTab();
wind->isEmpty();
Tab B = Tab("uu", "c","z");
wind->newTab(B);
wind->newTab(S);
Tab C = Tab("ss", "xx","hh");
wind->newTab(C);
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(3);
Tab F = Tab("eee", "q","ss");
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->print();
wind->closeTab();
wind->newTab(F);
wind->closeTab();
Tab G = Tab("yyy", "bb","vvv");
wind->newTab(G);
wind->print();
wind->print();
wind->isEmpty();
wind->newTab(T);
wind->closeTab();
wind->isEmpty();
Tab L = Tab("vv", "ii","s");
wind->newTab(L);
wind->newTab(U);
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->print();
wind->closeTab();
wind->newTab(W);
wind->isEmpty();
wind->newTab(X);
wind->print();
wind->newTab(Y);
wind->print();
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(2);
wind->moveActiveTabTo(2);
wind->closeTab();
wind->getActiveTab();
wind->newTab(Z);
wind->closeTab();
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(1);
wind->print();
wind->changeActiveTabTo(1);
wind->closeTab();
wind->moveActiveTabTo(1);
wind->print();
wind->changeActiveTabTo(1);
delete wind;
}
	return 0;
}