#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
Tab S = Tab("n", "eee","uuu");
wind->isEmpty();
Tab R = Tab("nn", "j","d");
wind->moveActiveTabTo(0);
Tab V = Tab("f", "l","t");
wind->isEmpty();
Tab K = Tab("q", "v","ppp");
wind->closeTab();
wind->newTab(K);
wind->moveActiveTabTo(3);
Tab E = Tab("bb", "v","ggg");
wind->moveActiveTabTo(0);
Tab Z = Tab("i", "w","sss");
wind->isEmpty();
Tab Y = Tab("iii", "qq","ss");
wind->print();
Tab B = Tab("sss", "nnn","r");
wind->isEmpty();
Tab O = Tab("jjj", "n","hh");
wind->newTab(B);
Tab D = Tab("ppp", "r","mmm");
wind->print();
wind->getActiveTab();
Tab C = Tab("mm", "nn","vv");
wind->changeActiveTabTo(5);
Tab X = Tab("bb", "xxx","yyy");
wind->isEmpty();
Tab J = Tab("xx", "ccc","vv");
wind->print();
wind->closeTab();
wind->changeActiveTabTo(4);
wind->print();
Tab L = Tab("rr", "pp","sss");
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->closeTab();
Tab G = Tab("n", "nn","i");
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
wind->moveActiveTabTo(5);
Tab F = Tab("jjj", "k","ee");
wind->newTab(C);
wind->closeTab();
Tab P = Tab("l", "yy","mm");
wind->print();
Tab T = Tab("kk", "tt","hhh");
wind->isEmpty();
wind->closeTab();
wind->newTab(D);
wind->getActiveTab();
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->print();
Tab Q = Tab("d", "z","b");
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(2);
Tab A = Tab("yy", "d","m");
wind->moveActiveTabTo(2);
Tab I = Tab("i", "gg","v");
wind->closeTab();
Tab U = Tab("y", "yyy","www");
wind->newTab(A);
wind->moveActiveTabTo(3);
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
wind->closeTab();
wind->print();
wind->newTab(E);
wind->isEmpty();
Tab H = Tab("zzz", "vvv","rr");
wind->moveActiveTabTo(3);
wind->print();
wind->moveActiveTabTo(2);
wind->newTab(F);
wind->changeActiveTabTo(3);
wind->newTab(G);
wind->isEmpty();
wind->moveActiveTabTo(3);
Tab M = Tab("ttt", "lll","z");
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
wind->newTab(H);
wind->newTab(I);
wind->newTab(J);
wind->isEmpty();
wind->closeTab();
wind->print();
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->print();
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->isEmpty();
wind->newTab(L);
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->isEmpty();
wind->print();
wind->newTab(M);
wind->print();
wind->newTab(O);
wind->newTab(P);
wind->print();
wind->moveActiveTabTo(3);
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->getActiveTab();
wind->newTab(Q);
wind->closeTab();
wind->closeTab();
wind->print();
Tab N = Tab("a", "ccc","tt");
wind->closeTab();
wind->isEmpty();
wind->moveActiveTabTo(4);
delete wind;
}
	return 0;
}