#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->closeTab();
Tab Q = Tab("d", "www","rrr");
wind->print();
wind->changeActiveTabTo(3);
Tab T = Tab("ii", "d","cc");
wind->newTab(Q);
Tab H = Tab("mmm", "l","ccc");
wind->print();
Tab N = Tab("ee", "uu","rr");
wind->closeTab();
Tab B = Tab("q", "cc","gg");
wind->newTab(B);
Tab A = Tab("s", "ff","q");
wind->closeTab();
wind->closeTab();
Tab V = Tab("nnn", "o","bb");
wind->isEmpty();
Tab C = Tab("jjj", "n","ll");
wind->getActiveTab();
wind->changeActiveTabTo(3);
Tab S = Tab("e", "ooo","zz");
wind->newTab(A);
Tab Y = Tab("aaa", "t","s");
wind->newTab(C);
wind->isEmpty();
wind->newTab(H);
wind->print();
Tab J = Tab("ccc", "c","n");
wind->print();
wind->print();
Tab G = Tab("www", "yy","jjj");
wind->moveActiveTabTo(4);
wind->changeActiveTabTo(0);
wind->newTab(G);
wind->closeTab();
Tab R = Tab("pp", "sss","ss");
wind->moveActiveTabTo(0);
Tab K = Tab("ppp", "b","q");
wind->print();
wind->getActiveTab();
wind->newTab(J);
wind->print();
Tab U = Tab("hh", "uu","nnn");
wind->isEmpty();
Tab E = Tab("jj", "u","gg");
wind->getActiveTab();
wind->print();
wind->isEmpty();
Tab P = Tab("r", "fff","g");
wind->moveActiveTabTo(0);
wind->closeTab();
Tab Z = Tab("hh", "ccc","aaa");
wind->getActiveTab();
wind->newTab(E);
wind->changeActiveTabTo(4);
wind->newTab(K);
wind->getActiveTab();
wind->print();
Tab I = Tab("o", "dd","kk");
wind->print();
wind->print();
wind->closeTab();
wind->print();
wind->changeActiveTabTo(4);
wind->print();
wind->print();
wind->moveActiveTabTo(2);
wind->moveActiveTabTo(1);
Tab M = Tab("sss", "o","ff");
wind->changeActiveTabTo(1);
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(1);
wind->moveActiveTabTo(4);
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->print();
Tab X = Tab("n", "hhh","kk");
wind->print();
wind->newTab(I);
wind->newTab(M);
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->closeTab();
wind->isEmpty();
wind->print();
wind->newTab(N);
wind->getActiveTab();
Tab L = Tab("ggg", "ee","q");
wind->closeTab();
Tab W = Tab("n", "y","xxx");
wind->moveActiveTabTo(3);
wind->isEmpty();
wind->newTab(L);
Tab F = Tab("xx", "uu","uu");
wind->moveActiveTabTo(5);
wind->closeTab();
wind->moveActiveTabTo(4);
wind->print();
Tab O = Tab("kk", "ddd","ttt");
wind->moveActiveTabTo(3);
wind->isEmpty();
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->print();
wind->print();
wind->changeActiveTabTo(2);
wind->moveActiveTabTo(2);
wind->closeTab();
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(4);
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(2);
wind->newTab(F);
wind->newTab(O);
wind->newTab(P);
wind->getActiveTab();
wind->newTab(R);
wind->changeActiveTabTo(3);
wind->print();
delete wind;
}
	return 0;
}