#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->changeActiveTabTo(1);
Tab Q = Tab("gg", "yy","nnn");
wind->isEmpty();
Tab C = Tab("r", "g","r");
wind->isEmpty();
Tab W = Tab("zz", "tt","i");
wind->moveActiveTabTo(1);
wind->closeTab();
Tab T = Tab("o", "s","nn");
wind->isEmpty();
Tab P = Tab("hhh", "k","ppp");
wind->print();
Tab Y = Tab("w", "s","rr");
wind->newTab(C);
Tab O = Tab("ddd", "yy","uuu");
wind->changeActiveTabTo(3);
Tab V = Tab("kkk", "gg","yyy");
wind->isEmpty();
Tab I = Tab("tt", "m","d");
wind->changeActiveTabTo(3);
wind->isEmpty();
Tab Z = Tab("bbb", "vvv","qqq");
wind->newTab(I);
Tab N = Tab("eee", "k","f");
wind->isEmpty();
Tab H = Tab("aa", "ggg","ccc");
wind->newTab(H);
Tab A = Tab("v", "ii","w");
wind->newTab(A);
wind->isEmpty();
Tab G = Tab("u", "ccc","d");
wind->moveActiveTabTo(1);
wind->isEmpty();
Tab F = Tab("dd", "vv","e");
wind->print();
Tab B = Tab("aaa", "v","ddd");
wind->moveActiveTabTo(4);
Tab J = Tab("hh", "vv","kkk");
wind->changeActiveTabTo(1);
wind->getActiveTab();
Tab E = Tab("ccc", "vv","fff");
wind->moveActiveTabTo(4);
wind->isEmpty();
wind->isEmpty();
Tab M = Tab("a", "r","kkk");
wind->print();
wind->isEmpty();
wind->changeActiveTabTo(4);
Tab U = Tab("h", "e","ppp");
wind->isEmpty();
Tab K = Tab("ww", "fff","fff");
wind->getActiveTab();
Tab X = Tab("jj", "y","r");
wind->closeTab();
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->changeActiveTabTo(0);
wind->getActiveTab();
Tab S = Tab("kkk", "ccc","j");
wind->isEmpty();
wind->print();
wind->print();
wind->moveActiveTabTo(4);
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->closeTab();
wind->print();
Tab D = Tab("dd", "yy","t");
wind->isEmpty();
wind->getActiveTab();
wind->isEmpty();
wind->print();
wind->isEmpty();
wind->newTab(B);
Tab L = Tab("xx", "rr","oo");
wind->newTab(D);
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(3);
wind->print();
wind->changeActiveTabTo(5);
wind->getActiveTab();
wind->print();
wind->newTab(E);
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->changeActiveTabTo(2);
wind->closeTab();
wind->moveActiveTabTo(2);
Tab R = Tab("zzz", "lll","mm");
wind->moveActiveTabTo(5);
wind->newTab(F);
wind->closeTab();
wind->isEmpty();
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->changeActiveTabTo(0);
wind->print();
wind->print();
wind->closeTab();
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->newTab(G);
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(2);
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(3);
wind->newTab(J);
wind->moveActiveTabTo(3);
wind->print();
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(2);
wind->closeTab();
wind->isEmpty();
wind->print();
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(2);
delete wind;
}
	return 0;
}