#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
Tab U = Tab("aa", "ii","ccc");
wind->newTab(U);
Tab A = Tab("f", "vvv","f");
wind->getActiveTab();
Tab X = Tab("s", "qqq","sss");
wind->closeTab();
Tab R = Tab("m", "h","d");
wind->changeActiveTabTo(3);
Tab V = Tab("x", "l","ff");
wind->moveActiveTabTo(3);
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(3);
Tab I = Tab("ccc", "p","i");
wind->moveActiveTabTo(2);
Tab Q = Tab("m", "pp","vvv");
wind->closeTab();
Tab Y = Tab("ww", "sss","uuu");
wind->changeActiveTabTo(5);
Tab N = Tab("o", "bbb","ll");
wind->closeTab();
wind->getActiveTab();
Tab L = Tab("yyy", "qq","yy");
wind->newTab(A);
Tab S = Tab("oo", "l","rr");
wind->closeTab();
Tab Z = Tab("jjj", "ii","yy");
wind->moveActiveTabTo(1);
Tab F = Tab("g", "aaa","cc");
wind->changeActiveTabTo(2);
Tab G = Tab("xx", "aa","hhh");
wind->closeTab();
wind->changeActiveTabTo(3);
wind->closeTab();
Tab K = Tab("zz", "ww","ww");
wind->closeTab();
wind->changeActiveTabTo(1);
Tab C = Tab("mmm", "x","yy");
wind->moveActiveTabTo(3);
Tab M = Tab("ww", "i","d");
wind->changeActiveTabTo(2);
Tab W = Tab("aaa", "jjj","xx");
wind->newTab(C);
wind->print();
Tab D = Tab("v", "m","mmm");
wind->print();
wind->isEmpty();
Tab B = Tab("vv", "ooo","k");
wind->print();
wind->isEmpty();
Tab T = Tab("kkk", "ee","x");
wind->newTab(B);
Tab P = Tab("u", "p","bbb");
wind->moveActiveTabTo(5);
Tab O = Tab("ss", "r","xxx");
wind->print();
wind->getActiveTab();
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->closeTab();
Tab J = Tab("a", "p","r");
wind->isEmpty();
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->moveActiveTabTo(0);
wind->print();
wind->isEmpty();
wind->print();
wind->newTab(D);
Tab E = Tab("eee", "ee","s");
wind->getActiveTab();
Tab H = Tab("l", "jj","dd");
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(1);
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->newTab(E);
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->newTab(F);
wind->newTab(G);
wind->print();
wind->getActiveTab();
wind->closeTab();
wind->print();
wind->changeActiveTabTo(4);
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(3);
wind->newTab(H);
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->newTab(I);
wind->isEmpty();
wind->closeTab();
wind->moveActiveTabTo(4);
wind->closeTab();
wind->closeTab();
wind->closeTab();
wind->newTab(J);
wind->changeActiveTabTo(4);
wind->isEmpty();
wind->isEmpty();
wind->changeActiveTabTo(2);
wind->newTab(K);
wind->newTab(L);
wind->newTab(M);
wind->newTab(N);
wind->newTab(O);
wind->isEmpty();
wind->print();
wind->changeActiveTabTo(2);
wind->closeTab();
delete wind;
}
	return 0;
}