#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->getActiveTab();
Tab T = Tab("r", "gg","l");
wind->isEmpty();
Tab U = Tab("lll", "fff","yy");
wind->isEmpty();
Tab O = Tab("ff", "nn","hhh");
wind->changeActiveTabTo(5);
Tab P = Tab("g", "ss","r");
wind->moveActiveTabTo(3);
Tab L = Tab("uu", "yyy","yy");
wind->changeActiveTabTo(4);
Tab H = Tab("uu", "j","ttt");
wind->moveActiveTabTo(4);
Tab A = Tab("fff", "fff","bbb");
wind->print();
Tab I = Tab("n", "w","u");
wind->getActiveTab();
Tab Z = Tab("nnn", "oo","z");
wind->changeActiveTabTo(3);
wind->print();
wind->getActiveTab();
Tab D = Tab("ll", "l","b");
wind->moveActiveTabTo(3);
Tab X = Tab("oo", "kkk","aaa");
wind->isEmpty();
wind->newTab(A);
wind->changeActiveTabTo(4);
wind->print();
Tab K = Tab("o", "mmm","ccc");
wind->isEmpty();
Tab F = Tab("ccc", "w","ll");
wind->changeActiveTabTo(0);
wind->isEmpty();
Tab S = Tab("r", "o","dd");
wind->newTab(D);
wind->print();
wind->isEmpty();
Tab E = Tab("ppp", "xx","w");
wind->moveActiveTabTo(1);
Tab Q = Tab("hh", "y","nn");
wind->closeTab();
wind->print();
Tab W = Tab("f", "vv","j");
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(5);
wind->isEmpty();
wind->isEmpty();
Tab G = Tab("fff", "cc","rr");
wind->isEmpty();
Tab R = Tab("lll", "bb","jjj");
wind->newTab(E);
wind->isEmpty();
Tab B = Tab("ggg", "kkk","n");
wind->closeTab();
wind->closeTab();
wind->moveActiveTabTo(2);
wind->closeTab();
Tab M = Tab("ww", "vv","vv");
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->newTab(B);
wind->moveActiveTabTo(5);
wind->print();
wind->print();
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
wind->newTab(F);
Tab Y = Tab("c", "hhh","sss");
wind->closeTab();
wind->closeTab();
Tab N = Tab("cc", "q","ppp");
wind->getActiveTab();
wind->newTab(G);
wind->print();
wind->getActiveTab();
wind->isEmpty();
wind->newTab(H);
Tab V = Tab("p", "iii","ll");
wind->closeTab();
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->isEmpty();
wind->isEmpty();
wind->getActiveTab();
wind->print();
wind->print();
wind->moveActiveTabTo(3);
wind->getActiveTab();
wind->getActiveTab();
wind->print();
wind->print();
wind->getActiveTab();
wind->newTab(I);
wind->changeActiveTabTo(2);
wind->closeTab();
wind->print();
wind->isEmpty();
wind->newTab(K);
wind->closeTab();
Tab J = Tab("g", "g","qq");
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(3);
wind->closeTab();
wind->closeTab();
wind->isEmpty();
wind->print();
wind->changeActiveTabTo(1);
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
wind->newTab(J);
wind->changeActiveTabTo(1);
wind->closeTab();
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(4);
wind->getActiveTab();
wind->print();
wind->moveActiveTabTo(2);
wind->print();
wind->moveActiveTabTo(1);
delete wind;
}
	return 0;
}