#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->changeActiveTabTo(2);
Tab F = Tab("ii", "m","jj");
wind->moveActiveTabTo(1);
Tab E = Tab("c", "qqq","kk");
wind->changeActiveTabTo(1);
Tab D = Tab("dd", "j","e");
wind->print();
wind->changeActiveTabTo(4);
Tab P = Tab("qqq", "kkk","xxx");
wind->closeTab();
Tab L = Tab("fff", "www","q");
wind->newTab(D);
Tab Q = Tab("i", "i","z");
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(1);
Tab Z = Tab("jj", "zz","x");
wind->closeTab();
Tab Y = Tab("gg", "a","rrr");
wind->newTab(E);
wind->newTab(F);
wind->getActiveTab();
Tab R = Tab("r", "mmm","yy");
wind->print();
Tab J = Tab("k", "aaa","hh");
wind->changeActiveTabTo(5);
Tab G = Tab("cc", "zz","nnn");
wind->isEmpty();
wind->newTab(G);
wind->changeActiveTabTo(2);
wind->closeTab();
Tab C = Tab("o", "ss","h");
wind->newTab(C);
wind->getActiveTab();
wind->closeTab();
Tab O = Tab("xx", "hhh","yy");
wind->changeActiveTabTo(4);
Tab V = Tab("m", "nn","bbb");
wind->closeTab();
Tab N = Tab("e", "hhh","qqq");
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(4);
Tab M = Tab("a", "v","uu");
wind->moveActiveTabTo(0);
wind->closeTab();
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->newTab(J);
Tab A = Tab("v", "ttt","l");
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(1);
Tab K = Tab("hh", "mm","jjj");
wind->isEmpty();
Tab U = Tab("aaa", "zzz","jj");
wind->closeTab();
Tab W = Tab("jjj", "nn","ppp");
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->getActiveTab();
wind->newTab(A);
wind->isEmpty();
wind->isEmpty();
Tab X = Tab("b", "tt","ggg");
wind->closeTab();
wind->isEmpty();
Tab I = Tab("s", "ppp","aaa");
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(4);
wind->getActiveTab();
Tab S = Tab("jjj", "w","xx");
wind->moveActiveTabTo(2);
Tab H = Tab("c", "tt","aaa");
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->moveActiveTabTo(2);
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->newTab(H);
wind->moveActiveTabTo(5);
wind->closeTab();
wind->closeTab();
wind->getActiveTab();
wind->print();
wind->newTab(I);
wind->changeActiveTabTo(4);
wind->getActiveTab();
wind->changeActiveTabTo(4);
wind->getActiveTab();
wind->isEmpty();
wind->print();
Tab B = Tab("g", "zz","x");
wind->newTab(B);
wind->moveActiveTabTo(0);
wind->print();
wind->getActiveTab();
wind->print();
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(4);
wind->print();
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->changeActiveTabTo(2);
wind->closeTab();
wind->newTab(K);
wind->moveActiveTabTo(0);
wind->getActiveTab();
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->print();
wind->closeTab();
wind->newTab(L);
Tab T = Tab("j", "d","kkk");
wind->moveActiveTabTo(1);
wind->closeTab();
wind->newTab(M);
wind->getActiveTab();
wind->isEmpty();
wind->newTab(N);
delete wind;
}
	return 0;
}