#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->changeActiveTabTo(0);
Tab J = Tab("nnn", "rrr","n");
wind->moveActiveTabTo(1);
Tab T = Tab("d", "jj","ddd");
wind->newTab(J);
Tab I = Tab("mm", "yy","nnn");
wind->isEmpty();
Tab X = Tab("yyy", "k","m");
wind->moveActiveTabTo(2);
Tab W = Tab("nn", "ddd","ppp");
wind->changeActiveTabTo(5);
wind->newTab(I);
Tab E = Tab("n", "mm","nn");
wind->getActiveTab();
Tab O = Tab("mm", "n","mmm");
wind->print();
Tab V = Tab("t", "iii","o");
wind->newTab(E);
Tab M = Tab("ggg", "mmm","ss");
wind->moveActiveTabTo(3);
Tab A = Tab("h", "w","mm");
wind->moveActiveTabTo(5);
wind->newTab(A);
Tab N = Tab("n", "uuu","ss");
wind->changeActiveTabTo(3);
wind->getActiveTab();
Tab K = Tab("iii", "g","zz");
wind->newTab(K);
wind->moveActiveTabTo(4);
Tab B = Tab("e", "nn","uuu");
wind->newTab(B);
wind->moveActiveTabTo(3);
wind->isEmpty();
Tab Q = Tab("bbb", "aaa","ii");
wind->getActiveTab();
wind->moveActiveTabTo(2);
wind->closeTab();
wind->closeTab();
wind->moveActiveTabTo(2);
wind->newTab(M);
Tab L = Tab("pp", "www","a");
wind->getActiveTab();
Tab R = Tab("fff", "o","oo");
wind->newTab(L);
Tab U = Tab("z", "k","lll");
wind->isEmpty();
wind->print();
Tab G = Tab("j", "eee","dd");
wind->closeTab();
wind->print();
Tab P = Tab("jj", "d","w");
wind->print();
Tab S = Tab("l", "ii","f");
wind->moveActiveTabTo(1);
Tab H = Tab("jjj", "r","tt");
wind->closeTab();
wind->closeTab();
wind->moveActiveTabTo(4);
wind->changeActiveTabTo(4);
wind->changeActiveTabTo(3);
wind->newTab(G);
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
wind->closeTab();
Tab F = Tab("r", "pp","ll");
wind->isEmpty();
wind->closeTab();
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->moveActiveTabTo(3);
wind->closeTab();
wind->newTab(F);
Tab C = Tab("c", "b","mmm");
wind->print();
wind->getActiveTab();
wind->print();
wind->moveActiveTabTo(3);
wind->isEmpty();
wind->closeTab();
wind->print();
wind->changeActiveTabTo(0);
Tab Y = Tab("z", "hh","ddd");
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(5);
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->newTab(C);
wind->moveActiveTabTo(2);
wind->closeTab();
wind->moveActiveTabTo(4);
wind->closeTab();
wind->newTab(H);
wind->moveActiveTabTo(2);
wind->closeTab();
wind->closeTab();
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->isEmpty();
Tab Z = Tab("bbb", "uu","hh");
wind->getActiveTab();
wind->moveActiveTabTo(1);
wind->print();
wind->changeActiveTabTo(2);
wind->print();
wind->newTab(N);
wind->closeTab();
wind->changeActiveTabTo(1);
wind->closeTab();
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->getActiveTab();
Tab D = Tab("ddd", "bb","i");
wind->closeTab();
wind->moveActiveTabTo(4);
wind->closeTab();
wind->closeTab();
wind->changeActiveTabTo(0);
wind->newTab(D);
wind->closeTab();
delete wind;
}
	return 0;
}