#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->changeActiveTabTo(3);
Tab L = Tab("y", "hh","rrr");
wind->isEmpty();
Tab J = Tab("r", "fff","pp");
wind->moveActiveTabTo(2);
Tab I = Tab("uu", "l","e");
wind->changeActiveTabTo(4);
Tab A = Tab("hh", "r","rr");
wind->newTab(A);
Tab Q = Tab("oo", "hh","qq");
wind->closeTab();
Tab P = Tab("oo", "v","gg");
wind->print();
Tab B = Tab("ppp", "kk","ccc");
wind->changeActiveTabTo(0);
Tab E = Tab("jj", "ddd","ww");
wind->moveActiveTabTo(3);
Tab F = Tab("gg", "yyy","ooo");
wind->getActiveTab();
wind->isEmpty();
Tab M = Tab("z", "cc","fff");
wind->getActiveTab();
Tab H = Tab("nn", "vv","u");
wind->closeTab();
wind->changeActiveTabTo(4);
Tab V = Tab("ll", "ccc","f");
wind->getActiveTab();
wind->closeTab();
wind->newTab(B);
Tab W = Tab("n", "i","fff");
wind->getActiveTab();
wind->closeTab();
Tab O = Tab("nn", "vv","xxx");
wind->print();
Tab S = Tab("j", "y","kkk");
wind->closeTab();
wind->getActiveTab();
wind->getActiveTab();
wind->print();
wind->moveActiveTabTo(1);
wind->print();
wind->getActiveTab();
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(1);
wind->changeActiveTabTo(5);
wind->newTab(E);
wind->print();
wind->getActiveTab();
wind->isEmpty();
wind->closeTab();
Tab C = Tab("gg", "ww","uuu");
wind->closeTab();
wind->print();
Tab K = Tab("fff", "www","aa");
wind->moveActiveTabTo(2);
wind->newTab(C);
Tab Z = Tab("jj", "ttt","kk");
wind->print();
Tab D = Tab("zzz", "g","pp");
wind->newTab(D);
wind->newTab(F);
Tab T = Tab("ee", "nn","x");
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->newTab(H);
Tab G = Tab("tt", "oo","b");
wind->moveActiveTabTo(2);
Tab R = Tab("sss", "s","nn");
wind->getActiveTab();
wind->newTab(G);
wind->getActiveTab();
Tab X = Tab("y", "bb","fff");
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->print();
wind->changeActiveTabTo(4);
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->getActiveTab();
wind->isEmpty();
wind->print();
Tab Y = Tab("h", "bbb","nnn");
wind->getActiveTab();
wind->closeTab();
wind->newTab(I);
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(1);
wind->newTab(J);
wind->getActiveTab();
wind->isEmpty();
wind->print();
wind->closeTab();
wind->changeActiveTabTo(0);
wind->closeTab();
wind->getActiveTab();
wind->print();
wind->getActiveTab();
wind->print();
wind->closeTab();
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->closeTab();
wind->moveActiveTabTo(2);
wind->print();
wind->changeActiveTabTo(1);
wind->newTab(K);
wind->closeTab();
wind->closeTab();
wind->closeTab();
wind->newTab(L);
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->print();
Tab N = Tab("d", "g","w");
wind->print();
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->changeActiveTabTo(0);
wind->newTab(M);
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
delete wind;
}
	return 0;
}