#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->getActiveTab();
Tab L = Tab("ii", "kkk","f");
wind->newTab(L);
Tab G = Tab("qq", "tt","rr");
wind->newTab(G);
Tab J = Tab("aaa", "w","y");
wind->moveActiveTabTo(0);
Tab P = Tab("nnn", "e","vv");
wind->isEmpty();
Tab T = Tab("z", "ggg","oo");
wind->moveActiveTabTo(1);
Tab X = Tab("b", "uuu","ff");
wind->newTab(J);
Tab I = Tab("p", "l","w");
wind->changeActiveTabTo(0);
Tab U = Tab("jj", "dd","www");
wind->changeActiveTabTo(3);
wind->closeTab();
Tab H = Tab("ee", "ee","t");
wind->newTab(H);
wind->newTab(I);
Tab R = Tab("z", "cc","d");
wind->closeTab();
Tab W = Tab("yy", "ee","e");
wind->isEmpty();
Tab Y = Tab("aa", "r","rr");
wind->getActiveTab();
Tab S = Tab("uu", "pp","n");
wind->isEmpty();
Tab C = Tab("mm", "vvv","n");
wind->moveActiveTabTo(2);
Tab Q = Tab("fff", "xx","rrr");
wind->changeActiveTabTo(2);
wind->newTab(C);
wind->isEmpty();
Tab O = Tab("bbb", "fff","b");
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(0);
Tab B = Tab("hh", "www","ff");
wind->isEmpty();
wind->moveActiveTabTo(3);
wind->getActiveTab();
wind->closeTab();
wind->getActiveTab();
Tab V = Tab("jjj", "o","www");
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(1);
wind->getActiveTab();
wind->moveActiveTabTo(1);
Tab A = Tab("t", "k","ggg");
wind->closeTab();
Tab M = Tab("uu", "b","z");
wind->newTab(A);
wind->getActiveTab();
Tab K = Tab("ll", "ii","rr");
wind->newTab(B);
wind->isEmpty();
wind->isEmpty();
wind->print();
Tab N = Tab("i", "t","b");
wind->getActiveTab();
wind->getActiveTab();
Tab F = Tab("hhh", "ff","o");
wind->print();
wind->newTab(F);
wind->getActiveTab();
wind->newTab(K);
wind->isEmpty();
wind->moveActiveTabTo(4);
wind->closeTab();
wind->print();
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(2);
wind->closeTab();
wind->newTab(M);
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->closeTab();
wind->moveActiveTabTo(5);
wind->getActiveTab();
Tab Z = Tab("j", "fff","h");
wind->moveActiveTabTo(4);
wind->isEmpty();
Tab D = Tab("f", "bb","q");
wind->getActiveTab();
wind->isEmpty();
wind->newTab(D);
wind->newTab(N);
wind->closeTab();
wind->getActiveTab();
wind->changeActiveTabTo(3);
wind->newTab(O);
wind->changeActiveTabTo(3);
wind->closeTab();
wind->moveActiveTabTo(0);
wind->newTab(P);
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->moveActiveTabTo(0);
Tab E = Tab("l", "nn","www");
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(0);
wind->closeTab();
wind->closeTab();
wind->print();
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
wind->getActiveTab();
wind->newTab(E);
wind->newTab(Q);
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->print();
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->print();
wind->closeTab();
wind->isEmpty();
wind->closeTab();
delete wind;
}
	return 0;
}