#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->getActiveTab();
Tab F = Tab("oo", "j","pp");
wind->getActiveTab();
Tab G = Tab("w", "ccc","c");
wind->moveActiveTabTo(1);
Tab K = Tab("sss", "t","sss");
wind->changeActiveTabTo(3);
Tab R = Tab("jjj", "uu","f");
wind->changeActiveTabTo(3);
wind->getActiveTab();
Tab V = Tab("xx", "c","eee");
wind->closeTab();
Tab N = Tab("k", "p","rr");
wind->moveActiveTabTo(5);
Tab L = Tab("lll", "k","rrr");
wind->newTab(F);
Tab Z = Tab("ddd", "zz","kk");
wind->moveActiveTabTo(0);
Tab I = Tab("l", "q","rr");
wind->isEmpty();
Tab P = Tab("ww", "a","ppp");
wind->changeActiveTabTo(5);
Tab B = Tab("ttt", "j","cc");
wind->newTab(B);
Tab O = Tab("sss", "www","cc");
wind->changeActiveTabTo(2);
Tab Q = Tab("n", "iii","u");
wind->print();
Tab W = Tab("zz", "ddd","q");
wind->newTab(G);
Tab M = Tab("b", "r","s");
wind->isEmpty();
Tab U = Tab("c", "a","aa");
wind->print();
wind->print();
wind->isEmpty();
Tab J = Tab("gg", "m","zzz");
wind->closeTab();
wind->getActiveTab();
Tab S = Tab("y", "iii","ccc");
wind->closeTab();
Tab D = Tab("mmm", "q","f");
wind->moveActiveTabTo(2);
Tab C = Tab("tt", "o","ppp");
wind->isEmpty();
wind->isEmpty();
wind->print();
wind->closeTab();
Tab T = Tab("xxx", "pp","kkk");
wind->isEmpty();
wind->moveActiveTabTo(1);
wind->moveActiveTabTo(2);
wind->changeActiveTabTo(5);
wind->isEmpty();
Tab E = Tab("rrr", "nn","sss");
wind->print();
wind->moveActiveTabTo(4);
Tab H = Tab("nn", "i","mm");
wind->moveActiveTabTo(4);
Tab Y = Tab("lll", "ppp","rrr");
wind->newTab(C);
wind->closeTab();
wind->changeActiveTabTo(3);
wind->newTab(D);
wind->changeActiveTabTo(2);
wind->closeTab();
wind->newTab(E);
wind->getActiveTab();
wind->print();
wind->closeTab();
wind->moveActiveTabTo(5);
wind->closeTab();
Tab X = Tab("ooo", "qqq","bbb");
wind->isEmpty();
wind->getActiveTab();
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->newTab(H);
wind->moveActiveTabTo(2);
wind->closeTab();
wind->closeTab();
wind->isEmpty();
wind->changeActiveTabTo(3);
wind->newTab(I);
wind->closeTab();
wind->changeActiveTabTo(3);
wind->print();
wind->closeTab();
Tab A = Tab("dd", "xxx","kk");
wind->isEmpty();
wind->newTab(A);
wind->print();
wind->moveActiveTabTo(1);
wind->isEmpty();
wind->newTab(J);
wind->changeActiveTabTo(3);
wind->newTab(K);
wind->isEmpty();
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->isEmpty();
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->closeTab();
wind->print();
wind->newTab(L);
wind->changeActiveTabTo(4);
wind->newTab(M);
wind->closeTab();
wind->moveActiveTabTo(4);
wind->print();
wind->newTab(N);
wind->closeTab();
wind->getActiveTab();
wind->getActiveTab();
wind->isEmpty();
wind->closeTab();
wind->newTab(O);
wind->print();
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(2);
wind->newTab(P);
wind->getActiveTab();
wind->print();
delete wind;
}
	return 0;
}