#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->moveActiveTabTo(3);
Tab F = Tab("x", "tt","mm");
wind->getActiveTab();
Tab D = Tab("l", "e","ii");
wind->newTab(D);
Tab U = Tab("r", "jj","aa");
wind->isEmpty();
Tab R = Tab("oo", "jj","c");
wind->isEmpty();
Tab M = Tab("n", "b","bbb");
wind->isEmpty();
Tab X = Tab("xxx", "rrr","k");
wind->isEmpty();
Tab A = Tab("uu", "i","uu");
wind->newTab(A);
wind->print();
wind->isEmpty();
Tab C = Tab("ggg", "yy","ttt");
wind->print();
Tab V = Tab("jj", "zz","rrr");
wind->closeTab();
Tab Q = Tab("vv", "aaa","n");
wind->closeTab();
Tab Z = Tab("n", "fff","g");
wind->isEmpty();
Tab O = Tab("hh", "h","z");
wind->print();
Tab J = Tab("b", "a","w");
wind->newTab(C);
wind->isEmpty();
wind->newTab(F);
wind->newTab(J);
Tab S = Tab("p", "rr","ff");
wind->isEmpty();
Tab K = Tab("xx", "ff","q");
wind->isEmpty();
wind->closeTab();
Tab E = Tab("ee", "ss","aaa");
wind->closeTab();
wind->getActiveTab();
wind->newTab(E);
wind->closeTab();
Tab N = Tab("j", "vvv","uu");
wind->changeActiveTabTo(5);
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->closeTab();
wind->getActiveTab();
wind->print();
Tab P = Tab("ee", "i","ooo");
wind->isEmpty();
Tab B = Tab("ppp", "kkk","w");
wind->isEmpty();
Tab G = Tab("ccc", "aaa","vvv");
wind->print();
wind->closeTab();
wind->print();
Tab H = Tab("ll", "ggg","i");
wind->moveActiveTabTo(0);
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
Tab T = Tab("n", "ddd","iii");
wind->isEmpty();
wind->print();
Tab L = Tab("ee", "c","zzz");
wind->closeTab();
wind->changeActiveTabTo(5);
wind->getActiveTab();
wind->closeTab();
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->closeTab();
wind->moveActiveTabTo(2);
wind->closeTab();
Tab I = Tab("hhh", "hh","gg");
wind->isEmpty();
wind->print();
wind->isEmpty();
wind->newTab(B);
wind->moveActiveTabTo(0);
wind->newTab(G);
wind->print();
wind->print();
wind->isEmpty();
wind->getActiveTab();
wind->changeActiveTabTo(0);
wind->getActiveTab();
wind->print();
Tab W = Tab("bb", "g","rr");
wind->closeTab();
wind->print();
wind->print();
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->newTab(H);
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(5);
wind->newTab(I);
wind->print();
wind->getActiveTab();
wind->newTab(K);
wind->newTab(L);
wind->changeActiveTabTo(1);
wind->isEmpty();
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
wind->closeTab();
wind->closeTab();
wind->isEmpty();
wind->closeTab();
wind->getActiveTab();
wind->changeActiveTabTo(4);
wind->changeActiveTabTo(0);
wind->print();
wind->moveActiveTabTo(3);
wind->newTab(M);
wind->isEmpty();
wind->print();
wind->moveActiveTabTo(5);
wind->closeTab();
wind->changeActiveTabTo(4);
wind->print();
delete wind;
}
	return 0;
}