#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->closeTab();
Tab I = Tab("b", "l","x");
wind->print();
Tab X = Tab("yyy", "e","d");
wind->moveActiveTabTo(3);
Tab P = Tab("nn", "s","ddd");
wind->closeTab();
Tab R = Tab("f", "ttt","eee");
wind->newTab(I);
Tab M = Tab("a", "y","lll");
wind->newTab(M);
Tab G = Tab("zzz", "yyy","o");
wind->getActiveTab();
Tab C = Tab("n", "gg","n");
wind->moveActiveTabTo(2);
Tab S = Tab("x", "ss","x");
wind->moveActiveTabTo(3);
wind->closeTab();
Tab N = Tab("zzz", "v","o");
wind->closeTab();
wind->getActiveTab();
wind->moveActiveTabTo(0);
wind->getActiveTab();
Tab H = Tab("ii", "kk","mmm");
wind->closeTab();
Tab E = Tab("sss", "qq","d");
wind->moveActiveTabTo(0);
Tab Y = Tab("qqq", "zz","ccc");
wind->getActiveTab();
wind->changeActiveTabTo(2);
Tab T = Tab("ttt", "ff","bbb");
wind->changeActiveTabTo(5);
wind->isEmpty();
wind->isEmpty();
Tab L = Tab("jjj", "nnn","n");
wind->isEmpty();
wind->print();
wind->print();
Tab U = Tab("jj", "w","xxx");
wind->isEmpty();
wind->closeTab();
Tab W = Tab("d", "nnn","uu");
wind->getActiveTab();
wind->isEmpty();
wind->newTab(C);
wind->changeActiveTabTo(5);
Tab K = Tab("v", "b","ooo");
wind->moveActiveTabTo(1);
Tab F = Tab("dd", "ll","hh");
wind->moveActiveTabTo(3);
wind->isEmpty();
Tab O = Tab("f", "r","w");
wind->changeActiveTabTo(3);
wind->moveActiveTabTo(4);
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->changeActiveTabTo(3);
wind->newTab(E);
wind->changeActiveTabTo(3);
wind->changeActiveTabTo(4);
Tab V = Tab("u", "ll","d");
wind->getActiveTab();
wind->moveActiveTabTo(1);
wind->closeTab();
wind->moveActiveTabTo(3);
wind->closeTab();
wind->print();
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->closeTab();
wind->print();
wind->print();
wind->getActiveTab();
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
wind->getActiveTab();
wind->isEmpty();
wind->changeActiveTabTo(4);
wind->closeTab();
wind->moveActiveTabTo(2);
Tab A = Tab("d", "vvv","ppp");
wind->changeActiveTabTo(4);
wind->closeTab();
wind->newTab(A);
wind->moveActiveTabTo(2);
wind->closeTab();
wind->getActiveTab();
wind->isEmpty();
Tab J = Tab("ff", "qqq","hh");
wind->getActiveTab();
wind->moveActiveTabTo(2);
wind->isEmpty();
wind->changeActiveTabTo(0);
wind->newTab(F);
wind->closeTab();
wind->newTab(G);
wind->closeTab();
wind->newTab(H);
wind->closeTab();
wind->closeTab();
wind->getActiveTab();
Tab B = Tab("ii", "uu","iii");
wind->isEmpty();
wind->isEmpty();
wind->moveActiveTabTo(1);
Tab Q = Tab("ll", "kk","zz");
wind->getActiveTab();
wind->closeTab();
wind->isEmpty();
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(1);
wind->print();
wind->closeTab();
wind->isEmpty();
wind->getActiveTab();
wind->newTab(B);
wind->print();
wind->changeActiveTabTo(0);
Tab Z = Tab("xxx", "tt","ii");
wind->newTab(J);
wind->moveActiveTabTo(3);
wind->newTab(K);
delete wind;
}
	return 0;
}