#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->getActiveTab();
Tab P = Tab("kkk", "nn","qq");
wind->newTab(P);
Tab I = Tab("yy", "t","jjj");
wind->moveActiveTabTo(0);
Tab N = Tab("ggg", "w","tt");
wind->isEmpty();
Tab T = Tab("z", "ff","u");
wind->changeActiveTabTo(0);
Tab K = Tab("w", "www","xxx");
wind->closeTab();
Tab R = Tab("hh", "z","xx");
wind->print();
Tab G = Tab("ooo", "gg","yy");
wind->getActiveTab();
Tab B = Tab("ff", "gg","s");
wind->newTab(B);
Tab A = Tab("ff", "ttt","ll");
wind->moveActiveTabTo(2);
Tab S = Tab("ppp", "l","kkk");
wind->isEmpty();
Tab W = Tab("aa", "ii","bb");
wind->isEmpty();
Tab Q = Tab("d", "pp","yy");
wind->closeTab();
wind->isEmpty();
Tab X = Tab("zzz", "ppp","ddd");
wind->changeActiveTabTo(4);
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(4);
wind->isEmpty();
wind->getActiveTab();
Tab U = Tab("m", "n","qq");
wind->changeActiveTabTo(5);
wind->closeTab();
wind->closeTab();
wind->closeTab();
Tab Z = Tab("e", "yy","ii");
wind->moveActiveTabTo(5);
Tab Y = Tab("jj", "oo","rrr");
wind->closeTab();
wind->closeTab();
Tab H = Tab("kk", "kkk","bb");
wind->moveActiveTabTo(1);
wind->moveActiveTabTo(2);
wind->getActiveTab();
wind->print();
Tab C = Tab("p", "xx","qq");
wind->newTab(A);
Tab M = Tab("eee", "i","www");
wind->getActiveTab();
wind->print();
wind->moveActiveTabTo(1);
Tab J = Tab("ccc", "ttt","m");
wind->changeActiveTabTo(2);
wind->newTab(C);
wind->newTab(G);
wind->newTab(H);
wind->moveActiveTabTo(2);
Tab F = Tab("ee", "m","yyy");
wind->print();
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->isEmpty();
wind->isEmpty();
wind->newTab(F);
wind->getActiveTab();
wind->isEmpty();
Tab E = Tab("mm", "j","e");
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->print();
wind->print();
wind->changeActiveTabTo(5);
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
Tab V = Tab("r", "sss","t");
wind->closeTab();
Tab L = Tab("lll", "ggg","bb");
wind->moveActiveTabTo(1);
wind->getActiveTab();
wind->changeActiveTabTo(3);
Tab O = Tab("pp", "iii","bbb");
wind->moveActiveTabTo(4);
wind->print();
wind->moveActiveTabTo(3);
wind->isEmpty();
wind->getActiveTab();
wind->closeTab();
wind->moveActiveTabTo(4);
wind->isEmpty();
wind->newTab(E);
wind->getActiveTab();
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(2);
wind->newTab(I);
wind->isEmpty();
wind->print();
wind->closeTab();
wind->changeActiveTabTo(1);
wind->isEmpty();
wind->print();
wind->newTab(J);
wind->print();
wind->print();
wind->getActiveTab();
wind->moveActiveTabTo(4);
wind->closeTab();
wind->print();
wind->isEmpty();
wind->print();
wind->newTab(K);
wind->getActiveTab();
wind->print();
wind->isEmpty();
wind->newTab(L);
wind->isEmpty();
wind->moveActiveTabTo(0);
wind->changeActiveTabTo(5);
wind->closeTab();
delete wind;
}
	return 0;
}