#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
Tab Y = Tab("kkk", "b","ooo");
wind->changeActiveTabTo(0);
Tab G = Tab("yyy", "s","g");
wind->moveActiveTabTo(0);
Tab D = Tab("q", "aa","k");
wind->newTab(D);
Tab Q = Tab("jj", "y","rr");
wind->getActiveTab();
Tab A = Tab("aaa", "jjj","nnn");
wind->closeTab();
Tab I = Tab("p", "uuu","m");
wind->getActiveTab();
wind->isEmpty();
Tab O = Tab("ggg", "jjj","c");
wind->moveActiveTabTo(0);
Tab C = Tab("rrr", "bbb","vvv");
wind->print();
wind->print();
Tab V = Tab("h", "w","iii");
wind->isEmpty();
wind->getActiveTab();
Tab H = Tab("ooo", "e","bb");
wind->isEmpty();
Tab P = Tab("ll", "xxx","ppp");
wind->closeTab();
Tab S = Tab("ff", "zz","hh");
wind->print();
Tab Z = Tab("ff", "zzz","ii");
wind->closeTab();
wind->isEmpty();
wind->newTab(A);
wind->getActiveTab();
wind->newTab(C);
wind->newTab(G);
Tab F = Tab("rrr", "r","hh");
wind->isEmpty();
Tab W = Tab("tt", "ww","vvv");
wind->changeActiveTabTo(2);
wind->getActiveTab();
Tab R = Tab("c", "y","iii");
wind->print();
wind->newTab(F);
Tab N = Tab("ggg", "sss","yyy");
wind->newTab(H);
Tab M = Tab("qq", "n","ii");
wind->getActiveTab();
wind->getActiveTab();
Tab K = Tab("oo", "q","ggg");
wind->closeTab();
wind->getActiveTab();
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(3);
wind->print();
Tab J = Tab("yy", "bb","aaa");
wind->print();
Tab B = Tab("mm", "yy","s");
wind->isEmpty();
wind->closeTab();
wind->newTab(B);
wind->isEmpty();
wind->isEmpty();
wind->closeTab();
wind->getActiveTab();
Tab E = Tab("ttt", "ccc","vv");
wind->moveActiveTabTo(5);
wind->getActiveTab();
Tab L = Tab("oo", "bb","vv");
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
Tab U = Tab("dd", "oo","c");
wind->print();
wind->print();
wind->changeActiveTabTo(5);
wind->moveActiveTabTo(3);
wind->getActiveTab();
wind->newTab(E);
Tab T = Tab("nnn", "d","r");
wind->getActiveTab();
wind->print();
wind->print();
wind->getActiveTab();
wind->getActiveTab();
wind->closeTab();
wind->closeTab();
wind->getActiveTab();
Tab X = Tab("z", "yyy","eee");
wind->moveActiveTabTo(2);
wind->closeTab();
wind->print();
wind->moveActiveTabTo(4);
wind->moveActiveTabTo(0);
wind->print();
wind->closeTab();
wind->isEmpty();
wind->closeTab();
wind->isEmpty();
wind->isEmpty();
wind->isEmpty();
wind->newTab(I);
wind->changeActiveTabTo(2);
wind->isEmpty();
wind->getActiveTab();
wind->isEmpty();
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(4);
wind->print();
wind->closeTab();
wind->print();
wind->closeTab();
wind->closeTab();
wind->closeTab();
wind->print();
wind->changeActiveTabTo(3);
wind->closeTab();
wind->print();
wind->moveActiveTabTo(2);
wind->newTab(J);
wind->closeTab();
wind->moveActiveTabTo(5);
wind->moveActiveTabTo(5);
wind->isEmpty();
wind->moveActiveTabTo(1);
delete wind;
}
	return 0;
}