#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Window* wind = new Window();
wind->isEmpty();
Tab U = Tab("lll", "k","ii");
wind->print();
Tab V = Tab("x", "n","nnn");
wind->changeActiveTabTo(3);
Tab E = Tab("j", "www","yy");
wind->closeTab();
Tab W = Tab("oo", "t","rrr");
wind->getActiveTab();
wind->print();
Tab B = Tab("kk", "f","ee");
wind->closeTab();
Tab K = Tab("hh", "u","rrr");
wind->print();
Tab H = Tab("qqq", "i","ppp");
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->changeActiveTabTo(4);
Tab R = Tab("y", "qq","vv");
wind->moveActiveTabTo(3);
wind->print();
Tab Z = Tab("cc", "g","b");
wind->isEmpty();
Tab G = Tab("ff", "zzz","tt");
wind->getActiveTab();
Tab A = Tab("w", "sss","qq");
wind->changeActiveTabTo(4);
Tab X = Tab("jjj", "eee","v");
wind->isEmpty();
Tab M = Tab("d", "jjj","kk");
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(5);
Tab I = Tab("yy", "ll","uuu");
wind->closeTab();
Tab Y = Tab("xx", "www","mm");
wind->changeActiveTabTo(0);
wind->isEmpty();
wind->changeActiveTabTo(1);
wind->closeTab();
wind->newTab(A);
Tab P = Tab("z", "ss","hhh");
wind->print();
wind->changeActiveTabTo(4);
wind->moveActiveTabTo(5);
wind->getActiveTab();
Tab S = Tab("pp", "nnn","l");
wind->print();
wind->closeTab();
wind->closeTab();
Tab O = Tab("f", "n","ccc");
wind->getActiveTab();
Tab C = Tab("j", "xx","s");
wind->closeTab();
wind->print();
Tab F = Tab("h", "p","t");
wind->closeTab();
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(0);
Tab T = Tab("qqq", "aa","j");
wind->moveActiveTabTo(3);
wind->closeTab();
wind->getActiveTab();
wind->closeTab();
wind->changeActiveTabTo(0);
wind->moveActiveTabTo(2);
wind->isEmpty();
Tab N = Tab("bb", "cc","u");
wind->moveActiveTabTo(4);
Tab L = Tab("ppp", "o","xxx");
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->newTab(B);
wind->closeTab();
wind->print();
wind->moveActiveTabTo(5);
Tab D = Tab("l", "x","s");
wind->moveActiveTabTo(2);
wind->isEmpty();
Tab Q = Tab("e", "uu","f");
wind->moveActiveTabTo(5);
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->newTab(C);
wind->newTab(D);
wind->changeActiveTabTo(2);
wind->getActiveTab();
wind->getActiveTab();
wind->moveActiveTabTo(5);
wind->closeTab();
wind->getActiveTab();
wind->print();
wind->print();
wind->changeActiveTabTo(5);
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(3);
wind->newTab(E);
wind->isEmpty();
wind->moveActiveTabTo(4);
wind->getActiveTab();
wind->isEmpty();
wind->closeTab();
wind->print();
wind->closeTab();
wind->closeTab();
wind->print();
wind->closeTab();
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->getActiveTab();
wind->changeActiveTabTo(2);
wind->changeActiveTabTo(1);
wind->moveActiveTabTo(0);
wind->print();
Tab J = Tab("zz", "m","vvv");
wind->getActiveTab();
wind->newTab(F);
wind->print();
wind->isEmpty();
wind->print();
wind->newTab(G);
wind->isEmpty();
wind->newTab(H);
wind->changeActiveTabTo(2);
delete wind;
}
	return 0;
}