#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("ff", "oo","f");
Tab B = Tab("vvv", "g","b");
Tab C = Tab("q", "jjj","mmm");
Tab D = Tab("sss", "eee","tt");
Tab E = Tab("qqq", "ggg","bbb");
Tab F = Tab("r", "aaa","nn");
Tab G = Tab("bbb", "cc","l");
Tab H = Tab("gg", "jj","qqq");
Tab I = Tab("yy", "ddd","uu");
Tab J = Tab("rr", "ll","mm");
Tab K = Tab("e", "p","zz");
Tab L = Tab("sss", "xxx","yy");
Tab M = Tab("xx", "ff","mm");
Tab N = Tab("zzz", "ff","g");
Tab O = Tab("zzz", "ss","uuu");
Tab P = Tab("j", "v","xxx");
Tab Q = Tab("v", "p","dd");
Tab R = Tab("yyy", "kkk","aa");
Tab S = Tab("q", "d","q");
Tab T = Tab("jj", "i","iii");
Tab U = Tab("qq", "bb","pp");
Tab V = Tab("r", "ii","fff");
Tab W = Tab("n", "o","vvv");
Tab X = Tab("l", "lll","www");
Tab Y = Tab("y", "bbb","z");
Tab Z = Tab("oo", "eee","nn");
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(A);
d.moveActiveTabTo(3);
a.moveActiveTabTo(1);
b.newTab(B);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(C);
b.newTab(D);
c.newTab(E);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(0);
b.newTab(F);
c.newTab(G);
d.moveActiveTabTo(0);
a.newTab(H);
b.newTab(I);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(5);
b.newTab(J);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(K);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(L);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.newTab(M);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(3);
b.newTab(N);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.newTab(O);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(P);
d.changeActiveTabTo(0);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(Q);
b.changeActiveTabTo(2);
c.newTab(R);
d.changeActiveTabTo(2);
a.changeActiveTabTo(0);
b.newTab(S);
c.newTab(T);
d.newTab(U);
a.newTab(V);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(W);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(X);
d.changeActiveTabTo(5);
a.changeActiveTabTo(0);
b.newTab(Y);
c.newTab(Z);
d.changeActiveTabTo(0);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
c.changeActiveTabTo(5);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
d.moveActiveTabTo(2);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
b.moveActiveTabTo(4);
d.moveActiveTabTo(4);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->switchToWindow(8);
brows->newWindow();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(8);
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->switchToWindow(6);
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->newWindow();
brows->getWindow(6);
brows->newWindow();
brows->getWindow(2);
brows->newWindow();
brows->getWindow(3);
brows->getWindow(6);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->print();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->getWindow(0);
brows->switchToWindow(1);
brows->getWindow(2);
brows->print();
brows->print();
brows->switchToWindow(4);
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->newWindow();
brows->print();
brows->switchToWindow(4);
brows->newWindow();
brows->getWindow(2);
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->print();
brows->print();
brows->newWindow();
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(1);
brows->switchToWindow(1);
brows->switchToWindow(5);
brows->switchToWindow(0);
brows->switchToWindow(5);
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(6);
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(6);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(8);
brows->switchToWindow(5);
brows->mergeAllWindows();
brows->closeWindow();
delete brows;
}
	return 0;
};

