#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("ss", "ii","g");
Tab B = Tab("h", "gg","kkk");
Tab C = Tab("kk", "zzz","vv");
Tab D = Tab("rr", "g","ii");
Tab E = Tab("v", "c","vv");
Tab F = Tab("j", "f","ss");
Tab G = Tab("qq", "ii","oo");
Tab H = Tab("hhh", "iii","ee");
Tab I = Tab("e", "g","yyy");
Tab J = Tab("g", "uu","p");
Tab K = Tab("uu", "c","hh");
Tab L = Tab("kkk", "hh","ttt");
Tab M = Tab("l", "ppp","mm");
Tab N = Tab("aaa", "yy","zzz");
Tab O = Tab("aa", "l","o");
Tab P = Tab("ttt", "fff","q");
Tab Q = Tab("pp", "m","qq");
Tab R = Tab("rrr", "oo","bb");
Tab S = Tab("r", "ss","ttt");
Tab T = Tab("e", "lll","kk");
Tab U = Tab("iii", "ii","e");
Tab V = Tab("nn", "p","mm");
Tab W = Tab("qq", "ppp","zz");
Tab X = Tab("nnn", "n","q");
Tab Y = Tab("m", "lll","j");
Tab Z = Tab("uuu", "u","ppp");
a.newTab(A);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(B);
a.changeActiveTabTo(3);
b.newTab(C);
c.newTab(D);
d.changeActiveTabTo(3);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(E);
b.newTab(F);
c.changeActiveTabTo(4);
d.newTab(G);
a.newTab(H);
b.newTab(I);
c.moveActiveTabTo(0);
d.newTab(J);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(K);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(L);
d.moveActiveTabTo(4);
a.newTab(M);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(N);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(O);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.newTab(P);
c.newTab(Q);
d.changeActiveTabTo(0);
a.newTab(R);
b.changeActiveTabTo(2);
c.newTab(S);
d.changeActiveTabTo(2);
a.moveActiveTabTo(3);
b.newTab(T);
c.changeActiveTabTo(3);
d.newTab(U);
a.newTab(V);
b.changeActiveTabTo(5);
c.newTab(W);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(X);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(Y);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(Z);
d.moveActiveTabTo(0);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
a.changeActiveTabTo(1);
c.changeActiveTabTo(1);
c.moveActiveTabTo(2);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
d.changeActiveTabTo(3);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(2);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(1);
c.changeActiveTabTo(1);
a.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->getWindow(6);
brows->switchToWindow(3);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(0);
brows->getWindow(0);
brows->switchToWindow(8);
brows->newWindow();
brows->switchToWindow(6);
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(8);
brows->getWindow(7);
brows->getWindow(3);
brows->closeWindow();
brows->getWindow(2);
brows->closeEmptyWindows();
brows->getWindow(8);
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(2);
brows->getWindow(3);
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(3);
brows->print();
brows->switchToWindow(3);
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->getWindow(2);
brows->getWindow(9);
brows->print();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(0);
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(1);
brows->switchToWindow(3);
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->switchToWindow(4);
brows->getWindow(2);
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(6);
brows->print();
brows->switchToWindow(9);
brows->getWindow(8);
brows->switchToWindow(9);
brows->closeWindow();
brows->switchToWindow(8);
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->switchToWindow(0);
brows->getWindow(8);
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
delete brows;
}
	return 0;
};

