#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("kkk", "vvv","ll");
Tab B = Tab("kkk", "qq","b");
Tab C = Tab("j", "w","jjj");
Tab D = Tab("pp", "hhh","lll");
Tab E = Tab("n", "ee","xxx");
Tab F = Tab("sss", "xxx","q");
Tab G = Tab("u", "nnn","fff");
Tab H = Tab("zzz", "q","gg");
Tab I = Tab("lll", "qqq","qqq");
Tab J = Tab("hhh", "ff","fff");
Tab K = Tab("x", "p","rr");
Tab L = Tab("ii", "g","c");
Tab M = Tab("gg", "uuu","vvv");
Tab N = Tab("d", "zzz","tt");
Tab O = Tab("bbb", "m","q");
Tab P = Tab("dd", "jj","jjj");
Tab Q = Tab("h", "oo","lll");
Tab R = Tab("xxx", "m","a");
Tab S = Tab("a", "v","ppp");
Tab T = Tab("jjj", "x","s");
Tab U = Tab("g", "qqq","tt");
Tab V = Tab("zzz", "pp","i");
Tab W = Tab("nn", "ff","f");
Tab X = Tab("yy", "w","q");
Tab Y = Tab("g", "f","qqq");
Tab Z = Tab("ii", "eee","xx");
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(A);
b.moveActiveTabTo(3);
c.newTab(B);
d.moveActiveTabTo(3);
a.newTab(C);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
b.newTab(D);
c.newTab(E);
d.changeActiveTabTo(3);
a.newTab(F);
b.changeActiveTabTo(0);
c.newTab(G);
d.changeActiveTabTo(0);
a.changeActiveTabTo(4);
b.newTab(H);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(I);
b.moveActiveTabTo(0);
c.newTab(J);
d.changeActiveTabTo(0);
a.moveActiveTabTo(0);
b.newTab(K);
c.changeActiveTabTo(0);
d.newTab(L);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(M);
a.newTab(N);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(O);
b.newTab(P);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(Q);
b.newTab(R);
c.newTab(S);
d.changeActiveTabTo(3);
a.newTab(T);
b.newTab(U);
c.newTab(V);
d.changeActiveTabTo(5);
a.newTab(W);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(5);
b.newTab(X);
c.newTab(Y);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(Z);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
c.changeActiveTabTo(1);
b.changeActiveTabTo(2);
d.moveActiveTabTo(2);
b.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(2);
d.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
d.changeActiveTabTo(3);
b.moveActiveTabTo(5);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->print();
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->getWindow(2);
brows->switchToWindow(7);
brows->getWindow(2);
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(9);
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->getWindow(3);
brows->mergeAllWindows();
brows->getWindow(5);
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(7);
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->newWindow();
brows->switchToWindow(6);
brows->switchToWindow(4);
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->newWindow();
brows->getWindow(5);
brows->newWindow();
brows->getWindow(9);
brows->getWindow(7);
brows->switchToWindow(8);
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(4);
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(2);
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(8);
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->getWindow(0);
brows->getWindow(3);
brows->print();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->getWindow(6);
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->closeWindow();
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->getWindow(1);
brows->getWindow(4);
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->print();
brows->switchToWindow(0);
brows->newWindow();
brows->switchToWindow(9);
brows->closeWindow();
brows->closeEmptyWindows();
delete brows;
}
	return 0;
}