#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("ss", "nnn","ii");
Tab B = Tab("f", "r","qqq");
Tab C = Tab("ee", "uuu","dd");
Tab D = Tab("h", "h","x");
Tab E = Tab("p", "hh","n");
Tab F = Tab("ee", "vv","lll");
Tab G = Tab("rr", "l","oo");
Tab H = Tab("h", "mm","bbb");
Tab I = Tab("m", "yy","m");
Tab J = Tab("ii", "m","uuu");
Tab K = Tab("y", "ddd","hhh");
Tab L = Tab("x", "xx","b");
Tab M = Tab("oo", "hh","ee");
Tab N = Tab("h", "qqq","mm");
Tab O = Tab("g", "uu","rrr");
Tab P = Tab("l", "nn","x");
Tab Q = Tab("x", "pp","qq");
Tab R = Tab("ww", "ttt","qqq");
Tab S = Tab("m", "ggg","p");
Tab T = Tab("g", "pp","z");
Tab U = Tab("u", "o","eee");
Tab V = Tab("vv", "uu","ppp");
Tab W = Tab("ppp", "xx","ee");
Tab X = Tab("fff", "u","uuu");
Tab Y = Tab("q", "qq","u");
Tab Z = Tab("a", "qqq","ll");
a.newTab(A);
b.moveActiveTabTo(0);
c.newTab(B);
d.newTab(C);
a.newTab(D);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(2);
b.newTab(E);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(F);
b.newTab(G);
c.newTab(H);
d.newTab(I);
a.newTab(J);
b.newTab(K);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(0);
b.newTab(L);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(M);
b.newTab(N);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(O);
b.newTab(P);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(4);
b.newTab(Q);
c.changeActiveTabTo(4);
d.newTab(R);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(S);
d.changeActiveTabTo(4);
a.moveActiveTabTo(5);
b.newTab(T);
c.moveActiveTabTo(5);
d.newTab(U);
a.moveActiveTabTo(1);
b.newTab(V);
c.newTab(W);
d.moveActiveTabTo(1);
a.newTab(X);
b.newTab(Y);
c.newTab(Z);
d.newTab(Z);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.moveActiveTabTo(3);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(4);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
d.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
a.moveActiveTabTo(2);
c.changeActiveTabTo(2);
a.changeActiveTabTo(0);
c.moveActiveTabTo(0);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
b.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
a.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.changeActiveTabTo(1);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(9);
brows->getWindow(7);
brows->print();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->getWindow(0);
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(0);
brows->print();
brows->closeWindow();
brows->switchToWindow(5);
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(9);
brows->print();
brows->newWindow();
brows->getWindow(0);
brows->closeEmptyWindows();
brows->getWindow(3);
brows->print();
brows->print();
brows->newWindow();
brows->newWindow();
brows->getWindow(8);
brows->switchToWindow(1);
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->print();
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(0);
brows->print();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(2);
brows->switchToWindow(2);
brows->closeWindow();
brows->print();
brows->getWindow(7);
brows->getWindow(7);
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(7);
brows->closeWindow();
brows->getWindow(2);
brows->closeWindow();
brows->switchToWindow(1);
brows->getWindow(1);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(3);
brows->print();
brows->newWindow();
brows->print();
brows->switchToWindow(8);
brows->newWindow();
brows->print();
brows->print();
brows->getWindow(4);
brows->newWindow();
brows->getWindow(2);
brows->closeEmptyWindows();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->getWindow(1);
brows->print();
brows->getWindow(9);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->getWindow(7);
brows->getWindow(9);
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->getWindow(0);
brows->switchToWindow(0);
brows->newWindow();
brows->print();
brows->switchToWindow(0);
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->print();
delete brows;
}
	return 0;
}