#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("ww", "t","ss");
Tab B = Tab("ddd", "ttt","gg");
Tab C = Tab("ccc", "q","rr");
Tab D = Tab("zzz", "v","l");
Tab E = Tab("qqq", "kk","aa");
Tab F = Tab("e", "uu","qq");
Tab G = Tab("e", "y","j");
Tab H = Tab("ll", "j","s");
Tab I = Tab("ff", "iii","o");
Tab J = Tab("zzz", "d","oo");
Tab K = Tab("vv", "ll","s");
Tab L = Tab("f", "yy","jjj");
Tab M = Tab("e", "ddd","tt");
Tab N = Tab("zz", "oo","qq");
Tab O = Tab("ii", "aaa","f");
Tab P = Tab("x", "kk","r");
Tab Q = Tab("sss", "u","f");
Tab R = Tab("uu", "o","d");
Tab S = Tab("v", "ddd","fff");
Tab T = Tab("uuu", "nnn","l");
Tab U = Tab("x", "ddd","mmm");
Tab V = Tab("www", "ppp","mm");
Tab W = Tab("fff", "mmm","u");
Tab X = Tab("kkk", "nnn","n");
Tab Y = Tab("o", "ii","n");
Tab Z = Tab("uuu", "ss","eee");
a.changeActiveTabTo(4);
b.newTab(A);
c.moveActiveTabTo(4);
d.newTab(B);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(C);
d.moveActiveTabTo(3);
a.moveActiveTabTo(4);
b.newTab(D);
c.newTab(E);
d.newTab(F);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.newTab(G);
d.newTab(H);
a.moveActiveTabTo(4);
b.newTab(I);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.newTab(J);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(K);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(L);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.newTab(M);
a.newTab(N);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(O);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(P);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(Q);
a.newTab(R);
b.changeActiveTabTo(3);
c.newTab(S);
d.moveActiveTabTo(3);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(3);
b.newTab(T);
c.moveActiveTabTo(3);
d.newTab(U);
a.newTab(V);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(0);
b.newTab(W);
c.moveActiveTabTo(0);
d.newTab(X);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(Y);
a.newTab(Z);
b.moveActiveTabTo(4);
c.newTab(Z);
d.moveActiveTabTo(4);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
d.changeActiveTabTo(3);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(2);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
c.changeActiveTabTo(0);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeWindow();
brows->getWindow(7);
brows->closeWindow();
brows->switchToWindow(6);
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(7);
brows->getWindow(5);
brows->newWindow();
brows->switchToWindow(4);
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->getWindow(6);
brows->print();
brows->switchToWindow(1);
brows->closeWindow();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->getWindow(4);
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(0);
brows->closeWindow();
brows->switchToWindow(1);
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->switchToWindow(7);
brows->getWindow(5);
brows->closeEmptyWindows();
brows->getWindow(6);
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(9);
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(4);
brows->switchToWindow(5);
brows->switchToWindow(5);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(7);
brows->newWindow();
brows->switchToWindow(5);
brows->newWindow();
brows->newWindow();
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(7);
brows->print();
brows->switchToWindow(5);
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(7);
delete brows;
}
	return 0;
}