#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("ccc", "mmm","b");
Tab B = Tab("ii", "h","yy");
Tab C = Tab("jj", "ll","ll");
Tab D = Tab("ee", "k","t");
Tab E = Tab("g", "l","xxx");
Tab F = Tab("r", "aa","ii");
Tab G = Tab("yy", "h","aaa");
Tab H = Tab("ccc", "tt","uuu");
Tab I = Tab("yy", "t","gg");
Tab J = Tab("yy", "cc","j");
Tab K = Tab("aa", "ppp","www");
Tab L = Tab("p", "uu","oo");
Tab M = Tab("tt", "ccc","mm");
Tab N = Tab("qq", "r","g");
Tab O = Tab("s", "l","tt");
Tab P = Tab("mmm", "uuu","z");
Tab Q = Tab("www", "ccc","sss");
Tab R = Tab("qq", "ww","i");
Tab S = Tab("i", "eee","xxx");
Tab T = Tab("v", "dd","www");
Tab U = Tab("ttt", "z","lll");
Tab V = Tab("ggg", "gg","s");
Tab W = Tab("tt", "sss","b");
Tab X = Tab("qqq", "x","nn");
Tab Y = Tab("d", "jjj","aaa");
Tab Z = Tab("kk", "hhh","lll");
a.moveActiveTabTo(0);
b.newTab(A);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(B);
b.newTab(C);
c.moveActiveTabTo(2);
d.newTab(D);
a.newTab(E);
b.moveActiveTabTo(2);
c.newTab(F);
d.moveActiveTabTo(2);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(G);
d.newTab(H);
a.newTab(I);
b.newTab(J);
c.changeActiveTabTo(3);
d.newTab(K);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(L);
d.moveActiveTabTo(0);
a.newTab(M);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(N);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(O);
b.newTab(P);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(Q);
d.newTab(R);
a.newTab(S);
b.newTab(T);
c.newTab(U);
d.newTab(V);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(W);
a.changeActiveTabTo(2);
b.newTab(X);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(Y);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(Z);
b.moveActiveTabTo(1);
b.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
a.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
a.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
b.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
c.moveActiveTabTo(5);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
d.changeActiveTabTo(0);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->print();
brows->getWindow(6);
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->getWindow(4);
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->switchToWindow(9);
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(3);
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->print();
brows->getWindow(3);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->getWindow(9);
brows->switchToWindow(1);
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->getWindow(8);
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(5);
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->getWindow(9);
brows->getWindow(3);
brows->switchToWindow(6);
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(3);
brows->getWindow(6);
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->getWindow(4);
brows->closeWindow();
brows->getWindow(5);
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(5);
brows->switchToWindow(0);
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->print();
brows->getWindow(7);
brows->switchToWindow(3);
brows->closeWindow();
brows->switchToWindow(9);
brows->newWindow();
brows->switchToWindow(2);
brows->newWindow();
brows->print();
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
delete brows;
}
	return 0;
}