#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("www", "b","pp");
Tab B = Tab("t", "v","i");
Tab C = Tab("bb", "dd","g");
Tab D = Tab("t", "j","v");
Tab E = Tab("ww", "ggg","c");
Tab F = Tab("nn", "kkk","ww");
Tab G = Tab("gg", "ttt","i");
Tab H = Tab("l", "ddd","zz");
Tab I = Tab("r", "d","mm");
Tab J = Tab("j", "ii","l");
Tab K = Tab("n", "p","m");
Tab L = Tab("c", "dd","ss");
Tab M = Tab("yy", "lll","a");
Tab N = Tab("lll", "g","ddd");
Tab O = Tab("rrr", "r","b");
Tab P = Tab("ss", "rrr","dd");
Tab Q = Tab("gg", "aaa","b");
Tab R = Tab("ddd", "h","m");
Tab S = Tab("h", "uuu","bbb");
Tab T = Tab("bb", "kk","w");
Tab U = Tab("pp", "ttt","o");
Tab V = Tab("q", "h","w");
Tab W = Tab("ii", "b","xx");
Tab X = Tab("bbb", "u","nn");
Tab Y = Tab("kkk", "kk","o");
Tab Z = Tab("vv", "d","ttt");
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.newTab(A);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(B);
d.newTab(C);
a.newTab(D);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(2);
b.newTab(E);
c.newTab(F);
d.moveActiveTabTo(2);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(G);
d.newTab(H);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(1);
b.newTab(I);
c.newTab(J);
d.newTab(K);
a.newTab(L);
b.changeActiveTabTo(1);
c.newTab(M);
d.changeActiveTabTo(1);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(N);
d.moveActiveTabTo(2);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(O);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(P);
b.newTab(Q);
c.newTab(R);
d.newTab(S);
a.newTab(T);
b.newTab(U);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(V);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(W);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(X);
b.newTab(Y);
c.newTab(Z);
d.moveActiveTabTo(2);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(2);
a.changeActiveTabTo(3);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
c.changeActiveTabTo(0);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
c.moveActiveTabTo(2);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->getWindow(5);
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->print();
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->getWindow(8);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(7);
brows->getWindow(8);
brows->getWindow(6);
brows->getWindow(7);
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(5);
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->getWindow(2);
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(7);
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(7);
brows->newWindow();
brows->getWindow(2);
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(6);
brows->newWindow();
brows->print();
brows->getWindow(8);
brows->mergeAllWindows();
brows->print();
brows->print();
brows->newWindow();
brows->getWindow(3);
brows->switchToWindow(5);
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->switchToWindow(2);
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->print();
brows->mergeAllWindows();
brows->getWindow(6);
brows->newWindow();
brows->closeEmptyWindows();
delete brows;
}
	return 0;
}