#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("ff", "lll","x");
Tab B = Tab("nn", "v","rr");
Tab C = Tab("jj", "iii","mmm");
Tab D = Tab("e", "l","g");
Tab E = Tab("hhh", "ggg","www");
Tab F = Tab("qqq", "hh","dd");
Tab G = Tab("jj", "ii","z");
Tab H = Tab("s", "ll","vvv");
Tab I = Tab("mmm", "u","bbb");
Tab J = Tab("u", "u","ee");
Tab K = Tab("ee", "eee","nn");
Tab L = Tab("ddd", "ee","mmm");
Tab M = Tab("nn", "ooo","jjj");
Tab N = Tab("z", "ccc","a");
Tab O = Tab("c", "i","oo");
Tab P = Tab("n", "rrr","jjj");
Tab Q = Tab("u", "xxx","hh");
Tab R = Tab("uu", "jjj","jj");
Tab S = Tab("nn", "zz","bb");
Tab T = Tab("oo", "t","t");
Tab U = Tab("ee", "kk","x");
Tab V = Tab("l", "ggg","rr");
Tab W = Tab("oo", "lll","vv");
Tab X = Tab("zz", "bbb","vv");
Tab Y = Tab("p", "u","h");
Tab Z = Tab("m", "u","ppp");
a.newTab(A);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(B);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(C);
d.newTab(D);
a.changeActiveTabTo(1);
b.newTab(E);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(1);
b.newTab(F);
c.changeActiveTabTo(1);
d.newTab(G);
a.changeActiveTabTo(2);
b.newTab(H);
c.newTab(I);
d.moveActiveTabTo(2);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(J);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(K);
a.newTab(L);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(2);
b.newTab(M);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(N);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.newTab(O);
d.moveActiveTabTo(2);
a.changeActiveTabTo(0);
b.newTab(P);
c.newTab(Q);
d.moveActiveTabTo(0);
a.newTab(R);
b.changeActiveTabTo(3);
c.newTab(S);
d.newTab(T);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(U);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(V);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(W);
a.newTab(X);
b.newTab(Y);
c.newTab(Z);
d.moveActiveTabTo(0);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
d.changeActiveTabTo(4);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(0);
d.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
b.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
a.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
d.moveActiveTabTo(0);
b.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
b.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(7);
brows->closeWindow();
brows->newWindow();
brows->getWindow(2);
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->print();
brows->switchToWindow(1);
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->getWindow(6);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->switchToWindow(4);
brows->closeWindow();
brows->switchToWindow(7);
brows->newWindow();
brows->newWindow();
brows->getWindow(5);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(4);
brows->print();
brows->getWindow(4);
brows->switchToWindow(6);
brows->newWindow();
brows->newWindow();
brows->getWindow(7);
brows->switchToWindow(3);
brows->getWindow(6);
brows->getWindow(4);
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(0);
brows->newWindow();
brows->getWindow(3);
brows->print();
brows->print();
brows->switchToWindow(3);
brows->print();
brows->switchToWindow(4);
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->closeWindow();
brows->getWindow(3);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(6);
brows->switchToWindow(2);
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->getWindow(3);
brows->getWindow(5);
brows->getWindow(8);
brows->print();
brows->getWindow(4);
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(6);
brows->closeWindow();
brows->print();
brows->print();
brows->getWindow(5);
brows->getWindow(7);
brows->print();
brows->getWindow(3);
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
delete brows;
}
	return 0;
}