#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("q", "ii","ss");
Tab B = Tab("fff", "bb","a");
Tab C = Tab("q", "rr","dd");
Tab D = Tab("uuu", "ttt","bbb");
Tab E = Tab("lll", "uuu","d");
Tab F = Tab("x", "zzz","oo");
Tab G = Tab("a", "rr","k");
Tab H = Tab("eee", "m","k");
Tab I = Tab("qq", "uuu","x");
Tab J = Tab("dd", "y","ii");
Tab K = Tab("ttt", "f","vvv");
Tab L = Tab("www", "ggg","bb");
Tab M = Tab("j", "bb","n");
Tab N = Tab("nnn", "z","jj");
Tab O = Tab("lll", "u","pp");
Tab P = Tab("oo", "jjj","m");
Tab Q = Tab("s", "bb","a");
Tab R = Tab("sss", "g","bb");
Tab S = Tab("g", "j","h");
Tab T = Tab("m", "ii","ss");
Tab U = Tab("xx", "www","ttt");
Tab V = Tab("pp", "a","o");
Tab W = Tab("ii", "ll","o");
Tab X = Tab("ggg", "mm","z");
Tab Y = Tab("x", "dd","hhh");
Tab Z = Tab("tt", "jjj","zz");
a.newTab(A);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(B);
a.moveActiveTabTo(1);
b.newTab(C);
c.newTab(D);
d.moveActiveTabTo(1);
a.newTab(E);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(F);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(G);
d.newTab(H);
a.moveActiveTabTo(3);
b.newTab(I);
c.newTab(J);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(K);
d.newTab(L);
a.changeActiveTabTo(3);
b.newTab(M);
c.newTab(N);
d.changeActiveTabTo(3);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(O);
d.moveActiveTabTo(2);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.newTab(P);
a.newTab(Q);
b.changeActiveTabTo(0);
c.newTab(R);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(S);
d.newTab(T);
a.changeActiveTabTo(5);
b.newTab(U);
c.changeActiveTabTo(5);
d.newTab(V);
a.changeActiveTabTo(5);
b.newTab(W);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(X);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(Y);
b.newTab(Z);
c.moveActiveTabTo(2);
d.newTab(Z);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
a.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(0);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
c.changeActiveTabTo(3);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
c.changeActiveTabTo(4);
a.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(0);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
c.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(2);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->print();
brows->getWindow(1);
brows->switchToWindow(6);
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(0);
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(2);
brows->newWindow();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(6);
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(0);
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(0);
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->print();
brows->newWindow();
brows->getWindow(0);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->closeEmptyWindows();
brows->getWindow(0);
brows->print();
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(4);
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->switchToWindow(6);
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(6);
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(9);
brows->getWindow(3);
brows->closeWindow();
brows->closeWindow();
brows->getWindow(3);
brows->newWindow();
brows->newWindow();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->print();
brows->switchToWindow(7);
delete brows;
}
	return 0;
}