#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("bb", "ppp","a");
Tab B = Tab("o", "xx","d");
Tab C = Tab("k", "fff","yyy");
Tab D = Tab("ppp", "rr","ccc");
Tab E = Tab("fff", "bb","zzz");
Tab F = Tab("sss", "ww","mm");
Tab G = Tab("uuu", "dd","yyy");
Tab H = Tab("s", "ll","kk");
Tab I = Tab("pp", "ppp","vv");
Tab J = Tab("d", "sss","lll");
Tab K = Tab("gg", "ttt","c");
Tab L = Tab("ddd", "lll","zzz");
Tab M = Tab("www", "rr","ii");
Tab N = Tab("d", "uu","mmm");
Tab O = Tab("r", "j","v");
Tab P = Tab("oo", "bbb","tt");
Tab Q = Tab("bb", "n","k");
Tab R = Tab("w", "vv","kkk");
Tab S = Tab("kkk", "ooo","k");
Tab T = Tab("ccc", "b","ddd");
Tab U = Tab("f", "i","ccc");
Tab V = Tab("y", "g","bbb");
Tab W = Tab("jjj", "qq","bbb");
Tab X = Tab("www", "e","g");
Tab Y = Tab("e", "cc","s");
Tab Z = Tab("ddd", "zzz","r");
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(A);
d.newTab(B);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(C);
d.changeActiveTabTo(4);
a.changeActiveTabTo(2);
b.newTab(D);
c.newTab(E);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.newTab(F);
d.changeActiveTabTo(1);
a.newTab(G);
b.moveActiveTabTo(2);
c.newTab(H);
d.moveActiveTabTo(2);
a.newTab(I);
b.newTab(J);
c.newTab(K);
d.moveActiveTabTo(4);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(L);
d.changeActiveTabTo(4);
a.newTab(M);
b.newTab(N);
c.changeActiveTabTo(0);
d.newTab(O);
a.changeActiveTabTo(0);
b.newTab(P);
c.changeActiveTabTo(0);
d.newTab(Q);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.newTab(R);
d.changeActiveTabTo(2);
a.changeActiveTabTo(4);
b.newTab(S);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(T);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(U);
b.newTab(V);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(W);
b.newTab(X);
c.newTab(Y);
d.moveActiveTabTo(1);
a.newTab(Z);
b.newTab(Z);
c.changeActiveTabTo(3);
d.newTab(Z);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
b.moveActiveTabTo(4);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
a.moveActiveTabTo(0);
d.moveActiveTabTo(0);
c.moveActiveTabTo(4);
b.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(3);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->switchToWindow(2);
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(0);
brows->getWindow(2);
brows->newWindow();
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->getWindow(6);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(8);
brows->switchToWindow(6);
brows->closeWindow();
brows->switchToWindow(4);
brows->newWindow();
brows->print();
brows->switchToWindow(2);
brows->newWindow();
brows->print();
brows->newWindow();
brows->switchToWindow(1);
brows->switchToWindow(5);
brows->getWindow(9);
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(0);
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->getWindow(1);
brows->print();
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->getWindow(9);
brows->print();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(2);
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(8);
brows->switchToWindow(2);
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->switchToWindow(4);
brows->getWindow(7);
brows->newWindow();
brows->getWindow(4);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->getWindow(3);
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->switchToWindow(4);
brows->newWindow();
brows->switchToWindow(2);
brows->closeWindow();
brows->print();
brows->switchToWindow(4);
brows->newWindow();
brows->print();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->switchToWindow(8);
brows->getWindow(5);
delete brows;
}
	return 0;
}