#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("rrr", "eee","iii");
Tab B = Tab("qq", "qqq","ttt");
Tab C = Tab("uuu", "p","hh");
Tab D = Tab("pp", "hhh","y");
Tab E = Tab("zz", "jjj","qq");
Tab F = Tab("z", "yy","hhh");
Tab G = Tab("bb", "j","p");
Tab H = Tab("vv", "a","zz");
Tab I = Tab("eee", "kkk","o");
Tab J = Tab("nn", "n","h");
Tab K = Tab("ggg", "oo","tt");
Tab L = Tab("b", "b","cc");
Tab M = Tab("lll", "ww","aa");
Tab N = Tab("hh", "ooo","ddd");
Tab O = Tab("qq", "j","j");
Tab P = Tab("jj", "zzz","xx");
Tab Q = Tab("t", "aaa","r");
Tab R = Tab("ee", "hhh","mm");
Tab S = Tab("o", "bb","r");
Tab T = Tab("b", "b","g");
Tab U = Tab("mmm", "rr","vvv");
Tab V = Tab("q", "l","aa");
Tab W = Tab("dd", "ll","aa");
Tab X = Tab("www", "p","e");
Tab Y = Tab("kkk", "s","ee");
Tab Z = Tab("xxx", "ss","lll");
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(A);
a.newTab(B);
b.moveActiveTabTo(2);
c.newTab(C);
d.changeActiveTabTo(2);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(D);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(E);
b.newTab(F);
c.newTab(G);
d.changeActiveTabTo(5);
a.changeActiveTabTo(2);
b.newTab(H);
c.moveActiveTabTo(2);
d.newTab(I);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.newTab(J);
d.changeActiveTabTo(1);
a.newTab(K);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(L);
b.newTab(M);
c.changeActiveTabTo(4);
d.newTab(N);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(O);
d.newTab(P);
a.changeActiveTabTo(0);
b.newTab(Q);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(R);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(S);
b.moveActiveTabTo(2);
c.newTab(T);
d.changeActiveTabTo(2);
a.newTab(U);
b.newTab(V);
c.moveActiveTabTo(3);
d.newTab(W);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(X);
d.changeActiveTabTo(5);
a.newTab(Y);
b.newTab(Z);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
c.moveActiveTabTo(2);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(2);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(1);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(1);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(4);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->getWindow(6);
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(7);
brows->getWindow(9);
brows->mergeAllWindows();
brows->getWindow(4);
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(2);
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(4);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->closeWindow();
brows->switchToWindow(2);
brows->print();
brows->getWindow(6);
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(9);
brows->getWindow(7);
brows->switchToWindow(7);
brows->switchToWindow(7);
brows->switchToWindow(2);
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->getWindow(5);
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(1);
brows->print();
brows->switchToWindow(2);
brows->newWindow();
brows->getWindow(4);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(6);
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->getWindow(9);
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->getWindow(0);
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(8);
brows->getWindow(4);
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->switchToWindow(8);
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->getWindow(5);
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->getWindow(3);
brows->closeEmptyWindows();
brows->mergeAllWindows();
delete brows;
}
	return 0;
}