#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("k", "r","kk");
Tab B = Tab("e", "e","e");
Tab C = Tab("ddd", "mm","w");
Tab D = Tab("eee", "n","ppp");
Tab E = Tab("aaa", "o","f");
Tab F = Tab("qq", "w","xxx");
Tab G = Tab("www", "a","kk");
Tab H = Tab("w", "j","www");
Tab I = Tab("n", "rrr","cc");
Tab J = Tab("l", "zz","aa");
Tab K = Tab("f", "p","ddd");
Tab L = Tab("z", "b","cc");
Tab M = Tab("lll", "l","u");
Tab N = Tab("iii", "a","ddd");
Tab O = Tab("cc", "qq","hhh");
Tab P = Tab("dd", "uuu","bb");
Tab Q = Tab("t", "www","ii");
Tab R = Tab("jjj", "yy","s");
Tab S = Tab("cc", "tt","a");
Tab T = Tab("w", "jjj","cc");
Tab U = Tab("iii", "vvv","ss");
Tab V = Tab("q", "r","h");
Tab W = Tab("o", "v","ddd");
Tab X = Tab("www", "bb","f");
Tab Y = Tab("g", "sss","jjj");
Tab Z = Tab("z", "k","g");
a.newTab(A);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(B);
a.newTab(C);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(D);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(E);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(F);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(G);
d.changeActiveTabTo(4);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(H);
d.moveActiveTabTo(5);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(I);
d.moveActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(J);
d.moveActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(K);
a.changeActiveTabTo(3);
b.newTab(L);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(2);
b.newTab(M);
c.newTab(N);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(O);
a.moveActiveTabTo(3);
b.newTab(P);
c.newTab(Q);
d.newTab(R);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(S);
d.newTab(T);
a.changeActiveTabTo(5);
b.newTab(U);
c.newTab(V);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(W);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(X);
d.newTab(Y);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.newTab(Z);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
a.moveActiveTabTo(0);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
a.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
d.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(4);
d.changeActiveTabTo(4);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
b.changeActiveTabTo(3);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(8);
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(3);
brows->switchToWindow(0);
brows->newWindow();
brows->getWindow(2);
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->print();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->closeWindow();
brows->print();
brows->print();
brows->closeWindow();
brows->getWindow(3);
brows->getWindow(0);
brows->getWindow(9);
brows->switchToWindow(8);
brows->switchToWindow(0);
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->getWindow(3);
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->print();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->getWindow(7);
brows->getWindow(0);
brows->closeEmptyWindows();
brows->getWindow(9);
brows->newWindow();
brows->switchToWindow(1);
brows->print();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->getWindow(2);
brows->newWindow();
brows->switchToWindow(0);
brows->getWindow(9);
brows->newWindow();
brows->print();
brows->switchToWindow(4);
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(6);
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(4);
brows->getWindow(3);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(9);
brows->newWindow();
brows->switchToWindow(7);
brows->print();
brows->switchToWindow(6);
brows->getWindow(4);
brows->getWindow(2);
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->switchToWindow(2);
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(2);
brows->getWindow(7);
brows->getWindow(7);
brows->print();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(3);
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->print();
brows->newWindow();
brows->getWindow(8);
brows->switchToWindow(0);
brows->closeEmptyWindows();
delete brows;
}
	return 0;
}