#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("bbb", "g","e");
Tab B = Tab("ii", "dd","o");
Tab C = Tab("fff", "yy","xxx");
Tab D = Tab("rr", "mm","jj");
Tab E = Tab("yy", "e","qqq");
Tab F = Tab("lll", "aa","yyy");
Tab G = Tab("ss", "y","fff");
Tab H = Tab("sss", "qqq","o");
Tab I = Tab("nnn", "qqq","u");
Tab J = Tab("o", "dd","s");
Tab K = Tab("b", "gg","qq");
Tab L = Tab("xx", "i","yy");
Tab M = Tab("mm", "mmm","mm");
Tab N = Tab("aa", "sss","n");
Tab O = Tab("jj", "h","yyy");
Tab P = Tab("ff", "nn","ppp");
Tab Q = Tab("q", "c","m");
Tab R = Tab("ww", "kkk","ddd");
Tab S = Tab("ddd", "ggg","q");
Tab T = Tab("jjj", "t","ww");
Tab U = Tab("vvv", "g","y");
Tab V = Tab("ooo", "o","hhh");
Tab W = Tab("uuu", "ii","ff");
Tab X = Tab("aa", "oo","rr");
Tab Y = Tab("iii", "qq","gg");
Tab Z = Tab("yy", "xxx","z");
a.newTab(A);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(B);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(C);
d.newTab(D);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(E);
a.newTab(F);
b.newTab(G);
c.newTab(H);
d.changeActiveTabTo(2);
a.newTab(I);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(J);
a.newTab(K);
b.newTab(L);
c.newTab(M);
d.moveActiveTabTo(1);
a.newTab(N);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(O);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.newTab(P);
d.moveActiveTabTo(1);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(Q);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(R);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(S);
a.newTab(T);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.newTab(U);
d.changeActiveTabTo(1);
a.changeActiveTabTo(5);
b.newTab(V);
c.moveActiveTabTo(5);
d.newTab(W);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(X);
a.changeActiveTabTo(5);
b.newTab(Y);
c.moveActiveTabTo(5);
d.newTab(Z);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
a.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(5);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
d.changeActiveTabTo(3);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(4);
d.moveActiveTabTo(4);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
c.moveActiveTabTo(5);
c.moveActiveTabTo(3);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(1);
d.moveActiveTabTo(1);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
c.changeActiveTabTo(2);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(0);
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(0);
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(1);
brows->newWindow();
brows->print();
brows->print();
brows->getWindow(2);
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->switchToWindow(4);
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(0);
brows->getWindow(3);
brows->mergeAllWindows();
brows->getWindow(1);
brows->getWindow(0);
brows->print();
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(1);
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->getWindow(6);
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(7);
brows->switchToWindow(3);
brows->getWindow(3);
brows->newWindow();
brows->switchToWindow(9);
brows->getWindow(9);
brows->getWindow(5);
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(5);
brows->switchToWindow(4);
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(4);
brows->switchToWindow(8);
brows->closeWindow();
brows->print();
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->print();
brows->getWindow(9);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(9);
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->switchToWindow(8);
brows->print();
brows->switchToWindow(3);
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
delete brows;
}
	return 0;
}