#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("pp", "vv","kkk");
Tab B = Tab("j", "l","pp");
Tab C = Tab("kkk", "lll","fff");
Tab D = Tab("o", "ww","l");
Tab E = Tab("z", "v","e");
Tab F = Tab("y", "f","yyy");
Tab G = Tab("ii", "zz","z");
Tab H = Tab("gg", "mm","r");
Tab I = Tab("k", "bb","aa");
Tab J = Tab("ff", "zz","c");
Tab K = Tab("vv", "j","a");
Tab L = Tab("pp", "qq","d");
Tab M = Tab("w", "rrr","r");
Tab N = Tab("vvv", "ii","ll");
Tab O = Tab("l", "sss","p");
Tab P = Tab("j", "q","iii");
Tab Q = Tab("ttt", "xxx","i");
Tab R = Tab("d", "ddd","cc");
Tab S = Tab("p", "iii","y");
Tab T = Tab("vvv", "xx","rrr");
Tab U = Tab("zz", "ccc","d");
Tab V = Tab("ppp", "a","s");
Tab W = Tab("ff", "rrr","t");
Tab X = Tab("zzz", "hhh","kk");
Tab Y = Tab("v", "y","l");
Tab Z = Tab("i", "j","r");
a.newTab(A);
b.newTab(B);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(C);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(D);
a.newTab(E);
b.newTab(F);
c.changeActiveTabTo(2);
d.newTab(G);
a.changeActiveTabTo(2);
b.newTab(H);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(I);
b.newTab(J);
c.newTab(K);
d.moveActiveTabTo(4);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(L);
d.newTab(M);
a.newTab(N);
b.newTab(O);
c.changeActiveTabTo(2);
d.newTab(P);
a.newTab(Q);
b.newTab(R);
c.newTab(S);
d.moveActiveTabTo(2);
a.moveActiveTabTo(3);
b.newTab(T);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
b.newTab(U);
c.newTab(V);
d.moveActiveTabTo(0);
a.changeActiveTabTo(3);
b.newTab(W);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(4);
b.newTab(X);
c.newTab(Y);
d.newTab(Z);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
b.changeActiveTabTo(1);
b.moveActiveTabTo(0);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
a.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(3);
c.changeActiveTabTo(3);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(6);
brows->getWindow(8);
brows->switchToWindow(3);
brows->newWindow();
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->newWindow();
brows->switchToWindow(8);
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->getWindow(5);
brows->getWindow(0);
brows->switchToWindow(4);
brows->closeWindow();
brows->print();
brows->getWindow(1);
brows->mergeAllWindows();
brows->getWindow(3);
brows->getWindow(2);
brows->newWindow();
brows->getWindow(0);
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(4);
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->getWindow(9);
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->switchToWindow(6);
brows->getWindow(9);
brows->getWindow(2);
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(1);
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(6);
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->getWindow(2);
brows->mergeAllWindows();
brows->print();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->getWindow(0);
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->newWindow();
brows->closeWindow();
brows->print();
brows->print();
brows->getWindow(2);
brows->print();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(7);
brows->newWindow();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->getWindow(6);
brows->getWindow(6);
brows->newWindow();
brows->getWindow(7);
brows->getWindow(9);
delete brows;
}
	return 0;
}