#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("vvv", "y","nnn");
Tab B = Tab("fff", "n","nnn");
Tab C = Tab("pp", "xx","ddd");
Tab D = Tab("f", "gg","zzz");
Tab E = Tab("eee", "o","dd");
Tab F = Tab("v", "z","ggg");
Tab G = Tab("l", "jj","ooo");
Tab H = Tab("uu", "zzz","zzz");
Tab I = Tab("ccc", "vv","t");
Tab J = Tab("o", "r","q");
Tab K = Tab("o", "ttt","gg");
Tab L = Tab("b", "n","ppp");
Tab M = Tab("ddd", "uu","j");
Tab N = Tab("ee", "uu","u");
Tab O = Tab("qqq", "vv","nnn");
Tab P = Tab("o", "qqq","xx");
Tab Q = Tab("s", "ii","r");
Tab R = Tab("zzz", "vv","j");
Tab S = Tab("p", "yyy","qq");
Tab T = Tab("aaa", "a","vv");
Tab U = Tab("cc", "d","hhh");
Tab V = Tab("xxx", "z","ppp");
Tab W = Tab("v", "vv","kkk");
Tab X = Tab("kk", "gg","i");
Tab Y = Tab("aa", "ooo","t");
Tab Z = Tab("tt", "jj","nn");
a.newTab(A);
b.newTab(B);
c.moveActiveTabTo(5);
d.newTab(C);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(D);
d.newTab(E);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(F);
b.changeActiveTabTo(1);
c.newTab(G);
d.moveActiveTabTo(1);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(H);
a.moveActiveTabTo(2);
b.newTab(I);
c.moveActiveTabTo(2);
d.newTab(J);
a.moveActiveTabTo(4);
b.newTab(K);
c.newTab(L);
d.newTab(M);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(N);
d.changeActiveTabTo(5);
a.newTab(O);
b.changeActiveTabTo(5);
c.newTab(P);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(0);
b.newTab(Q);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(R);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(S);
b.changeActiveTabTo(5);
c.newTab(T);
d.changeActiveTabTo(5);
a.newTab(U);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(2);
b.newTab(V);
c.newTab(W);
d.changeActiveTabTo(2);
a.newTab(X);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(Y);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.newTab(Z);
d.moveActiveTabTo(1);
a.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(1);
c.changeActiveTabTo(1);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
d.moveActiveTabTo(1);
a.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
d.moveActiveTabTo(0);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->getWindow(7);
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->getWindow(3);
brows->getWindow(8);
brows->switchToWindow(1);
brows->newWindow();
brows->switchToWindow(5);
brows->print();
brows->print();
brows->newWindow();
brows->switchToWindow(4);
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->mergeAllWindows();
brows->getWindow(7);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(4);
brows->newWindow();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(0);
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(1);
brows->print();
brows->getWindow(8);
brows->getWindow(6);
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(5);
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->print();
brows->closeWindow();
brows->getWindow(0);
brows->closeWindow();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->switchToWindow(5);
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(6);
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->switchToWindow(6);
brows->print();
brows->getWindow(9);
brows->print();
brows->newWindow();
brows->print();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(6);
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(4);
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
delete brows;
}
	return 0;
}