#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("yyy", "ii","yy");
Tab B = Tab("ccc", "r","nn");
Tab C = Tab("g", "aaa","zz");
Tab D = Tab("m", "rr","p");
Tab E = Tab("xx", "e","zzz");
Tab F = Tab("t", "pp","t");
Tab G = Tab("y", "h","n");
Tab H = Tab("ccc", "s","p");
Tab I = Tab("sss", "rrr","cc");
Tab J = Tab("lll", "yyy","iii");
Tab K = Tab("w", "ttt","mmm");
Tab L = Tab("cc", "fff","bbb");
Tab M = Tab("yyy", "f","vvv");
Tab N = Tab("uu", "r","jjj");
Tab O = Tab("ee", "aaa","s");
Tab P = Tab("mm", "zz","gg");
Tab Q = Tab("ppp", "x","d");
Tab R = Tab("uuu", "mm","jj");
Tab S = Tab("oo", "r","aaa");
Tab T = Tab("bbb", "vvv","jjj");
Tab U = Tab("xxx", "eee","xxx");
Tab V = Tab("y", "l","pp");
Tab W = Tab("i", "ii","k");
Tab X = Tab("i", "aaa","nnn");
Tab Y = Tab("qqq", "m","ee");
Tab Z = Tab("ggg", "ee","i");
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(A);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(B);
b.newTab(C);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.newTab(D);
c.newTab(E);
d.newTab(F);
a.changeActiveTabTo(1);
b.newTab(G);
c.newTab(H);
d.newTab(I);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(J);
d.newTab(K);
a.newTab(L);
b.changeActiveTabTo(4);
c.newTab(M);
d.changeActiveTabTo(4);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(1);
b.newTab(N);
c.newTab(O);
d.changeActiveTabTo(1);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(P);
a.newTab(Q);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(5);
b.newTab(R);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(S);
d.moveActiveTabTo(5);
a.newTab(T);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.newTab(U);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(V);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(W);
a.newTab(X);
b.newTab(Y);
c.newTab(Z);
d.changeActiveTabTo(3);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
b.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(0);
d.moveActiveTabTo(0);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->getWindow(2);
brows->print();
brows->getWindow(8);
brows->newWindow();
brows->newWindow();
brows->getWindow(0);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(6);
brows->switchToWindow(0);
brows->print();
brows->switchToWindow(3);
brows->print();
brows->closeWindow();
brows->newWindow();
brows->getWindow(5);
brows->newWindow();
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->print();
brows->getWindow(9);
brows->newWindow();
brows->closeWindow();
brows->getWindow(6);
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->newWindow();
brows->getWindow(0);
brows->switchToWindow(1);
brows->print();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(2);
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(8);
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(4);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(7);
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->switchToWindow(9);
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->getWindow(8);
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
delete brows;
}
	return 0;
}