#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("bb", "hh","qqq");
Tab B = Tab("a", "eee","f");
Tab C = Tab("z", "vv","q");
Tab D = Tab("gg", "oo","xx");
Tab E = Tab("gg", "e","fff");
Tab F = Tab("m", "ttt","ccc");
Tab G = Tab("yy", "jjj","hh");
Tab H = Tab("qq", "vvv","jjj");
Tab I = Tab("aa", "ggg","iii");
Tab J = Tab("mmm", "x","n");
Tab K = Tab("mmm", "aa","c");
Tab L = Tab("o", "z","dd");
Tab M = Tab("aaa", "ggg","hhh");
Tab N = Tab("nnn", "mm","j");
Tab O = Tab("z", "x","kk");
Tab P = Tab("iii", "ll","d");
Tab Q = Tab("e", "rrr","yyy");
Tab R = Tab("ff", "ll","lll");
Tab S = Tab("t", "dd","oo");
Tab T = Tab("sss", "ttt","m");
Tab U = Tab("qq", "aaa","b");
Tab V = Tab("y", "bbb","qqq");
Tab W = Tab("l", "mm","ee");
Tab X = Tab("uuu", "ttt","bb");
Tab Y = Tab("iii", "mmm","e");
Tab Z = Tab("xx", "yyy","ddd");
a.moveActiveTabTo(1);
b.newTab(A);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(B);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.newTab(C);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(D);
d.changeActiveTabTo(5);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(E);
a.newTab(F);
b.newTab(G);
c.newTab(H);
d.newTab(I);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(J);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(K);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(L);
a.newTab(M);
b.moveActiveTabTo(1);
c.newTab(N);
d.changeActiveTabTo(1);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(O);
b.moveActiveTabTo(5);
c.newTab(P);
d.moveActiveTabTo(5);
a.changeActiveTabTo(4);
b.newTab(Q);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(R);
b.newTab(S);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(5);
b.newTab(T);
c.changeActiveTabTo(5);
d.newTab(U);
a.changeActiveTabTo(1);
b.newTab(V);
c.moveActiveTabTo(1);
d.newTab(W);
a.moveActiveTabTo(3);
b.newTab(X);
c.newTab(Y);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.newTab(Z);
c.newTab(Z);
d.newTab(Z);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
b.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
d.moveActiveTabTo(0);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
d.moveActiveTabTo(2);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
a.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
b.moveActiveTabTo(3);
d.changeActiveTabTo(3);
c.changeActiveTabTo(5);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
c.changeActiveTabTo(5);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->switchToWindow(1);
brows->getWindow(7);
brows->newWindow();
brows->print();
brows->switchToWindow(4);
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->print();
brows->switchToWindow(5);
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->print();
brows->switchToWindow(7);
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(7);
brows->newWindow();
brows->getWindow(5);
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->getWindow(3);
brows->getWindow(2);
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->print();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->print();
brows->getWindow(2);
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->getWindow(1);
brows->getWindow(0);
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->newWindow();
brows->print();
brows->switchToWindow(2);
brows->newWindow();
brows->getWindow(6);
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->newWindow();
brows->switchToWindow(1);
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(6);
brows->print();
brows->switchToWindow(7);
brows->print();
brows->switchToWindow(8);
brows->getWindow(3);
brows->switchToWindow(0);
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->getWindow(1);
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->print();
brows->getWindow(4);
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(7);
brows->getWindow(0);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(3);
brows->mergeAllWindows();
brows->getWindow(4);
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(5);
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
delete brows;
}
	return 0;
}