#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("t", "aaa","ooo");
Tab B = Tab("gg", "tt","oo");
Tab C = Tab("iii", "i","rrr");
Tab D = Tab("ll", "ss","p");
Tab E = Tab("r", "ppp","ggg");
Tab F = Tab("aaa", "d","ee");
Tab G = Tab("z", "q","z");
Tab H = Tab("y", "a","ggg");
Tab I = Tab("pp", "a","w");
Tab J = Tab("aaa", "ww","d");
Tab K = Tab("z", "v","k");
Tab L = Tab("a", "yyy","lll");
Tab M = Tab("vv", "dd","t");
Tab N = Tab("lll", "b","tt");
Tab O = Tab("aaa", "m","qq");
Tab P = Tab("lll", "zzz","gg");
Tab Q = Tab("bbb", "qqq","f");
Tab R = Tab("q", "nn","qqq");
Tab S = Tab("ppp", "yy","y");
Tab T = Tab("oo", "q","ppp");
Tab U = Tab("u", "bb","uu");
Tab V = Tab("fff", "x","f");
Tab W = Tab("ooo", "p","ttt");
Tab X = Tab("a", "q","ccc");
Tab Y = Tab("oo", "e","y");
Tab Z = Tab("d", "cc","nn");
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(A);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(B);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(4);
b.newTab(C);
c.moveActiveTabTo(4);
d.newTab(D);
a.newTab(E);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(F);
b.newTab(G);
c.newTab(H);
d.moveActiveTabTo(1);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(I);
d.changeActiveTabTo(2);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(3);
b.newTab(J);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(K);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(L);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.newTab(M);
b.changeActiveTabTo(4);
c.newTab(N);
d.newTab(O);
a.newTab(P);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(Q);
a.newTab(R);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(S);
a.newTab(T);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(4);
b.newTab(U);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(V);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(W);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(X);
a.newTab(Y);
b.changeActiveTabTo(1);
c.newTab(Z);
d.moveActiveTabTo(1);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
a.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
b.changeActiveTabTo(3);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
b.moveActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
b.changeActiveTabTo(3);
d.changeActiveTabTo(3);
c.moveActiveTabTo(3);
a.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(2);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
b.moveActiveTabTo(1);
d.moveActiveTabTo(1);
d.moveActiveTabTo(5);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->print();
brows->print();
brows->closeWindow();
brows->switchToWindow(0);
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->getWindow(5);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(3);
brows->getWindow(1);
brows->closeWindow();
brows->getWindow(2);
brows->getWindow(7);
brows->switchToWindow(5);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(7);
brows->switchToWindow(6);
brows->getWindow(5);
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(9);
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(9);
brows->switchToWindow(6);
brows->newWindow();
brows->switchToWindow(5);
brows->getWindow(2);
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(7);
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(1);
brows->print();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->switchToWindow(0);
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->print();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->newWindow();
brows->newWindow();
brows->switchToWindow(8);
brows->switchToWindow(5);
brows->print();
brows->closeEmptyWindows();
delete brows;
}
	return 0;
}