#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("vv", "w","j");
Tab B = Tab("d", "ee","t");
Tab C = Tab("a", "t","jjj");
Tab D = Tab("tt", "x","ppp");
Tab E = Tab("d", "ii","ee");
Tab F = Tab("www", "nnn","yyy");
Tab G = Tab("zz", "c","j");
Tab H = Tab("nn", "y","x");
Tab I = Tab("zz", "q","t");
Tab J = Tab("f", "y","www");
Tab K = Tab("b", "v","qq");
Tab L = Tab("g", "d","hh");
Tab M = Tab("ooo", "h","ee");
Tab N = Tab("f", "i","y");
Tab O = Tab("s", "zz","y");
Tab P = Tab("aa", "k","r");
Tab Q = Tab("s", "nnn","ii");
Tab R = Tab("iii", "i","jjj");
Tab S = Tab("tt", "d","ss");
Tab T = Tab("d", "rrr","rr");
Tab U = Tab("iii", "d","pp");
Tab V = Tab("u", "aa","dd");
Tab W = Tab("zzz", "ll","m");
Tab X = Tab("uuu", "s","nn");
Tab Y = Tab("mm", "bbb","tt");
Tab Z = Tab("ttt", "kk","eee");
a.newTab(A);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(B);
b.newTab(C);
c.newTab(D);
d.changeActiveTabTo(2);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(E);
a.moveActiveTabTo(1);
b.newTab(F);
c.newTab(G);
d.moveActiveTabTo(1);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(H);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.newTab(I);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(J);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(K);
a.moveActiveTabTo(4);
b.newTab(L);
c.newTab(M);
d.newTab(N);
a.moveActiveTabTo(5);
b.newTab(O);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(P);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(Q);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(R);
d.changeActiveTabTo(3);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(S);
d.newTab(T);
a.newTab(U);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.newTab(V);
c.newTab(W);
d.newTab(X);
a.newTab(Y);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(3);
b.newTab(Z);
c.newTab(Z);
d.changeActiveTabTo(3);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
b.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
b.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->getWindow(2);
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->getWindow(7);
brows->print();
brows->getWindow(7);
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(7);
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(7);
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->getWindow(7);
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->switchToWindow(4);
brows->switchToWindow(6);
brows->newWindow();
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(7);
brows->newWindow();
brows->getWindow(0);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(3);
brows->print();
brows->getWindow(9);
brows->print();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(8);
brows->newWindow();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->getWindow(0);
brows->switchToWindow(6);
brows->getWindow(1);
brows->getWindow(0);
brows->mergeAllWindows();
brows->getWindow(5);
brows->print();
brows->newWindow();
brows->newWindow();
brows->getWindow(7);
brows->switchToWindow(9);
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(5);
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->newWindow();
brows->getWindow(2);
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->newWindow();
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(8);
brows->print();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(5);
brows->newWindow();
brows->getWindow(3);
brows->print();
brows->getWindow(0);
brows->closeWindow();
brows->getWindow(4);
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(8);
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(6);
delete brows;
}
	return 0;
}