#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("n", "c","ccc");
Tab B = Tab("p", "nnn","kk");
Tab C = Tab("m", "bb","ccc");
Tab D = Tab("gg", "y","r");
Tab E = Tab("f", "rrr","hhh");
Tab F = Tab("f", "o","jj");
Tab G = Tab("zzz", "gg","cc");
Tab H = Tab("m", "fff","uuu");
Tab I = Tab("hhh", "u","c");
Tab J = Tab("qqq", "l","fff");
Tab K = Tab("yyy", "b","eee");
Tab L = Tab("zzz", "ww","j");
Tab M = Tab("t", "nnn","tt");
Tab N = Tab("p", "rr","zzz");
Tab O = Tab("l", "xx","hhh");
Tab P = Tab("nn", "ff","ee");
Tab Q = Tab("ii", "aaa","sss");
Tab R = Tab("y", "nn","mm");
Tab S = Tab("zzz", "sss","z");
Tab T = Tab("l", "y","ss");
Tab U = Tab("yy", "mmm","uu");
Tab V = Tab("u", "jjj","kkk");
Tab W = Tab("l", "s","lll");
Tab X = Tab("kk", "f","yy");
Tab Y = Tab("u", "ff","ppp");
Tab Z = Tab("uu", "ff","zzz");
a.newTab(A);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(B);
b.changeActiveTabTo(0);
c.newTab(C);
d.newTab(D);
a.newTab(E);
b.newTab(F);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(G);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.newTab(H);
b.newTab(I);
c.moveActiveTabTo(5);
d.newTab(J);
a.newTab(K);
b.newTab(L);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(M);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(N);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(O);
b.newTab(P);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(Q);
b.moveActiveTabTo(5);
c.newTab(R);
d.newTab(S);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(T);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(U);
a.moveActiveTabTo(4);
b.newTab(V);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(2);
b.newTab(W);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(X);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(Y);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(Z);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
d.changeActiveTabTo(5);
b.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
b.moveActiveTabTo(4);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(5);
d.changeActiveTabTo(5);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->getWindow(3);
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->switchToWindow(3);
brows->print();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(2);
brows->print();
brows->newWindow();
brows->closeWindow();
brows->getWindow(1);
brows->closeEmptyWindows();
brows->getWindow(0);
brows->closeEmptyWindows();
brows->getWindow(9);
brows->print();
brows->getWindow(9);
brows->print();
brows->newWindow();
brows->print();
brows->getWindow(9);
brows->switchToWindow(2);
brows->getWindow(1);
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(8);
brows->switchToWindow(2);
brows->newWindow();
brows->getWindow(7);
brows->print();
brows->print();
brows->newWindow();
brows->print();
brows->getWindow(3);
brows->closeWindow();
brows->newWindow();
brows->getWindow(3);
brows->print();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->getWindow(1);
brows->closeWindow();
brows->closeWindow();
brows->getWindow(6);
brows->switchToWindow(9);
brows->getWindow(0);
brows->switchToWindow(4);
brows->print();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->getWindow(1);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(5);
brows->switchToWindow(6);
brows->switchToWindow(3);
brows->newWindow();
brows->getWindow(4);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->closeWindow();
brows->switchToWindow(3);
brows->switchToWindow(7);
brows->getWindow(3);
brows->getWindow(8);
brows->newWindow();
brows->getWindow(1);
brows->closeWindow();
brows->switchToWindow(4);
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->closeWindow();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(4);
brows->print();
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(3);
delete brows;
}
	return 0;
}