#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("v", "xx","nn");
Tab B = Tab("r", "l","ll");
Tab C = Tab("qq", "j","aa");
Tab D = Tab("p", "aa","qqq");
Tab E = Tab("o", "xx","m");
Tab F = Tab("k", "hhh","yy");
Tab G = Tab("qq", "hhh","uu");
Tab H = Tab("nn", "jjj","aaa");
Tab I = Tab("vv", "kkk","ttt");
Tab J = Tab("v", "ss","ee");
Tab K = Tab("ppp", "ww","kk");
Tab L = Tab("u", "yyy","b");
Tab M = Tab("u", "yyy","ddd");
Tab N = Tab("bb", "v","z");
Tab O = Tab("nn", "ee","mmm");
Tab P = Tab("yyy", "hh","fff");
Tab Q = Tab("aa", "vvv","f");
Tab R = Tab("qq", "xx","yy");
Tab S = Tab("zzz", "k","d");
Tab T = Tab("jjj", "qq","mm");
Tab U = Tab("ii", "y","nnn");
Tab V = Tab("fff", "www","hh");
Tab W = Tab("kk", "uu","tt");
Tab X = Tab("rr", "r","h");
Tab Y = Tab("ddd", "tt","k");
Tab Z = Tab("bbb", "oo","mmm");
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(A);
a.newTab(B);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(C);
a.changeActiveTabTo(4);
b.newTab(D);
c.changeActiveTabTo(4);
d.newTab(E);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.newTab(F);
d.moveActiveTabTo(2);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(1);
b.newTab(G);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
b.newTab(H);
c.newTab(I);
d.newTab(J);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(K);
a.newTab(L);
b.newTab(M);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(N);
b.newTab(O);
c.changeActiveTabTo(1);
d.newTab(P);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(Q);
d.newTab(R);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(S);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(T);
a.newTab(U);
b.newTab(V);
c.newTab(W);
d.newTab(X);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(Y);
a.newTab(Z);
b.changeActiveTabTo(2);
c.newTab(Z);
d.newTab(Z);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
c.moveActiveTabTo(3);
b.changeActiveTabTo(2);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
d.changeActiveTabTo(2);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
d.changeActiveTabTo(5);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
c.changeActiveTabTo(4);
d.changeActiveTabTo(2);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
c.changeActiveTabTo(5);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->getWindow(0);
brows->closeEmptyWindows();
brows->switchToWindow(8);
brows->getWindow(3);
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(7);
brows->newWindow();
brows->getWindow(4);
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(8);
brows->print();
brows->switchToWindow(3);
brows->print();
brows->newWindow();
brows->switchToWindow(9);
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(4);
brows->switchToWindow(9);
brows->getWindow(5);
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(1);
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(9);
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(7);
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->switchToWindow(4);
brows->switchToWindow(1);
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->print();
brows->newWindow();
brows->switchToWindow(7);
brows->newWindow();
brows->getWindow(9);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->getWindow(3);
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(0);
brows->newWindow();
brows->newWindow();
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
delete brows;
}
	return 0;
}