#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("cc", "o","bbb");
Tab B = Tab("ddd", "gg","aaa");
Tab C = Tab("k", "dd","oo");
Tab D = Tab("l", "zzz","u");
Tab E = Tab("ww", "w","ss");
Tab F = Tab("ddd", "ppp","nn");
Tab G = Tab("ddd", "ooo","qq");
Tab H = Tab("x", "tt","mmm");
Tab I = Tab("ddd", "ff","o");
Tab J = Tab("kk", "zz","ee");
Tab K = Tab("cc", "nn","n");
Tab L = Tab("m", "ccc","k");
Tab M = Tab("kkk", "x","p");
Tab N = Tab("a", "yyy","aa");
Tab O = Tab("hhh", "n","vvv");
Tab P = Tab("a", "gg","tt");
Tab Q = Tab("mm", "mmm","p");
Tab R = Tab("www", "l","d");
Tab S = Tab("dd", "rrr","o");
Tab T = Tab("ddd", "ttt","zz");
Tab U = Tab("tt", "nn","www");
Tab V = Tab("pp", "xxx","aaa");
Tab W = Tab("bbb", "zz","ww");
Tab X = Tab("sss", "tt","bb");
Tab Y = Tab("oo", "k","xx");
Tab Z = Tab("ccc", "iii","hh");
a.newTab(A);
b.moveActiveTabTo(0);
c.newTab(B);
d.newTab(C);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(D);
a.changeActiveTabTo(0);
b.newTab(E);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.newTab(F);
b.newTab(G);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(H);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(I);
b.newTab(J);
c.moveActiveTabTo(3);
d.newTab(K);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(2);
b.newTab(L);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(3);
b.newTab(M);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(N);
b.newTab(O);
c.moveActiveTabTo(4);
d.newTab(P);
a.newTab(Q);
b.newTab(R);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(S);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(T);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(3);
b.newTab(U);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(V);
b.newTab(W);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
b.newTab(X);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(3);
b.newTab(Y);
c.newTab(Z);
d.moveActiveTabTo(3);
b.changeActiveTabTo(4);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(2);
c.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(7);
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(9);
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->getWindow(8);
brows->print();
brows->switchToWindow(6);
brows->print();
brows->switchToWindow(3);
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->newWindow();
brows->switchToWindow(0);
brows->getWindow(3);
brows->getWindow(9);
brows->switchToWindow(9);
brows->switchToWindow(5);
brows->switchToWindow(5);
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->getWindow(4);
brows->mergeAllWindows();
brows->switchToWindow(4);
brows->newWindow();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(8);
brows->mergeAllWindows();
brows->getWindow(7);
brows->mergeAllWindows();
brows->print();
brows->getWindow(1);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->switchToWindow(9);
brows->print();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(3);
brows->newWindow();
brows->switchToWindow(9);
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(2);
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(5);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(7);
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(2);
brows->closeWindow();
brows->closeWindow();
brows->getWindow(4);
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(9);
brows->newWindow();
brows->print();
brows->switchToWindow(7);
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->getWindow(3);
brows->switchToWindow(3);
brows->switchToWindow(5);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(5);
brows->print();
brows->print();
delete brows;
}
	return 0;
}