#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("bb", "p","q");
Tab B = Tab("w", "tt","pp");
Tab C = Tab("ss", "ppp","iii");
Tab D = Tab("u", "xx","mmm");
Tab E = Tab("fff", "bbb","l");
Tab F = Tab("l", "p","ss");
Tab G = Tab("w", "j","hh");
Tab H = Tab("ddd", "yyy","ccc");
Tab I = Tab("tt", "mmm","iii");
Tab J = Tab("ooo", "ww","rr");
Tab K = Tab("o", "kkk","cc");
Tab L = Tab("mmm", "vv","m");
Tab M = Tab("d", "vvv","z");
Tab N = Tab("uu", "yy","yy");
Tab O = Tab("ggg", "uu","jjj");
Tab P = Tab("zzz", "d","m");
Tab Q = Tab("hh", "aaa","kk");
Tab R = Tab("www", "ff","d");
Tab S = Tab("n", "zz","ss");
Tab T = Tab("tt", "qq","t");
Tab U = Tab("y", "jj","u");
Tab V = Tab("vvv", "ww","nn");
Tab W = Tab("ooo", "uuu","vv");
Tab X = Tab("aaa", "rrr","cc");
Tab Y = Tab("s", "q","h");
Tab Z = Tab("rrr", "kk","jj");
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(A);
a.newTab(B);
b.newTab(C);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(D);
b.newTab(E);
c.newTab(F);
d.moveActiveTabTo(3);
a.newTab(G);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(H);
b.newTab(I);
c.newTab(J);
d.moveActiveTabTo(5);
a.newTab(K);
b.newTab(L);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(M);
b.newTab(N);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(3);
b.newTab(O);
c.changeActiveTabTo(3);
d.newTab(P);
a.changeActiveTabTo(3);
b.newTab(Q);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(5);
b.newTab(R);
c.newTab(S);
d.changeActiveTabTo(5);
a.newTab(T);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(U);
b.newTab(V);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(W);
b.moveActiveTabTo(2);
c.newTab(X);
d.newTab(Y);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(Z);
d.moveActiveTabTo(4);
a.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(2);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
b.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(2);
d.changeActiveTabTo(2);
b.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
c.changeActiveTabTo(4);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(0);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(3);
brows->switchToWindow(0);
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(3);
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(6);
brows->getWindow(6);
brows->closeEmptyWindows();
brows->switchToWindow(6);
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->switchToWindow(6);
brows->getWindow(6);
brows->switchToWindow(3);
brows->print();
brows->getWindow(4);
brows->mergeAllWindows();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(2);
brows->closeWindow();
brows->switchToWindow(3);
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->getWindow(5);
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(0);
brows->print();
brows->getWindow(0);
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(4);
brows->print();
brows->print();
brows->getWindow(8);
brows->newWindow();
brows->switchToWindow(2);
brows->newWindow();
brows->switchToWindow(1);
brows->print();
brows->switchToWindow(6);
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->newWindow();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->print();
brows->getWindow(8);
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(7);
brows->getWindow(3);
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->closeWindow();
brows->print();
brows->print();
brows->print();
delete brows;
}
	return 0;
}