#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("jj", "ii","uuu");
Tab B = Tab("m", "bbb","vvv");
Tab C = Tab("kk", "ooo","aa");
Tab D = Tab("ppp", "t","f");
Tab E = Tab("vv", "vvv","a");
Tab F = Tab("uuu", "f","q");
Tab G = Tab("z", "mm","d");
Tab H = Tab("ll", "l","z");
Tab I = Tab("r", "w","aa");
Tab J = Tab("ppp", "e","ccc");
Tab K = Tab("ll", "ss","aaa");
Tab L = Tab("n", "sss","s");
Tab M = Tab("ee", "vv","dd");
Tab N = Tab("xx", "o","qq");
Tab O = Tab("mmm", "xx","pp");
Tab P = Tab("b", "g","ttt");
Tab Q = Tab("pp", "ggg","a");
Tab R = Tab("ee", "uu","x");
Tab S = Tab("b", "rr","tt");
Tab T = Tab("y", "hh","dd");
Tab U = Tab("e", "s","uu");
Tab V = Tab("lll", "n","lll");
Tab W = Tab("ff", "jj","r");
Tab X = Tab("nnn", "ooo","b");
Tab Y = Tab("tt", "v","bbb");
Tab Z = Tab("rr", "www","mmm");
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(A);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(B);
a.newTab(C);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(D);
b.moveActiveTabTo(5);
c.newTab(E);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
b.newTab(F);
c.newTab(G);
d.moveActiveTabTo(1);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(0);
b.newTab(H);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.newTab(I);
c.newTab(J);
d.newTab(K);
a.newTab(L);
b.newTab(M);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(1);
b.newTab(N);
c.moveActiveTabTo(1);
d.newTab(O);
a.newTab(P);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(Q);
b.moveActiveTabTo(5);
c.newTab(R);
d.changeActiveTabTo(5);
a.moveActiveTabTo(3);
b.newTab(S);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(4);
b.newTab(T);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(U);
b.newTab(V);
c.changeActiveTabTo(2);
d.newTab(W);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(X);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.newTab(Y);
d.moveActiveTabTo(1);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(Z);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(0);
d.changeActiveTabTo(5);
c.moveActiveTabTo(2);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
b.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(2);
a.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
a.changeActiveTabTo(2);
d.changeActiveTabTo(2);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(6);
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->getWindow(7);
brows->switchToWindow(5);
brows->getWindow(8);
brows->closeWindow();
brows->switchToWindow(6);
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->print();
brows->getWindow(6);
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->getWindow(1);
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(4);
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(6);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(7);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->getWindow(2);
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->getWindow(3);
brows->print();
brows->switchToWindow(9);
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->print();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(7);
brows->newWindow();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(6);
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->print();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->closeWindow();
brows->newWindow();
delete brows;
}
	return 0;
}