#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("nnn", "m","vvv");
Tab B = Tab("a", "q","n");
Tab C = Tab("p", "hhh","rr");
Tab D = Tab("nnn", "h","dd");
Tab E = Tab("hh", "h","w");
Tab F = Tab("o", "xx","g");
Tab G = Tab("ggg", "ccc","vvv");
Tab H = Tab("zz", "m","dd");
Tab I = Tab("d", "hhh","nnn");
Tab J = Tab("ff", "nn","gg");
Tab K = Tab("x", "c","u");
Tab L = Tab("vv", "aa","a");
Tab M = Tab("a", "xxx","ttt");
Tab N = Tab("zz", "jjj","xxx");
Tab O = Tab("fff", "gg","cc");
Tab P = Tab("w", "m","ccc");
Tab Q = Tab("nnn", "nn","p");
Tab R = Tab("iii", "r","j");
Tab S = Tab("vv", "bb","zz");
Tab T = Tab("rrr", "ttt","ppp");
Tab U = Tab("w", "oo","xxx");
Tab V = Tab("k", "f","kk");
Tab W = Tab("c", "ss","oo");
Tab X = Tab("v", "ddd","e");
Tab Y = Tab("j", "n","rr");
Tab Z = Tab("nn", "dd","ll");
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(A);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(4);
b.newTab(B);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.newTab(C);
d.changeActiveTabTo(2);
a.moveActiveTabTo(1);
b.newTab(D);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(E);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(F);
d.newTab(G);
a.newTab(H);
b.newTab(I);
c.newTab(J);
d.changeActiveTabTo(5);
a.newTab(K);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(1);
b.newTab(L);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(3);
b.newTab(M);
c.changeActiveTabTo(3);
d.newTab(N);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.newTab(O);
d.changeActiveTabTo(1);
a.newTab(P);
b.newTab(Q);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(R);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(S);
a.newTab(T);
b.changeActiveTabTo(4);
c.newTab(U);
d.moveActiveTabTo(4);
a.changeActiveTabTo(5);
b.newTab(V);
c.changeActiveTabTo(5);
d.newTab(W);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.newTab(X);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(Y);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(Z);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
c.changeActiveTabTo(4);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
c.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
d.changeActiveTabTo(1);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
c.changeActiveTabTo(1);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->getWindow(3);
brows->newWindow();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->getWindow(7);
brows->closeWindow();
brows->switchToWindow(2);
brows->print();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(3);
brows->print();
brows->newWindow();
brows->newWindow();
brows->getWindow(8);
brows->closeWindow();
brows->print();
brows->getWindow(2);
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->print();
brows->print();
brows->switchToWindow(8);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->switchToWindow(8);
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(3);
brows->newWindow();
brows->getWindow(8);
brows->print();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->switchToWindow(6);
brows->getWindow(2);
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->switchToWindow(9);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(9);
brows->getWindow(3);
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->getWindow(2);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(9);
brows->switchToWindow(9);
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(2);
brows->newWindow();
brows->newWindow();
brows->getWindow(9);
brows->getWindow(6);
brows->newWindow();
brows->getWindow(7);
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(7);
brows->getWindow(1);
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->switchToWindow(7);
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(4);
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
delete brows;
}
	return 0;
}