#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("zz", "ppp","ccc");
Tab B = Tab("xx", "sss","h");
Tab C = Tab("aaa", "g","uuu");
Tab D = Tab("ss", "hhh","y");
Tab E = Tab("gg", "zzz","q");
Tab F = Tab("vv", "nnn","uuu");
Tab G = Tab("l", "w","zz");
Tab H = Tab("nn", "sss","hh");
Tab I = Tab("ttt", "bbb","j");
Tab J = Tab("u", "lll","jjj");
Tab K = Tab("bb", "qq","pp");
Tab L = Tab("h", "ff","zzz");
Tab M = Tab("sss", "nn","ccc");
Tab N = Tab("ccc", "lll","h");
Tab O = Tab("iii", "uu","m");
Tab P = Tab("k", "qqq","bb");
Tab Q = Tab("o", "g","uu");
Tab R = Tab("l", "qq","f");
Tab S = Tab("ww", "eee","yyy");
Tab T = Tab("vvv", "iii","g");
Tab U = Tab("b", "aaa","s");
Tab V = Tab("i", "nnn","jjj");
Tab W = Tab("f", "yy","i");
Tab X = Tab("zz", "qq","k");
Tab Y = Tab("kk", "hh","cc");
Tab Z = Tab("kk", "e","hhh");
a.moveActiveTabTo(3);
b.newTab(A);
c.moveActiveTabTo(3);
d.newTab(B);
a.moveActiveTabTo(0);
b.newTab(C);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(D);
b.newTab(E);
c.newTab(F);
d.changeActiveTabTo(2);
a.moveActiveTabTo(3);
b.newTab(G);
c.changeActiveTabTo(3);
d.newTab(H);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(I);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(J);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(K);
a.newTab(L);
b.newTab(M);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(N);
b.changeActiveTabTo(2);
c.newTab(O);
d.changeActiveTabTo(2);
a.changeActiveTabTo(4);
b.newTab(P);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(4);
b.newTab(Q);
c.newTab(R);
d.newTab(S);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(T);
d.newTab(U);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(V);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(W);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(X);
d.moveActiveTabTo(2);
a.changeActiveTabTo(5);
b.newTab(Y);
c.newTab(Z);
d.newTab(Z);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
a.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.moveActiveTabTo(1);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(3);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
b.moveActiveTabTo(3);
b.changeActiveTabTo(1);
a.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->getWindow(6);
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(1);
brows->closeWindow();
brows->closeWindow();
brows->getWindow(1);
brows->getWindow(9);
brows->print();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->getWindow(9);
brows->newWindow();
brows->newWindow();
brows->print();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(4);
brows->newWindow();
brows->switchToWindow(3);
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(7);
brows->switchToWindow(4);
brows->closeWindow();
brows->getWindow(2);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(6);
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(1);
brows->mergeAllWindows();
brows->getWindow(0);
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(8);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(5);
brows->switchToWindow(1);
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(4);
brows->newWindow();
brows->print();
brows->getWindow(4);
brows->switchToWindow(8);
brows->closeWindow();
brows->getWindow(0);
brows->getWindow(2);
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->getWindow(8);
brows->closeWindow();
brows->newWindow();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->getWindow(6);
brows->print();
brows->print();
brows->getWindow(8);
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(8);
brows->closeWindow();
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
delete brows;
}
	return 0;
}