#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("i", "aaa","nnn");
Tab B = Tab("ddd", "hh","kk");
Tab C = Tab("k", "a","a");
Tab D = Tab("b", "ccc","l");
Tab E = Tab("x", "s","n");
Tab F = Tab("t", "nn","vvv");
Tab G = Tab("ttt", "kkk","x");
Tab H = Tab("nnn", "sss","y");
Tab I = Tab("uuu", "www","z");
Tab J = Tab("fff", "mmm","jjj");
Tab K = Tab("ggg", "a","dd");
Tab L = Tab("qq", "qqq","g");
Tab M = Tab("sss", "ff","yyy");
Tab N = Tab("yyy", "aaa","www");
Tab O = Tab("h", "aa","eee");
Tab P = Tab("w", "y","c");
Tab Q = Tab("vv", "vvv","h");
Tab R = Tab("rr", "vvv","cc");
Tab S = Tab("aaa", "mm","bb");
Tab T = Tab("mm", "kk","bb");
Tab U = Tab("e", "aa","i");
Tab V = Tab("oo", "n","n");
Tab W = Tab("oo", "uu","c");
Tab X = Tab("e", "k","bbb");
Tab Y = Tab("xx", "k","yy");
Tab Z = Tab("g", "m","qq");
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(A);
d.newTab(B);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(C);
a.changeActiveTabTo(1);
b.newTab(D);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.newTab(E);
d.moveActiveTabTo(1);
a.newTab(F);
b.changeActiveTabTo(1);
c.newTab(G);
d.changeActiveTabTo(1);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(H);
d.newTab(I);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(J);
d.newTab(K);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(L);
d.newTab(M);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.newTab(N);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(O);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(P);
a.newTab(Q);
b.newTab(R);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(S);
d.moveActiveTabTo(2);
a.newTab(T);
b.newTab(U);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.newTab(V);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(W);
a.moveActiveTabTo(1);
b.newTab(X);
c.newTab(Y);
d.changeActiveTabTo(1);
a.newTab(Z);
b.newTab(Z);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(0);
c.moveActiveTabTo(0);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
d.moveActiveTabTo(1);
d.changeActiveTabTo(5);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
b.moveActiveTabTo(0);
d.changeActiveTabTo(0);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
c.changeActiveTabTo(1);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
b.moveActiveTabTo(3);
d.changeActiveTabTo(3);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->getWindow(9);
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->getWindow(4);
brows->switchToWindow(4);
brows->newWindow();
brows->newWindow();
brows->print();
brows->switchToWindow(8);
brows->print();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->getWindow(9);
brows->closeWindow();
brows->print();
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(4);
brows->print();
brows->newWindow();
brows->print();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(3);
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(4);
brows->getWindow(0);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(0);
brows->getWindow(5);
brows->getWindow(3);
brows->getWindow(9);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->getWindow(2);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(0);
brows->print();
brows->mergeAllWindows();
brows->print();
brows->getWindow(2);
brows->switchToWindow(3);
brows->closeWindow();
brows->getWindow(3);
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->getWindow(5);
brows->switchToWindow(7);
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->switchToWindow(6);
brows->switchToWindow(2);
brows->switchToWindow(8);
delete brows;
}
	return 0;
}