#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("cc", "yyy","mmm");
Tab B = Tab("d", "ww","ddd");
Tab C = Tab("iii", "sss","ff");
Tab D = Tab("hh", "m","yyy");
Tab E = Tab("r", "s","mm");
Tab F = Tab("xxx", "zz","n");
Tab G = Tab("aa", "hh","bb");
Tab H = Tab("sss", "yy","xxx");
Tab I = Tab("yyy", "nn","yyy");
Tab J = Tab("vv", "z","ll");
Tab K = Tab("yyy", "uu","ss");
Tab L = Tab("jjj", "rrr","rr");
Tab M = Tab("bb", "s","ww");
Tab N = Tab("xxx", "k","bbb");
Tab O = Tab("l", "i","z");
Tab P = Tab("s", "mmm","bb");
Tab Q = Tab("rr", "r","q");
Tab R = Tab("p", "y","hhh");
Tab S = Tab("qq", "xx","ee");
Tab T = Tab("s", "tt","ww");
Tab U = Tab("f", "xxx","y");
Tab V = Tab("zz", "yy","f");
Tab W = Tab("qq", "aa","xxx");
Tab X = Tab("q", "ppp","rrr");
Tab Y = Tab("www", "d","ee");
Tab Z = Tab("q", "ss","ff");
a.newTab(A);
b.newTab(B);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(C);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(D);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(0);
b.newTab(E);
c.newTab(F);
d.moveActiveTabTo(0);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(G);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(H);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(I);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(J);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(K);
a.newTab(L);
b.moveActiveTabTo(2);
c.newTab(M);
d.moveActiveTabTo(2);
a.newTab(N);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(2);
b.newTab(O);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(P);
b.changeActiveTabTo(0);
c.newTab(Q);
d.newTab(R);
a.moveActiveTabTo(1);
b.newTab(S);
c.newTab(T);
d.changeActiveTabTo(1);
a.newTab(U);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.newTab(V);
b.newTab(W);
c.changeActiveTabTo(4);
d.newTab(X);
a.newTab(Y);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(Z);
a.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
d.moveActiveTabTo(2);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(0);
d.changeActiveTabTo(0);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
d.moveActiveTabTo(1);
c.moveActiveTabTo(0);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(4);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->print();
brows->switchToWindow(3);
brows->mergeAllWindows();
brows->getWindow(0);
brows->closeWindow();
brows->print();
brows->getWindow(6);
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(4);
brows->print();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(6);
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->newWindow();
brows->print();
brows->switchToWindow(2);
brows->print();
brows->mergeAllWindows();
brows->getWindow(3);
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(4);
brows->print();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->getWindow(8);
brows->getWindow(4);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->getWindow(3);
brows->closeEmptyWindows();
brows->getWindow(6);
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(1);
brows->print();
brows->print();
brows->switchToWindow(8);
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->switchToWindow(9);
brows->print();
brows->getWindow(6);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->getWindow(5);
brows->switchToWindow(0);
brows->getWindow(0);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(1);
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->switchToWindow(4);
brows->newWindow();
brows->getWindow(0);
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->getWindow(4);
brows->switchToWindow(3);
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(8);
brows->getWindow(0);
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(0);
brows->print();
brows->print();
brows->closeWindow();
brows->switchToWindow(6);
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->switchToWindow(2);
brows->newWindow();
brows->getWindow(8);
brows->print();
brows->closeWindow();
delete brows;
}
	return 0;
}