#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("ooo", "qqq","b");
Tab B = Tab("xxx", "sss","ss");
Tab C = Tab("vvv", "uu","m");
Tab D = Tab("ll", "uuu","nnn");
Tab E = Tab("yy", "hh","rr");
Tab F = Tab("lll", "oo","l");
Tab G = Tab("aaa", "hh","uuu");
Tab H = Tab("bb", "s","y");
Tab I = Tab("zz", "m","bb");
Tab J = Tab("p", "o","fff");
Tab K = Tab("vvv", "v","i");
Tab L = Tab("w", "ppp","yyy");
Tab M = Tab("w", "u","q");
Tab N = Tab("e", "aa","l");
Tab O = Tab("h", "i","ttt");
Tab P = Tab("fff", "jjj","mmm");
Tab Q = Tab("z", "f","gg");
Tab R = Tab("qqq", "sss","pp");
Tab S = Tab("q", "nn","h");
Tab T = Tab("z", "mm","i");
Tab U = Tab("l", "i","l");
Tab V = Tab("www", "m","f");
Tab W = Tab("fff", "xxx","f");
Tab X = Tab("q", "ii","gg");
Tab Y = Tab("hh", "s","v");
Tab Z = Tab("ttt", "nn","p");
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(A);
d.newTab(B);
a.changeActiveTabTo(4);
b.newTab(C);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(1);
b.newTab(D);
c.changeActiveTabTo(1);
d.newTab(E);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(F);
d.changeActiveTabTo(3);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.newTab(G);
d.changeActiveTabTo(1);
a.changeActiveTabTo(4);
b.newTab(H);
c.changeActiveTabTo(4);
d.newTab(I);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(J);
d.moveActiveTabTo(4);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(K);
d.moveActiveTabTo(3);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(L);
b.moveActiveTabTo(3);
c.newTab(M);
d.newTab(N);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.newTab(O);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(P);
b.changeActiveTabTo(4);
c.newTab(Q);
d.changeActiveTabTo(4);
a.newTab(R);
b.moveActiveTabTo(5);
c.newTab(S);
d.changeActiveTabTo(5);
a.newTab(T);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(U);
d.moveActiveTabTo(4);
a.newTab(V);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(W);
a.newTab(X);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(Y);
a.newTab(Z);
b.newTab(Z);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
a.moveActiveTabTo(2);
d.changeActiveTabTo(2);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
c.moveActiveTabTo(1);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
a.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->switchToWindow(4);
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(7);
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(5);
brows->print();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(4);
brows->switchToWindow(3);
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->switchToWindow(7);
brows->switchToWindow(3);
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(6);
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->switchToWindow(0);
brows->switchToWindow(6);
brows->newWindow();
brows->getWindow(9);
brows->closeEmptyWindows();
brows->getWindow(4);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->getWindow(3);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->getWindow(8);
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(6);
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(5);
brows->switchToWindow(6);
brows->getWindow(9);
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(6);
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
delete brows;
}
	return 0;
}