#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("ddd", "g","yyy");
Tab B = Tab("y", "p","jj");
Tab C = Tab("eee", "xxx","n");
Tab D = Tab("ww", "kkk","bb");
Tab E = Tab("ooo", "nnn","uu");
Tab F = Tab("rrr", "bbb","rrr");
Tab G = Tab("nnn", "cc","ooo");
Tab H = Tab("uuu", "c","bb");
Tab I = Tab("g", "ww","vv");
Tab J = Tab("t", "mm","ww");
Tab K = Tab("iii", "eee","ooo");
Tab L = Tab("ttt", "r","h");
Tab M = Tab("v", "l","f");
Tab N = Tab("hhh", "gg","r");
Tab O = Tab("ppp", "vvv","h");
Tab P = Tab("fff", "uuu","ss");
Tab Q = Tab("hh", "jjj","rr");
Tab R = Tab("a", "a","ppp");
Tab S = Tab("cc", "gg","ttt");
Tab T = Tab("e", "e","hhh");
Tab U = Tab("ooo", "iii","t");
Tab V = Tab("d", "kkk","uuu");
Tab W = Tab("rr", "bbb","f");
Tab X = Tab("ll", "i","ee");
Tab Y = Tab("xx", "uu","xx");
Tab Z = Tab("zzz", "mm","hh");
a.newTab(A);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(B);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.newTab(C);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(D);
a.newTab(E);
b.newTab(F);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(2);
b.newTab(G);
c.changeActiveTabTo(2);
d.newTab(H);
a.newTab(I);
b.newTab(J);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(K);
b.newTab(L);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(M);
d.changeActiveTabTo(4);
a.newTab(N);
b.moveActiveTabTo(0);
c.newTab(O);
d.moveActiveTabTo(0);
a.newTab(P);
b.newTab(Q);
c.newTab(R);
d.changeActiveTabTo(3);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(S);
b.newTab(T);
c.moveActiveTabTo(0);
d.newTab(U);
a.changeActiveTabTo(0);
b.newTab(V);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(W);
d.newTab(X);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(Y);
a.moveActiveTabTo(0);
b.newTab(Z);
c.moveActiveTabTo(0);
d.newTab(Z);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
d.changeActiveTabTo(3);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
a.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(5);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(1);
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(3);
brows->newWindow();
brows->print();
brows->print();
brows->getWindow(3);
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->switchToWindow(7);
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->newWindow();
brows->closeWindow();
brows->getWindow(9);
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->getWindow(9);
brows->print();
brows->switchToWindow(0);
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(7);
brows->closeWindow();
brows->print();
brows->print();
brows->switchToWindow(4);
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(5);
brows->print();
brows->closeWindow();
brows->switchToWindow(0);
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(4);
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->getWindow(8);
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(6);
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->getWindow(5);
brows->closeWindow();
brows->getWindow(2);
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->getWindow(4);
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
delete brows;
}
	return 0;
}