#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("ee", "ii","kkk");
Tab B = Tab("www", "mm","hh");
Tab C = Tab("z", "zzz","ooo");
Tab D = Tab("t", "nn","rrr");
Tab E = Tab("yyy", "d","z");
Tab F = Tab("ww", "dd","c");
Tab G = Tab("qq", "fff","j");
Tab H = Tab("d", "aaa","ccc");
Tab I = Tab("bbb", "v","ii");
Tab J = Tab("sss", "r","ccc");
Tab K = Tab("o", "xxx","g");
Tab L = Tab("gg", "l","mmm");
Tab M = Tab("iii", "qq","ff");
Tab N = Tab("rr", "ttt","ll");
Tab O = Tab("vvv", "e","y");
Tab P = Tab("ff", "ss","xx");
Tab Q = Tab("rr", "iii","b");
Tab R = Tab("q", "m","vv");
Tab S = Tab("mmm", "ee","zzz");
Tab T = Tab("zz", "xx","rrr");
Tab U = Tab("e", "n","vv");
Tab V = Tab("gg", "kkk","f");
Tab W = Tab("ee", "nn","ggg");
Tab X = Tab("jj", "ss","a");
Tab Y = Tab("i", "r","ii");
Tab Z = Tab("ddd", "ooo","ll");
a.newTab(A);
b.newTab(B);
c.newTab(C);
d.changeActiveTabTo(1);
a.newTab(D);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(E);
a.newTab(F);
b.newTab(G);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(2);
b.newTab(H);
c.newTab(I);
d.newTab(J);
a.changeActiveTabTo(2);
b.newTab(K);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(L);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(M);
b.newTab(N);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(5);
b.newTab(O);
c.newTab(P);
d.changeActiveTabTo(5);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(4);
b.newTab(Q);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.newTab(R);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(S);
b.newTab(T);
c.newTab(U);
d.changeActiveTabTo(1);
a.newTab(V);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(W);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.newTab(X);
a.newTab(Y);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(Z);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
a.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.moveActiveTabTo(2);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
c.changeActiveTabTo(5);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
b.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(2);
d.changeActiveTabTo(2);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeWindow();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(5);
brows->switchToWindow(8);
brows->switchToWindow(0);
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->print();
brows->switchToWindow(0);
brows->getWindow(6);
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(3);
brows->switchToWindow(5);
brows->getWindow(5);
brows->closeEmptyWindows();
brows->print();
brows->getWindow(5);
brows->print();
brows->getWindow(8);
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(0);
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->switchToWindow(6);
brows->getWindow(4);
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(4);
brows->switchToWindow(6);
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(9);
brows->switchToWindow(5);
brows->switchToWindow(5);
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->getWindow(1);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(8);
brows->getWindow(9);
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(6);
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
delete brows;
}
	return 0;
}