#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("rr", "cc","hh");
Tab B = Tab("x", "xx","eee");
Tab C = Tab("bb", "d","www");
Tab D = Tab("ppp", "cc","d");
Tab E = Tab("bbb", "www","iii");
Tab F = Tab("b", "v","u");
Tab G = Tab("uuu", "fff","u");
Tab H = Tab("bb", "vv","t");
Tab I = Tab("nn", "f","kkk");
Tab J = Tab("f", "zzz","xxx");
Tab K = Tab("rr", "dd","m");
Tab L = Tab("xx", "eee","w");
Tab M = Tab("hh", "hhh","gg");
Tab N = Tab("o", "mmm","o");
Tab O = Tab("ss", "zzz","v");
Tab P = Tab("mmm", "www","n");
Tab Q = Tab("f", "nnn","rr");
Tab R = Tab("d", "uuu","v");
Tab S = Tab("ooo", "w","aa");
Tab T = Tab("w", "rr","cc");
Tab U = Tab("qq", "ppp","d");
Tab V = Tab("j", "ee","kk");
Tab W = Tab("n", "ggg","i");
Tab X = Tab("xx", "hhh","sss");
Tab Y = Tab("l", "ppp","eee");
Tab Z = Tab("l", "v","t");
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(A);
d.moveActiveTabTo(4);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(B);
b.changeActiveTabTo(5);
c.newTab(C);
d.changeActiveTabTo(5);
a.changeActiveTabTo(3);
b.newTab(D);
c.changeActiveTabTo(3);
d.newTab(E);
a.newTab(F);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(G);
d.newTab(H);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(I);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(J);
a.changeActiveTabTo(2);
b.newTab(K);
c.newTab(L);
d.moveActiveTabTo(2);
a.moveActiveTabTo(3);
b.newTab(M);
c.newTab(N);
d.newTab(O);
a.moveActiveTabTo(4);
b.newTab(P);
c.newTab(Q);
d.changeActiveTabTo(4);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(3);
b.newTab(R);
c.newTab(S);
d.changeActiveTabTo(3);
a.newTab(T);
b.moveActiveTabTo(1);
c.newTab(U);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(V);
b.newTab(W);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.newTab(X);
c.newTab(Y);
d.moveActiveTabTo(5);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.newTab(Z);
d.changeActiveTabTo(2);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
a.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(1);
c.changeActiveTabTo(1);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(5);
a.moveActiveTabTo(1);
c.moveActiveTabTo(1);
a.changeActiveTabTo(3);
c.changeActiveTabTo(3);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(2);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
b.changeActiveTabTo(4);
b.moveActiveTabTo(0);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
b.moveActiveTabTo(2);
d.moveActiveTabTo(2);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->getWindow(8);
brows->print();
brows->closeWindow();
brows->getWindow(6);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->getWindow(8);
brows->getWindow(8);
brows->closeEmptyWindows();
brows->getWindow(0);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(9);
brows->switchToWindow(5);
brows->newWindow();
brows->switchToWindow(4);
brows->print();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(1);
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(2);
brows->newWindow();
brows->closeWindow();
brows->getWindow(3);
brows->getWindow(9);
brows->switchToWindow(4);
brows->getWindow(8);
brows->getWindow(2);
brows->getWindow(4);
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->switchToWindow(4);
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->print();
brows->print();
brows->switchToWindow(4);
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(2);
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->getWindow(9);
brows->switchToWindow(2);
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(9);
brows->getWindow(0);
brows->print();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(8);
brows->getWindow(1);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(6);
delete brows;
}
	return 0;
}