#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("sss", "c","vvv");
Tab B = Tab("j", "j","zzz");
Tab C = Tab("xx", "rrr","eee");
Tab D = Tab("g", "a","ppp");
Tab E = Tab("bb", "gg","mm");
Tab F = Tab("s", "aaa","ll");
Tab G = Tab("i", "ppp","l");
Tab H = Tab("www", "ee","qq");
Tab I = Tab("lll", "ddd","jj");
Tab J = Tab("g", "e","ff");
Tab K = Tab("jj", "bb","mmm");
Tab L = Tab("mmm", "ccc","gg");
Tab M = Tab("u", "uu","jj");
Tab N = Tab("d", "nn","t");
Tab O = Tab("ppp", "d","hh");
Tab P = Tab("ccc", "tt","ii");
Tab Q = Tab("xxx", "f","nn");
Tab R = Tab("gg", "hh","vvv");
Tab S = Tab("oo", "qqq","rr");
Tab T = Tab("yyy", "ooo","ss");
Tab U = Tab("yy", "nnn","z");
Tab V = Tab("rr", "q","c");
Tab W = Tab("xx", "g","xxx");
Tab X = Tab("fff", "w","aaa");
Tab Y = Tab("jjj", "p","rrr");
Tab Z = Tab("nnn", "oo","bbb");
a.newTab(A);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.newTab(B);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.newTab(C);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(1);
b.newTab(D);
c.moveActiveTabTo(1);
d.newTab(E);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(F);
a.newTab(G);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(H);
a.changeActiveTabTo(1);
b.newTab(I);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(5);
b.newTab(J);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.newTab(K);
c.moveActiveTabTo(4);
d.newTab(L);
a.newTab(M);
b.newTab(N);
c.newTab(O);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(P);
d.newTab(Q);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(R);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(S);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(T);
d.moveActiveTabTo(0);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(U);
a.newTab(V);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(W);
a.changeActiveTabTo(4);
b.newTab(X);
c.changeActiveTabTo(4);
d.newTab(Y);
a.newTab(Z);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(Z);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.moveActiveTabTo(0);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
a.changeActiveTabTo(1);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->getWindow(3);
brows->closeWindow();
brows->print();
brows->getWindow(0);
brows->print();
brows->switchToWindow(7);
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(8);
brows->closeWindow();
brows->switchToWindow(8);
brows->closeWindow();
brows->closeWindow();
brows->getWindow(8);
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->print();
brows->getWindow(2);
brows->newWindow();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->getWindow(6);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->getWindow(1);
brows->mergeAllWindows();
brows->getWindow(5);
brows->newWindow();
brows->print();
brows->getWindow(1);
brows->getWindow(4);
brows->switchToWindow(8);
brows->closeWindow();
brows->switchToWindow(9);
brows->switchToWindow(1);
brows->getWindow(5);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->getWindow(3);
brows->getWindow(4);
brows->switchToWindow(3);
brows->print();
brows->switchToWindow(0);
brows->getWindow(6);
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->getWindow(9);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(4);
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->switchToWindow(3);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->getWindow(6);
brows->newWindow();
brows->getWindow(8);
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
delete brows;
}
	return 0;
}