#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("ii", "q","nn");
Tab B = Tab("o", "c","f");
Tab C = Tab("s", "u","r");
Tab D = Tab("eee", "fff","ccc");
Tab E = Tab("ttt", "nnn","m");
Tab F = Tab("ooo", "yyy","q");
Tab G = Tab("vvv", "n","j");
Tab H = Tab("gg", "yyy","w");
Tab I = Tab("b", "cc","rrr");
Tab J = Tab("qqq", "www","aa");
Tab K = Tab("qq", "ii","q");
Tab L = Tab("ppp", "qqq","nn");
Tab M = Tab("vv", "ddd","hh");
Tab N = Tab("xx", "vv","e");
Tab O = Tab("o", "yy","tt");
Tab P = Tab("ppp", "ll","bb");
Tab Q = Tab("xxx", "xxx","ooo");
Tab R = Tab("k", "jj","d");
Tab S = Tab("kk", "c","nnn");
Tab T = Tab("ddd", "yy","hh");
Tab U = Tab("fff", "oo","ppp");
Tab V = Tab("mmm", "o","xx");
Tab W = Tab("jj", "tt","tt");
Tab X = Tab("i", "gg","o");
Tab Y = Tab("ll", "l","hhh");
Tab Z = Tab("v", "nn","dd");
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(A);
b.newTab(B);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(1);
b.newTab(C);
c.newTab(D);
d.moveActiveTabTo(1);
a.moveActiveTabTo(5);
b.newTab(E);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(F);
d.moveActiveTabTo(0);
a.newTab(G);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(H);
d.newTab(I);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(J);
d.newTab(K);
a.moveActiveTabTo(5);
b.newTab(L);
c.moveActiveTabTo(5);
d.newTab(M);
a.moveActiveTabTo(5);
b.newTab(N);
c.moveActiveTabTo(5);
d.newTab(O);
a.newTab(P);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(Q);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(R);
b.changeActiveTabTo(4);
c.newTab(S);
d.moveActiveTabTo(4);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.newTab(T);
d.newTab(U);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(V);
b.newTab(W);
c.newTab(X);
d.newTab(Y);
a.newTab(Z);
b.newTab(Z);
c.newTab(Z);
d.moveActiveTabTo(4);
b.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
c.changeActiveTabTo(5);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
d.changeActiveTabTo(4);
d.moveActiveTabTo(3);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
a.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
d.changeActiveTabTo(1);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
b.changeActiveTabTo(2);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeWindow();
brows->getWindow(7);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(5);
brows->getWindow(9);
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->getWindow(5);
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(6);
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(0);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->getWindow(8);
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(1);
brows->switchToWindow(5);
brows->getWindow(7);
brows->switchToWindow(4);
brows->getWindow(5);
brows->getWindow(3);
brows->print();
brows->switchToWindow(0);
brows->getWindow(6);
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->getWindow(5);
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(4);
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(3);
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(0);
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(6);
brows->mergeAllWindows();
brows->getWindow(1);
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->switchToWindow(3);
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(8);
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->switchToWindow(2);
brows->getWindow(7);
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->getWindow(0);
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->getWindow(8);
delete brows;
}
	return 0;
}