#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("eee", "q","ddd");
Tab B = Tab("qq", "lll","ddd");
Tab C = Tab("ttt", "m","j");
Tab D = Tab("rr", "f","s");
Tab E = Tab("ddd", "dd","d");
Tab F = Tab("x", "hh","nn");
Tab G = Tab("yyy", "ooo","p");
Tab H = Tab("o", "uu","z");
Tab I = Tab("www", "vv","jjj");
Tab J = Tab("yy", "vvv","h");
Tab K = Tab("ll", "rrr","ff");
Tab L = Tab("yyy", "tt","j");
Tab M = Tab("sss", "nnn","jjj");
Tab N = Tab("h", "v","ccc");
Tab O = Tab("ii", "g","mmm");
Tab P = Tab("aa", "ccc","dd");
Tab Q = Tab("nnn", "nn","r");
Tab R = Tab("x", "ee","xx");
Tab S = Tab("a", "kkk","kkk");
Tab T = Tab("ww", "ddd","t");
Tab U = Tab("ggg", "ggg","fff");
Tab V = Tab("g", "w","s");
Tab W = Tab("mmm", "ss","uu");
Tab X = Tab("bbb", "www","mmm");
Tab Y = Tab("ccc", "rr","q");
Tab Z = Tab("vv", "dd","n");
a.newTab(A);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(4);
b.newTab(B);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(C);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(3);
b.newTab(D);
c.newTab(E);
d.changeActiveTabTo(3);
a.newTab(F);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(G);
d.moveActiveTabTo(5);
a.changeActiveTabTo(5);
b.newTab(H);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
b.newTab(I);
c.newTab(J);
d.moveActiveTabTo(1);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(K);
d.newTab(L);
a.newTab(M);
b.changeActiveTabTo(2);
c.newTab(N);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(O);
d.moveActiveTabTo(3);
a.newTab(P);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(Q);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(R);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(S);
d.moveActiveTabTo(3);
a.changeActiveTabTo(0);
b.newTab(T);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
b.newTab(U);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(V);
a.moveActiveTabTo(3);
b.newTab(W);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.newTab(X);
b.newTab(Y);
c.newTab(Z);
d.moveActiveTabTo(2);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
b.changeActiveTabTo(0);
a.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
b.moveActiveTabTo(5);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(4);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
a.moveActiveTabTo(0);
d.changeActiveTabTo(0);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->getWindow(5);
brows->closeWindow();
brows->getWindow(2);
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->getWindow(4);
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->print();
brows->getWindow(4);
brows->switchToWindow(2);
brows->getWindow(0);
brows->closeEmptyWindows();
brows->getWindow(1);
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(7);
brows->print();
brows->newWindow();
brows->getWindow(4);
brows->newWindow();
brows->switchToWindow(8);
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(4);
brows->getWindow(7);
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(0);
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->getWindow(8);
brows->getWindow(9);
brows->print();
brows->getWindow(9);
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(6);
brows->print();
brows->switchToWindow(7);
brows->getWindow(6);
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->switchToWindow(8);
brows->closeWindow();
brows->print();
brows->newWindow();
brows->newWindow();
brows->getWindow(1);
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->print();
delete brows;
}
	return 0;
}