#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("w", "ss","ff");
Tab B = Tab("j", "aa","kk");
Tab C = Tab("b", "bbb","ppp");
Tab D = Tab("l", "gg","oo");
Tab E = Tab("y", "xx","iii");
Tab F = Tab("yy", "sss","tt");
Tab G = Tab("y", "aaa","bb");
Tab H = Tab("zzz", "nn","xx");
Tab I = Tab("nnn", "c","xx");
Tab J = Tab("ggg", "dd","u");
Tab K = Tab("lll", "j","hh");
Tab L = Tab("uu", "m","mmm");
Tab M = Tab("aaa", "b","tt");
Tab N = Tab("ii", "m","yy");
Tab O = Tab("u", "e","c");
Tab P = Tab("t", "hh","ll");
Tab Q = Tab("ooo", "qqq","jj");
Tab R = Tab("lll", "a","ss");
Tab S = Tab("o", "jjj","bb");
Tab T = Tab("ww", "ccc","q");
Tab U = Tab("i", "gg","vvv");
Tab V = Tab("c", "ff","www");
Tab W = Tab("dd", "ppp","l");
Tab X = Tab("xxx", "s","yyy");
Tab Y = Tab("b", "ll","cc");
Tab Z = Tab("fff", "nn","eee");
a.moveActiveTabTo(3);
b.newTab(A);
c.newTab(B);
d.newTab(C);
a.newTab(D);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(4);
b.newTab(E);
c.changeActiveTabTo(4);
d.newTab(F);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.newTab(G);
b.newTab(H);
c.newTab(I);
d.newTab(J);
a.newTab(K);
b.newTab(L);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(M);
d.moveActiveTabTo(2);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.newTab(N);
d.changeActiveTabTo(1);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(O);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(P);
a.newTab(Q);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(R);
a.newTab(S);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.newTab(T);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(U);
a.changeActiveTabTo(0);
b.newTab(V);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(W);
d.newTab(X);
a.newTab(Y);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(Z);
c.moveActiveTabTo(0);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
b.moveActiveTabTo(2);
d.moveActiveTabTo(2);
b.moveActiveTabTo(3);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
b.changeActiveTabTo(5);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->closeWindow();
brows->closeWindow();
brows->getWindow(5);
brows->getWindow(8);
brows->closeEmptyWindows();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->getWindow(1);
brows->mergeAllWindows();
brows->getWindow(2);
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->print();
brows->getWindow(5);
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->switchToWindow(6);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->switchToWindow(3);
brows->switchToWindow(1);
brows->getWindow(1);
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(4);
brows->closeWindow();
brows->switchToWindow(6);
brows->switchToWindow(1);
brows->newWindow();
brows->getWindow(2);
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(0);
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(7);
brows->getWindow(8);
brows->getWindow(0);
brows->getWindow(9);
brows->newWindow();
brows->newWindow();
brows->switchToWindow(7);
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(3);
brows->getWindow(5);
brows->closeWindow();
brows->newWindow();
brows->print();
brows->switchToWindow(2);
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->switchToWindow(6);
brows->newWindow();
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->getWindow(0);
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->switchToWindow(4);
brows->getWindow(8);
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(0);
brows->print();
brows->mergeAllWindows();
brows->getWindow(6);
brows->closeEmptyWindows();
delete brows;
}
	return 0;
}