#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("y", "h","kk");
Tab B = Tab("cc", "ccc","c");
Tab C = Tab("hhh", "z","ff");
Tab D = Tab("cc", "l","a");
Tab E = Tab("uuu", "qq","fff");
Tab F = Tab("nn", "b","kk");
Tab G = Tab("sss", "ddd","ss");
Tab H = Tab("mmm", "tt","n");
Tab I = Tab("kk", "hh","r");
Tab J = Tab("kkk", "xx","ddd");
Tab K = Tab("r", "ll","nn");
Tab L = Tab("a", "uuu","xx");
Tab M = Tab("vvv", "qqq","lll");
Tab N = Tab("xx", "nnn","kk");
Tab O = Tab("g", "vvv","p");
Tab P = Tab("ooo", "gg","y");
Tab Q = Tab("ccc", "bbb","rrr");
Tab R = Tab("n", "ggg","i");
Tab S = Tab("m", "o","bb");
Tab T = Tab("xx", "ff","uu");
Tab U = Tab("ss", "fff","lll");
Tab V = Tab("tt", "ii","ggg");
Tab W = Tab("cc", "qqq","uuu");
Tab X = Tab("ttt", "rr","j");
Tab Y = Tab("ii", "jjj","dd");
Tab Z = Tab("p", "y","jj");
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(1);
b.newTab(A);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(B);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(C);
d.newTab(D);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(E);
b.newTab(F);
c.newTab(G);
d.newTab(H);
a.newTab(I);
b.newTab(J);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(K);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(2);
b.newTab(L);
c.newTab(M);
d.changeActiveTabTo(2);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(N);
d.moveActiveTabTo(0);
a.changeActiveTabTo(1);
b.newTab(O);
c.newTab(P);
d.newTab(Q);
a.newTab(R);
b.changeActiveTabTo(0);
c.newTab(S);
d.moveActiveTabTo(0);
a.moveActiveTabTo(0);
b.newTab(T);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(U);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(V);
b.moveActiveTabTo(5);
c.newTab(W);
d.changeActiveTabTo(5);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(X);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(Y);
d.changeActiveTabTo(2);
a.newTab(Z);
b.newTab(Z);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
b.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(4);
brows->print();
brows->getWindow(4);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(9);
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->getWindow(4);
brows->closeWindow();
brows->print();
brows->switchToWindow(7);
brows->print();
brows->closeWindow();
brows->switchToWindow(6);
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(0);
brows->print();
brows->newWindow();
brows->print();
brows->switchToWindow(5);
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->getWindow(6);
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->getWindow(6);
brows->newWindow();
brows->getWindow(3);
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(4);
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->switchToWindow(9);
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->newWindow();
brows->newWindow();
brows->print();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(9);
brows->newWindow();
brows->closeWindow();
brows->getWindow(8);
brows->switchToWindow(4);
brows->newWindow();
brows->getWindow(9);
brows->getWindow(1);
brows->mergeAllWindows();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(5);
brows->switchToWindow(1);
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(7);
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(0);
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
delete brows;
}
	return 0;
}