#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("g", "uuu","ppp");
Tab B = Tab("u", "sss","ccc");
Tab C = Tab("aa", "vv","b");
Tab D = Tab("www", "zzz","ppp");
Tab E = Tab("yy", "x","xx");
Tab F = Tab("ccc", "xx","ff");
Tab G = Tab("aaa", "yy","www");
Tab H = Tab("d", "nnn","gg");
Tab I = Tab("d", "bb","qqq");
Tab J = Tab("hh", "w","s");
Tab K = Tab("xxx", "s","kkk");
Tab L = Tab("yyy", "mmm","e");
Tab M = Tab("d", "uuu","m");
Tab N = Tab("g", "zz","r");
Tab O = Tab("l", "w","t");
Tab P = Tab("r", "uuu","aaa");
Tab Q = Tab("ooo", "w","j");
Tab R = Tab("uuu", "sss","iii");
Tab S = Tab("i", "ttt","qq");
Tab T = Tab("aaa", "d","bb");
Tab U = Tab("v", "ii","yy");
Tab V = Tab("eee", "f","ppp");
Tab W = Tab("xxx", "l","cc");
Tab X = Tab("ss", "ee","q");
Tab Y = Tab("z", "cc","pp");
Tab Z = Tab("lll", "aaa","aaa");
a.newTab(A);
b.newTab(B);
c.changeActiveTabTo(2);
d.newTab(C);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.newTab(D);
d.newTab(E);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.newTab(F);
d.moveActiveTabTo(2);
a.newTab(G);
b.newTab(H);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(I);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.newTab(J);
b.moveActiveTabTo(1);
c.newTab(K);
d.changeActiveTabTo(1);
a.moveActiveTabTo(2);
b.newTab(L);
c.changeActiveTabTo(2);
d.newTab(M);
a.newTab(N);
b.newTab(O);
c.moveActiveTabTo(2);
d.newTab(P);
a.newTab(Q);
b.moveActiveTabTo(3);
c.newTab(R);
d.moveActiveTabTo(3);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(S);
a.newTab(T);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(U);
a.newTab(V);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(W);
a.newTab(X);
b.changeActiveTabTo(3);
c.newTab(Y);
d.newTab(Z);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
d.changeActiveTabTo(4);
d.moveActiveTabTo(2);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
b.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
d.changeActiveTabTo(2);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
b.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
c.moveActiveTabTo(1);
c.changeActiveTabTo(3);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(2);
c.changeActiveTabTo(2);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
b.changeActiveTabTo(5);
d.moveActiveTabTo(2);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
b.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->switchToWindow(5);
brows->getWindow(7);
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(0);
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->print();
brows->print();
brows->switchToWindow(9);
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->print();
brows->print();
brows->switchToWindow(4);
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->getWindow(8);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(9);
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->switchToWindow(9);
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(9);
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->getWindow(0);
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(4);
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->getWindow(2);
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->switchToWindow(8);
brows->getWindow(2);
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(6);
brows->getWindow(2);
brows->newWindow();
brows->switchToWindow(6);
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(1);
brows->switchToWindow(9);
brows->getWindow(4);
brows->getWindow(1);
brows->getWindow(3);
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(1);
brows->getWindow(6);
brows->closeWindow();
brows->switchToWindow(7);
brows->getWindow(4);
brows->getWindow(8);
brows->newWindow();
brows->getWindow(3);
brows->newWindow();
brows->getWindow(0);
brows->getWindow(8);
brows->switchToWindow(5);
delete brows;
}
	return 0;
}