#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("xxx", "c","ooo");
Tab B = Tab("ll", "rrr","jj");
Tab C = Tab("pp", "ggg","yy");
Tab D = Tab("r", "qqq","hh");
Tab E = Tab("sss", "www","rr");
Tab F = Tab("ppp", "m","l");
Tab G = Tab("ttt", "kkk","a");
Tab H = Tab("uu", "zz","ll");
Tab I = Tab("v", "y","nnn");
Tab J = Tab("i", "ii","ff");
Tab K = Tab("uuu", "ppp","bbb");
Tab L = Tab("kkk", "www","p");
Tab M = Tab("qq", "jj","l");
Tab N = Tab("f", "bbb","i");
Tab O = Tab("vv", "uuu","eee");
Tab P = Tab("rr", "lll","lll");
Tab Q = Tab("jj", "xx","l");
Tab R = Tab("b", "xx","ww");
Tab S = Tab("m", "ccc","fff");
Tab T = Tab("n", "ccc","ww");
Tab U = Tab("t", "d","aa");
Tab V = Tab("iii", "ww","sss");
Tab W = Tab("oo", "nnn","x");
Tab X = Tab("j", "nn","ttt");
Tab Y = Tab("dd", "nnn","i");
Tab Z = Tab("kkk", "nnn","y");
a.moveActiveTabTo(5);
b.newTab(A);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(B);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(1);
b.newTab(C);
c.newTab(D);
d.newTab(E);
a.newTab(F);
b.changeActiveTabTo(5);
c.newTab(G);
d.newTab(H);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(I);
a.newTab(J);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(K);
a.newTab(L);
b.moveActiveTabTo(2);
c.newTab(M);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.newTab(N);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.newTab(O);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(P);
b.newTab(Q);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(R);
d.moveActiveTabTo(3);
a.changeActiveTabTo(1);
b.newTab(S);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(T);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(U);
a.newTab(V);
b.changeActiveTabTo(2);
c.newTab(W);
d.moveActiveTabTo(2);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(X);
b.newTab(Y);
c.newTab(Z);
d.changeActiveTabTo(4);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(2);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
b.changeActiveTabTo(1);
a.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(5);
a.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(2);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
b.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->newWindow();
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(8);
brows->switchToWindow(1);
brows->getWindow(0);
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->switchToWindow(5);
brows->print();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->print();
brows->switchToWindow(6);
brows->getWindow(5);
brows->switchToWindow(4);
brows->getWindow(6);
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(6);
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->getWindow(8);
brows->print();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->print();
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(8);
brows->closeWindow();
brows->getWindow(3);
brows->closeEmptyWindows();
brows->getWindow(7);
brows->getWindow(3);
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(7);
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->getWindow(3);
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->print();
brows->getWindow(8);
brows->getWindow(8);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->getWindow(4);
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->getWindow(6);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(8);
delete brows;
}
	return 0;
}