#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("jj", "yy","bbb");
Tab B = Tab("gg", "rr","f");
Tab C = Tab("rrr", "uu","hhh");
Tab D = Tab("d", "g","aaa");
Tab E = Tab("zz", "ii","zzz");
Tab F = Tab("j", "qqq","d");
Tab G = Tab("ll", "iii","uuu");
Tab H = Tab("tt", "j","pp");
Tab I = Tab("g", "ll","xxx");
Tab J = Tab("eee", "x","pp");
Tab K = Tab("i", "mmm","h");
Tab L = Tab("oo", "ff","yyy");
Tab M = Tab("n", "sss","ooo");
Tab N = Tab("kkk", "g","zz");
Tab O = Tab("x", "sss","lll");
Tab P = Tab("jj", "yy","q");
Tab Q = Tab("m", "ddd","ee");
Tab R = Tab("rr", "zz","lll");
Tab S = Tab("g", "jj","cc");
Tab T = Tab("kkk", "w","yyy");
Tab U = Tab("z", "ee","zz");
Tab V = Tab("vvv", "n","r");
Tab W = Tab("c", "ggg","kkk");
Tab X = Tab("iii", "ee","p");
Tab Y = Tab("j", "r","y");
Tab Z = Tab("sss", "nnn","mmm");
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(A);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(B);
d.newTab(C);
a.newTab(D);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(5);
b.newTab(E);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.newTab(F);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(5);
b.newTab(G);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(H);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(I);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(J);
b.moveActiveTabTo(4);
c.newTab(K);
d.newTab(L);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(M);
d.newTab(N);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.newTab(O);
d.newTab(P);
a.moveActiveTabTo(1);
b.newTab(Q);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(2);
b.newTab(R);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(S);
b.newTab(T);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.newTab(U);
b.changeActiveTabTo(4);
c.newTab(V);
d.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.newTab(W);
c.newTab(X);
d.moveActiveTabTo(4);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
b.newTab(Y);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.newTab(Z);
d.changeActiveTabTo(1);
a.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
c.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
d.changeActiveTabTo(1);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(5);
d.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
c.changeActiveTabTo(4);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(1);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->print();
brows->getWindow(1);
brows->print();
brows->getWindow(8);
brows->print();
brows->print();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->getWindow(9);
brows->getWindow(7);
brows->getWindow(5);
brows->getWindow(5);
brows->switchToWindow(4);
brows->print();
brows->newWindow();
brows->print();
brows->getWindow(4);
brows->getWindow(6);
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->getWindow(4);
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->getWindow(0);
brows->switchToWindow(1);
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(0);
brows->switchToWindow(8);
brows->getWindow(3);
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->switchToWindow(5);
brows->getWindow(9);
brows->getWindow(3);
brows->switchToWindow(7);
brows->switchToWindow(5);
brows->newWindow();
brows->getWindow(7);
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(2);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(2);
brows->closeWindow();
brows->newWindow();
brows->getWindow(4);
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(6);
brows->getWindow(8);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->newWindow();
brows->newWindow();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->newWindow();
brows->newWindow();
brows->getWindow(6);
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(5);
delete brows;
}
	return 0;
}