#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("ccc", "ii","eee");
Tab B = Tab("x", "jj","u");
Tab C = Tab("xxx", "ttt","uu");
Tab D = Tab("nnn", "e","sss");
Tab E = Tab("a", "a","lll");
Tab F = Tab("f", "h","m");
Tab G = Tab("gg", "vv","fff");
Tab H = Tab("i", "j","iii");
Tab I = Tab("ggg", "gg","ooo");
Tab J = Tab("xxx", "tt","ppp");
Tab K = Tab("ff", "r","bb");
Tab L = Tab("xx", "eee","sss");
Tab M = Tab("bb", "rr","ddd");
Tab N = Tab("z", "ttt","o");
Tab O = Tab("pp", "u","ff");
Tab P = Tab("t", "kkk","qq");
Tab Q = Tab("uuu", "m","fff");
Tab R = Tab("yy", "yy","p");
Tab S = Tab("qq", "vvv","kk");
Tab T = Tab("o", "tt","g");
Tab U = Tab("jj", "oo","m");
Tab V = Tab("p", "bbb","gg");
Tab W = Tab("a", "jjj","gg");
Tab X = Tab("ss", "a","xx");
Tab Y = Tab("e", "dd","vv");
Tab Z = Tab("n", "r","lll");
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(A);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(B);
d.newTab(C);
a.moveActiveTabTo(5);
b.newTab(D);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(5);
b.newTab(E);
c.changeActiveTabTo(5);
d.newTab(F);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(G);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.newTab(H);
d.changeActiveTabTo(1);
a.changeActiveTabTo(1);
b.newTab(I);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(J);
b.changeActiveTabTo(1);
c.newTab(K);
d.changeActiveTabTo(1);
a.moveActiveTabTo(0);
b.newTab(L);
c.newTab(M);
d.newTab(N);
a.newTab(O);
b.newTab(P);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(Q);
b.changeActiveTabTo(2);
c.newTab(R);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
b.newTab(S);
c.newTab(T);
d.moveActiveTabTo(3);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(U);
d.changeActiveTabTo(0);
a.newTab(V);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(W);
b.changeActiveTabTo(1);
c.newTab(X);
d.newTab(Y);
a.newTab(Z);
b.newTab(Z);
c.moveActiveTabTo(5);
d.newTab(Z);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
c.changeActiveTabTo(1);
a.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
d.moveActiveTabTo(2);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
c.changeActiveTabTo(3);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->print();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->switchToWindow(0);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->switchToWindow(7);
brows->newWindow();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->newWindow();
brows->getWindow(2);
brows->switchToWindow(5);
brows->switchToWindow(7);
brows->getWindow(7);
brows->print();
brows->switchToWindow(3);
brows->print();
brows->getWindow(7);
brows->getWindow(2);
brows->getWindow(5);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->getWindow(9);
brows->newWindow();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->getWindow(2);
brows->switchToWindow(3);
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->closeWindow();
brows->getWindow(1);
brows->switchToWindow(9);
brows->getWindow(7);
brows->switchToWindow(7);
brows->print();
brows->getWindow(5);
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(8);
brows->newWindow();
brows->getWindow(4);
brows->getWindow(6);
brows->getWindow(4);
brows->getWindow(7);
brows->switchToWindow(7);
brows->getWindow(9);
brows->closeEmptyWindows();
brows->getWindow(3);
brows->newWindow();
brows->newWindow();
brows->switchToWindow(4);
brows->switchToWindow(6);
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->getWindow(9);
brows->print();
brows->print();
brows->newWindow();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(4);
brows->getWindow(5);
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->getWindow(1);
brows->switchToWindow(3);
brows->print();
brows->getWindow(9);
brows->print();
brows->getWindow(2);
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->getWindow(9);
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->switchToWindow(9);
brows->getWindow(3);
brows->newWindow();
brows->closeWindow();
delete brows;
}
	return 0;
}