#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("j", "dd","mmm");
Tab B = Tab("g", "eee","ddd");
Tab C = Tab("tt", "ddd","bbb");
Tab D = Tab("ppp", "jjj","y");
Tab E = Tab("xx", "s","e");
Tab F = Tab("k", "bbb","jjj");
Tab G = Tab("lll", "vvv","q");
Tab H = Tab("y", "g","f");
Tab I = Tab("eee", "ii","bb");
Tab J = Tab("www", "uuu","r");
Tab K = Tab("v", "ss","a");
Tab L = Tab("q", "nnn","oo");
Tab M = Tab("rrr", "yyy","h");
Tab N = Tab("cc", "c","l");
Tab O = Tab("lll", "w","e");
Tab P = Tab("ll", "cc","ttt");
Tab Q = Tab("pp", "o","aa");
Tab R = Tab("tt", "ww","rr");
Tab S = Tab("ss", "gg","aaa");
Tab T = Tab("rr", "p","ooo");
Tab U = Tab("zz", "vv","uuu");
Tab V = Tab("aa", "tt","ss");
Tab W = Tab("bbb", "w","o");
Tab X = Tab("ddd", "mmm","e");
Tab Y = Tab("qqq", "ooo","eee");
Tab Z = Tab("u", "eee","qq");
a.moveActiveTabTo(3);
b.newTab(A);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.newTab(B);
a.newTab(C);
b.newTab(D);
c.newTab(E);
d.moveActiveTabTo(3);
a.newTab(F);
b.moveActiveTabTo(1);
c.newTab(G);
d.newTab(H);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(I);
b.moveActiveTabTo(3);
c.newTab(J);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(K);
d.changeActiveTabTo(0);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(L);
d.changeActiveTabTo(5);
a.changeActiveTabTo(5);
b.newTab(M);
c.newTab(N);
d.newTab(O);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(P);
a.changeActiveTabTo(3);
b.newTab(Q);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(R);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(S);
d.changeActiveTabTo(4);
a.moveActiveTabTo(2);
b.newTab(T);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(0);
b.newTab(U);
c.changeActiveTabTo(0);
d.newTab(V);
a.newTab(W);
b.newTab(X);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(Y);
d.newTab(Z);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
d.changeActiveTabTo(4);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
c.moveActiveTabTo(5);
a.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
d.moveActiveTabTo(0);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->getWindow(2);
brows->newWindow();
brows->switchToWindow(7);
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(7);
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->getWindow(8);
brows->getWindow(3);
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(7);
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->switchToWindow(7);
brows->closeWindow();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(7);
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->closeWindow();
brows->getWindow(5);
brows->closeWindow();
brows->closeWindow();
brows->getWindow(4);
brows->switchToWindow(3);
brows->switchToWindow(9);
brows->getWindow(9);
brows->newWindow();
brows->switchToWindow(8);
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(5);
brows->getWindow(4);
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->getWindow(0);
brows->getWindow(7);
brows->print();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(2);
brows->switchToWindow(9);
brows->getWindow(5);
brows->getWindow(2);
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(1);
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(1);
brows->closeEmptyWindows();
brows->getWindow(0);
brows->closeWindow();
brows->switchToWindow(6);
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(6);
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
delete brows;
}
	return 0;
}