#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("vv", "uu","k");
Tab B = Tab("yy", "b","mmm");
Tab C = Tab("dd", "l","uuu");
Tab D = Tab("ii", "i","ww");
Tab E = Tab("r", "d","r");
Tab F = Tab("ll", "hh","zzz");
Tab G = Tab("w", "ppp","rrr");
Tab H = Tab("ss", "ss","oo");
Tab I = Tab("v", "m","a");
Tab J = Tab("v", "m","cc");
Tab K = Tab("pp", "t","cc");
Tab L = Tab("a", "y","oo");
Tab M = Tab("www", "q","j");
Tab N = Tab("x", "ooo","dd");
Tab O = Tab("kkk", "zz","ggg");
Tab P = Tab("ttt", "ii","u");
Tab Q = Tab("ooo", "k","ll");
Tab R = Tab("ff", "cc","t");
Tab S = Tab("bbb", "rr","nnn");
Tab T = Tab("yyy", "ff","ee");
Tab U = Tab("nnn", "hhh","kk");
Tab V = Tab("uuu", "j","dd");
Tab W = Tab("qqq", "qq","e");
Tab X = Tab("ii", "ttt","i");
Tab Y = Tab("w", "vvv","q");
Tab Z = Tab("xxx", "ddd","c");
a.newTab(A);
b.newTab(B);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.newTab(C);
c.newTab(D);
d.newTab(E);
a.changeActiveTabTo(0);
b.newTab(F);
c.changeActiveTabTo(0);
d.newTab(G);
a.moveActiveTabTo(5);
b.newTab(H);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(I);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(J);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.newTab(K);
d.moveActiveTabTo(2);
a.moveActiveTabTo(5);
b.newTab(L);
c.newTab(M);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(N);
a.moveActiveTabTo(0);
b.newTab(O);
c.moveActiveTabTo(0);
d.newTab(P);
a.newTab(Q);
b.newTab(R);
c.moveActiveTabTo(5);
d.newTab(S);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(5);
b.newTab(T);
c.newTab(U);
d.newTab(V);
a.moveActiveTabTo(3);
b.newTab(W);
c.moveActiveTabTo(3);
d.newTab(X);
a.newTab(Y);
b.newTab(Z);
c.moveActiveTabTo(1);
d.newTab(Z);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
d.changeActiveTabTo(5);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
c.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
c.changeActiveTabTo(1);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(1);
a.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
d.moveActiveTabTo(0);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(5);
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->switchToWindow(6);
brows->print();
brows->switchToWindow(6);
brows->getWindow(8);
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->getWindow(8);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->getWindow(4);
brows->closeWindow();
brows->getWindow(2);
brows->switchToWindow(0);
brows->getWindow(8);
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(2);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->newWindow();
brows->switchToWindow(9);
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->getWindow(8);
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->switchToWindow(7);
brows->getWindow(4);
brows->switchToWindow(0);
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(2);
brows->closeEmptyWindows();
brows->getWindow(5);
brows->print();
brows->newWindow();
brows->getWindow(0);
brows->newWindow();
brows->getWindow(2);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->getWindow(7);
brows->getWindow(2);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(0);
brows->print();
brows->print();
brows->switchToWindow(0);
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->getWindow(4);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
delete brows;
}
	return 0;
}