#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("qq", "yy","z");
Tab B = Tab("aaa", "eee","ddd");
Tab C = Tab("uu", "hhh","g");
Tab D = Tab("jjj", "cc","nn");
Tab E = Tab("iii", "kk","kk");
Tab F = Tab("dd", "kkk","mm");
Tab G = Tab("aa", "uu","g");
Tab H = Tab("b", "iii","ee");
Tab I = Tab("xxx", "mm","cc");
Tab J = Tab("jj", "ss","rrr");
Tab K = Tab("m", "mm","o");
Tab L = Tab("qqq", "www","www");
Tab M = Tab("kkk", "u","nnn");
Tab N = Tab("e", "h","ooo");
Tab O = Tab("aa", "ff","xxx");
Tab P = Tab("gg", "gg","p");
Tab Q = Tab("xxx", "ll","a");
Tab R = Tab("r", "o","dd");
Tab S = Tab("nnn", "i","p");
Tab T = Tab("z", "aaa","kkk");
Tab U = Tab("aa", "jjj","a");
Tab V = Tab("b", "ttt","w");
Tab W = Tab("b", "uu","ggg");
Tab X = Tab("zz", "www","uuu");
Tab Y = Tab("n", "rrr","nn");
Tab Z = Tab("vv", "ccc","u");
a.changeActiveTabTo(2);
b.newTab(A);
c.moveActiveTabTo(2);
d.newTab(B);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.newTab(C);
c.changeActiveTabTo(5);
d.newTab(D);
a.changeActiveTabTo(3);
b.newTab(E);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(F);
b.moveActiveTabTo(4);
c.newTab(G);
d.moveActiveTabTo(4);
a.moveActiveTabTo(4);
b.newTab(H);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.newTab(I);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(5);
b.newTab(J);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(K);
b.newTab(L);
c.moveActiveTabTo(3);
d.newTab(M);
a.moveActiveTabTo(1);
b.newTab(N);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(O);
d.changeActiveTabTo(3);
a.newTab(P);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(Q);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.newTab(R);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(S);
b.newTab(T);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(U);
b.newTab(V);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(W);
a.newTab(X);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(Y);
b.newTab(Z);
c.newTab(Z);
d.moveActiveTabTo(2);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
c.moveActiveTabTo(2);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
a.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
d.moveActiveTabTo(4);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
d.changeActiveTabTo(3);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
d.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
d.moveActiveTabTo(5);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(9);
brows->getWindow(4);
brows->switchToWindow(3);
brows->newWindow();
brows->print();
brows->print();
brows->getWindow(4);
brows->closeEmptyWindows();
brows->getWindow(8);
brows->getWindow(4);
brows->closeWindow();
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->getWindow(3);
brows->print();
brows->closeWindow();
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(9);
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->print();
brows->getWindow(5);
brows->print();
brows->closeWindow();
brows->switchToWindow(8);
brows->getWindow(2);
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->closeWindow();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(6);
brows->getWindow(7);
brows->closeWindow();
brows->getWindow(6);
brows->newWindow();
brows->switchToWindow(2);
brows->newWindow();
brows->closeWindow();
brows->print();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->getWindow(3);
brows->getWindow(9);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(8);
brows->getWindow(6);
brows->getWindow(9);
brows->switchToWindow(3);
brows->switchToWindow(1);
brows->print();
brows->switchToWindow(3);
brows->newWindow();
brows->switchToWindow(6);
brows->closeWindow();
brows->getWindow(0);
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->getWindow(3);
brows->getWindow(0);
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(9);
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(9);
brows->closeWindow();
brows->newWindow();
brows->getWindow(9);
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->switchToWindow(3);
delete brows;
}
	return 0;
}