#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("o", "mm","ww");
Tab B = Tab("j", "a","jjj");
Tab C = Tab("zz", "sss","j");
Tab D = Tab("fff", "xxx","mmm");
Tab E = Tab("xx", "kkk","c");
Tab F = Tab("vvv", "rr","v");
Tab G = Tab("mmm", "jjj","jjj");
Tab H = Tab("ww", "hhh","ii");
Tab I = Tab("nn", "u","xxx");
Tab J = Tab("jjj", "ggg","kk");
Tab K = Tab("tt", "uuu","zzz");
Tab L = Tab("pp", "z","s");
Tab M = Tab("o", "nnn","yy");
Tab N = Tab("m", "m","xx");
Tab O = Tab("iii", "gg","ff");
Tab P = Tab("k", "gg","ppp");
Tab Q = Tab("ff", "ff","zzz");
Tab R = Tab("rr", "jj","r");
Tab S = Tab("y", "p","b");
Tab T = Tab("mmm", "sss","ddd");
Tab U = Tab("ww", "yy","ooo");
Tab V = Tab("xx", "m","qq");
Tab W = Tab("aa", "iii","eee");
Tab X = Tab("g", "w","iii");
Tab Y = Tab("l", "t","ww");
Tab Z = Tab("xxx", "nnn","ii");
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(4);
b.newTab(A);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(B);
b.newTab(C);
c.newTab(D);
d.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(E);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(F);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(G);
a.moveActiveTabTo(3);
b.newTab(H);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.newTab(I);
d.changeActiveTabTo(2);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
b.newTab(J);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(K);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(L);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.newTab(M);
d.newTab(N);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(O);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(P);
d.moveActiveTabTo(5);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(Q);
d.changeActiveTabTo(5);
a.moveActiveTabTo(1);
b.newTab(R);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(S);
a.newTab(T);
b.newTab(U);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(V);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(W);
d.newTab(X);
a.newTab(Y);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(Z);
b.newTab(Z);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.changeActiveTabTo(0);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(2);
a.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
a.changeActiveTabTo(5);
d.changeActiveTabTo(5);
c.moveActiveTabTo(2);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeWindow();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(4);
brows->getWindow(2);
brows->closeWindow();
brows->print();
brows->getWindow(4);
brows->mergeAllWindows();
brows->getWindow(2);
brows->getWindow(7);
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(8);
brows->closeWindow();
brows->getWindow(1);
brows->newWindow();
brows->getWindow(0);
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(7);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(7);
brows->newWindow();
brows->closeWindow();
brows->getWindow(9);
brows->newWindow();
brows->getWindow(4);
brows->closeWindow();
brows->getWindow(2);
brows->newWindow();
brows->closeWindow();
brows->getWindow(6);
brows->print();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->print();
brows->getWindow(2);
brows->mergeAllWindows();
brows->getWindow(0);
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(9);
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->getWindow(0);
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->print();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->getWindow(5);
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(6);
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
delete brows;
}
	return 0;
}