#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("rr", "s","kk");
Tab B = Tab("rr", "q","vvv");
Tab C = Tab("jjj", "ddd","jjj");
Tab D = Tab("ttt", "fff","ccc");
Tab E = Tab("u", "l","uuu");
Tab F = Tab("tt", "ff","kkk");
Tab G = Tab("j", "oo","eee");
Tab H = Tab("hhh", "aa","i");
Tab I = Tab("hhh", "mmm","ooo");
Tab J = Tab("l", "jjj","e");
Tab K = Tab("l", "hh","eee");
Tab L = Tab("e", "uu","jj");
Tab M = Tab("ccc", "nnn","vv");
Tab N = Tab("p", "l","hh");
Tab O = Tab("b", "aa","qq");
Tab P = Tab("v", "yyy","x");
Tab Q = Tab("lll", "z","v");
Tab R = Tab("y", "bb","iii");
Tab S = Tab("ww", "b","q");
Tab T = Tab("jj", "uu","x");
Tab U = Tab("oo", "ddd","ttt");
Tab V = Tab("e", "b","q");
Tab W = Tab("s", "ddd","sss");
Tab X = Tab("b", "g","sss");
Tab Y = Tab("kkk", "ii","rrr");
Tab Z = Tab("vvv", "w","xxx");
a.newTab(A);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(B);
b.newTab(C);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(4);
b.newTab(D);
c.changeActiveTabTo(4);
d.newTab(E);
a.moveActiveTabTo(0);
b.newTab(F);
c.changeActiveTabTo(0);
d.newTab(G);
a.changeActiveTabTo(3);
b.newTab(H);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(I);
b.changeActiveTabTo(2);
c.newTab(J);
d.changeActiveTabTo(2);
a.moveActiveTabTo(1);
b.newTab(K);
c.newTab(L);
d.newTab(M);
a.newTab(N);
b.moveActiveTabTo(1);
c.newTab(O);
d.moveActiveTabTo(1);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(P);
a.moveActiveTabTo(2);
b.newTab(Q);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(R);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.newTab(S);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(1);
b.newTab(T);
c.moveActiveTabTo(1);
d.newTab(U);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.newTab(V);
d.newTab(W);
a.newTab(X);
b.changeActiveTabTo(2);
c.newTab(Y);
d.newTab(Z);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
a.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
a.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(0);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(5);
d.moveActiveTabTo(5);
d.changeActiveTabTo(4);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->getWindow(8);
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->newWindow();
brows->getWindow(3);
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(6);
brows->switchToWindow(1);
brows->switchToWindow(6);
brows->getWindow(4);
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->getWindow(8);
brows->print();
brows->getWindow(8);
brows->getWindow(8);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(3);
brows->closeWindow();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->print();
brows->print();
brows->switchToWindow(4);
brows->getWindow(6);
brows->mergeAllWindows();
brows->print();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->switchToWindow(8);
brows->print();
brows->print();
brows->newWindow();
brows->print();
brows->print();
brows->switchToWindow(3);
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(6);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->getWindow(4);
brows->closeEmptyWindows();
brows->getWindow(5);
brows->newWindow();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(3);
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(1);
brows->closeWindow();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(7);
delete brows;
}
	return 0;
}