#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("ww", "x","u");
Tab B = Tab("d", "ee","h");
Tab C = Tab("ss", "y","y");
Tab D = Tab("t", "sss","zz");
Tab E = Tab("ccc", "m","eee");
Tab F = Tab("vv", "xx","vvv");
Tab G = Tab("bb", "eee","yyy");
Tab H = Tab("lll", "sss","xx");
Tab I = Tab("y", "y","mm");
Tab J = Tab("ccc", "f","j");
Tab K = Tab("zz", "k","oo");
Tab L = Tab("tt", "s","ppp");
Tab M = Tab("mmm", "f","a");
Tab N = Tab("ccc", "qqq","mm");
Tab O = Tab("yyy", "www","z");
Tab P = Tab("sss", "m","b");
Tab Q = Tab("hhh", "ooo","ee");
Tab R = Tab("a", "aaa","ggg");
Tab S = Tab("aaa", "ggg","xx");
Tab T = Tab("iii", "cc","t");
Tab U = Tab("z", "z","rr");
Tab V = Tab("mmm", "cc","jj");
Tab W = Tab("iii", "www","c");
Tab X = Tab("nn", "z","jjj");
Tab Y = Tab("uuu", "t","eee");
Tab Z = Tab("ccc", "lll","zzz");
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(A);
d.newTab(B);
a.moveActiveTabTo(1);
b.newTab(C);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(D);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
b.newTab(E);
c.newTab(F);
d.newTab(G);
a.changeActiveTabTo(0);
b.newTab(H);
c.newTab(I);
d.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(J);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(K);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(L);
b.newTab(M);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(N);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(3);
b.newTab(O);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(P);
b.newTab(Q);
c.moveActiveTabTo(2);
d.newTab(R);
a.newTab(S);
b.moveActiveTabTo(0);
c.newTab(T);
d.changeActiveTabTo(0);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.newTab(U);
d.changeActiveTabTo(2);
a.newTab(V);
b.changeActiveTabTo(3);
c.newTab(W);
d.changeActiveTabTo(3);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(X);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(Y);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.newTab(Z);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(Z);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
c.moveActiveTabTo(5);
a.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
c.moveActiveTabTo(4);
a.moveActiveTabTo(2);
c.moveActiveTabTo(2);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->print();
brows->getWindow(5);
brows->mergeAllWindows();
brows->getWindow(5);
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->getWindow(2);
brows->switchToWindow(9);
brows->print();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->getWindow(2);
brows->closeEmptyWindows();
brows->print();
brows->getWindow(8);
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(9);
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->closeWindow();
brows->switchToWindow(3);
brows->newWindow();
brows->newWindow();
brows->switchToWindow(7);
brows->getWindow(1);
brows->getWindow(6);
brows->closeWindow();
brows->print();
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->getWindow(9);
brows->switchToWindow(5);
brows->closeWindow();
brows->print();
brows->switchToWindow(4);
brows->switchToWindow(9);
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->switchToWindow(3);
brows->print();
brows->getWindow(0);
brows->print();
brows->closeWindow();
brows->switchToWindow(8);
brows->print();
brows->closeEmptyWindows();
brows->getWindow(4);
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(3);
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->getWindow(7);
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->closeWindow();
brows->getWindow(5);
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(9);
brows->switchToWindow(3);
brows->switchToWindow(8);
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->getWindow(8);
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->getWindow(5);
delete brows;
}
	return 0;
}