#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("d", "hh","ww");
Tab B = Tab("qq", "gg","bbb");
Tab C = Tab("ww", "jjj","ccc");
Tab D = Tab("uu", "ggg","cc");
Tab E = Tab("u", "kk","www");
Tab F = Tab("a", "pp","mmm");
Tab G = Tab("d", "y","l");
Tab H = Tab("y", "z","ff");
Tab I = Tab("l", "tt","uuu");
Tab J = Tab("tt", "lll","v");
Tab K = Tab("vv", "rrr","ll");
Tab L = Tab("rrr", "zz","n");
Tab M = Tab("eee", "b","ttt");
Tab N = Tab("bbb", "zzz","vv");
Tab O = Tab("v", "r","rrr");
Tab P = Tab("ccc", "m","oo");
Tab Q = Tab("uu", "d","p");
Tab R = Tab("yy", "nn","rr");
Tab S = Tab("bb", "u","dd");
Tab T = Tab("vvv", "n","ll");
Tab U = Tab("c", "ggg","pp");
Tab V = Tab("qqq", "bb","p");
Tab W = Tab("vv", "d","ll");
Tab X = Tab("tt", "pp","ooo");
Tab Y = Tab("mm", "ggg","q");
Tab Z = Tab("vvv", "h","xx");
a.moveActiveTabTo(3);
b.newTab(A);
c.changeActiveTabTo(3);
d.newTab(B);
a.moveActiveTabTo(5);
b.newTab(C);
c.newTab(D);
d.moveActiveTabTo(5);
a.newTab(E);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(F);
b.newTab(G);
c.newTab(H);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.newTab(I);
b.newTab(J);
c.moveActiveTabTo(2);
d.newTab(K);
a.changeActiveTabTo(5);
b.newTab(L);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(M);
b.changeActiveTabTo(5);
c.newTab(N);
d.moveActiveTabTo(5);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(O);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(P);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.newTab(Q);
b.changeActiveTabTo(2);
c.newTab(R);
d.newTab(S);
a.moveActiveTabTo(4);
b.newTab(T);
c.newTab(U);
d.newTab(V);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(W);
a.newTab(X);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(2);
b.newTab(Y);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(3);
b.newTab(Z);
c.changeActiveTabTo(3);
d.newTab(Z);
b.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
d.changeActiveTabTo(0);
c.moveActiveTabTo(2);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
d.moveActiveTabTo(1);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
a.moveActiveTabTo(2);
a.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(3);
c.changeActiveTabTo(3);
a.moveActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
c.changeActiveTabTo(2);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->getWindow(7);
brows->getWindow(5);
brows->closeWindow();
brows->closeWindow();
brows->getWindow(9);
brows->switchToWindow(5);
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->getWindow(8);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(7);
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(7);
brows->getWindow(7);
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->switchToWindow(9);
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(9);
brows->getWindow(1);
brows->print();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(4);
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->getWindow(8);
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->getWindow(0);
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(6);
brows->newWindow();
brows->getWindow(0);
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->switchToWindow(1);
brows->print();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(2);
brows->closeEmptyWindows();
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->print();
delete brows;
}
	return 0;
}