#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("ff", "l","ddd");
Tab B = Tab("nn", "ii","q");
Tab C = Tab("uuu", "yyy","mmm");
Tab D = Tab("ff", "aa","w");
Tab E = Tab("kk", "jjj","xxx");
Tab F = Tab("y", "uu","vv");
Tab G = Tab("uuu", "i","b");
Tab H = Tab("uuu", "yyy","ooo");
Tab I = Tab("ff", "ddd","ll");
Tab J = Tab("uu", "mmm","kkk");
Tab K = Tab("zzz", "s","ss");
Tab L = Tab("ll", "hh","pp");
Tab M = Tab("gg", "ooo","hhh");
Tab N = Tab("nn", "aa","g");
Tab O = Tab("g", "kk","y");
Tab P = Tab("eee", "ggg","ddd");
Tab Q = Tab("c", "vvv","aa");
Tab R = Tab("uu", "f","jjj");
Tab S = Tab("h", "u","ww");
Tab T = Tab("jjj", "ppp","j");
Tab U = Tab("xxx", "cc","mmm");
Tab V = Tab("sss", "l","nn");
Tab W = Tab("pp", "iii","c");
Tab X = Tab("aaa", "rrr","xxx");
Tab Y = Tab("ggg", "kkk","j");
Tab Z = Tab("p", "qq","x");
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(A);
d.moveActiveTabTo(4);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(0);
b.newTab(B);
c.changeActiveTabTo(0);
d.newTab(C);
a.newTab(D);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(E);
b.changeActiveTabTo(4);
c.newTab(F);
d.changeActiveTabTo(4);
a.changeActiveTabTo(2);
b.newTab(G);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(H);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(5);
b.newTab(I);
c.newTab(J);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.newTab(K);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(L);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(5);
b.newTab(M);
c.newTab(N);
d.moveActiveTabTo(5);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(O);
d.changeActiveTabTo(0);
a.newTab(P);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(Q);
a.moveActiveTabTo(1);
b.newTab(R);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(S);
d.changeActiveTabTo(0);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(T);
d.moveActiveTabTo(0);
a.newTab(U);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(V);
a.newTab(W);
b.changeActiveTabTo(1);
c.newTab(X);
d.newTab(Y);
a.moveActiveTabTo(0);
b.newTab(Z);
c.newTab(Z);
d.changeActiveTabTo(0);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
d.changeActiveTabTo(0);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
d.moveActiveTabTo(2);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
a.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(1);
c.moveActiveTabTo(1);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(2);
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(6);
brows->closeWindow();
brows->switchToWindow(3);
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(9);
brows->switchToWindow(5);
brows->print();
brows->closeWindow();
brows->print();
brows->getWindow(5);
brows->print();
brows->switchToWindow(0);
brows->getWindow(1);
brows->getWindow(6);
brows->closeWindow();
brows->getWindow(3);
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->getWindow(2);
brows->print();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->getWindow(5);
brows->print();
brows->switchToWindow(0);
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->getWindow(4);
brows->print();
brows->closeWindow();
brows->newWindow();
brows->getWindow(0);
brows->print();
brows->switchToWindow(4);
brows->switchToWindow(7);
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(7);
brows->getWindow(3);
brows->print();
brows->newWindow();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->switchToWindow(4);
brows->getWindow(0);
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(8);
brows->newWindow();
brows->getWindow(6);
brows->closeWindow();
brows->newWindow();
brows->print();
brows->getWindow(0);
brows->getWindow(4);
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(3);
brows->print();
brows->getWindow(7);
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->newWindow();
brows->getWindow(3);
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
delete brows;
}
	return 0;
}