#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("gg", "c","nnn");
Tab B = Tab("z", "uu","oo");
Tab C = Tab("zzz", "rr","uuu");
Tab D = Tab("pp", "o","vv");
Tab E = Tab("hh", "lll","fff");
Tab F = Tab("v", "yy","s");
Tab G = Tab("ooo", "aa","hh");
Tab H = Tab("sss", "vvv","mmm");
Tab I = Tab("tt", "ss","t");
Tab J = Tab("w", "ddd","z");
Tab K = Tab("ww", "hhh","sss");
Tab L = Tab("a", "eee","qq");
Tab M = Tab("h", "c","k");
Tab N = Tab("iii", "q","ttt");
Tab O = Tab("fff", "hh","jj");
Tab P = Tab("jjj", "vv","jj");
Tab Q = Tab("fff", "gg","r");
Tab R = Tab("a", "r","p");
Tab S = Tab("gg", "g","oo");
Tab T = Tab("qqq", "c","vv");
Tab U = Tab("zzz", "ddd","jj");
Tab V = Tab("jj", "mm","oo");
Tab W = Tab("xx", "mm","s");
Tab X = Tab("ppp", "zz","ll");
Tab Y = Tab("b", "pp","mmm");
Tab Z = Tab("c", "nnn","ll");
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(A);
b.moveActiveTabTo(0);
c.newTab(B);
d.changeActiveTabTo(0);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(C);
d.newTab(D);
a.newTab(E);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(F);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(G);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(H);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(2);
b.newTab(I);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(J);
b.newTab(K);
c.moveActiveTabTo(4);
d.newTab(L);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(M);
d.newTab(N);
a.newTab(O);
b.newTab(P);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(5);
b.newTab(Q);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(5);
b.newTab(R);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(S);
b.moveActiveTabTo(0);
c.newTab(T);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(U);
a.newTab(V);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(W);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(X);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.newTab(Y);
d.newTab(Z);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
c.changeActiveTabTo(0);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
a.moveActiveTabTo(2);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
d.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(2);
brows->getWindow(8);
brows->getWindow(5);
brows->switchToWindow(7);
brows->switchToWindow(1);
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->getWindow(6);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(5);
brows->getWindow(3);
brows->newWindow();
brows->closeWindow();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(4);
brows->newWindow();
brows->closeWindow();
brows->getWindow(6);
brows->getWindow(7);
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(7);
brows->print();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->getWindow(0);
brows->getWindow(4);
brows->mergeAllWindows();
brows->getWindow(3);
brows->closeWindow();
brows->switchToWindow(5);
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(8);
brows->newWindow();
brows->switchToWindow(5);
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(5);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->print();
brows->switchToWindow(0);
brows->getWindow(8);
brows->print();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->closeWindow();
brows->getWindow(0);
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(4);
brows->closeEmptyWindows();
delete brows;
}
	return 0;
}