#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("fff", "uu","mm");
Tab B = Tab("tt", "ww","q");
Tab C = Tab("d", "aa","uuu");
Tab D = Tab("xxx", "nnn","uu");
Tab E = Tab("ooo", "kk","ggg");
Tab F = Tab("gg", "xx","fff");
Tab G = Tab("iii", "pp","q");
Tab H = Tab("eee", "ss","g");
Tab I = Tab("ee", "ooo","ii");
Tab J = Tab("fff", "ccc","kkk");
Tab K = Tab("ggg", "oo","kk");
Tab L = Tab("bb", "z","eee");
Tab M = Tab("jj", "xxx","vv");
Tab N = Tab("nnn", "jj","pp");
Tab O = Tab("uu", "d","nn");
Tab P = Tab("vvv", "w","ggg");
Tab Q = Tab("gg", "e","v");
Tab R = Tab("ccc", "aaa","ii");
Tab S = Tab("mmm", "g","ii");
Tab T = Tab("r", "o","m");
Tab U = Tab("x", "xxx","w");
Tab V = Tab("ww", "d","x");
Tab W = Tab("r", "jjj","bb");
Tab X = Tab("rrr", "z","qq");
Tab Y = Tab("qq", "ooo","lll");
Tab Z = Tab("uuu", "ii","p");
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.newTab(A);
d.moveActiveTabTo(1);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.newTab(B);
a.newTab(C);
b.newTab(D);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(1);
b.newTab(E);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(F);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(G);
a.newTab(H);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(I);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(J);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.newTab(K);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(L);
d.newTab(M);
a.newTab(N);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(0);
b.newTab(O);
c.newTab(P);
d.newTab(Q);
a.newTab(R);
b.changeActiveTabTo(0);
c.newTab(S);
d.newTab(T);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(U);
d.changeActiveTabTo(4);
a.newTab(V);
b.newTab(W);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.newTab(X);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(Y);
d.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(Z);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
a.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
a.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(5);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
a.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
d.changeActiveTabTo(1);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(3);
c.changeActiveTabTo(3);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->switchToWindow(3);
brows->newWindow();
brows->getWindow(7);
brows->getWindow(9);
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(4);
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->switchToWindow(4);
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->switchToWindow(0);
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(6);
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->switchToWindow(1);
brows->getWindow(4);
brows->getWindow(2);
brows->switchToWindow(6);
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->getWindow(3);
brows->print();
brows->newWindow();
brows->newWindow();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->getWindow(1);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(7);
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->getWindow(2);
brows->closeWindow();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->getWindow(1);
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(5);
brows->getWindow(8);
brows->switchToWindow(9);
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
delete brows;
}
	return 0;
}