#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("u", "b","aa");
Tab B = Tab("gg", "k","n");
Tab C = Tab("pp", "aaa","lll");
Tab D = Tab("jjj", "fff","ttt");
Tab E = Tab("ppp", "m","iii");
Tab F = Tab("g", "u","pp");
Tab G = Tab("iii", "o","cc");
Tab H = Tab("ee", "q","q");
Tab I = Tab("l", "a","u");
Tab J = Tab("b", "f","ff");
Tab K = Tab("bb", "jjj","l");
Tab L = Tab("x", "c","oo");
Tab M = Tab("vv", "f","uuu");
Tab N = Tab("nn", "ggg","t");
Tab O = Tab("lll", "f","ooo");
Tab P = Tab("bbb", "gg","cc");
Tab Q = Tab("xxx", "kk","iii");
Tab R = Tab("uuu", "c","c");
Tab S = Tab("ww", "ooo","e");
Tab T = Tab("vvv", "ooo","bb");
Tab U = Tab("gg", "p","u");
Tab V = Tab("h", "kk","yyy");
Tab W = Tab("uu", "v","uu");
Tab X = Tab("b", "mmm","l");
Tab Y = Tab("rr", "mm","zzz");
Tab Z = Tab("lll", "ccc","k");
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(A);
d.newTab(B);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(C);
a.newTab(D);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(E);
a.newTab(F);
b.newTab(G);
c.newTab(H);
d.newTab(I);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(J);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(1);
b.newTab(K);
c.newTab(L);
d.moveActiveTabTo(1);
a.newTab(M);
b.moveActiveTabTo(3);
c.newTab(N);
d.changeActiveTabTo(3);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(2);
b.newTab(O);
c.newTab(P);
d.moveActiveTabTo(2);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(1);
b.newTab(Q);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
b.newTab(R);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(0);
b.newTab(S);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.newTab(T);
b.newTab(U);
c.newTab(V);
d.newTab(W);
a.newTab(X);
b.changeActiveTabTo(3);
c.newTab(Y);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(Z);
b.changeActiveTabTo(3);
c.newTab(Z);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
d.changeActiveTabTo(2);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
a.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(2);
d.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->mergeAllWindows();
brows->getWindow(0);
brows->getWindow(5);
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(5);
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(9);
brows->print();
brows->getWindow(0);
brows->switchToWindow(2);
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->switchToWindow(2);
brows->print();
brows->getWindow(4);
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(7);
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(3);
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->print();
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(3);
brows->switchToWindow(5);
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(6);
brows->print();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->switchToWindow(5);
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(9);
brows->getWindow(6);
brows->switchToWindow(9);
brows->switchToWindow(6);
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->getWindow(6);
brows->switchToWindow(0);
brows->print();
brows->closeWindow();
brows->switchToWindow(2);
brows->print();
brows->mergeAllWindows();
brows->getWindow(6);
brows->getWindow(9);
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(1);
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(1);
brows->getWindow(1);
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->getWindow(4);
brows->getWindow(4);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(1);
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->print();
brows->closeWindow();
delete brows;
}
	return 0;
}