#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("sss", "ttt","mm");
Tab B = Tab("x", "ll","l");
Tab C = Tab("dd", "www","f");
Tab D = Tab("i", "jj","qq");
Tab E = Tab("ccc", "oo","v");
Tab F = Tab("tt", "eee","ww");
Tab G = Tab("n", "j","ttt");
Tab H = Tab("d", "ttt","ee");
Tab I = Tab("yyy", "hh","gg");
Tab J = Tab("xx", "c","c");
Tab K = Tab("t", "p","sss");
Tab L = Tab("v", "ooo","eee");
Tab M = Tab("ww", "h","q");
Tab N = Tab("lll", "nn","oo");
Tab O = Tab("nn", "pp","ff");
Tab P = Tab("z", "k","f");
Tab Q = Tab("y", "vvv","hh");
Tab R = Tab("ttt", "bb","jj");
Tab S = Tab("x", "uuu","www");
Tab T = Tab("zz", "ll","x");
Tab U = Tab("ee", "gg","r");
Tab V = Tab("yyy", "bb","x");
Tab W = Tab("hhh", "uu","oo");
Tab X = Tab("e", "iii","v");
Tab Y = Tab("yyy", "rr","rr");
Tab Z = Tab("r", "k","h");
a.newTab(A);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(B);
b.newTab(C);
c.newTab(D);
d.changeActiveTabTo(5);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(E);
b.newTab(F);
c.newTab(G);
d.newTab(H);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(1);
b.newTab(I);
c.newTab(J);
d.moveActiveTabTo(1);
a.moveActiveTabTo(2);
b.newTab(K);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(L);
b.newTab(M);
c.newTab(N);
d.changeActiveTabTo(1);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(O);
a.newTab(P);
b.newTab(Q);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.newTab(R);
d.newTab(S);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(T);
d.changeActiveTabTo(3);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(U);
a.changeActiveTabTo(5);
b.newTab(V);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(W);
b.changeActiveTabTo(1);
c.newTab(X);
d.newTab(Y);
a.moveActiveTabTo(3);
b.newTab(Z);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
d.changeActiveTabTo(2);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(1);
c.changeActiveTabTo(1);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
a.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
c.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
b.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->getWindow(9);
brows->getWindow(0);
brows->print();
brows->switchToWindow(0);
brows->switchToWindow(1);
brows->print();
brows->newWindow();
brows->switchToWindow(2);
brows->getWindow(5);
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(1);
brows->newWindow();
brows->closeWindow();
brows->getWindow(0);
brows->getWindow(3);
brows->closeWindow();
brows->switchToWindow(4);
brows->getWindow(5);
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->getWindow(5);
brows->switchToWindow(6);
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(8);
brows->getWindow(5);
brows->getWindow(9);
brows->print();
brows->print();
brows->switchToWindow(3);
brows->closeWindow();
brows->switchToWindow(7);
brows->switchToWindow(2);
brows->print();
brows->getWindow(0);
brows->print();
brows->switchToWindow(6);
brows->getWindow(0);
brows->closeWindow();
brows->getWindow(4);
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(2);
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->closeWindow();
brows->switchToWindow(3);
brows->closeWindow();
brows->getWindow(3);
brows->print();
brows->switchToWindow(6);
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->switchToWindow(4);
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->getWindow(2);
brows->switchToWindow(2);
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(3);
brows->getWindow(4);
brows->switchToWindow(1);
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(6);
brows->getWindow(3);
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(6);
brows->print();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->getWindow(7);
brows->switchToWindow(1);
brows->getWindow(5);
brows->print();
brows->getWindow(8);
brows->getWindow(0);
brows->getWindow(0);
brows->print();
brows->getWindow(8);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
delete brows;
}
	return 0;
}