#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("sss", "g","z");
Tab B = Tab("ccc", "iii","pp");
Tab C = Tab("ee", "xxx","c");
Tab D = Tab("lll", "xxx","ff");
Tab E = Tab("mm", "f","aa");
Tab F = Tab("kk", "n","gg");
Tab G = Tab("p", "kk","ii");
Tab H = Tab("dd", "r","bbb");
Tab I = Tab("g", "u","uuu");
Tab J = Tab("zzz", "uuu","nn");
Tab K = Tab("jjj", "a","ddd");
Tab L = Tab("m", "m","j");
Tab M = Tab("ccc", "nn","eee");
Tab N = Tab("t", "q","iii");
Tab O = Tab("v", "dd","gg");
Tab P = Tab("gg", "yy","qq");
Tab Q = Tab("www", "hhh","k");
Tab R = Tab("rr", "p","xxx");
Tab S = Tab("ss", "sss","ee");
Tab T = Tab("yyy", "y","iii");
Tab U = Tab("rrr", "g","gg");
Tab V = Tab("xx", "xx","eee");
Tab W = Tab("ttt", "ii","zzz");
Tab X = Tab("l", "ppp","mmm");
Tab Y = Tab("ddd", "qqq","kk");
Tab Z = Tab("qqq", "e","ggg");
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(A);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(B);
d.moveActiveTabTo(4);
a.newTab(C);
b.changeActiveTabTo(2);
c.newTab(D);
d.changeActiveTabTo(2);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(E);
d.newTab(F);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(G);
d.newTab(H);
a.newTab(I);
b.changeActiveTabTo(0);
c.newTab(J);
d.newTab(K);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(L);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(M);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(1);
b.newTab(N);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(O);
b.newTab(P);
c.changeActiveTabTo(1);
d.newTab(Q);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(R);
d.changeActiveTabTo(4);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(S);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(T);
b.newTab(U);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(V);
d.changeActiveTabTo(5);
a.newTab(W);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(X);
b.newTab(Y);
c.changeActiveTabTo(4);
d.newTab(Z);
b.moveActiveTabTo(5);
d.changeActiveTabTo(5);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
b.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
c.moveActiveTabTo(3);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(6);
brows->switchToWindow(4);
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(7);
brows->newWindow();
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(6);
brows->print();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(7);
brows->switchToWindow(7);
brows->getWindow(3);
brows->newWindow();
brows->getWindow(0);
brows->getWindow(0);
brows->newWindow();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->print();
brows->getWindow(7);
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(5);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->getWindow(4);
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(0);
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->getWindow(1);
brows->mergeAllWindows();
brows->print();
brows->print();
brows->closeWindow();
brows->print();
brows->getWindow(3);
brows->mergeAllWindows();
brows->getWindow(5);
brows->getWindow(7);
brows->closeWindow();
brows->switchToWindow(8);
brows->getWindow(0);
brows->switchToWindow(6);
brows->getWindow(3);
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->newWindow();
brows->switchToWindow(6);
brows->print();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->getWindow(7);
brows->switchToWindow(5);
brows->switchToWindow(0);
brows->newWindow();
brows->switchToWindow(3);
brows->print();
brows->mergeAllWindows();
brows->getWindow(5);
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(5);
brows->getWindow(0);
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(9);
brows->switchToWindow(5);
brows->print();
brows->newWindow();
brows->closeWindow();
brows->getWindow(5);
brows->mergeAllWindows();
brows->switchToWindow(6);
brows->switchToWindow(2);
brows->getWindow(2);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->getWindow(2);
brows->print();
brows->switchToWindow(6);
brows->getWindow(8);
brows->mergeAllWindows();
delete brows;
}
	return 0;
}