#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("fff", "u","xx");
Tab B = Tab("ddd", "ooo","gg");
Tab C = Tab("k", "vvv","n");
Tab D = Tab("z", "rr","w");
Tab E = Tab("mm", "ccc","g");
Tab F = Tab("zzz", "www","ggg");
Tab G = Tab("bbb", "q","bb");
Tab H = Tab("ttt", "mm","e");
Tab I = Tab("vvv", "ll","zzz");
Tab J = Tab("mmm", "xxx","q");
Tab K = Tab("w", "eee","i");
Tab L = Tab("ll", "u","rr");
Tab M = Tab("gg", "bbb","www");
Tab N = Tab("w", "ttt","yy");
Tab O = Tab("nn", "dd","xxx");
Tab P = Tab("e", "w","ee");
Tab Q = Tab("xxx", "bbb","c");
Tab R = Tab("xxx", "l","qq");
Tab S = Tab("w", "ff","zzz");
Tab T = Tab("bbb", "f","mm");
Tab U = Tab("ggg", "x","y");
Tab V = Tab("uu", "cc","vvv");
Tab W = Tab("y", "c","bbb");
Tab X = Tab("l", "e","ll");
Tab Y = Tab("nn", "ttt","ss");
Tab Z = Tab("kk", "z","dd");
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.newTab(A);
a.newTab(B);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(C);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(D);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(E);
d.moveActiveTabTo(4);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.newTab(F);
d.moveActiveTabTo(1);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(G);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(H);
d.changeActiveTabTo(5);
a.newTab(I);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(J);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(K);
d.newTab(L);
a.changeActiveTabTo(4);
b.newTab(M);
c.newTab(N);
d.newTab(O);
a.newTab(P);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(Q);
b.newTab(R);
c.moveActiveTabTo(4);
d.newTab(S);
a.changeActiveTabTo(3);
b.newTab(T);
c.moveActiveTabTo(3);
d.newTab(U);
a.newTab(V);
b.moveActiveTabTo(1);
c.newTab(W);
d.moveActiveTabTo(1);
a.newTab(X);
b.newTab(Y);
c.newTab(Z);
d.newTab(Z);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
b.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->newWindow();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->getWindow(6);
brows->switchToWindow(1);
brows->print();
brows->switchToWindow(1);
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->getWindow(5);
brows->print();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->getWindow(4);
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(9);
brows->getWindow(6);
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(0);
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(5);
brows->closeWindow();
brows->switchToWindow(1);
brows->switchToWindow(6);
brows->switchToWindow(8);
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(2);
brows->newWindow();
brows->getWindow(4);
brows->newWindow();
brows->print();
brows->newWindow();
brows->getWindow(6);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(0);
brows->getWindow(6);
brows->print();
brows->switchToWindow(4);
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(9);
brows->print();
brows->switchToWindow(4);
brows->print();
brows->print();
brows->getWindow(9);
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(3);
brows->getWindow(1);
brows->getWindow(1);
brows->switchToWindow(1);
brows->switchToWindow(1);
brows->closeWindow();
brows->switchToWindow(0);
brows->getWindow(4);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->switchToWindow(3);
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(0);
brows->mergeAllWindows();
brows->getWindow(9);
delete brows;
}
	return 0;
}