#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("mmm", "cc","k");
Tab B = Tab("hhh", "vv","aaa");
Tab C = Tab("x", "m","hhh");
Tab D = Tab("ff", "rrr","bb");
Tab E = Tab("lll", "ll","a");
Tab F = Tab("hh", "sss","ttt");
Tab G = Tab("k", "m","iii");
Tab H = Tab("ttt", "uuu","l");
Tab I = Tab("hh", "oo","w");
Tab J = Tab("yy", "ww","kk");
Tab K = Tab("ii", "f","q");
Tab L = Tab("ss", "i","ff");
Tab M = Tab("fff", "q","sss");
Tab N = Tab("kk", "mm","ggg");
Tab O = Tab("m", "fff","x");
Tab P = Tab("hhh", "rrr","w");
Tab Q = Tab("ttt", "pp","aa");
Tab R = Tab("xxx", "y","kk");
Tab S = Tab("n", "bbb","o");
Tab T = Tab("bb", "zzz","ii");
Tab U = Tab("ddd", "v","uu");
Tab V = Tab("kk", "uuu","qqq");
Tab W = Tab("v", "qq","ddd");
Tab X = Tab("rr", "p","ccc");
Tab Y = Tab("ee", "x","uu");
Tab Z = Tab("xxx", "ff","p");
a.moveActiveTabTo(2);
b.newTab(A);
c.newTab(B);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(C);
a.newTab(D);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(E);
d.newTab(F);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.newTab(G);
d.changeActiveTabTo(1);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(H);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(I);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(J);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(K);
a.newTab(L);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(M);
a.newTab(N);
b.changeActiveTabTo(2);
c.newTab(O);
d.changeActiveTabTo(2);
a.newTab(P);
b.newTab(Q);
c.changeActiveTabTo(4);
d.newTab(R);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(S);
d.changeActiveTabTo(3);
a.moveActiveTabTo(1);
b.newTab(T);
c.changeActiveTabTo(1);
d.newTab(U);
a.changeActiveTabTo(2);
b.newTab(V);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(5);
b.newTab(W);
c.newTab(X);
d.newTab(Y);
a.newTab(Z);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
a.moveActiveTabTo(2);
d.changeActiveTabTo(2);
c.moveActiveTabTo(4);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
a.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(5);
a.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(9);
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(8);
brows->switchToWindow(9);
brows->getWindow(9);
brows->switchToWindow(4);
brows->print();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(9);
brows->getWindow(4);
brows->switchToWindow(6);
brows->print();
brows->closeWindow();
brows->print();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->print();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->newWindow();
brows->print();
brows->getWindow(9);
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(3);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(1);
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->getWindow(6);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->getWindow(6);
brows->newWindow();
brows->print();
brows->getWindow(0);
brows->print();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(0);
brows->getWindow(9);
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->switchToWindow(8);
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->getWindow(4);
brows->print();
brows->getWindow(6);
brows->closeWindow();
brows->switchToWindow(2);
brows->switchToWindow(5);
brows->getWindow(6);
brows->closeEmptyWindows();
delete brows;
}
	return 0;
}