#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("oo", "l","ggg");
Tab B = Tab("ii", "yyy","aa");
Tab C = Tab("gg", "xx","ee");
Tab D = Tab("aaa", "eee","a");
Tab E = Tab("xx", "ddd","g");
Tab F = Tab("f", "mmm","rrr");
Tab G = Tab("vv", "dd","c");
Tab H = Tab("zzz", "m","ttt");
Tab I = Tab("gg", "vvv","gg");
Tab J = Tab("ll", "zz","uuu");
Tab K = Tab("iii", "ggg","zzz");
Tab L = Tab("bb", "jj","l");
Tab M = Tab("d", "mmm","b");
Tab N = Tab("gg", "ff","fff");
Tab O = Tab("sss", "hhh","aaa");
Tab P = Tab("hh", "ee","nn");
Tab Q = Tab("ggg", "h","ccc");
Tab R = Tab("dd", "u","gg");
Tab S = Tab("jjj", "a","gg");
Tab T = Tab("u", "ww","uuu");
Tab U = Tab("z", "q","rrr");
Tab V = Tab("ww", "aa","s");
Tab W = Tab("m", "k","dd");
Tab X = Tab("p", "b","ooo");
Tab Y = Tab("e", "jjj","z");
Tab Z = Tab("vv", "aa","b");
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
b.newTab(A);
c.newTab(B);
d.changeActiveTabTo(4);
a.newTab(C);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(D);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
b.newTab(E);
c.newTab(F);
d.moveActiveTabTo(4);
a.changeActiveTabTo(1);
b.newTab(G);
c.newTab(H);
d.newTab(I);
a.newTab(J);
b.newTab(K);
c.changeActiveTabTo(1);
d.newTab(L);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
b.newTab(M);
c.newTab(N);
d.moveActiveTabTo(3);
a.newTab(O);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(P);
a.changeActiveTabTo(1);
b.newTab(Q);
c.newTab(R);
d.newTab(S);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(T);
d.newTab(U);
a.newTab(V);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(W);
a.moveActiveTabTo(4);
b.newTab(X);
c.newTab(Y);
d.newTab(Z);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
d.moveActiveTabTo(4);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
b.changeActiveTabTo(2);
d.moveActiveTabTo(2);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
b.moveActiveTabTo(1);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
a.moveActiveTabTo(4);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(0);
d.changeActiveTabTo(0);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(5);
brows->switchToWindow(9);
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(4);
brows->print();
brows->closeWindow();
brows->switchToWindow(7);
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(6);
brows->getWindow(9);
brows->newWindow();
brows->getWindow(9);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->print();
brows->closeWindow();
brows->switchToWindow(0);
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(2);
brows->print();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->switchToWindow(6);
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(7);
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->switchToWindow(5);
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(1);
brows->switchToWindow(4);
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->getWindow(6);
brows->newWindow();
brows->switchToWindow(0);
brows->getWindow(1);
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->getWindow(6);
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(9);
brows->print();
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->getWindow(9);
brows->print();
brows->getWindow(2);
brows->getWindow(0);
brows->mergeAllWindows();
brows->print();
brows->getWindow(2);
brows->getWindow(2);
brows->switchToWindow(1);
brows->getWindow(3);
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->switchToWindow(3);
delete brows;
}
	return 0;
}