#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("rr", "ii","jjj");
Tab B = Tab("vv", "y","y");
Tab C = Tab("pp", "aaa","ff");
Tab D = Tab("m", "yy","nnn");
Tab E = Tab("n", "q","e");
Tab F = Tab("vv", "vv","zzz");
Tab G = Tab("p", "q","ff");
Tab H = Tab("ooo", "ccc","t");
Tab I = Tab("m", "o","uuu");
Tab J = Tab("ttt", "w","kkk");
Tab K = Tab("s", "yyy","hh");
Tab L = Tab("w", "r","q");
Tab M = Tab("ff", "ggg","ll");
Tab N = Tab("vv", "fff","cc");
Tab O = Tab("ll", "ttt","tt");
Tab P = Tab("l", "uuu","l");
Tab Q = Tab("v", "uu","lll");
Tab R = Tab("iii", "eee","i");
Tab S = Tab("ii", "vv","cc");
Tab T = Tab("zzz", "tt","l");
Tab U = Tab("zzz", "iii","ii");
Tab V = Tab("xx", "gg","j");
Tab W = Tab("hhh", "vv","www");
Tab X = Tab("d", "ttt","tt");
Tab Y = Tab("vv", "cc","ff");
Tab Z = Tab("bbb", "xxx","zz");
a.newTab(A);
b.newTab(B);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(C);
a.newTab(D);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(E);
a.changeActiveTabTo(3);
b.newTab(F);
c.newTab(G);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(H);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
b.newTab(I);
c.newTab(J);
d.changeActiveTabTo(1);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(K);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(L);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(M);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(N);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(O);
b.changeActiveTabTo(0);
c.newTab(P);
d.newTab(Q);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(5);
b.newTab(R);
c.newTab(S);
d.moveActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(T);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(U);
d.moveActiveTabTo(0);
a.newTab(V);
b.changeActiveTabTo(1);
c.newTab(W);
d.newTab(X);
a.newTab(Y);
b.moveActiveTabTo(3);
c.newTab(Z);
d.moveActiveTabTo(3);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(4);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
d.moveActiveTabTo(0);
d.moveActiveTabTo(5);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
a.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->switchToWindow(7);
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->getWindow(9);
brows->getWindow(4);
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->switchToWindow(4);
brows->closeEmptyWindows();
brows->getWindow(0);
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->newWindow();
brows->closeWindow();
brows->getWindow(7);
brows->getWindow(0);
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(1);
brows->closeWindow();
brows->getWindow(6);
brows->closeWindow();
brows->getWindow(0);
brows->print();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->getWindow(3);
brows->closeWindow();
brows->switchToWindow(7);
brows->switchToWindow(0);
brows->print();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(2);
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(8);
brows->print();
brows->print();
brows->switchToWindow(7);
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(1);
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->getWindow(8);
brows->print();
brows->getWindow(8);
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->getWindow(2);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->switchToWindow(2);
brows->switchToWindow(7);
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(2);
brows->print();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(2);
brows->newWindow();
brows->print();
delete brows;
}
	return 0;
}