#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("sss", "vvv","mm");
Tab B = Tab("kkk", "mmm","pp");
Tab C = Tab("g", "i","jj");
Tab D = Tab("jjj", "zzz","y");
Tab E = Tab("z", "zz","ee");
Tab F = Tab("rr", "ii","rrr");
Tab G = Tab("ooo", "ee","ggg");
Tab H = Tab("uu", "m","ii");
Tab I = Tab("uuu", "hhh","c");
Tab J = Tab("d", "y","l");
Tab K = Tab("jj", "xxx","hh");
Tab L = Tab("dd", "b","j");
Tab M = Tab("kk", "ggg","u");
Tab N = Tab("a", "uu","h");
Tab O = Tab("mm", "m","ii");
Tab P = Tab("kkk", "f","z");
Tab Q = Tab("ff", "nnn","y");
Tab R = Tab("aa", "nn","t");
Tab S = Tab("xxx", "e","mmm");
Tab T = Tab("fff", "vvv","bb");
Tab U = Tab("ddd", "f","yy");
Tab V = Tab("sss", "vv","ggg");
Tab W = Tab("b", "m","pp");
Tab X = Tab("zzz", "ttt","x");
Tab Y = Tab("zzz", "pp","k");
Tab Z = Tab("tt", "g","j");
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(A);
d.newTab(B);
a.newTab(C);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(D);
b.newTab(E);
c.newTab(F);
d.moveActiveTabTo(5);
a.newTab(G);
b.newTab(H);
c.newTab(I);
d.moveActiveTabTo(5);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(J);
d.newTab(K);
a.moveActiveTabTo(4);
b.newTab(L);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(M);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(N);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(O);
b.newTab(P);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(Q);
d.newTab(R);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(S);
a.changeActiveTabTo(2);
b.newTab(T);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(U);
d.moveActiveTabTo(3);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(V);
b.newTab(W);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(X);
b.changeActiveTabTo(0);
c.newTab(Y);
d.newTab(Z);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
d.moveActiveTabTo(5);
a.changeActiveTabTo(5);
d.moveActiveTabTo(5);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(3);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
b.changeActiveTabTo(4);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(4);
d.changeActiveTabTo(4);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->newWindow();
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(9);
brows->getWindow(7);
brows->switchToWindow(4);
brows->switchToWindow(7);
brows->print();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->mergeAllWindows();
brows->getWindow(2);
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(0);
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->print();
brows->closeWindow();
brows->getWindow(4);
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(8);
brows->switchToWindow(4);
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(4);
brows->closeEmptyWindows();
brows->switchToWindow(8);
brows->print();
brows->mergeAllWindows();
brows->getWindow(7);
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->getWindow(1);
brows->switchToWindow(8);
brows->switchToWindow(2);
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(5);
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(5);
brows->closeWindow();
brows->switchToWindow(3);
brows->getWindow(8);
brows->getWindow(7);
brows->switchToWindow(2);
brows->switchToWindow(3);
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(1);
brows->newWindow();
brows->print();
brows->getWindow(3);
brows->getWindow(7);
brows->print();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(1);
brows->getWindow(8);
delete brows;
}
	return 0;
}