#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("s", "yyy","r");
Tab B = Tab("eee", "i","s");
Tab C = Tab("vv", "dd","hhh");
Tab D = Tab("yy", "bbb","yyy");
Tab E = Tab("iii", "ss","ll");
Tab F = Tab("ddd", "uu","x");
Tab G = Tab("b", "zz","kk");
Tab H = Tab("s", "b","ppp");
Tab I = Tab("ss", "ss","ww");
Tab J = Tab("mmm", "uuu","xxx");
Tab K = Tab("h", "yy","ooo");
Tab L = Tab("c", "yy","p");
Tab M = Tab("m", "aaa","rrr");
Tab N = Tab("c", "bb","zzz");
Tab O = Tab("m", "ww","ww");
Tab P = Tab("i", "u","aaa");
Tab Q = Tab("f", "f","ppp");
Tab R = Tab("e", "ppp","o");
Tab S = Tab("o", "ccc","j");
Tab T = Tab("sss", "vv","xx");
Tab U = Tab("s", "ppp","qqq");
Tab V = Tab("ggg", "aa","yyy");
Tab W = Tab("i", "x","tt");
Tab X = Tab("aaa", "aaa","iii");
Tab Y = Tab("ss", "qqq","r");
Tab Z = Tab("l", "kk","iii");
a.newTab(A);
b.newTab(B);
c.moveActiveTabTo(3);
d.newTab(C);
a.newTab(D);
b.changeActiveTabTo(0);
c.newTab(E);
d.changeActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(F);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(G);
b.newTab(H);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(I);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(J);
d.newTab(K);
a.newTab(L);
b.newTab(M);
c.newTab(N);
d.newTab(O);
a.newTab(P);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(Q);
d.newTab(R);
a.newTab(S);
b.newTab(T);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(3);
b.newTab(U);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(2);
b.newTab(V);
c.newTab(W);
d.changeActiveTabTo(2);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(X);
a.newTab(Y);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(Z);
b.newTab(Z);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(5);
c.moveActiveTabTo(5);
b.changeActiveTabTo(2);
d.changeActiveTabTo(2);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
a.changeActiveTabTo(4);
a.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(3);
d.changeActiveTabTo(3);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
a.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
d.moveActiveTabTo(4);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
b.changeActiveTabTo(2);
d.moveActiveTabTo(2);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(2);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
c.changeActiveTabTo(3);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->print();
brows->mergeAllWindows();
brows->getWindow(3);
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(7);
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(3);
brows->newWindow();
brows->switchToWindow(6);
brows->print();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(5);
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(3);
brows->closeWindow();
brows->getWindow(2);
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->switchToWindow(1);
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->getWindow(0);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(6);
brows->mergeAllWindows();
brows->getWindow(8);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(4);
brows->switchToWindow(5);
brows->print();
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(6);
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(2);
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->switchToWindow(9);
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->print();
brows->closeWindow();
brows->switchToWindow(5);
brows->switchToWindow(1);
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->getWindow(7);
brows->getWindow(0);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
delete brows;
}
	return 0;
}