#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("nn", "lll","r");
Tab B = Tab("ee", "a","bbb");
Tab C = Tab("ee", "ww","m");
Tab D = Tab("x", "yyy","x");
Tab E = Tab("sss", "hhh","yyy");
Tab F = Tab("ccc", "ll","rrr");
Tab G = Tab("fff", "sss","kk");
Tab H = Tab("x", "ss","d");
Tab I = Tab("f", "uuu","k");
Tab J = Tab("t", "p","v");
Tab K = Tab("kk", "j","jj");
Tab L = Tab("oo", "xxx","iii");
Tab M = Tab("hh", "hhh","d");
Tab N = Tab("vv", "zzz","b");
Tab O = Tab("b", "c","hhh");
Tab P = Tab("ooo", "r","ddd");
Tab Q = Tab("nn", "p","fff");
Tab R = Tab("f", "f","vvv");
Tab S = Tab("kkk", "yyy","ccc");
Tab T = Tab("rr", "rrr","h");
Tab U = Tab("k", "ff","yy");
Tab V = Tab("vv", "yyy","mm");
Tab W = Tab("ggg", "n","mm");
Tab X = Tab("aa", "m","o");
Tab Y = Tab("jj", "ooo","ppp");
Tab Z = Tab("hhh", "aa","qqq");
a.newTab(A);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.newTab(B);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(C);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
b.newTab(D);
c.changeActiveTabTo(4);
d.newTab(E);
a.newTab(F);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.newTab(G);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(H);
a.newTab(I);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.newTab(J);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(K);
d.newTab(L);
a.newTab(M);
b.changeActiveTabTo(2);
c.newTab(N);
d.changeActiveTabTo(2);
a.newTab(O);
b.newTab(P);
c.newTab(Q);
d.changeActiveTabTo(0);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(R);
d.moveActiveTabTo(0);
a.changeActiveTabTo(5);
b.newTab(S);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(T);
b.newTab(U);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(V);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(5);
b.newTab(W);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(X);
a.newTab(Y);
b.newTab(Z);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
c.moveActiveTabTo(2);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
c.moveActiveTabTo(3);
b.changeActiveTabTo(0);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
a.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->getWindow(9);
brows->getWindow(1);
brows->print();
brows->getWindow(6);
brows->closeEmptyWindows();
brows->getWindow(7);
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->getWindow(4);
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(0);
brows->getWindow(5);
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->getWindow(2);
brows->closeEmptyWindows();
brows->getWindow(9);
brows->switchToWindow(9);
brows->print();
brows->getWindow(9);
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->getWindow(2);
brows->print();
brows->closeWindow();
brows->switchToWindow(6);
brows->print();
brows->switchToWindow(7);
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->newWindow();
brows->print();
brows->closeWindow();
brows->getWindow(2);
brows->getWindow(5);
brows->mergeAllWindows();
brows->switchToWindow(9);
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(2);
brows->closeWindow();
brows->newWindow();
brows->getWindow(5);
brows->mergeAllWindows();
brows->getWindow(4);
brows->closeEmptyWindows();
brows->getWindow(4);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(4);
brows->newWindow();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(3);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(0);
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(5);
brows->getWindow(4);
brows->newWindow();
brows->switchToWindow(7);
brows->switchToWindow(1);
brows->switchToWindow(1);
brows->switchToWindow(6);
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->print();
brows->getWindow(8);
brows->mergeAllWindows();
brows->mergeAllWindows();
delete brows;
}
	return 0;
}