#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("hhh", "r","zzz");
Tab B = Tab("aaa", "mm","eee");
Tab C = Tab("e", "n","uuu");
Tab D = Tab("y", "ee","g");
Tab E = Tab("n", "mm","y");
Tab F = Tab("a", "a","rr");
Tab G = Tab("ii", "ddd","uu");
Tab H = Tab("a", "vvv","i");
Tab I = Tab("m", "uu","mm");
Tab J = Tab("l", "l","ss");
Tab K = Tab("ii", "l","zz");
Tab L = Tab("ddd", "gg","ppp");
Tab M = Tab("e", "hh","xxx");
Tab N = Tab("h", "uu","kk");
Tab O = Tab("s", "u","xx");
Tab P = Tab("v", "ll","ww");
Tab Q = Tab("ll", "ddd","g");
Tab R = Tab("nnn", "kkk","ee");
Tab S = Tab("u", "rr","jjj");
Tab T = Tab("m", "xx","y");
Tab U = Tab("xx", "m","s");
Tab V = Tab("ii", "gg","p");
Tab W = Tab("w", "tt","qqq");
Tab X = Tab("ggg", "qqq","www");
Tab Y = Tab("mmm", "nn","m");
Tab Z = Tab("uu", "vv","cc");
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(A);
d.changeActiveTabTo(0);
a.newTab(B);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(C);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(D);
a.newTab(E);
b.moveActiveTabTo(2);
c.newTab(F);
d.newTab(G);
a.changeActiveTabTo(2);
b.newTab(H);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(I);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(0);
b.newTab(J);
c.newTab(K);
d.moveActiveTabTo(0);
a.newTab(L);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(M);
a.changeActiveTabTo(2);
b.newTab(N);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(O);
b.newTab(P);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(Q);
a.newTab(R);
b.moveActiveTabTo(1);
c.newTab(S);
d.changeActiveTabTo(1);
a.newTab(T);
b.changeActiveTabTo(1);
c.newTab(U);
d.newTab(V);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.newTab(W);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.newTab(X);
d.changeActiveTabTo(1);
a.newTab(Y);
b.changeActiveTabTo(3);
c.newTab(Z);
d.newTab(Z);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(4);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
d.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
d.changeActiveTabTo(1);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
d.changeActiveTabTo(3);
c.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(4);
d.moveActiveTabTo(4);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->switchToWindow(8);
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(5);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(5);
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(2);
brows->newWindow();
brows->newWindow();
brows->switchToWindow(3);
brows->print();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->print();
brows->getWindow(3);
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(2);
brows->getWindow(5);
brows->newWindow();
brows->print();
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->getWindow(0);
brows->getWindow(6);
brows->newWindow();
brows->print();
brows->getWindow(9);
brows->switchToWindow(4);
brows->print();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(6);
brows->newWindow();
brows->getWindow(8);
brows->switchToWindow(8);
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->switchToWindow(9);
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(2);
brows->getWindow(6);
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->print();
brows->switchToWindow(6);
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->switchToWindow(9);
brows->newWindow();
brows->print();
brows->getWindow(4);
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->switchToWindow(2);
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(2);
brows->getWindow(4);
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->getWindow(2);
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
delete brows;
}
	return 0;
}