#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("vvv", "aaa","p");
Tab B = Tab("dd", "s","gg");
Tab C = Tab("nn", "j","ooo");
Tab D = Tab("zz", "www","ee");
Tab E = Tab("e", "r","tt");
Tab F = Tab("rr", "ccc","vv");
Tab G = Tab("kkk", "oo","bb");
Tab H = Tab("w", "nn","fff");
Tab I = Tab("nnn", "s","oo");
Tab J = Tab("k", "a","v");
Tab K = Tab("lll", "pp","lll");
Tab L = Tab("ee", "h","fff");
Tab M = Tab("mm", "vvv","p");
Tab N = Tab("ggg", "xx","aa");
Tab O = Tab("zz", "hh","xx");
Tab P = Tab("q", "nnn","yyy");
Tab Q = Tab("n", "zz","ee");
Tab R = Tab("www", "www","vv");
Tab S = Tab("rr", "oo","y");
Tab T = Tab("mmm", "fff","hh");
Tab U = Tab("c", "kk","ss");
Tab V = Tab("kk", "kk","g");
Tab W = Tab("l", "hhh","eee");
Tab X = Tab("qqq", "q","t");
Tab Y = Tab("zzz", "ii","cc");
Tab Z = Tab("c", "kkk","g");
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(A);
a.newTab(B);
b.newTab(C);
c.moveActiveTabTo(1);
d.newTab(D);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(3);
b.newTab(E);
c.changeActiveTabTo(3);
d.newTab(F);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(G);
d.newTab(H);
a.newTab(I);
b.changeActiveTabTo(2);
c.newTab(J);
d.changeActiveTabTo(2);
a.newTab(K);
b.changeActiveTabTo(0);
c.newTab(L);
d.newTab(M);
a.newTab(N);
b.changeActiveTabTo(5);
c.newTab(O);
d.newTab(P);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(Q);
b.moveActiveTabTo(1);
c.newTab(R);
d.moveActiveTabTo(1);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(S);
a.newTab(T);
b.newTab(U);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(5);
b.newTab(V);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(W);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(X);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(Y);
d.changeActiveTabTo(5);
a.moveActiveTabTo(2);
b.newTab(Z);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
a.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
a.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
d.changeActiveTabTo(2);
c.changeActiveTabTo(0);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
d.moveActiveTabTo(2);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(1);
a.moveActiveTabTo(2);
c.moveActiveTabTo(5);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
d.moveActiveTabTo(2);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->getWindow(7);
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(8);
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(3);
brows->getWindow(2);
brows->switchToWindow(1);
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(3);
brows->getWindow(4);
brows->switchToWindow(4);
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->getWindow(8);
brows->print();
brows->getWindow(8);
brows->print();
brows->getWindow(8);
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->switchToWindow(8);
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(4);
brows->switchToWindow(6);
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->getWindow(1);
brows->switchToWindow(7);
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->print();
brows->newWindow();
brows->print();
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(8);
brows->newWindow();
brows->getWindow(8);
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(1);
brows->closeWindow();
brows->getWindow(8);
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(5);
brows->getWindow(8);
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(0);
brows->newWindow();
brows->getWindow(8);
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->getWindow(2);
brows->switchToWindow(9);
brows->getWindow(0);
brows->mergeAllWindows();
brows->getWindow(3);
brows->switchToWindow(6);
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(4);
delete brows;
}
	return 0;
}