#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("d", "ll","q");
Tab B = Tab("ff", "p","lll");
Tab C = Tab("eee", "rrr","fff");
Tab D = Tab("m", "bbb","bb");
Tab E = Tab("uuu", "f","rrr");
Tab F = Tab("qqq", "jjj","tt");
Tab G = Tab("x", "oo","bbb");
Tab H = Tab("hh", "x","s");
Tab I = Tab("ddd", "h","v");
Tab J = Tab("zz", "gg","tt");
Tab K = Tab("ttt", "ooo","mm");
Tab L = Tab("kkk", "www","d");
Tab M = Tab("mm", "qqq","eee");
Tab N = Tab("ii", "www","c");
Tab O = Tab("w", "ggg","ee");
Tab P = Tab("i", "ff","ff");
Tab Q = Tab("ppp", "n","u");
Tab R = Tab("l", "j","www");
Tab S = Tab("xxx", "ff","oo");
Tab T = Tab("h", "o","ooo");
Tab U = Tab("mmm", "h","www");
Tab V = Tab("nn", "r","cc");
Tab W = Tab("yy", "iii","ttt");
Tab X = Tab("nnn", "mmm","ee");
Tab Y = Tab("h", "u","qqq");
Tab Z = Tab("vv", "qq","ff");
a.moveActiveTabTo(2);
b.newTab(A);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(B);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(C);
b.newTab(D);
c.newTab(E);
d.changeActiveTabTo(4);
a.newTab(F);
b.newTab(G);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(H);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(I);
a.newTab(J);
b.changeActiveTabTo(0);
c.newTab(K);
d.changeActiveTabTo(0);
a.changeActiveTabTo(0);
b.newTab(L);
c.moveActiveTabTo(0);
d.newTab(M);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(N);
d.newTab(O);
a.moveActiveTabTo(5);
b.newTab(P);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(Q);
b.newTab(R);
c.moveActiveTabTo(5);
d.newTab(S);
a.moveActiveTabTo(3);
b.newTab(T);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(2);
b.newTab(U);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(V);
d.changeActiveTabTo(0);
a.newTab(W);
b.newTab(X);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(0);
b.newTab(Y);
c.newTab(Z);
d.newTab(Z);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(5);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(3);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->switchToWindow(5);
brows->switchToWindow(1);
brows->closeWindow();
brows->getWindow(9);
brows->switchToWindow(8);
brows->switchToWindow(6);
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(5);
brows->switchToWindow(3);
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->print();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->print();
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->getWindow(9);
brows->newWindow();
brows->switchToWindow(2);
brows->print();
brows->getWindow(4);
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->print();
brows->getWindow(2);
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->print();
brows->print();
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(3);
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->switchToWindow(8);
brows->print();
brows->newWindow();
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(6);
brows->getWindow(4);
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(8);
brows->print();
brows->newWindow();
brows->switchToWindow(4);
brows->newWindow();
brows->switchToWindow(9);
brows->closeWindow();
brows->getWindow(9);
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(7);
brows->print();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
delete brows;
}
	return 0;
}