#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("iii", "hh","ll");
Tab B = Tab("dd", "d","a");
Tab C = Tab("yyy", "ttt","c");
Tab D = Tab("h", "w","x");
Tab E = Tab("zz", "fff","bb");
Tab F = Tab("yy", "lll","iii");
Tab G = Tab("rrr", "aaa","tt");
Tab H = Tab("ss", "jj","oo");
Tab I = Tab("ttt", "i","gg");
Tab J = Tab("zz", "uu","xx");
Tab K = Tab("ppp", "h","qqq");
Tab L = Tab("w", "ll","tt");
Tab M = Tab("bb", "u","h");
Tab N = Tab("r", "h","b");
Tab O = Tab("kk", "yy","ff");
Tab P = Tab("u", "v","a");
Tab Q = Tab("bbb", "sss","yy");
Tab R = Tab("ttt", "i","pp");
Tab S = Tab("g", "n","vvv");
Tab T = Tab("ww", "sss","qqq");
Tab U = Tab("ggg", "vv","uu");
Tab V = Tab("cc", "zzz","l");
Tab W = Tab("v", "b","t");
Tab X = Tab("s", "tt","x");
Tab Y = Tab("uu", "m","q");
Tab Z = Tab("n", "eee","i");
a.moveActiveTabTo(4);
b.newTab(A);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(B);
b.moveActiveTabTo(3);
c.newTab(C);
d.moveActiveTabTo(3);
a.newTab(D);
b.newTab(E);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(F);
d.moveActiveTabTo(3);
a.newTab(G);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(H);
d.changeActiveTabTo(5);
a.changeActiveTabTo(5);
b.newTab(I);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(J);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(K);
d.moveActiveTabTo(4);
a.newTab(L);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(M);
a.newTab(N);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(O);
b.newTab(P);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(Q);
b.newTab(R);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(S);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.newTab(T);
d.changeActiveTabTo(2);
a.changeActiveTabTo(0);
b.newTab(U);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(V);
d.changeActiveTabTo(4);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(W);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(X);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(Y);
d.newTab(Z);
a.changeActiveTabTo(2);
d.changeActiveTabTo(2);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(1);
c.changeActiveTabTo(1);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(1);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(3);
c.changeActiveTabTo(3);
b.changeActiveTabTo(0);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->print();
brows->getWindow(8);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->print();
brows->closeWindow();
brows->getWindow(9);
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->getWindow(7);
brows->switchToWindow(3);
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(1);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(0);
brows->getWindow(3);
brows->newWindow();
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(8);
brows->print();
brows->getWindow(8);
brows->newWindow();
brows->newWindow();
brows->switchToWindow(6);
brows->closeWindow();
brows->print();
brows->getWindow(7);
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(1);
brows->getWindow(1);
brows->mergeAllWindows();
brows->switchToWindow(9);
brows->switchToWindow(0);
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(5);
brows->mergeAllWindows();
brows->getWindow(2);
brows->closeWindow();
brows->switchToWindow(2);
brows->switchToWindow(8);
brows->print();
brows->getWindow(9);
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->closeWindow();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->getWindow(2);
brows->newWindow();
delete brows;
}
	return 0;
}