#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("ff", "bbb","n");
Tab B = Tab("ii", "ooo","xxx");
Tab C = Tab("ddd", "zz","c");
Tab D = Tab("r", "v","sss");
Tab E = Tab("vvv", "l","mm");
Tab F = Tab("a", "www","q");
Tab G = Tab("m", "sss","rrr");
Tab H = Tab("f", "dd","mmm");
Tab I = Tab("ii", "gg","xxx");
Tab J = Tab("kk", "jjj","hhh");
Tab K = Tab("m", "j","d");
Tab L = Tab("aa", "j","b");
Tab M = Tab("g", "ooo","i");
Tab N = Tab("xxx", "ccc","ll");
Tab O = Tab("f", "jjj","xxx");
Tab P = Tab("eee", "s","yy");
Tab Q = Tab("ddd", "h","rrr");
Tab R = Tab("nnn", "kkk","yy");
Tab S = Tab("fff", "qq","ppp");
Tab T = Tab("lll", "ttt","w");
Tab U = Tab("yy", "ii","e");
Tab V = Tab("lll", "sss","uu");
Tab W = Tab("lll", "r","b");
Tab X = Tab("pp", "f","eee");
Tab Y = Tab("c", "kkk","r");
Tab Z = Tab("mmm", "ooo","aaa");
a.newTab(A);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.newTab(B);
d.changeActiveTabTo(1);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(C);
b.newTab(D);
c.newTab(E);
d.newTab(F);
a.moveActiveTabTo(4);
b.newTab(G);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
b.newTab(H);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(2);
b.newTab(I);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(J);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(K);
d.moveActiveTabTo(4);
a.moveActiveTabTo(0);
b.newTab(L);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(2);
b.newTab(M);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(3);
b.newTab(N);
c.newTab(O);
d.moveActiveTabTo(3);
a.newTab(P);
b.newTab(Q);
c.changeActiveTabTo(1);
d.newTab(R);
a.newTab(S);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
b.newTab(T);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(U);
a.newTab(V);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(W);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(X);
d.moveActiveTabTo(4);
a.changeActiveTabTo(5);
b.newTab(Y);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(Z);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
b.moveActiveTabTo(3);
d.changeActiveTabTo(3);
b.moveActiveTabTo(2);
d.changeActiveTabTo(2);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
b.changeActiveTabTo(0);
a.moveActiveTabTo(2);
c.moveActiveTabTo(2);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
d.changeActiveTabTo(2);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(3);
d.moveActiveTabTo(4);
a.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
a.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
d.changeActiveTabTo(5);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
d.changeActiveTabTo(4);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->getWindow(2);
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->getWindow(6);
brows->closeWindow();
brows->getWindow(4);
brows->closeWindow();
brows->switchToWindow(6);
brows->newWindow();
brows->getWindow(0);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(8);
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->print();
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(8);
brows->closeWindow();
brows->print();
brows->getWindow(0);
brows->closeWindow();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(6);
brows->getWindow(8);
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->getWindow(7);
brows->switchToWindow(1);
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->switchToWindow(9);
brows->getWindow(9);
brows->mergeAllWindows();
brows->getWindow(6);
brows->getWindow(2);
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->getWindow(2);
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->getWindow(4);
brows->getWindow(3);
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->getWindow(3);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(1);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->print();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->closeWindow();
brows->print();
brows->switchToWindow(7);
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->newWindow();
delete brows;
}
	return 0;
}