#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("x", "x","cc");
Tab B = Tab("nn", "dd","r");
Tab C = Tab("y", "s","lll");
Tab D = Tab("oo", "ii","ff");
Tab E = Tab("pp", "d","s");
Tab F = Tab("tt", "t","r");
Tab G = Tab("n", "a","bb");
Tab H = Tab("ll", "rr","qqq");
Tab I = Tab("vvv", "h","u");
Tab J = Tab("k", "ooo","gg");
Tab K = Tab("dd", "s","mmm");
Tab L = Tab("uuu", "kk","uuu");
Tab M = Tab("xx", "zzz","q");
Tab N = Tab("sss", "gg","www");
Tab O = Tab("ttt", "uu","zzz");
Tab P = Tab("r", "w","r");
Tab Q = Tab("vvv", "nn","rr");
Tab R = Tab("n", "ss","e");
Tab S = Tab("i", "dd","iii");
Tab T = Tab("ddd", "fff","gg");
Tab U = Tab("nn", "s","yy");
Tab V = Tab("ccc", "c","uuu");
Tab W = Tab("k", "vvv","x");
Tab X = Tab("yy", "w","gg");
Tab Y = Tab("aa", "u","k");
Tab Z = Tab("iii", "l","n");
a.newTab(A);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(B);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(C);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.newTab(D);
d.moveActiveTabTo(1);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(E);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(F);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(G);
d.changeActiveTabTo(4);
a.changeActiveTabTo(2);
b.newTab(H);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(1);
b.newTab(I);
c.moveActiveTabTo(1);
d.newTab(J);
a.changeActiveTabTo(5);
b.newTab(K);
c.newTab(L);
d.moveActiveTabTo(5);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(M);
d.changeActiveTabTo(2);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(4);
b.newTab(N);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.newTab(O);
d.moveActiveTabTo(1);
a.newTab(P);
b.newTab(Q);
c.newTab(R);
d.moveActiveTabTo(4);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(S);
b.newTab(T);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(4);
b.newTab(U);
c.newTab(V);
d.newTab(W);
a.newTab(X);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(Y);
a.newTab(Z);
b.newTab(Z);
c.newTab(Z);
d.moveActiveTabTo(5);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
d.moveActiveTabTo(2);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
b.changeActiveTabTo(3);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(5);
a.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
c.moveActiveTabTo(5);
c.changeActiveTabTo(1);
b.moveActiveTabTo(2);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
b.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(5);
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->getWindow(8);
brows->switchToWindow(6);
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->closeWindow();
brows->getWindow(8);
brows->switchToWindow(3);
brows->getWindow(7);
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->print();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(2);
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->switchToWindow(1);
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->getWindow(7);
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(9);
brows->getWindow(7);
brows->print();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->getWindow(4);
brows->closeWindow();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(1);
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->getWindow(6);
brows->print();
brows->getWindow(1);
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->print();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->switchToWindow(7);
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
delete brows;
}
	return 0;
}