#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("vvv", "xx","jj");
Tab B = Tab("ff", "r","t");
Tab C = Tab("kk", "ggg","t");
Tab D = Tab("dd", "f","mm");
Tab E = Tab("oo", "mmm","fff");
Tab F = Tab("lll", "qq","sss");
Tab G = Tab("ww", "x","i");
Tab H = Tab("m", "qqq","zz");
Tab I = Tab("ll", "jj","mm");
Tab J = Tab("kkk", "v","kk");
Tab K = Tab("f", "nn","sss");
Tab L = Tab("k", "mm","nn");
Tab M = Tab("a", "ee","ccc");
Tab N = Tab("w", "mm","w");
Tab O = Tab("iii", "p","pp");
Tab P = Tab("www", "aa","a");
Tab Q = Tab("c", "ii","ee");
Tab R = Tab("mmm", "d","r");
Tab S = Tab("b", "u","j");
Tab T = Tab("e", "jj","ooo");
Tab U = Tab("d", "ll","w");
Tab V = Tab("qqq", "hhh","v");
Tab W = Tab("yyy", "i","zzz");
Tab X = Tab("ww", "mmm","oo");
Tab Y = Tab("r", "b","ppp");
Tab Z = Tab("yy", "ww","ccc");
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(A);
a.newTab(B);
b.moveActiveTabTo(1);
c.newTab(C);
d.newTab(D);
a.newTab(E);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(F);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(G);
b.newTab(H);
c.moveActiveTabTo(4);
d.newTab(I);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(J);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(K);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(L);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.newTab(M);
d.changeActiveTabTo(2);
a.newTab(N);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.newTab(O);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(P);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(5);
b.newTab(Q);
c.changeActiveTabTo(5);
d.newTab(R);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(S);
a.newTab(T);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(U);
a.newTab(V);
b.changeActiveTabTo(1);
c.newTab(W);
d.moveActiveTabTo(1);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(1);
b.newTab(X);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(Y);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(2);
b.newTab(Z);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
d.moveActiveTabTo(2);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
b.changeActiveTabTo(3);
a.moveActiveTabTo(0);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
b.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.changeActiveTabTo(5);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->getWindow(8);
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(3);
brows->newWindow();
brows->newWindow();
brows->getWindow(6);
brows->switchToWindow(6);
brows->print();
brows->getWindow(0);
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(6);
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(4);
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->newWindow();
brows->print();
brows->closeWindow();
brows->getWindow(9);
brows->switchToWindow(3);
brows->newWindow();
brows->switchToWindow(5);
brows->switchToWindow(1);
brows->newWindow();
brows->switchToWindow(8);
brows->getWindow(0);
brows->mergeAllWindows();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(7);
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(7);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(0);
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->switchToWindow(6);
brows->closeWindow();
brows->getWindow(2);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->getWindow(4);
brows->switchToWindow(5);
brows->getWindow(5);
brows->closeWindow();
brows->print();
brows->getWindow(1);
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->print();
brows->switchToWindow(1);
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(4);
brows->getWindow(8);
brows->newWindow();
brows->getWindow(4);
brows->newWindow();
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->getWindow(7);
brows->mergeAllWindows();
brows->getWindow(5);
brows->closeWindow();
brows->switchToWindow(8);
brows->print();
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->getWindow(3);
brows->print();
brows->getWindow(4);
brows->print();
brows->closeWindow();
brows->switchToWindow(2);
delete brows;
}
	return 0;
}