#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("ff", "pp","e");
Tab B = Tab("yy", "qq","ww");
Tab C = Tab("yy", "xx","cc");
Tab D = Tab("vvv", "g","cc");
Tab E = Tab("qq", "eee","qq");
Tab F = Tab("hhh", "oo","bb");
Tab G = Tab("j", "ii","tt");
Tab H = Tab("mmm", "a","yyy");
Tab I = Tab("n", "l","jjj");
Tab J = Tab("ooo", "n","ddd");
Tab K = Tab("ss", "k","gg");
Tab L = Tab("qq", "yyy","w");
Tab M = Tab("x", "nn","ll");
Tab N = Tab("nnn", "b","q");
Tab O = Tab("w", "hhh","ddd");
Tab P = Tab("z", "nnn","uuu");
Tab Q = Tab("ddd", "m","rrr");
Tab R = Tab("n", "g","ii");
Tab S = Tab("ii", "iii","www");
Tab T = Tab("ii", "zzz","hh");
Tab U = Tab("s", "aa","bb");
Tab V = Tab("mm", "fff","e");
Tab W = Tab("m", "n","ttt");
Tab X = Tab("xx", "mm","k");
Tab Y = Tab("i", "vvv","y");
Tab Z = Tab("ccc", "x","ee");
a.newTab(A);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(B);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(C);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(D);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(E);
a.newTab(F);
b.changeActiveTabTo(4);
c.newTab(G);
d.moveActiveTabTo(4);
a.changeActiveTabTo(3);
b.newTab(H);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(4);
b.newTab(I);
c.moveActiveTabTo(4);
d.newTab(J);
a.newTab(K);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(L);
d.newTab(M);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(N);
d.changeActiveTabTo(4);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(O);
d.moveActiveTabTo(3);
a.newTab(P);
b.newTab(Q);
c.newTab(R);
d.moveActiveTabTo(1);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(S);
b.changeActiveTabTo(4);
c.newTab(T);
d.newTab(U);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(V);
d.newTab(W);
a.changeActiveTabTo(1);
b.newTab(X);
c.newTab(Y);
d.moveActiveTabTo(1);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(Z);
d.moveActiveTabTo(4);
a.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(2);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
c.moveActiveTabTo(5);
a.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
d.changeActiveTabTo(0);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(3);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->getWindow(4);
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->getWindow(2);
brows->getWindow(8);
brows->getWindow(3);
brows->getWindow(4);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(8);
brows->switchToWindow(5);
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->switchToWindow(7);
brows->switchToWindow(1);
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(4);
brows->print();
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(5);
brows->print();
brows->switchToWindow(4);
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(3);
brows->getWindow(7);
brows->switchToWindow(6);
brows->switchToWindow(3);
brows->newWindow();
brows->switchToWindow(7);
brows->print();
brows->closeWindow();
brows->getWindow(3);
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->getWindow(1);
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->closeWindow();
brows->getWindow(0);
brows->print();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->switchToWindow(7);
brows->getWindow(9);
brows->getWindow(0);
brows->newWindow();
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(0);
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(8);
brows->newWindow();
brows->print();
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->getWindow(0);
brows->print();
brows->getWindow(1);
brows->getWindow(3);
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(8);
brows->print();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(5);
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(8);
delete brows;
}
	return 0;
}