#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("zz", "z","vv");
Tab B = Tab("ccc", "s","fff");
Tab C = Tab("vv", "oo","q");
Tab D = Tab("qqq", "ss","vv");
Tab E = Tab("s", "mm","qq");
Tab F = Tab("g", "sss","qq");
Tab G = Tab("vvv", "qqq","vvv");
Tab H = Tab("vv", "ss","s");
Tab I = Tab("gg", "k","ee");
Tab J = Tab("s", "hhh","hhh");
Tab K = Tab("rrr", "b","ff");
Tab L = Tab("s", "e","yyy");
Tab M = Tab("jjj", "ttt","yyy");
Tab N = Tab("ggg", "f","ss");
Tab O = Tab("ff", "vv","l");
Tab P = Tab("ggg", "dd","ff");
Tab Q = Tab("zzz", "jjj","nn");
Tab R = Tab("dd", "gg","ggg");
Tab S = Tab("lll", "a","b");
Tab T = Tab("pp", "rr","rr");
Tab U = Tab("l", "qq","l");
Tab V = Tab("w", "f","r");
Tab W = Tab("tt", "t","yy");
Tab X = Tab("o", "aa","zz");
Tab Y = Tab("aaa", "uu","nnn");
Tab Z = Tab("aaa", "pp","p");
a.newTab(A);
b.newTab(B);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(C);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(D);
d.newTab(E);
a.newTab(F);
b.newTab(G);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.newTab(H);
c.moveActiveTabTo(1);
d.newTab(I);
a.newTab(J);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(K);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(L);
b.moveActiveTabTo(1);
c.newTab(M);
d.newTab(N);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(O);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(P);
a.newTab(Q);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(R);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(4);
b.newTab(S);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(5);
b.newTab(T);
c.changeActiveTabTo(5);
d.newTab(U);
a.newTab(V);
b.newTab(W);
c.moveActiveTabTo(3);
d.newTab(X);
a.newTab(Y);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(Z);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
a.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
c.moveActiveTabTo(5);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
b.moveActiveTabTo(0);
d.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.moveActiveTabTo(3);
d.changeActiveTabTo(3);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->closeWindow();
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(4);
brows->getWindow(6);
brows->getWindow(1);
brows->newWindow();
brows->newWindow();
brows->print();
brows->getWindow(0);
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(2);
brows->print();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(3);
brows->print();
brows->print();
brows->newWindow();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->print();
brows->print();
brows->getWindow(8);
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->print();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->switchToWindow(9);
brows->getWindow(6);
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(4);
brows->newWindow();
brows->getWindow(9);
brows->getWindow(5);
brows->closeWindow();
brows->switchToWindow(8);
brows->switchToWindow(3);
brows->mergeAllWindows();
brows->getWindow(4);
brows->print();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(8);
brows->getWindow(2);
brows->getWindow(1);
brows->print();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(7);
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(5);
brows->print();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->newWindow();
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(2);
brows->getWindow(5);
brows->getWindow(8);
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->closeWindow();
delete brows;
}
	return 0;
}