#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("rrr", "uuu","h");
Tab B = Tab("ww", "ss","www");
Tab C = Tab("a", "l","jj");
Tab D = Tab("t", "lll","qq");
Tab E = Tab("jj", "nnn","vv");
Tab F = Tab("zzz", "s","e");
Tab G = Tab("hhh", "jj","jjj");
Tab H = Tab("g", "gg","z");
Tab I = Tab("tt", "eee","jj");
Tab J = Tab("ii", "l","rr");
Tab K = Tab("jjj", "zz","f");
Tab L = Tab("ggg", "www","xx");
Tab M = Tab("zz", "t","kk");
Tab N = Tab("o", "ttt","o");
Tab O = Tab("ttt", "z","x");
Tab P = Tab("gg", "kkk","qqq");
Tab Q = Tab("gg", "bbb","uuu");
Tab R = Tab("jj", "yyy","bbb");
Tab S = Tab("xxx", "bb","mm");
Tab T = Tab("pp", "jjj","www");
Tab U = Tab("xxx", "o","rrr");
Tab V = Tab("ee", "bbb","vvv");
Tab W = Tab("rrr", "k","ff");
Tab X = Tab("ccc", "ooo","u");
Tab Y = Tab("w", "xxx","rrr");
Tab Z = Tab("y", "i","xx");
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.newTab(A);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.newTab(B);
d.newTab(C);
a.newTab(D);
b.moveActiveTabTo(0);
c.newTab(E);
d.moveActiveTabTo(0);
a.newTab(F);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(2);
b.newTab(G);
c.moveActiveTabTo(2);
d.newTab(H);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(I);
d.newTab(J);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(K);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(L);
b.newTab(M);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(0);
b.newTab(N);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(O);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(P);
d.changeActiveTabTo(5);
a.newTab(Q);
b.newTab(R);
c.moveActiveTabTo(5);
d.newTab(S);
a.newTab(T);
b.moveActiveTabTo(5);
c.newTab(U);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.newTab(V);
c.newTab(W);
d.changeActiveTabTo(0);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(X);
d.moveActiveTabTo(0);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.newTab(Y);
d.newTab(Z);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.changeActiveTabTo(3);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(0);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
c.changeActiveTabTo(2);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
a.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->newWindow();
brows->switchToWindow(0);
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(3);
brows->switchToWindow(2);
brows->print();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->switchToWindow(7);
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(9);
brows->closeWindow();
brows->switchToWindow(0);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->switchToWindow(5);
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(6);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(9);
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(9);
brows->getWindow(7);
brows->newWindow();
brows->closeWindow();
brows->print();
brows->switchToWindow(5);
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(5);
brows->getWindow(7);
brows->mergeAllWindows();
brows->print();
brows->getWindow(3);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(7);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->getWindow(5);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->getWindow(2);
brows->closeWindow();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->switchToWindow(8);
brows->switchToWindow(4);
brows->print();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(0);
brows->getWindow(4);
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->getWindow(8);
brows->switchToWindow(8);
brows->print();
brows->mergeAllWindows();
brows->getWindow(7);
brows->getWindow(0);
brows->newWindow();
delete brows;
}
	return 0;
}