#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("ppp", "rrr","ww");
Tab B = Tab("yyy", "ppp","n");
Tab C = Tab("r", "uu","o");
Tab D = Tab("i", "j","p");
Tab E = Tab("qq", "kk","qq");
Tab F = Tab("qq", "m","rrr");
Tab G = Tab("f", "ww","r");
Tab H = Tab("bb", "ppp","h");
Tab I = Tab("zzz", "m","rrr");
Tab J = Tab("ww", "lll","j");
Tab K = Tab("rr", "hhh","p");
Tab L = Tab("vv", "sss","o");
Tab M = Tab("dd", "i","n");
Tab N = Tab("rrr", "b","o");
Tab O = Tab("dd", "tt","rr");
Tab P = Tab("x", "hh","i");
Tab Q = Tab("ww", "qq","r");
Tab R = Tab("v", "e","ff");
Tab S = Tab("qqq", "y","uu");
Tab T = Tab("b", "ttt","kkk");
Tab U = Tab("xx", "ii","xxx");
Tab V = Tab("ee", "nnn","q");
Tab W = Tab("a", "uu","rr");
Tab X = Tab("k", "nnn","mmm");
Tab Y = Tab("jj", "nn","ttt");
Tab Z = Tab("bbb", "ss","hhh");
a.changeActiveTabTo(2);
b.newTab(A);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.newTab(B);
d.changeActiveTabTo(1);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.newTab(C);
d.changeActiveTabTo(1);
a.changeActiveTabTo(0);
b.newTab(D);
c.newTab(E);
d.changeActiveTabTo(0);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(5);
b.newTab(F);
c.newTab(G);
d.moveActiveTabTo(5);
a.newTab(H);
b.changeActiveTabTo(4);
c.newTab(I);
d.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.newTab(J);
c.newTab(K);
d.moveActiveTabTo(4);
a.newTab(L);
b.newTab(M);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.newTab(N);
b.changeActiveTabTo(3);
c.newTab(O);
d.newTab(P);
a.newTab(Q);
b.newTab(R);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(S);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(T);
a.changeActiveTabTo(0);
b.newTab(U);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(V);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(W);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(X);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.newTab(Y);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(Z);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
c.moveActiveTabTo(5);
a.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(3);
c.changeActiveTabTo(3);
b.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
a.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.changeActiveTabTo(4);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->print();
brows->print();
brows->switchToWindow(3);
brows->mergeAllWindows();
brows->getWindow(5);
brows->switchToWindow(4);
brows->print();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->newWindow();
brows->print();
brows->newWindow();
brows->print();
brows->switchToWindow(7);
brows->closeWindow();
brows->print();
brows->print();
brows->newWindow();
brows->getWindow(2);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->switchToWindow(2);
brows->switchToWindow(0);
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(9);
brows->getWindow(8);
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->switchToWindow(5);
brows->mergeAllWindows();
brows->switchToWindow(9);
brows->print();
brows->getWindow(5);
brows->print();
brows->closeWindow();
brows->getWindow(7);
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(2);
brows->closeWindow();
brows->getWindow(4);
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(6);
brows->getWindow(4);
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(9);
brows->getWindow(2);
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->switchToWindow(3);
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(5);
brows->switchToWindow(5);
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(8);
brows->print();
brows->getWindow(1);
brows->closeEmptyWindows();
brows->getWindow(9);
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(2);
brows->newWindow();
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->print();
brows->getWindow(8);
brows->getWindow(7);
brows->print();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(9);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->newWindow();
brows->closeEmptyWindows();
delete brows;
}
	return 0;
}