#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("gg", "gg","r");
Tab B = Tab("hhh", "l","d");
Tab C = Tab("zzz", "p","vv");
Tab D = Tab("vvv", "bbb","a");
Tab E = Tab("qqq", "ccc","uu");
Tab F = Tab("q", "zz","t");
Tab G = Tab("i", "g","yy");
Tab H = Tab("h", "gg","ttt");
Tab I = Tab("xx", "nnn","uu");
Tab J = Tab("n", "ppp","a");
Tab K = Tab("kk", "ff","cc");
Tab L = Tab("k", "mm","a");
Tab M = Tab("d", "ccc","n");
Tab N = Tab("qq", "i","oo");
Tab O = Tab("ss", "zzz","jjj");
Tab P = Tab("ppp", "i","e");
Tab Q = Tab("qq", "d","ccc");
Tab R = Tab("mm", "yyy","bbb");
Tab S = Tab("q", "c","uu");
Tab T = Tab("xxx", "ggg","ee");
Tab U = Tab("bb", "v","bb");
Tab V = Tab("oo", "h","cc");
Tab W = Tab("t", "zz","n");
Tab X = Tab("xxx", "zzz","i");
Tab Y = Tab("xx", "w","n");
Tab Z = Tab("xxx", "nnn","l");
a.changeActiveTabTo(2);
b.newTab(A);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(B);
d.changeActiveTabTo(0);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(C);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(5);
b.newTab(D);
c.moveActiveTabTo(5);
d.newTab(E);
a.newTab(F);
b.newTab(G);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(H);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(5);
b.newTab(I);
c.newTab(J);
d.moveActiveTabTo(5);
a.newTab(K);
b.newTab(L);
c.changeActiveTabTo(0);
d.newTab(M);
a.moveActiveTabTo(3);
b.newTab(N);
c.moveActiveTabTo(3);
d.newTab(O);
a.newTab(P);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(Q);
d.moveActiveTabTo(0);
a.newTab(R);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(5);
b.newTab(S);
c.changeActiveTabTo(5);
d.newTab(T);
a.newTab(U);
b.changeActiveTabTo(4);
c.newTab(V);
d.newTab(W);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(X);
d.changeActiveTabTo(5);
a.newTab(Y);
b.moveActiveTabTo(0);
c.newTab(Z);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
b.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
c.moveActiveTabTo(3);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
d.changeActiveTabTo(4);
d.changeActiveTabTo(5);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(2);
c.moveActiveTabTo(2);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
a.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->getWindow(3);
brows->getWindow(9);
brows->switchToWindow(3);
brows->getWindow(1);
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->newWindow();
brows->switchToWindow(9);
brows->print();
brows->getWindow(2);
brows->getWindow(1);
brows->switchToWindow(1);
brows->print();
brows->closeWindow();
brows->getWindow(2);
brows->closeWindow();
brows->newWindow();
brows->getWindow(6);
brows->closeWindow();
brows->closeWindow();
brows->getWindow(4);
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(2);
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->getWindow(0);
brows->mergeAllWindows();
brows->getWindow(6);
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->getWindow(0);
brows->getWindow(3);
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->closeWindow();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(9);
brows->newWindow();
brows->print();
brows->closeWindow();
brows->switchToWindow(5);
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->getWindow(5);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(3);
brows->switchToWindow(5);
brows->getWindow(3);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->newWindow();
brows->switchToWindow(3);
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->getWindow(1);
brows->closeWindow();
brows->getWindow(5);
brows->getWindow(7);
delete brows;
}
	return 0;
}