#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("o", "ll","ooo");
Tab B = Tab("jjj", "bb","ee");
Tab C = Tab("x", "u","bbb");
Tab D = Tab("kkk", "rrr","kkk");
Tab E = Tab("uuu", "bb","j");
Tab F = Tab("jj", "ss","zzz");
Tab G = Tab("mm", "g","t");
Tab H = Tab("qqq", "h","ccc");
Tab I = Tab("ee", "t","oo");
Tab J = Tab("p", "jj","i");
Tab K = Tab("ppp", "ccc","ddd");
Tab L = Tab("g", "gg","jj");
Tab M = Tab("aaa", "a","t");
Tab N = Tab("vvv", "vvv","sss");
Tab O = Tab("x", "ff","yyy");
Tab P = Tab("kkk", "l","g");
Tab Q = Tab("x", "ee","cc");
Tab R = Tab("ccc", "pp","aaa");
Tab S = Tab("uuu", "i","e");
Tab T = Tab("xxx", "kkk","u");
Tab U = Tab("ww", "eee","ii");
Tab V = Tab("o", "eee","ii");
Tab W = Tab("rrr", "t","ii");
Tab X = Tab("yy", "rr","o");
Tab Y = Tab("mm", "z","u");
Tab Z = Tab("mm", "u","i");
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(A);
d.moveActiveTabTo(5);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(B);
d.changeActiveTabTo(2);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(C);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(D);
a.newTab(E);
b.changeActiveTabTo(1);
c.newTab(F);
d.newTab(G);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(H);
b.newTab(I);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(J);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(K);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(L);
b.newTab(M);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(N);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(O);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.newTab(P);
d.changeActiveTabTo(1);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(5);
b.newTab(Q);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(R);
b.moveActiveTabTo(0);
c.newTab(S);
d.changeActiveTabTo(0);
a.moveActiveTabTo(3);
b.newTab(T);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(U);
b.newTab(V);
c.newTab(W);
d.changeActiveTabTo(5);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(X);
a.newTab(Y);
b.newTab(Z);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
b.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
d.changeActiveTabTo(5);
d.moveActiveTabTo(2);
a.moveActiveTabTo(5);
c.moveActiveTabTo(5);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(9);
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->getWindow(5);
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->switchToWindow(2);
brows->getWindow(4);
brows->getWindow(5);
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->getWindow(2);
brows->mergeAllWindows();
brows->getWindow(1);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->print();
brows->closeWindow();
brows->getWindow(3);
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(5);
brows->newWindow();
brows->getWindow(4);
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->newWindow();
brows->getWindow(2);
brows->closeWindow();
brows->switchToWindow(3);
brows->getWindow(6);
brows->print();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->switchToWindow(2);
brows->print();
brows->getWindow(8);
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->getWindow(1);
brows->getWindow(0);
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(4);
brows->switchToWindow(3);
brows->switchToWindow(8);
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->newWindow();
brows->getWindow(3);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->getWindow(5);
brows->print();
brows->switchToWindow(7);
brows->newWindow();
brows->switchToWindow(6);
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->closeWindow();
delete brows;
}
	return 0;
}