#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("i", "ll","sss");
Tab B = Tab("p", "nn","j");
Tab C = Tab("jj", "ss","xx");
Tab D = Tab("cc", "h","s");
Tab E = Tab("mmm", "r","www");
Tab F = Tab("qqq", "xxx","yy");
Tab G = Tab("c", "f","z");
Tab H = Tab("c", "ss","qqq");
Tab I = Tab("nnn", "yy","ff");
Tab J = Tab("eee", "l","uuu");
Tab K = Tab("ee", "aaa","zz");
Tab L = Tab("www", "ooo","bbb");
Tab M = Tab("tt", "ss","k");
Tab N = Tab("aa", "o","xx");
Tab O = Tab("aaa", "ee","ll");
Tab P = Tab("vvv", "q","c");
Tab Q = Tab("aaa", "ooo","r");
Tab R = Tab("s", "rrr","nn");
Tab S = Tab("aa", "v","r");
Tab T = Tab("xxx", "aaa","qqq");
Tab U = Tab("s", "yy","eee");
Tab V = Tab("uu", "eee","aa");
Tab W = Tab("uu", "rr","k");
Tab X = Tab("yy", "dd","www");
Tab Y = Tab("iii", "rr","a");
Tab Z = Tab("nnn", "zzz","xx");
a.newTab(A);
b.newTab(B);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(C);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.newTab(D);
b.moveActiveTabTo(0);
c.newTab(E);
d.changeActiveTabTo(0);
a.changeActiveTabTo(2);
b.newTab(F);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(G);
b.newTab(H);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(I);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(J);
a.newTab(K);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(L);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.newTab(M);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(0);
b.newTab(N);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(O);
d.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(P);
d.changeActiveTabTo(4);
a.moveActiveTabTo(5);
b.newTab(Q);
c.newTab(R);
d.changeActiveTabTo(5);
a.newTab(S);
b.newTab(T);
c.changeActiveTabTo(4);
d.newTab(U);
a.newTab(V);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(W);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(X);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(Y);
b.newTab(Z);
c.newTab(Z);
d.moveActiveTabTo(3);
b.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
c.moveActiveTabTo(1);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
c.changeActiveTabTo(4);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
a.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(1);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->getWindow(9);
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(9);
brows->newWindow();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(8);
brows->print();
brows->getWindow(4);
brows->print();
brows->closeWindow();
brows->getWindow(8);
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(4);
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->getWindow(1);
brows->switchToWindow(6);
brows->closeWindow();
brows->getWindow(1);
brows->getWindow(0);
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(0);
brows->switchToWindow(1);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(0);
brows->getWindow(8);
brows->newWindow();
brows->print();
brows->getWindow(4);
brows->print();
brows->switchToWindow(8);
brows->closeWindow();
brows->switchToWindow(7);
brows->print();
brows->print();
brows->getWindow(5);
brows->getWindow(0);
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(1);
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->getWindow(9);
brows->getWindow(3);
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->getWindow(9);
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(3);
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->getWindow(3);
brows->print();
brows->switchToWindow(2);
brows->switchToWindow(9);
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(1);
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->print();
brows->closeWindow();
delete brows;
}
	return 0;
}