#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("r", "hhh","jj");
Tab B = Tab("b", "rrr","ee");
Tab C = Tab("jjj", "f","jj");
Tab D = Tab("g", "r","xx");
Tab E = Tab("ooo", "ss","b");
Tab F = Tab("bb", "jjj","uuu");
Tab G = Tab("rrr", "fff","l");
Tab H = Tab("nnn", "ggg","fff");
Tab I = Tab("z", "x","d");
Tab J = Tab("vvv", "jj","kkk");
Tab K = Tab("z", "j","ggg");
Tab L = Tab("z", "oo","cc");
Tab M = Tab("d", "ttt","x");
Tab N = Tab("p", "ppp","vvv");
Tab O = Tab("kk", "fff","qqq");
Tab P = Tab("xx", "e","a");
Tab Q = Tab("aa", "ooo","vvv");
Tab R = Tab("ggg", "ppp","bbb");
Tab S = Tab("xxx", "vv","u");
Tab T = Tab("c", "gg","ww");
Tab U = Tab("d", "sss","f");
Tab V = Tab("mmm", "www","oo");
Tab W = Tab("ddd", "ii","ll");
Tab X = Tab("www", "u","eee");
Tab Y = Tab("ee", "oo","ii");
Tab Z = Tab("nnn", "cc","ss");
a.moveActiveTabTo(4);
b.newTab(A);
c.newTab(B);
d.moveActiveTabTo(4);
a.newTab(C);
b.newTab(D);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(E);
d.newTab(F);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(G);
d.newTab(H);
a.newTab(I);
b.newTab(J);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(K);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(L);
d.changeActiveTabTo(4);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(M);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(N);
d.changeActiveTabTo(5);
a.newTab(O);
b.moveActiveTabTo(3);
c.newTab(P);
d.changeActiveTabTo(3);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(Q);
d.moveActiveTabTo(3);
a.moveActiveTabTo(4);
b.newTab(R);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(S);
a.newTab(T);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(U);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(V);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.newTab(W);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(X);
d.changeActiveTabTo(3);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(Y);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(Z);
d.newTab(Z);
d.moveActiveTabTo(1);
a.moveActiveTabTo(2);
c.changeActiveTabTo(2);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
a.moveActiveTabTo(4);
b.moveActiveTabTo(5);
d.changeActiveTabTo(0);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
b.moveActiveTabTo(0);
d.changeActiveTabTo(0);
b.moveActiveTabTo(5);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
d.changeActiveTabTo(3);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->getWindow(4);
brows->getWindow(4);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->print();
brows->getWindow(9);
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->getWindow(7);
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(7);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->newWindow();
brows->getWindow(9);
brows->closeEmptyWindows();
brows->getWindow(1);
brows->newWindow();
brows->getWindow(1);
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->getWindow(9);
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(2);
brows->print();
brows->switchToWindow(0);
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(0);
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(2);
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->getWindow(6);
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(4);
brows->print();
brows->closeWindow();
brows->switchToWindow(0);
brows->closeWindow();
brows->getWindow(2);
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->closeWindow();
brows->switchToWindow(3);
brows->newWindow();
brows->getWindow(1);
brows->getWindow(2);
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->getWindow(7);
delete brows;
}
	return 0;
}