#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("mmm", "ggg","k");
Tab B = Tab("w", "d","e");
Tab C = Tab("g", "ttt","mmm");
Tab D = Tab("h", "oo","vv");
Tab E = Tab("r", "kk","uuu");
Tab F = Tab("g", "ww","fff");
Tab G = Tab("mm", "e","oo");
Tab H = Tab("cc", "fff","v");
Tab I = Tab("jj", "r","bbb");
Tab J = Tab("tt", "ddd","y");
Tab K = Tab("bbb", "b","jj");
Tab L = Tab("g", "cc","vvv");
Tab M = Tab("xxx", "r","l");
Tab N = Tab("eee", "g","aa");
Tab O = Tab("nn", "gg","ttt");
Tab P = Tab("n", "p","i");
Tab Q = Tab("aa", "ccc","k");
Tab R = Tab("zzz", "uu","y");
Tab S = Tab("mm", "zz","ttt");
Tab T = Tab("m", "uuu","j");
Tab U = Tab("o", "n","w");
Tab V = Tab("w", "i","e");
Tab W = Tab("p", "zz","l");
Tab X = Tab("ee", "ggg","ttt");
Tab Y = Tab("jj", "tt","vvv");
Tab Z = Tab("yyy", "i","ee");
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(A);
a.newTab(B);
b.newTab(C);
c.newTab(D);
d.changeActiveTabTo(5);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(4);
b.newTab(E);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(F);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(G);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(H);
d.changeActiveTabTo(2);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(I);
d.changeActiveTabTo(5);
a.newTab(J);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(K);
b.changeActiveTabTo(3);
c.newTab(L);
d.newTab(M);
a.newTab(N);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(O);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(P);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(Q);
d.newTab(R);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(S);
d.newTab(T);
a.changeActiveTabTo(4);
b.newTab(U);
c.newTab(V);
d.changeActiveTabTo(4);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(5);
b.newTab(W);
c.newTab(X);
d.moveActiveTabTo(5);
a.changeActiveTabTo(5);
b.newTab(Y);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(3);
b.newTab(Z);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
a.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(4);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
d.moveActiveTabTo(1);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
b.changeActiveTabTo(3);
d.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->switchToWindow(7);
brows->closeWindow();
brows->getWindow(2);
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(5);
brows->getWindow(7);
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->getWindow(9);
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->getWindow(0);
brows->newWindow();
brows->getWindow(9);
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->getWindow(1);
brows->print();
brows->getWindow(9);
brows->print();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(1);
brows->switchToWindow(5);
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(1);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(8);
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(5);
brows->switchToWindow(8);
brows->print();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(6);
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(8);
brows->switchToWindow(1);
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(9);
brows->closeWindow();
brows->switchToWindow(9);
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->closeWindow();
delete brows;
}
	return 0;
}