#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("f", "jj","lll");
Tab B = Tab("v", "ggg","dd");
Tab C = Tab("dd", "s","v");
Tab D = Tab("ggg", "r","www");
Tab E = Tab("uu", "nn","qqq");
Tab F = Tab("ww", "ttt","uu");
Tab G = Tab("y", "e","ee");
Tab H = Tab("a", "s","w");
Tab I = Tab("z", "yyy","p");
Tab J = Tab("ooo", "h","aa");
Tab K = Tab("mmm", "s","n");
Tab L = Tab("qq", "www","s");
Tab M = Tab("y", "bbb","ss");
Tab N = Tab("n", "vv","a");
Tab O = Tab("jj", "ee","ss");
Tab P = Tab("xx", "t","n");
Tab Q = Tab("ll", "w","nn");
Tab R = Tab("jj", "sss","ww");
Tab S = Tab("mm", "rrr","eee");
Tab T = Tab("pp", "ss","w");
Tab U = Tab("rrr", "jjj","tt");
Tab V = Tab("e", "gg","zz");
Tab W = Tab("ss", "aaa","rr");
Tab X = Tab("e", "mmm","z");
Tab Y = Tab("nn", "rrr","kkk");
Tab Z = Tab("ccc", "ii","ii");
a.newTab(A);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.newTab(B);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(C);
d.changeActiveTabTo(3);
a.newTab(D);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(E);
a.newTab(F);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(G);
a.newTab(H);
b.moveActiveTabTo(4);
c.newTab(I);
d.newTab(J);
a.moveActiveTabTo(5);
b.newTab(K);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(3);
b.newTab(L);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(3);
b.newTab(M);
c.newTab(N);
d.changeActiveTabTo(3);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(O);
d.changeActiveTabTo(5);
a.newTab(P);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(Q);
a.changeActiveTabTo(2);
b.newTab(R);
c.moveActiveTabTo(2);
d.newTab(S);
a.changeActiveTabTo(3);
b.newTab(T);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(U);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(V);
a.moveActiveTabTo(4);
b.newTab(W);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(X);
a.newTab(Y);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(Z);
b.newTab(Z);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(3);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
d.moveActiveTabTo(1);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(5);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->print();
brows->getWindow(6);
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->getWindow(4);
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->getWindow(5);
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(3);
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(5);
brows->getWindow(5);
brows->closeEmptyWindows();
brows->getWindow(8);
brows->mergeAllWindows();
brows->print();
brows->getWindow(8);
brows->switchToWindow(2);
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(6);
brows->newWindow();
brows->switchToWindow(7);
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->getWindow(9);
brows->print();
brows->newWindow();
brows->getWindow(2);
brows->switchToWindow(3);
brows->closeWindow();
brows->getWindow(5);
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->getWindow(7);
brows->getWindow(2);
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->newWindow();
brows->print();
brows->getWindow(4);
brows->getWindow(9);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(3);
brows->getWindow(5);
brows->getWindow(8);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(0);
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(7);
brows->getWindow(6);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(5);
brows->switchToWindow(6);
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->switchToWindow(7);
delete brows;
}
	return 0;
}