#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("d", "kk","ddd");
Tab B = Tab("g", "kk","b");
Tab C = Tab("ccc", "f","d");
Tab D = Tab("f", "hh","ddd");
Tab E = Tab("hhh", "ll","p");
Tab F = Tab("w", "yyy","nnn");
Tab G = Tab("ggg", "t","uuu");
Tab H = Tab("ccc", "nn","h");
Tab I = Tab("ccc", "ttt","jj");
Tab J = Tab("aa", "www","fff");
Tab K = Tab("hh", "xxx","e");
Tab L = Tab("ff", "v","uuu");
Tab M = Tab("fff", "e","dd");
Tab N = Tab("eee", "x","u");
Tab O = Tab("gg", "aa","hhh");
Tab P = Tab("lll", "j","gg");
Tab Q = Tab("zz", "i","w");
Tab R = Tab("dd", "y","xx");
Tab S = Tab("uuu", "d","kkk");
Tab T = Tab("q", "i","ll");
Tab U = Tab("ll", "z","sss");
Tab V = Tab("p", "xx","u");
Tab W = Tab("ttt", "f","h");
Tab X = Tab("u", "jjj","mm");
Tab Y = Tab("kk", "h","pp");
Tab Z = Tab("kk", "aa","n");
a.moveActiveTabTo(1);
b.newTab(A);
c.newTab(B);
d.moveActiveTabTo(1);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(C);
d.newTab(D);
a.newTab(E);
b.newTab(F);
c.changeActiveTabTo(1);
d.newTab(G);
a.moveActiveTabTo(2);
b.newTab(H);
c.newTab(I);
d.changeActiveTabTo(2);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(J);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.newTab(K);
b.newTab(L);
c.newTab(M);
d.newTab(N);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(O);
d.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.newTab(P);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(Q);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.newTab(R);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.newTab(S);
c.newTab(T);
d.changeActiveTabTo(0);
a.newTab(U);
b.newTab(V);
c.changeActiveTabTo(1);
d.newTab(W);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(X);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(1);
b.newTab(Y);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(3);
b.newTab(Z);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
b.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
d.moveActiveTabTo(4);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->newWindow();
brows->getWindow(7);
brows->getWindow(8);
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->switchToWindow(1);
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(0);
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->print();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(6);
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->closeWindow();
brows->getWindow(0);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->closeWindow();
brows->switchToWindow(5);
brows->switchToWindow(3);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(5);
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->switchToWindow(5);
brows->getWindow(3);
brows->print();
brows->switchToWindow(9);
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(8);
brows->switchToWindow(9);
brows->newWindow();
brows->getWindow(2);
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->getWindow(0);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(1);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(3);
brows->getWindow(9);
brows->closeWindow();
brows->switchToWindow(9);
brows->print();
brows->closeWindow();
brows->newWindow();
brows->getWindow(8);
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->mergeAllWindows();
brows->print();
brows->getWindow(4);
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(0);
brows->getWindow(7);
brows->closeEmptyWindows();
brows->getWindow(7);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(4);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(4);
brows->print();
brows->print();
brows->switchToWindow(4);
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(5);
brows->print();
brows->print();
brows->newWindow();
brows->getWindow(4);
brows->print();
delete brows;
}
	return 0;
}