#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("v", "l","u");
Tab B = Tab("hhh", "iii","h");
Tab C = Tab("xx", "ii","ccc");
Tab D = Tab("ddd", "cc","p");
Tab E = Tab("cc", "d","dd");
Tab F = Tab("p", "o","l");
Tab G = Tab("vvv", "uu","rr");
Tab H = Tab("s", "dd","xxx");
Tab I = Tab("aa", "jjj","ee");
Tab J = Tab("u", "v","iii");
Tab K = Tab("d", "ggg","mmm");
Tab L = Tab("l", "uu","ll");
Tab M = Tab("ww", "ii","ggg");
Tab N = Tab("jj", "h","g");
Tab O = Tab("t", "qq","bbb");
Tab P = Tab("o", "g","r");
Tab Q = Tab("g", "ll","xxx");
Tab R = Tab("nn", "ggg","r");
Tab S = Tab("q", "z","kk");
Tab T = Tab("zz", "vvv","c");
Tab U = Tab("ff", "s","bbb");
Tab V = Tab("jj", "qqq","x");
Tab W = Tab("eee", "uu","ee");
Tab X = Tab("zz", "g","sss");
Tab Y = Tab("o", "h","q");
Tab Z = Tab("gg", "ddd","rr");
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.newTab(A);
d.changeActiveTabTo(1);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(B);
b.newTab(C);
c.moveActiveTabTo(4);
d.newTab(D);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(4);
b.newTab(E);
c.newTab(F);
d.newTab(G);
a.newTab(H);
b.newTab(I);
c.moveActiveTabTo(5);
d.newTab(J);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.newTab(K);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(L);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(M);
a.changeActiveTabTo(3);
b.newTab(N);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(1);
b.newTab(O);
c.newTab(P);
d.moveActiveTabTo(1);
a.newTab(Q);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(2);
b.newTab(R);
c.newTab(S);
d.newTab(T);
a.moveActiveTabTo(3);
b.newTab(U);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(3);
b.newTab(V);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(W);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(4);
b.newTab(X);
c.changeActiveTabTo(4);
d.newTab(Y);
a.changeActiveTabTo(5);
b.newTab(Z);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(3);
c.changeActiveTabTo(3);
b.moveActiveTabTo(4);
d.moveActiveTabTo(4);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
d.moveActiveTabTo(3);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(3);
d.changeActiveTabTo(3);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
d.changeActiveTabTo(0);
b.moveActiveTabTo(1);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
c.moveActiveTabTo(2);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
d.changeActiveTabTo(0);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->getWindow(0);
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->switchToWindow(6);
brows->switchToWindow(6);
brows->switchToWindow(1);
brows->getWindow(1);
brows->getWindow(8);
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->newWindow();
brows->newWindow();
brows->switchToWindow(5);
brows->print();
brows->closeWindow();
brows->getWindow(9);
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->print();
brows->switchToWindow(9);
brows->closeWindow();
brows->getWindow(9);
brows->mergeAllWindows();
brows->getWindow(7);
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->getWindow(7);
brows->getWindow(3);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->getWindow(0);
brows->getWindow(8);
brows->newWindow();
brows->switchToWindow(2);
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->getWindow(5);
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(3);
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(2);
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(3);
brows->print();
brows->getWindow(1);
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(3);
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(5);
brows->newWindow();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
delete brows;
}
	return 0;
}