#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("g", "vvv","sss");
Tab B = Tab("ooo", "pp","yyy");
Tab C = Tab("m", "hhh","v");
Tab D = Tab("k", "lll","ss");
Tab E = Tab("kk", "bb","uu");
Tab F = Tab("rr", "r","uu");
Tab G = Tab("l", "lll","hh");
Tab H = Tab("ccc", "k","hh");
Tab I = Tab("ooo", "o","ww");
Tab J = Tab("t", "s","qqq");
Tab K = Tab("ii", "ff","gg");
Tab L = Tab("p", "tt","ss");
Tab M = Tab("xxx", "v","eee");
Tab N = Tab("pp", "d","j");
Tab O = Tab("uu", "t","lll");
Tab P = Tab("iii", "yyy","g");
Tab Q = Tab("qq", "kkk","qq");
Tab R = Tab("r", "ppp","kk");
Tab S = Tab("rrr", "ii","oo");
Tab T = Tab("w", "hh","mm");
Tab U = Tab("p", "bb","ooo");
Tab V = Tab("vvv", "q","i");
Tab W = Tab("ggg", "w","b");
Tab X = Tab("jjj", "aaa","l");
Tab Y = Tab("oo", "hhh","qq");
Tab Z = Tab("sss", "gg","r");
a.newTab(A);
b.moveActiveTabTo(0);
c.newTab(B);
d.moveActiveTabTo(0);
a.changeActiveTabTo(0);
b.newTab(C);
c.moveActiveTabTo(0);
d.newTab(D);
a.moveActiveTabTo(1);
b.newTab(E);
c.newTab(F);
d.changeActiveTabTo(1);
a.moveActiveTabTo(2);
b.newTab(G);
c.newTab(H);
d.changeActiveTabTo(2);
a.changeActiveTabTo(2);
b.newTab(I);
c.newTab(J);
d.changeActiveTabTo(2);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(4);
b.newTab(K);
c.newTab(L);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
b.newTab(M);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(N);
d.newTab(O);
a.changeActiveTabTo(2);
b.newTab(P);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(Q);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(R);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(S);
d.newTab(T);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(U);
a.newTab(V);
b.changeActiveTabTo(4);
c.newTab(W);
d.newTab(X);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(Y);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.newTab(Z);
d.newTab(Z);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
d.changeActiveTabTo(3);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
c.changeActiveTabTo(3);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
c.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
c.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
b.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->switchToWindow(9);
brows->print();
brows->print();
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(9);
brows->newWindow();
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->getWindow(9);
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->getWindow(3);
brows->switchToWindow(7);
brows->print();
brows->getWindow(7);
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->newWindow();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->print();
brows->switchToWindow(4);
brows->newWindow();
brows->getWindow(5);
brows->newWindow();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->getWindow(5);
brows->closeWindow();
brows->switchToWindow(9);
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->print();
brows->print();
brows->switchToWindow(1);
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->getWindow(4);
brows->closeWindow();
brows->switchToWindow(9);
brows->getWindow(0);
brows->newWindow();
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->newWindow();
brows->switchToWindow(3);
brows->switchToWindow(8);
brows->print();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(0);
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(8);
brows->print();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(5);
brows->getWindow(9);
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->getWindow(4);
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->print();
delete brows;
}
	return 0;
}