#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("ggg", "qqq","ff");
Tab B = Tab("ii", "gg","eee");
Tab C = Tab("u", "qqq","g");
Tab D = Tab("u", "jj","mmm");
Tab E = Tab("e", "kkk","x");
Tab F = Tab("vvv", "y","ii");
Tab G = Tab("uu", "kk","oo");
Tab H = Tab("zz", "zz","nn");
Tab I = Tab("bbb", "ii","k");
Tab J = Tab("k", "dd","f");
Tab K = Tab("jjj", "t","k");
Tab L = Tab("hh", "oo","gg");
Tab M = Tab("iii", "ee","vv");
Tab N = Tab("aa", "o","o");
Tab O = Tab("ttt", "ii","bb");
Tab P = Tab("xxx", "a","aa");
Tab Q = Tab("mm", "t","ddd");
Tab R = Tab("u", "aa","ii");
Tab S = Tab("eee", "uuu","xx");
Tab T = Tab("yyy", "y","uu");
Tab U = Tab("ii", "a","ccc");
Tab V = Tab("eee", "e","ee");
Tab W = Tab("ccc", "q","g");
Tab X = Tab("g", "rrr","k");
Tab Y = Tab("s", "fff","yy");
Tab Z = Tab("nnn", "j","i");
a.newTab(A);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(2);
b.newTab(B);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(C);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
b.newTab(D);
c.newTab(E);
d.moveActiveTabTo(2);
a.newTab(F);
b.changeActiveTabTo(0);
c.newTab(G);
d.changeActiveTabTo(0);
a.newTab(H);
b.newTab(I);
c.newTab(J);
d.moveActiveTabTo(4);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(K);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(L);
a.moveActiveTabTo(1);
b.newTab(M);
c.newTab(N);
d.changeActiveTabTo(1);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.newTab(O);
d.moveActiveTabTo(2);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(P);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(Q);
a.newTab(R);
b.newTab(S);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(T);
a.newTab(U);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(V);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(W);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(X);
d.moveActiveTabTo(5);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(Y);
d.changeActiveTabTo(4);
a.changeActiveTabTo(2);
b.newTab(Z);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
c.changeActiveTabTo(3);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
a.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
d.changeActiveTabTo(0);
b.moveActiveTabTo(1);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->switchToWindow(6);
brows->print();
brows->switchToWindow(7);
brows->getWindow(5);
brows->closeEmptyWindows();
brows->print();
brows->getWindow(7);
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->getWindow(1);
brows->closeWindow();
brows->getWindow(0);
brows->switchToWindow(5);
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(6);
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->getWindow(2);
brows->closeWindow();
brows->print();
brows->switchToWindow(9);
brows->getWindow(6);
brows->switchToWindow(4);
brows->getWindow(1);
brows->print();
brows->newWindow();
brows->getWindow(6);
brows->getWindow(4);
brows->closeWindow();
brows->switchToWindow(0);
brows->closeWindow();
brows->getWindow(0);
brows->switchToWindow(1);
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(3);
brows->print();
brows->getWindow(0);
brows->getWindow(3);
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(1);
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->getWindow(3);
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->print();
brows->newWindow();
brows->newWindow();
brows->getWindow(5);
brows->getWindow(0);
brows->switchToWindow(9);
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(0);
brows->getWindow(9);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(0);
brows->getWindow(5);
brows->closeEmptyWindows();
brows->print();
brows->getWindow(6);
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->getWindow(1);
brows->closeEmptyWindows();
delete brows;
}
	return 0;
}