#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("yy", "f","cc");
Tab B = Tab("u", "m","dd");
Tab C = Tab("d", "o","ccc");
Tab D = Tab("aa", "lll","vvv");
Tab E = Tab("w", "hhh","jjj");
Tab F = Tab("g", "ss","jjj");
Tab G = Tab("rr", "yyy","hhh");
Tab H = Tab("y", "pp","ee");
Tab I = Tab("z", "z","xx");
Tab J = Tab("e", "iii","zz");
Tab K = Tab("a", "ll","ooo");
Tab L = Tab("xxx", "mmm","cc");
Tab M = Tab("b", "j","q");
Tab N = Tab("u", "m","g");
Tab O = Tab("cc", "e","fff");
Tab P = Tab("jj", "yyy","ccc");
Tab Q = Tab("xxx", "rrr","ff");
Tab R = Tab("yy", "ttt","hh");
Tab S = Tab("bbb", "k","nn");
Tab T = Tab("ll", "v","ttt");
Tab U = Tab("aaa", "ccc","n");
Tab V = Tab("oo", "ff","ee");
Tab W = Tab("oo", "s","cc");
Tab X = Tab("i", "pp","bb");
Tab Y = Tab("rrr", "hh","i");
Tab Z = Tab("c", "kkk","zz");
a.newTab(A);
b.newTab(B);
c.moveActiveTabTo(0);
d.newTab(C);
a.changeActiveTabTo(4);
b.newTab(D);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(E);
b.newTab(F);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.newTab(G);
b.changeActiveTabTo(4);
c.newTab(H);
d.changeActiveTabTo(4);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(I);
d.newTab(J);
a.newTab(K);
b.changeActiveTabTo(5);
c.newTab(L);
d.newTab(M);
a.newTab(N);
b.newTab(O);
c.newTab(P);
d.changeActiveTabTo(1);
a.newTab(Q);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(5);
b.newTab(R);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(S);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(T);
a.newTab(U);
b.moveActiveTabTo(1);
c.newTab(V);
d.newTab(W);
a.changeActiveTabTo(3);
b.newTab(X);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(Y);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(Z);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(4);
a.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
d.changeActiveTabTo(3);
b.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.moveActiveTabTo(3);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.changeActiveTabTo(5);
b.moveActiveTabTo(2);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(1);
c.changeActiveTabTo(1);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.moveActiveTabTo(1);
c.changeActiveTabTo(1);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
b.changeActiveTabTo(4);
b.changeActiveTabTo(3);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
d.moveActiveTabTo(1);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->getWindow(3);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->newWindow();
brows->switchToWindow(2);
brows->newWindow();
brows->switchToWindow(9);
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(5);
brows->print();
brows->print();
brows->closeWindow();
brows->switchToWindow(1);
brows->getWindow(4);
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->print();
brows->switchToWindow(3);
brows->mergeAllWindows();
brows->getWindow(9);
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->newWindow();
brows->switchToWindow(2);
brows->print();
brows->getWindow(1);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(4);
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(4);
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->getWindow(6);
brows->print();
brows->print();
brows->switchToWindow(2);
brows->getWindow(0);
brows->switchToWindow(5);
brows->switchToWindow(4);
brows->switchToWindow(8);
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(1);
brows->newWindow();
brows->switchToWindow(8);
brows->getWindow(1);
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->getWindow(2);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->getWindow(3);
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->getWindow(2);
brows->print();
brows->switchToWindow(8);
brows->switchToWindow(9);
brows->closeWindow();
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(5);
brows->print();
brows->newWindow();
brows->getWindow(7);
delete brows;
}
	return 0;
}