#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("z", "qqq","q");
Tab B = Tab("cc", "zz","oo");
Tab C = Tab("k", "rrr","t");
Tab D = Tab("e", "ooo","f");
Tab E = Tab("ccc", "jj","ww");
Tab F = Tab("iii", "r","bb");
Tab G = Tab("ee", "c","cc");
Tab H = Tab("ss", "mm","ooo");
Tab I = Tab("qqq", "kk","ccc");
Tab J = Tab("bb", "oo","nn");
Tab K = Tab("ggg", "xxx","o");
Tab L = Tab("ggg", "u","ggg");
Tab M = Tab("ww", "j","zz");
Tab N = Tab("s", "ttt","uu");
Tab O = Tab("t", "hhh","aaa");
Tab P = Tab("qq", "z","u");
Tab Q = Tab("w", "gg","hh");
Tab R = Tab("c", "c","t");
Tab S = Tab("h", "ss","a");
Tab T = Tab("e", "jj","dd");
Tab U = Tab("x", "qq","fff");
Tab V = Tab("vvv", "qq","aaa");
Tab W = Tab("d", "tt","o");
Tab X = Tab("uu", "ttt","ttt");
Tab Y = Tab("aa", "u","c");
Tab Z = Tab("a", "s","oo");
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(A);
d.changeActiveTabTo(3);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.newTab(B);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(C);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(3);
b.newTab(D);
c.newTab(E);
d.moveActiveTabTo(3);
a.newTab(F);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(G);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(H);
a.newTab(I);
b.newTab(J);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(K);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
b.newTab(L);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(M);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.newTab(N);
a.newTab(O);
b.changeActiveTabTo(5);
c.newTab(P);
d.changeActiveTabTo(5);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(Q);
d.newTab(R);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(S);
d.newTab(T);
a.newTab(U);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(V);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(W);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(X);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(0);
b.newTab(Y);
c.moveActiveTabTo(0);
d.newTab(Z);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(1);
c.changeActiveTabTo(1);
a.changeActiveTabTo(0);
d.changeActiveTabTo(0);
b.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
d.moveActiveTabTo(2);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
b.changeActiveTabTo(3);
d.changeActiveTabTo(3);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->getWindow(4);
brows->switchToWindow(7);
brows->newWindow();
brows->getWindow(6);
brows->print();
brows->switchToWindow(1);
brows->closeWindow();
brows->print();
brows->print();
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->getWindow(0);
brows->switchToWindow(5);
brows->switchToWindow(3);
brows->getWindow(9);
brows->print();
brows->newWindow();
brows->getWindow(0);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(2);
brows->switchToWindow(9);
brows->getWindow(1);
brows->closeWindow();
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->switchToWindow(3);
brows->getWindow(9);
brows->mergeAllWindows();
brows->print();
brows->print();
brows->getWindow(2);
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(7);
brows->closeWindow();
brows->print();
brows->print();
brows->print();
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->print();
brows->getWindow(7);
brows->newWindow();
brows->getWindow(5);
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->getWindow(5);
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->switchToWindow(5);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(2);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->mergeAllWindows();
brows->getWindow(3);
brows->getWindow(5);
brows->getWindow(8);
brows->print();
brows->getWindow(8);
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->closeWindow();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->getWindow(9);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(0);
brows->getWindow(3);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(7);
delete brows;
}
	return 0;
}