#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("g", "xx","pp");
Tab B = Tab("u", "b","i");
Tab C = Tab("oo", "ccc","yy");
Tab D = Tab("kkk", "aaa","mm");
Tab E = Tab("v", "x","hhh");
Tab F = Tab("sss", "kk","hh");
Tab G = Tab("vv", "ii","ss");
Tab H = Tab("mmm", "zzz","ooo");
Tab I = Tab("vvv", "ff","ooo");
Tab J = Tab("ii", "aa","x");
Tab K = Tab("hh", "cc","kkk");
Tab L = Tab("ppp", "mm","m");
Tab M = Tab("aaa", "c","y");
Tab N = Tab("hh", "uu","w");
Tab O = Tab("ww", "c","m");
Tab P = Tab("u", "aa","aa");
Tab Q = Tab("uu", "t","qq");
Tab R = Tab("lll", "tt","u");
Tab S = Tab("uu", "j","eee");
Tab T = Tab("rr", "xx","bb");
Tab U = Tab("jj", "f","iii");
Tab V = Tab("eee", "zz","y");
Tab W = Tab("o", "bbb","hhh");
Tab X = Tab("ee", "z","v");
Tab Y = Tab("r", "hh","z");
Tab Z = Tab("zz", "hhh","qq");
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(A);
a.newTab(B);
b.newTab(C);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(2);
b.newTab(D);
c.newTab(E);
d.newTab(F);
a.moveActiveTabTo(0);
b.newTab(G);
c.newTab(H);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.newTab(I);
c.newTab(J);
d.moveActiveTabTo(5);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(1);
b.newTab(K);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(L);
d.newTab(M);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(N);
d.newTab(O);
a.changeActiveTabTo(3);
b.newTab(P);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(Q);
b.newTab(R);
c.newTab(S);
d.newTab(T);
a.newTab(U);
b.newTab(V);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(W);
b.moveActiveTabTo(3);
c.newTab(X);
d.moveActiveTabTo(3);
a.changeActiveTabTo(2);
b.newTab(Y);
c.newTab(Z);
d.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(3);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
d.moveActiveTabTo(0);
b.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(3);
c.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
a.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
c.changeActiveTabTo(0);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(0);
brows->closeWindow();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(8);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->switchToWindow(2);
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->print();
brows->getWindow(4);
brows->newWindow();
brows->newWindow();
brows->print();
brows->switchToWindow(2);
brows->switchToWindow(0);
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(7);
brows->mergeAllWindows();
brows->getWindow(6);
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(0);
brows->switchToWindow(9);
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(5);
brows->switchToWindow(0);
brows->switchToWindow(3);
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(2);
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->print();
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->switchToWindow(8);
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(8);
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->switchToWindow(6);
brows->getWindow(3);
brows->getWindow(0);
brows->print();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->switchToWindow(4);
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(7);
brows->newWindow();
brows->print();
brows->switchToWindow(5);
brows->mergeAllWindows();
delete brows;
}
	return 0;
}