#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("a", "ee","q");
Tab B = Tab("ppp", "rr","ddd");
Tab C = Tab("fff", "hhh","xx");
Tab D = Tab("l", "ttt","yyy");
Tab E = Tab("rr", "bbb","ll");
Tab F = Tab("ss", "r","uu");
Tab G = Tab("tt", "zzz","b");
Tab H = Tab("y", "u","f");
Tab I = Tab("kk", "ttt","gg");
Tab J = Tab("p", "q","mm");
Tab K = Tab("lll", "ww","k");
Tab L = Tab("h", "mmm","r");
Tab M = Tab("nn", "ttt","u");
Tab N = Tab("mmm", "cc","lll");
Tab O = Tab("pp", "uu","ggg");
Tab P = Tab("kkk", "sss","uu");
Tab Q = Tab("eee", "x","aaa");
Tab R = Tab("fff", "hhh","vvv");
Tab S = Tab("rr", "aa","zzz");
Tab T = Tab("ss", "f","b");
Tab U = Tab("p", "hh","f");
Tab V = Tab("gg", "aa","aa");
Tab W = Tab("xxx", "kk","zzz");
Tab X = Tab("rr", "yy","w");
Tab Y = Tab("u", "ss","w");
Tab Z = Tab("mm", "ooo","c");
a.newTab(A);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(B);
d.newTab(C);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(D);
d.changeActiveTabTo(3);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.newTab(E);
d.newTab(F);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(G);
d.moveActiveTabTo(5);
a.newTab(H);
b.newTab(I);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(J);
d.moveActiveTabTo(5);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(K);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(L);
a.newTab(M);
b.newTab(N);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(O);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(0);
b.newTab(P);
c.changeActiveTabTo(0);
d.newTab(Q);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(R);
d.newTab(S);
a.newTab(T);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(U);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(V);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(W);
a.newTab(X);
b.newTab(Y);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(Z);
b.changeActiveTabTo(0);
c.newTab(Z);
d.newTab(Z);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
c.moveActiveTabTo(5);
a.changeActiveTabTo(1);
c.changeActiveTabTo(1);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
b.moveActiveTabTo(2);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(7);
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->getWindow(5);
brows->newWindow();
brows->switchToWindow(7);
brows->print();
brows->switchToWindow(0);
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(6);
brows->print();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->switchToWindow(2);
brows->getWindow(7);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(4);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(3);
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->getWindow(0);
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->getWindow(5);
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->getWindow(8);
brows->closeWindow();
brows->print();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->getWindow(0);
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(0);
brows->mergeAllWindows();
brows->getWindow(7);
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->getWindow(5);
brows->print();
brows->print();
delete brows;
}
	return 0;
}