#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("iii", "x","ee");
Tab B = Tab("a", "iii","g");
Tab C = Tab("s", "v","kkk");
Tab D = Tab("dd", "b","t");
Tab E = Tab("jj", "ccc","ss");
Tab F = Tab("w", "eee","uu");
Tab G = Tab("lll", "u","t");
Tab H = Tab("h", "pp","pp");
Tab I = Tab("jj", "fff","z");
Tab J = Tab("bbb", "oo","qqq");
Tab K = Tab("p", "rr","b");
Tab L = Tab("aaa", "w","fff");
Tab M = Tab("uuu", "v","uu");
Tab N = Tab("xxx", "fff","qqq");
Tab O = Tab("h", "cc","y");
Tab P = Tab("bbb", "gg","zzz");
Tab Q = Tab("vv", "l","ttt");
Tab R = Tab("mm", "jj","xx");
Tab S = Tab("ddd", "t","fff");
Tab T = Tab("qqq", "c","eee");
Tab U = Tab("nn", "eee","nnn");
Tab V = Tab("zz", "eee","ggg");
Tab W = Tab("ggg", "t","s");
Tab X = Tab("l", "ee","ggg");
Tab Y = Tab("j", "zz","ddd");
Tab Z = Tab("vv", "qq","aa");
a.newTab(A);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(B);
d.changeActiveTabTo(3);
a.newTab(C);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.newTab(D);
c.moveActiveTabTo(4);
d.newTab(E);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(F);
d.changeActiveTabTo(4);
a.changeActiveTabTo(1);
b.newTab(G);
c.changeActiveTabTo(1);
d.newTab(H);
a.moveActiveTabTo(2);
b.newTab(I);
c.changeActiveTabTo(2);
d.newTab(J);
a.changeActiveTabTo(4);
b.newTab(K);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(3);
b.newTab(L);
c.changeActiveTabTo(3);
d.newTab(M);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(1);
b.newTab(N);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(O);
b.newTab(P);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(Q);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(R);
a.moveActiveTabTo(5);
b.newTab(S);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(1);
b.newTab(T);
c.newTab(U);
d.changeActiveTabTo(1);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(V);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(W);
b.moveActiveTabTo(4);
c.newTab(X);
d.moveActiveTabTo(4);
a.changeActiveTabTo(2);
b.newTab(Y);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(2);
b.newTab(Z);
c.moveActiveTabTo(2);
d.newTab(Z);
b.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(5);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
a.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
a.changeActiveTabTo(3);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->mergeAllWindows();
brows->switchToWindow(6);
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->print();
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->closeWindow();
brows->getWindow(2);
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(4);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(2);
brows->newWindow();
brows->print();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(2);
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(3);
brows->mergeAllWindows();
brows->switchToWindow(6);
brows->print();
brows->print();
brows->switchToWindow(2);
brows->switchToWindow(5);
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(4);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(9);
brows->switchToWindow(6);
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->getWindow(9);
brows->getWindow(6);
brows->closeWindow();
brows->switchToWindow(1);
brows->getWindow(3);
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->getWindow(9);
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(3);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(4);
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(3);
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->switchToWindow(5);
brows->print();
brows->getWindow(7);
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(4);
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(4);
brows->mergeAllWindows();
delete brows;
}
	return 0;
}