#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("hhh", "r","fff");
Tab B = Tab("v", "rrr","jjj");
Tab C = Tab("ccc", "m","u");
Tab D = Tab("aaa", "qqq","x");
Tab E = Tab("uu", "cc","s");
Tab F = Tab("xxx", "d","sss");
Tab G = Tab("xxx", "p","iii");
Tab H = Tab("ooo", "n","uu");
Tab I = Tab("e", "y","r");
Tab J = Tab("i", "u","rr");
Tab K = Tab("u", "www","aaa");
Tab L = Tab("ccc", "x","lll");
Tab M = Tab("hh", "kkk","w");
Tab N = Tab("d", "ppp","e");
Tab O = Tab("qq", "zz","ll");
Tab P = Tab("iii", "hh","ff");
Tab Q = Tab("bbb", "h","eee");
Tab R = Tab("d", "vvv","ee");
Tab S = Tab("qq", "zz","oo");
Tab T = Tab("c", "ggg","xxx");
Tab U = Tab("pp", "l","oo");
Tab V = Tab("w", "g","n");
Tab W = Tab("eee", "vv","xx");
Tab X = Tab("vv", "ooo","m");
Tab Y = Tab("qq", "qq","e");
Tab Z = Tab("o", "e","cc");
a.moveActiveTabTo(0);
b.newTab(A);
c.newTab(B);
d.moveActiveTabTo(0);
a.newTab(C);
b.newTab(D);
c.moveActiveTabTo(0);
d.newTab(E);
a.moveActiveTabTo(3);
b.newTab(F);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(G);
d.changeActiveTabTo(4);
a.changeActiveTabTo(5);
b.newTab(H);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(I);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(J);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(5);
b.newTab(K);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(L);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(M);
b.changeActiveTabTo(3);
c.newTab(N);
d.changeActiveTabTo(3);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.newTab(O);
d.newTab(P);
a.newTab(Q);
b.moveActiveTabTo(0);
c.newTab(R);
d.changeActiveTabTo(0);
a.newTab(S);
b.changeActiveTabTo(5);
c.newTab(T);
d.moveActiveTabTo(5);
a.newTab(U);
b.changeActiveTabTo(0);
c.newTab(V);
d.moveActiveTabTo(0);
a.changeActiveTabTo(0);
b.newTab(W);
c.newTab(X);
d.moveActiveTabTo(0);
a.changeActiveTabTo(1);
b.newTab(Y);
c.newTab(Z);
d.moveActiveTabTo(1);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(5);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(4);
d.moveActiveTabTo(4);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
a.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(1);
b.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
c.moveActiveTabTo(0);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
a.changeActiveTabTo(0);
d.moveActiveTabTo(0);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
d.changeActiveTabTo(2);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->print();
brows->print();
brows->getWindow(0);
brows->getWindow(3);
brows->getWindow(1);
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->print();
brows->newWindow();
brows->getWindow(8);
brows->print();
brows->print();
brows->newWindow();
brows->switchToWindow(8);
brows->getWindow(7);
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(6);
brows->switchToWindow(4);
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(3);
brows->switchToWindow(7);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(4);
brows->newWindow();
brows->getWindow(6);
brows->switchToWindow(7);
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->newWindow();
brows->getWindow(6);
brows->switchToWindow(6);
brows->print();
brows->newWindow();
brows->switchToWindow(4);
brows->newWindow();
brows->switchToWindow(6);
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(8);
brows->print();
brows->getWindow(6);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(9);
brows->getWindow(6);
brows->switchToWindow(3);
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->print();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->switchToWindow(9);
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->print();
brows->switchToWindow(3);
brows->newWindow();
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->getWindow(0);
brows->switchToWindow(5);
brows->getWindow(0);
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
delete brows;
}
	return 0;
}