#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("hhh", "zzz","ee");
Tab B = Tab("q", "ttt","p");
Tab C = Tab("uuu", "cc","hhh");
Tab D = Tab("qqq", "lll","bb");
Tab E = Tab("eee", "jj","kk");
Tab F = Tab("cc", "nn","o");
Tab G = Tab("ee", "pp","w");
Tab H = Tab("y", "fff","e");
Tab I = Tab("ttt", "l","d");
Tab J = Tab("j", "k","ww");
Tab K = Tab("eee", "mm","ii");
Tab L = Tab("qq", "k","gg");
Tab M = Tab("tt", "w","ppp");
Tab N = Tab("j", "p","u");
Tab O = Tab("eee", "i","xxx");
Tab P = Tab("w", "ll","ee");
Tab Q = Tab("e", "ddd","xxx");
Tab R = Tab("kkk", "x","t");
Tab S = Tab("k", "jj","lll");
Tab T = Tab("uu", "ee","oo");
Tab U = Tab("lll", "hhh","w");
Tab V = Tab("b", "ee","r");
Tab W = Tab("v", "uuu","w");
Tab X = Tab("h", "b","ii");
Tab Y = Tab("mm", "l","lll");
Tab Z = Tab("rr", "ppp","i");
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(5);
b.newTab(A);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(4);
b.newTab(B);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(4);
b.newTab(C);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.newTab(D);
b.newTab(E);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
b.newTab(F);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(3);
b.newTab(G);
c.newTab(H);
d.changeActiveTabTo(3);
a.newTab(I);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(J);
a.newTab(K);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(L);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(M);
a.newTab(N);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(O);
a.changeActiveTabTo(0);
b.newTab(P);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(Q);
d.changeActiveTabTo(3);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.newTab(R);
d.changeActiveTabTo(1);
a.newTab(S);
b.newTab(T);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(0);
b.newTab(U);
c.newTab(V);
d.moveActiveTabTo(0);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(W);
b.newTab(X);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(Y);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(1);
b.newTab(Z);
c.newTab(Z);
d.moveActiveTabTo(1);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
c.changeActiveTabTo(0);
c.changeActiveTabTo(2);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(2);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->getWindow(7);
brows->print();
brows->getWindow(3);
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(5);
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->print();
brows->getWindow(7);
brows->newWindow();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(1);
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(9);
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->getWindow(3);
brows->newWindow();
brows->getWindow(6);
brows->getWindow(1);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->switchToWindow(0);
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->switchToWindow(9);
brows->print();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->getWindow(6);
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->getWindow(5);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(3);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->getWindow(4);
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
delete brows;
}
	return 0;
}