#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("xxx", "pp","cc");
Tab B = Tab("rrr", "u","z");
Tab C = Tab("oo", "vvv","t");
Tab D = Tab("z", "gg","jjj");
Tab E = Tab("bb", "yyy","hh");
Tab F = Tab("t", "o","w");
Tab G = Tab("ll", "jj","a");
Tab H = Tab("z", "ll","ooo");
Tab I = Tab("jjj", "nnn","f");
Tab J = Tab("lll", "fff","ggg");
Tab K = Tab("ss", "o","g");
Tab L = Tab("e", "a","rr");
Tab M = Tab("qq", "ttt","ww");
Tab N = Tab("u", "zz","r");
Tab O = Tab("b", "kk","aaa");
Tab P = Tab("kkk", "ee","k");
Tab Q = Tab("vv", "xx","rr");
Tab R = Tab("g", "tt","qqq");
Tab S = Tab("vv", "jjj","b");
Tab T = Tab("d", "ss","gg");
Tab U = Tab("vv", "rr","vvv");
Tab V = Tab("l", "t","rr");
Tab W = Tab("lll", "sss","w");
Tab X = Tab("hhh", "jj","ss");
Tab Y = Tab("vvv", "zz","a");
Tab Z = Tab("a", "uuu","o");
a.moveActiveTabTo(1);
b.newTab(A);
c.newTab(B);
d.moveActiveTabTo(1);
a.newTab(C);
b.moveActiveTabTo(2);
c.newTab(D);
d.moveActiveTabTo(2);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(E);
b.newTab(F);
c.newTab(G);
d.newTab(H);
a.newTab(I);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(1);
b.newTab(J);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(K);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.newTab(L);
d.changeActiveTabTo(2);
a.newTab(M);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.newTab(N);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(O);
a.newTab(P);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(Q);
a.newTab(R);
b.moveActiveTabTo(1);
c.newTab(S);
d.newTab(T);
a.changeActiveTabTo(2);
b.newTab(U);
c.newTab(V);
d.newTab(W);
a.changeActiveTabTo(5);
b.newTab(X);
c.newTab(Y);
d.newTab(Z);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
d.changeActiveTabTo(3);
b.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(1);
c.changeActiveTabTo(1);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(2);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
a.moveActiveTabTo(2);
d.changeActiveTabTo(2);
b.changeActiveTabTo(4);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->getWindow(8);
brows->getWindow(7);
brows->closeEmptyWindows();
brows->switchToWindow(6);
brows->getWindow(5);
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(4);
brows->closeEmptyWindows();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(8);
brows->newWindow();
brows->switchToWindow(5);
brows->print();
brows->getWindow(0);
brows->print();
brows->switchToWindow(5);
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(4);
brows->mergeAllWindows();
brows->getWindow(3);
brows->getWindow(4);
brows->switchToWindow(6);
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->getWindow(3);
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(1);
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(9);
brows->newWindow();
brows->print();
brows->getWindow(9);
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->getWindow(2);
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(1);
brows->newWindow();
brows->getWindow(7);
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->getWindow(0);
brows->getWindow(2);
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->switchToWindow(8);
brows->print();
brows->closeEmptyWindows();
brows->getWindow(2);
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(8);
brows->print();
brows->getWindow(1);
brows->switchToWindow(3);
brows->print();
delete brows;
}
	return 0;
}