#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("jj", "lll","yy");
Tab B = Tab("mmm", "u","ppp");
Tab C = Tab("kkk", "nn","jjj");
Tab D = Tab("dd", "pp","g");
Tab E = Tab("ooo", "oo","tt");
Tab F = Tab("iii", "bb","iii");
Tab G = Tab("cc", "q","jjj");
Tab H = Tab("bb", "yy","pp");
Tab I = Tab("k", "ccc","ttt");
Tab J = Tab("mm", "jjj","ppp");
Tab K = Tab("yyy", "www","aa");
Tab L = Tab("c", "www","ooo");
Tab M = Tab("s", "ll","ccc");
Tab N = Tab("vv", "j","rrr");
Tab O = Tab("yyy", "n","gg");
Tab P = Tab("ccc", "nnn","hhh");
Tab Q = Tab("ttt", "kk","xx");
Tab R = Tab("pp", "kk","t");
Tab S = Tab("ww", "q","yyy");
Tab T = Tab("g", "mmm","ww");
Tab U = Tab("k", "iii","ppp");
Tab V = Tab("rrr", "w","hh");
Tab W = Tab("y", "y","jjj");
Tab X = Tab("ww", "uu","yy");
Tab Y = Tab("ggg", "xxx","qqq");
Tab Z = Tab("iii", "gg","ccc");
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(A);
d.newTab(B);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(C);
d.newTab(D);
a.newTab(E);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(F);
a.newTab(G);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(H);
a.moveActiveTabTo(0);
b.newTab(I);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(J);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(K);
d.moveActiveTabTo(5);
a.newTab(L);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.newTab(M);
c.newTab(N);
d.moveActiveTabTo(1);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(O);
d.moveActiveTabTo(2);
a.moveActiveTabTo(4);
b.newTab(P);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.newTab(Q);
b.moveActiveTabTo(3);
c.newTab(R);
d.moveActiveTabTo(3);
a.newTab(S);
b.newTab(T);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(4);
b.newTab(U);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(V);
b.moveActiveTabTo(4);
c.newTab(W);
d.newTab(X);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(Y);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(Z);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
c.changeActiveTabTo(4);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
b.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
d.moveActiveTabTo(2);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->getWindow(0);
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(5);
brows->getWindow(8);
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(3);
brows->mergeAllWindows();
brows->getWindow(2);
brows->print();
brows->print();
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->closeWindow();
brows->getWindow(3);
brows->getWindow(1);
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->print();
brows->print();
brows->switchToWindow(4);
brows->closeEmptyWindows();
brows->print();
brows->getWindow(7);
brows->switchToWindow(3);
brows->mergeAllWindows();
brows->getWindow(9);
brows->getWindow(9);
brows->closeWindow();
brows->print();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(8);
brows->getWindow(6);
brows->newWindow();
brows->newWindow();
brows->print();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(4);
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(6);
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(5);
brows->switchToWindow(3);
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->switchToWindow(8);
brows->getWindow(0);
brows->newWindow();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(2);
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->mergeAllWindows();
brows->getWindow(2);
brows->getWindow(3);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(3);
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->newWindow();
delete brows;
}
	return 0;
}