#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("ff", "iii","aaa");
Tab B = Tab("y", "e","t");
Tab C = Tab("gg", "aa","iii");
Tab D = Tab("jj", "nn","lll");
Tab E = Tab("ggg", "rr","ttt");
Tab F = Tab("x", "i","n");
Tab G = Tab("k", "xxx","yyy");
Tab H = Tab("ll", "mmm","kk");
Tab I = Tab("sss", "jj","ii");
Tab J = Tab("ee", "ddd","z");
Tab K = Tab("hhh", "ee","x");
Tab L = Tab("q", "qq","g");
Tab M = Tab("ddd", "a","lll");
Tab N = Tab("ff", "m","ee");
Tab O = Tab("jjj", "d","e");
Tab P = Tab("gg", "qqq","c");
Tab Q = Tab("ccc", "c","sss");
Tab R = Tab("rr", "nnn","iii");
Tab S = Tab("t", "zzz","zz");
Tab T = Tab("c", "vv","h");
Tab U = Tab("jj", "ll","ppp");
Tab V = Tab("o", "ppp","bb");
Tab W = Tab("kk", "kk","c");
Tab X = Tab("ddd", "fff","yy");
Tab Y = Tab("x", "cc","f");
Tab Z = Tab("j", "k","a");
a.changeActiveTabTo(4);
b.newTab(A);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(B);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(C);
d.changeActiveTabTo(2);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(D);
b.moveActiveTabTo(4);
c.newTab(E);
d.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(F);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(G);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.newTab(H);
a.newTab(I);
b.moveActiveTabTo(0);
c.newTab(J);
d.moveActiveTabTo(0);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(K);
d.moveActiveTabTo(0);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(L);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(M);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(N);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(1);
b.newTab(O);
c.moveActiveTabTo(1);
d.newTab(P);
a.newTab(Q);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(R);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(5);
b.newTab(S);
c.newTab(T);
d.moveActiveTabTo(5);
a.newTab(U);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(V);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(W);
a.changeActiveTabTo(4);
b.newTab(X);
c.newTab(Y);
d.newTab(Z);
b.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(2);
c.changeActiveTabTo(2);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
d.moveActiveTabTo(0);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
c.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->getWindow(4);
brows->closeEmptyWindows();
brows->getWindow(3);
brows->mergeAllWindows();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->getWindow(7);
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->newWindow();
brows->newWindow();
brows->getWindow(3);
brows->switchToWindow(2);
brows->print();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(9);
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->closeWindow();
brows->getWindow(3);
brows->closeWindow();
brows->getWindow(6);
brows->newWindow();
brows->switchToWindow(0);
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(2);
brows->print();
brows->switchToWindow(7);
brows->print();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->closeWindow();
brows->switchToWindow(5);
brows->getWindow(3);
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->closeWindow();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->getWindow(0);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(6);
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(1);
brows->closeWindow();
brows->closeWindow();
brows->getWindow(4);
brows->closeWindow();
brows->print();
brows->getWindow(0);
brows->newWindow();
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->switchToWindow(7);
brows->print();
brows->newWindow();
delete brows;
}
	return 0;
}