#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("sss", "n","z");
Tab B = Tab("zz", "k","ttt");
Tab C = Tab("m", "ggg","n");
Tab D = Tab("vv", "u","hh");
Tab E = Tab("nnn", "oo","ii");
Tab F = Tab("oo", "s","s");
Tab G = Tab("l", "ooo","p");
Tab H = Tab("hh", "lll","aa");
Tab I = Tab("w", "mmm","sss");
Tab J = Tab("a", "p","ooo");
Tab K = Tab("aa", "oo","vvv");
Tab L = Tab("q", "g","c");
Tab M = Tab("lll", "s","ww");
Tab N = Tab("ss", "f","y");
Tab O = Tab("ggg", "ooo","ss");
Tab P = Tab("rrr", "nnn","aa");
Tab Q = Tab("ddd", "eee","vvv");
Tab R = Tab("p", "uu","o");
Tab S = Tab("l", "eee","d");
Tab T = Tab("b", "www","aa");
Tab U = Tab("rrr", "ww","y");
Tab V = Tab("gg", "jj","w");
Tab W = Tab("d", "zz","p");
Tab X = Tab("gg", "uuu","p");
Tab Y = Tab("bbb", "jj","g");
Tab Z = Tab("zzz", "a","ii");
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(A);
d.moveActiveTabTo(3);
a.changeActiveTabTo(2);
b.newTab(B);
c.newTab(C);
d.moveActiveTabTo(2);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(D);
b.newTab(E);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(3);
b.newTab(F);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(G);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(H);
a.newTab(I);
b.moveActiveTabTo(0);
c.newTab(J);
d.changeActiveTabTo(0);
a.newTab(K);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(L);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(M);
b.newTab(N);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
b.newTab(O);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(P);
a.changeActiveTabTo(2);
b.newTab(Q);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(5);
b.newTab(R);
c.newTab(S);
d.newTab(T);
a.newTab(U);
b.moveActiveTabTo(1);
c.newTab(V);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.newTab(W);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(X);
b.newTab(Y);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(Z);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
b.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
a.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->closeWindow();
brows->switchToWindow(1);
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(6);
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->getWindow(3);
brows->print();
brows->print();
brows->switchToWindow(5);
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->getWindow(0);
brows->switchToWindow(5);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(4);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(4);
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->getWindow(8);
brows->closeWindow();
brows->getWindow(9);
brows->getWindow(1);
brows->switchToWindow(0);
brows->print();
brows->getWindow(3);
brows->switchToWindow(1);
brows->closeWindow();
brows->switchToWindow(5);
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(6);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(8);
brows->print();
brows->newWindow();
brows->print();
brows->getWindow(7);
brows->getWindow(0);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->switchToWindow(9);
brows->switchToWindow(8);
brows->switchToWindow(3);
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(1);
delete brows;
}
	return 0;
}