#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("xxx", "xx","nn");
Tab B = Tab("ff", "ww","ll");
Tab C = Tab("iii", "c","xx");
Tab D = Tab("f", "y","g");
Tab E = Tab("u", "i","lll");
Tab F = Tab("f", "fff","xx");
Tab G = Tab("u", "www","dd");
Tab H = Tab("z", "pp","iii");
Tab I = Tab("xxx", "rrr","ggg");
Tab J = Tab("zzz", "k","ii");
Tab K = Tab("nn", "f","ww");
Tab L = Tab("ddd", "kkk","n");
Tab M = Tab("kkk", "h","jjj");
Tab N = Tab("t", "mm","gg");
Tab O = Tab("jjj", "mm","lll");
Tab P = Tab("hhh", "ppp","ddd");
Tab Q = Tab("mmm", "o","pp");
Tab R = Tab("mmm", "r","mmm");
Tab S = Tab("ii", "zz","zzz");
Tab T = Tab("mmm", "mm","e");
Tab U = Tab("yyy", "y","a");
Tab V = Tab("g", "oo","qqq");
Tab W = Tab("p", "aa","t");
Tab X = Tab("y", "jjj","ww");
Tab Y = Tab("ddd", "nnn","kkk");
Tab Z = Tab("qqq", "ss","uuu");
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.newTab(A);
a.moveActiveTabTo(3);
b.newTab(B);
c.newTab(C);
d.changeActiveTabTo(3);
a.newTab(D);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(E);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(1);
b.newTab(F);
c.newTab(G);
d.moveActiveTabTo(1);
a.newTab(H);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(I);
a.changeActiveTabTo(0);
b.newTab(J);
c.newTab(K);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.newTab(L);
c.changeActiveTabTo(5);
d.newTab(M);
a.newTab(N);
b.newTab(O);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(P);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(Q);
d.newTab(R);
a.newTab(S);
b.newTab(T);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
b.newTab(U);
c.changeActiveTabTo(1);
d.newTab(V);
a.newTab(W);
b.newTab(X);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.newTab(Y);
d.moveActiveTabTo(1);
a.newTab(Z);
b.newTab(Z);
c.changeActiveTabTo(5);
d.newTab(Z);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
d.changeActiveTabTo(2);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
d.moveActiveTabTo(3);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(1);
c.changeActiveTabTo(1);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
c.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
b.moveActiveTabTo(3);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
c.moveActiveTabTo(0);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->print();
brows->print();
brows->newWindow();
brows->print();
brows->print();
brows->newWindow();
brows->getWindow(0);
brows->newWindow();
brows->switchToWindow(8);
brows->print();
brows->switchToWindow(6);
brows->getWindow(2);
brows->switchToWindow(7);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->getWindow(9);
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->print();
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(6);
brows->getWindow(2);
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->getWindow(6);
brows->print();
brows->closeEmptyWindows();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->getWindow(3);
brows->newWindow();
brows->print();
brows->getWindow(2);
brows->getWindow(2);
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->getWindow(0);
brows->closeWindow();
brows->getWindow(9);
brows->closeWindow();
brows->getWindow(7);
brows->newWindow();
brows->switchToWindow(0);
brows->closeWindow();
brows->switchToWindow(3);
brows->getWindow(9);
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(9);
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->closeWindow();
brows->print();
brows->getWindow(0);
brows->getWindow(1);
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(9);
brows->newWindow();
brows->getWindow(3);
brows->getWindow(3);
brows->newWindow();
brows->closeWindow();
brows->getWindow(5);
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(5);
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->switchToWindow(0);
brows->getWindow(6);
brows->print();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
delete brows;
}
	return 0;
}