#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("mmm", "o","kkk");
Tab B = Tab("www", "q","oo");
Tab C = Tab("uu", "y","ggg");
Tab D = Tab("eee", "k","qq");
Tab E = Tab("q", "kk","pp");
Tab F = Tab("d", "n","a");
Tab G = Tab("pp", "ee","uuu");
Tab H = Tab("uu", "ee","o");
Tab I = Tab("dd", "f","nn");
Tab J = Tab("oo", "ww","xxx");
Tab K = Tab("ww", "yy","xxx");
Tab L = Tab("qq", "ee","b");
Tab M = Tab("ll", "iii","gg");
Tab N = Tab("ooo", "nn","h");
Tab O = Tab("p", "zzz","qq");
Tab P = Tab("o", "tt","o");
Tab Q = Tab("hh", "fff","zz");
Tab R = Tab("xxx", "ww","uuu");
Tab S = Tab("g", "www","mmm");
Tab T = Tab("v", "kk","iii");
Tab U = Tab("m", "z","ll");
Tab V = Tab("ss", "c","cc");
Tab W = Tab("ooo", "rrr","rr");
Tab X = Tab("mm", "bbb","zzz");
Tab Y = Tab("eee", "t","aa");
Tab Z = Tab("cc", "k","p");
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(1);
b.newTab(A);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(B);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(C);
a.newTab(D);
b.moveActiveTabTo(4);
c.newTab(E);
d.newTab(F);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(G);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.newTab(H);
c.newTab(I);
d.newTab(J);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(0);
b.newTab(K);
c.newTab(L);
d.moveActiveTabTo(0);
a.newTab(M);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(N);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(O);
d.newTab(P);
a.newTab(Q);
b.newTab(R);
c.newTab(S);
d.moveActiveTabTo(3);
a.changeActiveTabTo(0);
b.newTab(T);
c.moveActiveTabTo(0);
d.newTab(U);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(V);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(W);
b.moveActiveTabTo(4);
c.newTab(X);
d.moveActiveTabTo(4);
a.newTab(Y);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(Z);
a.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(1);
c.moveActiveTabTo(1);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
d.changeActiveTabTo(5);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
c.changeActiveTabTo(5);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
a.changeActiveTabTo(3);
a.moveActiveTabTo(2);
c.changeActiveTabTo(2);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.changeActiveTabTo(3);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->getWindow(0);
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->print();
brows->closeWindow();
brows->getWindow(2);
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(0);
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->getWindow(6);
brows->switchToWindow(7);
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(8);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->switchToWindow(6);
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->getWindow(3);
brows->closeEmptyWindows();
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->getWindow(5);
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(9);
brows->print();
brows->getWindow(7);
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(8);
brows->print();
brows->getWindow(0);
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(4);
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(2);
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(0);
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->getWindow(6);
brows->getWindow(7);
brows->switchToWindow(6);
brows->closeWindow();
brows->switchToWindow(4);
brows->getWindow(9);
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
delete brows;
}
	return 0;
}