#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("sss", "lll","k");
Tab B = Tab("rrr", "j","ss");
Tab C = Tab("k", "aaa","xxx");
Tab D = Tab("uu", "xxx","ff");
Tab E = Tab("mmm", "ooo","xxx");
Tab F = Tab("q", "jjj","nn");
Tab G = Tab("hh", "ww","yyy");
Tab H = Tab("sss", "o","hhh");
Tab I = Tab("z", "sss","uuu");
Tab J = Tab("xxx", "g","f");
Tab K = Tab("ss", "jjj","ggg");
Tab L = Tab("lll", "h","jjj");
Tab M = Tab("e", "ff","xxx");
Tab N = Tab("sss", "c","qq");
Tab O = Tab("rr", "mm","dd");
Tab P = Tab("uuu", "ee","yyy");
Tab Q = Tab("tt", "iii","x");
Tab R = Tab("l", "www","uu");
Tab S = Tab("h", "a","r");
Tab T = Tab("cc", "zzz","a");
Tab U = Tab("n", "g","s");
Tab V = Tab("g", "dd","s");
Tab W = Tab("kk", "ttt","i");
Tab X = Tab("ttt", "eee","oo");
Tab Y = Tab("mm", "r","ss");
Tab Z = Tab("hh", "qqq","www");
a.changeActiveTabTo(4);
b.newTab(A);
c.changeActiveTabTo(4);
d.newTab(B);
a.newTab(C);
b.changeActiveTabTo(5);
c.newTab(D);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.newTab(E);
c.changeActiveTabTo(4);
d.newTab(F);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(G);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(2);
b.newTab(H);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(5);
b.newTab(I);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(J);
b.newTab(K);
c.changeActiveTabTo(3);
d.newTab(L);
a.moveActiveTabTo(4);
b.newTab(M);
c.newTab(N);
d.moveActiveTabTo(4);
a.newTab(O);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.newTab(P);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(Q);
a.newTab(R);
b.moveActiveTabTo(0);
c.newTab(S);
d.moveActiveTabTo(0);
a.newTab(T);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(U);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(V);
b.newTab(W);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.newTab(X);
b.changeActiveTabTo(1);
c.newTab(Y);
d.newTab(Z);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
d.moveActiveTabTo(2);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
c.moveActiveTabTo(0);
a.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
d.changeActiveTabTo(0);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(1);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
b.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->newWindow();
brows->print();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(0);
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->switchToWindow(2);
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->print();
brows->getWindow(6);
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(5);
brows->getWindow(7);
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(6);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(5);
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(5);
brows->print();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->getWindow(6);
brows->switchToWindow(6);
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(7);
brows->switchToWindow(7);
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->getWindow(0);
brows->closeEmptyWindows();
brows->getWindow(6);
brows->getWindow(2);
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->switchToWindow(9);
brows->closeWindow();
brows->print();
brows->newWindow();
brows->switchToWindow(5);
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->getWindow(2);
brows->newWindow();
brows->print();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(9);
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(2);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(5);
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(6);
delete brows;
}
	return 0;
}