#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("ccc", "eee","w");
Tab B = Tab("b", "eee","v");
Tab C = Tab("hh", "g","vvv");
Tab D = Tab("s", "j","uu");
Tab E = Tab("ww", "mmm","ooo");
Tab F = Tab("xxx", "xxx","kkk");
Tab G = Tab("vv", "mmm","k");
Tab H = Tab("xxx", "kk","ee");
Tab I = Tab("iii", "uuu","p");
Tab J = Tab("dd", "mm","iii");
Tab K = Tab("aaa", "zzz","s");
Tab L = Tab("j", "uu","zzz");
Tab M = Tab("c", "w","xx");
Tab N = Tab("aaa", "aaa","h");
Tab O = Tab("ss", "ff","mm");
Tab P = Tab("n", "iii","l");
Tab Q = Tab("b", "ww","m");
Tab R = Tab("gg", "tt","lll");
Tab S = Tab("ss", "uu","uu");
Tab T = Tab("l", "ww","sss");
Tab U = Tab("uuu", "h","h");
Tab V = Tab("mm", "kk","hhh");
Tab W = Tab("mm", "kkk","lll");
Tab X = Tab("ss", "tt","rrr");
Tab Y = Tab("bbb", "ccc","nn");
Tab Z = Tab("mm", "b","d");
a.newTab(A);
b.newTab(B);
c.moveActiveTabTo(3);
d.newTab(C);
a.newTab(D);
b.newTab(E);
c.newTab(F);
d.newTab(G);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(H);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(I);
a.newTab(J);
b.moveActiveTabTo(2);
c.newTab(K);
d.moveActiveTabTo(2);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(L);
d.changeActiveTabTo(5);
a.changeActiveTabTo(2);
b.newTab(M);
c.moveActiveTabTo(2);
d.newTab(N);
a.newTab(O);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(P);
a.changeActiveTabTo(3);
b.newTab(Q);
c.moveActiveTabTo(3);
d.newTab(R);
a.newTab(S);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(T);
d.newTab(U);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(V);
a.newTab(W);
b.moveActiveTabTo(0);
c.newTab(X);
d.changeActiveTabTo(0);
a.newTab(Y);
b.newTab(Z);
c.newTab(Z);
d.newTab(Z);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
b.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
d.moveActiveTabTo(0);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
b.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
d.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
b.changeActiveTabTo(2);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
a.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->newWindow();
brows->print();
brows->print();
brows->closeWindow();
brows->switchToWindow(2);
brows->closeWindow();
brows->switchToWindow(3);
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->getWindow(5);
brows->switchToWindow(9);
brows->switchToWindow(4);
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(0);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(5);
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->switchToWindow(8);
brows->getWindow(4);
brows->getWindow(2);
brows->switchToWindow(5);
brows->getWindow(1);
brows->getWindow(1);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(2);
brows->switchToWindow(0);
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->getWindow(1);
brows->closeWindow();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->switchToWindow(1);
brows->switchToWindow(2);
brows->switchToWindow(4);
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(1);
brows->switchToWindow(2);
brows->getWindow(5);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->getWindow(4);
brows->newWindow();
brows->getWindow(0);
delete brows;
}
	return 0;
}