#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("yy", "e","oo");
Tab B = Tab("u", "c","v");
Tab C = Tab("vvv", "ff","m");
Tab D = Tab("r", "ii","uuu");
Tab E = Tab("h", "r","w");
Tab F = Tab("jj", "ggg","mmm");
Tab G = Tab("t", "y","qq");
Tab H = Tab("uuu", "hhh","uu");
Tab I = Tab("eee", "zz","nnn");
Tab J = Tab("w", "o","aaa");
Tab K = Tab("o", "aa","ll");
Tab L = Tab("o", "r","vvv");
Tab M = Tab("qqq", "g","m");
Tab N = Tab("k", "ee","m");
Tab O = Tab("s", "j","rrr");
Tab P = Tab("i", "ww","nn");
Tab Q = Tab("ggg", "fff","iii");
Tab R = Tab("xxx", "oo","hhh");
Tab S = Tab("c", "rrr","ff");
Tab T = Tab("vvv", "q","o");
Tab U = Tab("vvv", "ww","yy");
Tab V = Tab("nn", "bb","ddd");
Tab W = Tab("eee", "hh","nnn");
Tab X = Tab("ss", "jjj","jjj");
Tab Y = Tab("uu", "z","k");
Tab Z = Tab("fff", "zz","lll");
a.moveActiveTabTo(4);
b.newTab(A);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(B);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(3);
b.newTab(C);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(4);
b.newTab(D);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(E);
d.newTab(F);
a.newTab(G);
b.newTab(H);
c.newTab(I);
d.changeActiveTabTo(0);
a.changeActiveTabTo(4);
b.newTab(J);
c.changeActiveTabTo(4);
d.newTab(K);
a.changeActiveTabTo(1);
b.newTab(L);
c.newTab(M);
d.moveActiveTabTo(1);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(N);
a.changeActiveTabTo(1);
b.newTab(O);
c.newTab(P);
d.newTab(Q);
a.newTab(R);
b.changeActiveTabTo(3);
c.newTab(S);
d.changeActiveTabTo(3);
a.newTab(T);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(3);
b.newTab(U);
c.changeActiveTabTo(3);
d.newTab(V);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(W);
b.changeActiveTabTo(5);
c.newTab(X);
d.changeActiveTabTo(5);
a.newTab(Y);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(Z);
b.newTab(Z);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(0);
a.moveActiveTabTo(1);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
c.moveActiveTabTo(0);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
d.changeActiveTabTo(3);
b.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(0);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
b.moveActiveTabTo(0);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->getWindow(9);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(0);
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->getWindow(4);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(4);
brows->getWindow(2);
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(6);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(8);
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->print();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->switchToWindow(7);
brows->newWindow();
brows->getWindow(0);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->print();
brows->switchToWindow(8);
brows->getWindow(8);
brows->print();
brows->switchToWindow(7);
brows->newWindow();
brows->print();
brows->getWindow(7);
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(8);
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->getWindow(3);
brows->print();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->getWindow(6);
brows->getWindow(0);
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(4);
brows->closeEmptyWindows();
delete brows;
}
	return 0;
}