#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("uu", "h","ii");
Tab B = Tab("kkk", "j","v");
Tab C = Tab("w", "kk","pp");
Tab D = Tab("vv", "e","uuu");
Tab E = Tab("n", "g","zz");
Tab F = Tab("gg", "cc","yy");
Tab G = Tab("yyy", "v","mm");
Tab H = Tab("m", "g","zzz");
Tab I = Tab("ttt", "bb","kk");
Tab J = Tab("z", "ff","p");
Tab K = Tab("mm", "hh","qqq");
Tab L = Tab("mm", "lll","f");
Tab M = Tab("i", "ggg","hh");
Tab N = Tab("ww", "d","uuu");
Tab O = Tab("m", "bbb","p");
Tab P = Tab("d", "i","ss");
Tab Q = Tab("ii", "v","f");
Tab R = Tab("v", "g","cc");
Tab S = Tab("z", "www","e");
Tab T = Tab("kk", "yyy","ee");
Tab U = Tab("a", "g","j");
Tab V = Tab("pp", "zzz","zzz");
Tab W = Tab("ll", "cc","sss");
Tab X = Tab("a", "ee","e");
Tab Y = Tab("lll", "j","hh");
Tab Z = Tab("yy", "m","tt");
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.newTab(A);
d.newTab(B);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(C);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(D);
d.changeActiveTabTo(5);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(E);
d.newTab(F);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(G);
d.moveActiveTabTo(5);
a.moveActiveTabTo(2);
b.newTab(H);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(I);
b.newTab(J);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(K);
d.moveActiveTabTo(2);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(L);
d.newTab(M);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(N);
a.changeActiveTabTo(0);
b.newTab(O);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(0);
b.newTab(P);
c.moveActiveTabTo(0);
d.newTab(Q);
a.newTab(R);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(S);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(T);
b.newTab(U);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(V);
a.newTab(W);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(X);
a.newTab(Y);
b.newTab(Z);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(3);
d.changeActiveTabTo(3);
d.changeActiveTabTo(3);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
b.changeActiveTabTo(0);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(5);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
b.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->switchToWindow(7);
brows->getWindow(6);
brows->closeWindow();
brows->switchToWindow(2);
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(0);
brows->newWindow();
brows->switchToWindow(3);
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->getWindow(0);
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(4);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(2);
brows->print();
brows->closeEmptyWindows();
brows->getWindow(3);
brows->closeWindow();
brows->closeWindow();
brows->getWindow(0);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->newWindow();
brows->newWindow();
brows->print();
brows->switchToWindow(0);
brows->getWindow(3);
brows->newWindow();
brows->print();
brows->switchToWindow(3);
brows->getWindow(1);
brows->closeEmptyWindows();
brows->getWindow(6);
brows->newWindow();
brows->closeWindow();
brows->print();
brows->switchToWindow(5);
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(6);
brows->getWindow(7);
brows->getWindow(9);
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(7);
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(1);
brows->switchToWindow(0);
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(2);
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->getWindow(8);
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->getWindow(7);
brows->print();
brows->getWindow(6);
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(8);
brows->mergeAllWindows();
brows->getWindow(0);
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(6);
brows->getWindow(9);
brows->newWindow();
brows->newWindow();
brows->switchToWindow(7);
delete brows;
}
	return 0;
}