#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("ooo", "gg","xxx");
Tab B = Tab("m", "iii","ss");
Tab C = Tab("e", "k","www");
Tab D = Tab("s", "l","tt");
Tab E = Tab("kkk", "ii","yyy");
Tab F = Tab("a", "yyy","ooo");
Tab G = Tab("tt", "xxx","mmm");
Tab H = Tab("nnn", "qqq","ccc");
Tab I = Tab("b", "t","c");
Tab J = Tab("ooo", "ww","kkk");
Tab K = Tab("w", "ppp","ppp");
Tab L = Tab("i", "mm","cc");
Tab M = Tab("yy", "ll","x");
Tab N = Tab("mm", "u","sss");
Tab O = Tab("rrr", "h","t");
Tab P = Tab("lll", "x","bbb");
Tab Q = Tab("dd", "d","sss");
Tab R = Tab("fff", "eee","nn");
Tab S = Tab("n", "lll","aaa");
Tab T = Tab("gg", "rrr","r");
Tab U = Tab("kkk", "kk","xx");
Tab V = Tab("ggg", "s","l");
Tab W = Tab("t", "hhh","oo");
Tab X = Tab("eee", "kkk","yy");
Tab Y = Tab("aaa", "b","iii");
Tab Z = Tab("i", "z","d");
a.moveActiveTabTo(5);
b.newTab(A);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.newTab(B);
b.newTab(C);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(D);
b.newTab(E);
c.changeActiveTabTo(0);
d.newTab(F);
a.newTab(G);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(4);
b.newTab(H);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(I);
b.changeActiveTabTo(5);
c.newTab(J);
d.moveActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.newTab(K);
b.changeActiveTabTo(3);
c.newTab(L);
d.changeActiveTabTo(3);
a.moveActiveTabTo(2);
b.newTab(M);
c.newTab(N);
d.newTab(O);
a.changeActiveTabTo(1);
b.newTab(P);
c.changeActiveTabTo(1);
d.newTab(Q);
a.newTab(R);
b.changeActiveTabTo(3);
c.newTab(S);
d.newTab(T);
a.changeActiveTabTo(3);
b.newTab(U);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(1);
b.newTab(V);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(1);
b.newTab(W);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.newTab(X);
d.newTab(Y);
a.newTab(Z);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(4);
d.moveActiveTabTo(4);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
d.changeActiveTabTo(4);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->getWindow(1);
brows->mergeAllWindows();
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(0);
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(5);
brows->mergeAllWindows();
brows->getWindow(2);
brows->switchToWindow(0);
brows->newWindow();
brows->print();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->getWindow(2);
brows->getWindow(8);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(5);
brows->switchToWindow(0);
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(9);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(8);
brows->switchToWindow(9);
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->getWindow(6);
brows->switchToWindow(6);
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(8);
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->getWindow(7);
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->switchToWindow(4);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(3);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->newWindow();
brows->switchToWindow(1);
delete brows;
}
	return 0;
}