#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("h", "lll","x");
Tab B = Tab("nn", "gg","v");
Tab C = Tab("w", "zz","qq");
Tab D = Tab("fff", "ooo","s");
Tab E = Tab("qq", "t","hhh");
Tab F = Tab("zz", "ooo","c");
Tab G = Tab("ddd", "i","y");
Tab H = Tab("ee", "b","kk");
Tab I = Tab("zz", "kkk","p");
Tab J = Tab("t", "zz","hhh");
Tab K = Tab("xx", "ee","i");
Tab L = Tab("jjj", "tt","qqq");
Tab M = Tab("x", "b","r");
Tab N = Tab("ttt", "oo","yy");
Tab O = Tab("qq", "hh","xx");
Tab P = Tab("hhh", "y","rrr");
Tab Q = Tab("r", "qq","ll");
Tab R = Tab("xx", "ww","tt");
Tab S = Tab("q", "yy","tt");
Tab T = Tab("kkk", "vv","hh");
Tab U = Tab("ll", "ooo","cc");
Tab V = Tab("vvv", "kk","aaa");
Tab W = Tab("ff", "vvv","ee");
Tab X = Tab("gg", "hh","ss");
Tab Y = Tab("ww", "ppp","aa");
Tab Z = Tab("u", "qq","sss");
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.newTab(A);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(B);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(C);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(D);
a.newTab(E);
b.moveActiveTabTo(2);
c.newTab(F);
d.newTab(G);
a.newTab(H);
b.newTab(I);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(J);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(K);
a.newTab(L);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(M);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(N);
a.newTab(O);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(P);
a.newTab(Q);
b.newTab(R);
c.newTab(S);
d.newTab(T);
a.changeActiveTabTo(0);
b.newTab(U);
c.newTab(V);
d.newTab(W);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(X);
d.moveActiveTabTo(3);
a.newTab(Y);
b.newTab(Z);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
d.changeActiveTabTo(1);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(1);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(3);
d.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(2);
c.moveActiveTabTo(2);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.changeActiveTabTo(3);
d.changeActiveTabTo(3);
c.changeActiveTabTo(1);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(6);
brows->print();
brows->getWindow(0);
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(5);
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->print();
brows->mergeAllWindows();
brows->getWindow(6);
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(4);
brows->newWindow();
brows->getWindow(7);
brows->closeWindow();
brows->switchToWindow(4);
brows->getWindow(7);
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(5);
brows->newWindow();
brows->switchToWindow(5);
brows->getWindow(0);
brows->newWindow();
brows->getWindow(9);
brows->closeWindow();
brows->print();
brows->switchToWindow(1);
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->getWindow(0);
brows->newWindow();
brows->getWindow(2);
brows->closeEmptyWindows();
brows->switchToWindow(5);
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(6);
brows->newWindow();
brows->switchToWindow(9);
brows->getWindow(0);
brows->newWindow();
brows->switchToWindow(4);
brows->getWindow(4);
brows->closeWindow();
brows->getWindow(7);
brows->print();
brows->print();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(1);
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(0);
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
delete brows;
}
	return 0;
}