#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("fff", "mm","oo");
Tab B = Tab("ii", "kk","ggg");
Tab C = Tab("aaa", "l","h");
Tab D = Tab("d", "kkk","bbb");
Tab E = Tab("kk", "j","v");
Tab F = Tab("u", "y","ff");
Tab G = Tab("zzz", "x","p");
Tab H = Tab("yyy", "s","r");
Tab I = Tab("vvv", "ooo","k");
Tab J = Tab("q", "v","iii");
Tab K = Tab("xx", "mm","eee");
Tab L = Tab("rrr", "a","u");
Tab M = Tab("hh", "e","mm");
Tab N = Tab("ll", "nnn","h");
Tab O = Tab("ll", "vv","rrr");
Tab P = Tab("mmm", "ccc","i");
Tab Q = Tab("uu", "aaa","f");
Tab R = Tab("ddd", "fff","nnn");
Tab S = Tab("bbb", "f","q");
Tab T = Tab("h", "hh","kkk");
Tab U = Tab("oo", "ggg","qqq");
Tab V = Tab("kkk", "i","a");
Tab W = Tab("ddd", "ddd","aaa");
Tab X = Tab("nnn", "vv","c");
Tab Y = Tab("vvv", "www","ooo");
Tab Z = Tab("n", "yyy","ooo");
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(A);
a.newTab(B);
b.newTab(C);
c.newTab(D);
d.newTab(E);
a.newTab(F);
b.moveActiveTabTo(0);
c.newTab(G);
d.newTab(H);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(I);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.newTab(J);
b.newTab(K);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(L);
d.changeActiveTabTo(3);
a.newTab(M);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(N);
a.moveActiveTabTo(5);
b.newTab(O);
c.changeActiveTabTo(5);
d.newTab(P);
a.newTab(Q);
b.newTab(R);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(S);
d.moveActiveTabTo(5);
a.newTab(T);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.newTab(U);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.newTab(V);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(W);
b.newTab(X);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(Y);
a.moveActiveTabTo(4);
b.newTab(Z);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
d.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
b.moveActiveTabTo(2);
d.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
b.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(0);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.moveActiveTabTo(4);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(4);
d.moveActiveTabTo(4);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeWindow();
brows->getWindow(3);
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(4);
brows->closeWindow();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(7);
brows->print();
brows->switchToWindow(1);
brows->getWindow(5);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->closeWindow();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(2);
brows->getWindow(4);
brows->getWindow(6);
brows->print();
brows->getWindow(0);
brows->getWindow(5);
brows->closeWindow();
brows->switchToWindow(9);
brows->switchToWindow(4);
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(6);
brows->newWindow();
brows->getWindow(2);
brows->getWindow(1);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->newWindow();
brows->closeWindow();
brows->getWindow(8);
brows->print();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(6);
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(8);
brows->switchToWindow(7);
brows->switchToWindow(3);
brows->switchToWindow(9);
brows->newWindow();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->getWindow(3);
brows->mergeAllWindows();
brows->switchToWindow(4);
brows->print();
brows->getWindow(1);
brows->getWindow(0);
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->getWindow(9);
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(2);
brows->print();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->switchToWindow(5);
brows->getWindow(1);
brows->switchToWindow(8);
delete brows;
}
	return 0;
}