#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("s", "pp","j");
Tab B = Tab("ccc", "ttt","ooo");
Tab C = Tab("v", "zzz","aa");
Tab D = Tab("j", "jj","vvv");
Tab E = Tab("ee", "bbb","a");
Tab F = Tab("g", "k","y");
Tab G = Tab("uu", "iii","cc");
Tab H = Tab("ii", "x","fff");
Tab I = Tab("ddd", "mm","oo");
Tab J = Tab("aa", "xx","rr");
Tab K = Tab("y", "ee","f");
Tab L = Tab("mm", "d","yy");
Tab M = Tab("s", "zz","ddd");
Tab N = Tab("sss", "kk","nn");
Tab O = Tab("aaa", "mmm","rrr");
Tab P = Tab("eee", "jj","mmm");
Tab Q = Tab("ccc", "p","s");
Tab R = Tab("ee", "d","ttt");
Tab S = Tab("a", "ttt","qqq");
Tab T = Tab("u", "sss","fff");
Tab U = Tab("ss", "ggg","mm");
Tab V = Tab("b", "hh","i");
Tab W = Tab("ddd", "r","cc");
Tab X = Tab("g", "p","s");
Tab Y = Tab("vvv", "zz","a");
Tab Z = Tab("kkk", "ff","k");
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.newTab(A);
b.newTab(B);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(C);
b.newTab(D);
c.newTab(E);
d.changeActiveTabTo(5);
a.newTab(F);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(5);
b.newTab(G);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(0);
b.newTab(H);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(I);
d.changeActiveTabTo(5);
a.moveActiveTabTo(0);
b.newTab(J);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.newTab(K);
b.newTab(L);
c.changeActiveTabTo(4);
d.newTab(M);
a.moveActiveTabTo(4);
b.newTab(N);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.newTab(O);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.newTab(P);
b.newTab(Q);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(R);
d.changeActiveTabTo(2);
a.newTab(S);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(2);
b.newTab(T);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(U);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(V);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(W);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(X);
d.changeActiveTabTo(4);
a.newTab(Y);
b.newTab(Z);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
d.moveActiveTabTo(4);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(5);
brows->getWindow(0);
brows->getWindow(7);
brows->mergeAllWindows();
brows->print();
brows->print();
brows->closeWindow();
brows->print();
brows->getWindow(1);
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(5);
brows->getWindow(1);
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->newWindow();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->getWindow(2);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(6);
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(8);
brows->print();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(5);
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->getWindow(5);
brows->switchToWindow(7);
brows->closeWindow();
brows->switchToWindow(5);
brows->getWindow(1);
brows->newWindow();
brows->closeWindow();
brows->getWindow(3);
brows->getWindow(0);
brows->switchToWindow(3);
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(2);
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->getWindow(7);
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(2);
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->getWindow(5);
brows->getWindow(7);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(7);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(0);
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->print();
brows->closeWindow();
delete brows;
}
	return 0;
}