#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("q", "zzz","dd");
Tab B = Tab("vv", "oo","rr");
Tab C = Tab("q", "g","fff");
Tab D = Tab("b", "x","pp");
Tab E = Tab("i", "s","ppp");
Tab F = Tab("w", "dd","rr");
Tab G = Tab("qqq", "n","hhh");
Tab H = Tab("ooo", "gg","dd");
Tab I = Tab("nnn", "h","ll");
Tab J = Tab("ee", "u","s");
Tab K = Tab("e", "ll","jj");
Tab L = Tab("sss", "o","ggg");
Tab M = Tab("z", "d","aaa");
Tab N = Tab("r", "jj","fff");
Tab O = Tab("e", "bbb","oo");
Tab P = Tab("nnn", "lll","n");
Tab Q = Tab("iii", "uuu","g");
Tab R = Tab("ggg", "fff","qqq");
Tab S = Tab("lll", "ggg","oo");
Tab T = Tab("rr", "b","xxx");
Tab U = Tab("f", "q","hh");
Tab V = Tab("z", "ttt","z");
Tab W = Tab("lll", "v","bbb");
Tab X = Tab("ttt", "t","q");
Tab Y = Tab("jj", "hh","ccc");
Tab Z = Tab("ddd", "ggg","kkk");
a.moveActiveTabTo(3);
b.newTab(A);
c.newTab(B);
d.newTab(C);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(D);
d.moveActiveTabTo(0);
a.newTab(E);
b.changeActiveTabTo(3);
c.newTab(F);
d.newTab(G);
a.moveActiveTabTo(2);
b.newTab(H);
c.moveActiveTabTo(2);
d.newTab(I);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(J);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(K);
d.newTab(L);
a.newTab(M);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(N);
d.moveActiveTabTo(2);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(4);
b.newTab(O);
c.changeActiveTabTo(4);
d.newTab(P);
a.newTab(Q);
b.newTab(R);
c.newTab(S);
d.moveActiveTabTo(3);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(T);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.newTab(U);
d.moveActiveTabTo(1);
a.changeActiveTabTo(3);
b.newTab(V);
c.newTab(W);
d.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(X);
d.moveActiveTabTo(0);
a.newTab(Y);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(2);
b.newTab(Z);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(0);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
b.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
b.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
d.changeActiveTabTo(0);
a.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(1);
c.changeActiveTabTo(1);
a.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->closeWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->getWindow(3);
brows->getWindow(7);
brows->print();
brows->newWindow();
brows->getWindow(1);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->getWindow(8);
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(5);
brows->getWindow(6);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(0);
brows->print();
brows->print();
brows->newWindow();
brows->switchToWindow(4);
brows->switchToWindow(9);
brows->newWindow();
brows->switchToWindow(3);
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(9);
brows->getWindow(3);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->newWindow();
brows->closeWindow();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(1);
brows->print();
brows->getWindow(3);
brows->getWindow(3);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->getWindow(6);
brows->print();
brows->switchToWindow(9);
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(5);
brows->print();
brows->switchToWindow(4);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->print();
brows->getWindow(7);
brows->getWindow(4);
brows->getWindow(6);
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->switchToWindow(6);
brows->switchToWindow(9);
brows->switchToWindow(2);
brows->print();
brows->getWindow(2);
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->getWindow(6);
brows->print();
brows->print();
brows->switchToWindow(3);
brows->switchToWindow(7);
brows->getWindow(3);
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(1);
brows->print();
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(4);
delete brows;
}
	return 0;
}