#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("a", "ooo","ee");
Tab B = Tab("hh", "p","ee");
Tab C = Tab("nnn", "c","ggg");
Tab D = Tab("y", "v","m");
Tab E = Tab("x", "uuu","dd");
Tab F = Tab("r", "n","e");
Tab G = Tab("n", "l","ttt");
Tab H = Tab("www", "qqq","rrr");
Tab I = Tab("i", "ooo","z");
Tab J = Tab("ee", "ttt","ww");
Tab K = Tab("xx", "a","ee");
Tab L = Tab("oo", "o","m");
Tab M = Tab("aaa", "gg","o");
Tab N = Tab("d", "vvv","p");
Tab O = Tab("ttt", "xxx","xxx");
Tab P = Tab("x", "x","gg");
Tab Q = Tab("ddd", "zz","www");
Tab R = Tab("www", "yyy","xx");
Tab S = Tab("yy", "y","ff");
Tab T = Tab("cc", "kkk","www");
Tab U = Tab("j", "e","uuu");
Tab V = Tab("nn", "hh","z");
Tab W = Tab("k", "gg","nnn");
Tab X = Tab("bb", "rrr","c");
Tab Y = Tab("ooo", "z","m");
Tab Z = Tab("r", "oo","ee");
a.newTab(A);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
b.newTab(B);
c.newTab(C);
d.moveActiveTabTo(0);
a.newTab(D);
b.newTab(E);
c.newTab(F);
d.changeActiveTabTo(3);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(2);
b.newTab(G);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(H);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(I);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(J);
d.newTab(K);
a.moveActiveTabTo(0);
b.newTab(L);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.newTab(M);
b.moveActiveTabTo(5);
c.newTab(N);
d.changeActiveTabTo(5);
a.changeActiveTabTo(0);
b.newTab(O);
c.newTab(P);
d.newTab(Q);
a.newTab(R);
b.newTab(S);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(1);
b.newTab(T);
c.newTab(U);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(V);
a.newTab(W);
b.moveActiveTabTo(0);
c.newTab(X);
d.moveActiveTabTo(0);
a.newTab(Y);
b.moveActiveTabTo(0);
c.newTab(Z);
d.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
d.moveActiveTabTo(4);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
c.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
a.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.moveActiveTabTo(5);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->print();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(0);
brows->print();
brows->newWindow();
brows->switchToWindow(2);
brows->switchToWindow(6);
brows->getWindow(4);
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(9);
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(2);
brows->switchToWindow(4);
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->getWindow(0);
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(0);
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->getWindow(4);
brows->getWindow(9);
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->getWindow(6);
brows->newWindow();
brows->getWindow(4);
brows->mergeAllWindows();
brows->switchToWindow(1);
brows->closeWindow();
brows->print();
brows->getWindow(4);
brows->newWindow();
brows->getWindow(5);
brows->print();
brows->getWindow(3);
brows->getWindow(8);
brows->getWindow(6);
brows->switchToWindow(3);
brows->newWindow();
brows->switchToWindow(7);
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->getWindow(7);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->newWindow();
brows->getWindow(5);
brows->mergeAllWindows();
brows->getWindow(5);
brows->getWindow(0);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->print();
brows->getWindow(5);
brows->print();
brows->print();
brows->switchToWindow(6);
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(9);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(6);
brows->closeWindow();
brows->newWindow();
brows->print();
brows->switchToWindow(9);
brows->print();
brows->switchToWindow(9);
brows->closeWindow();
brows->closeEmptyWindows();
delete brows;
}
	return 0;
}