#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("qq", "ss","kkk");
Tab B = Tab("qq", "zz","ccc");
Tab C = Tab("yy", "n","b");
Tab D = Tab("vv", "ii","uu");
Tab E = Tab("aaa", "ttt","t");
Tab F = Tab("ddd", "iii","mmm");
Tab G = Tab("n", "pp","mmm");
Tab H = Tab("www", "yy","r");
Tab I = Tab("c", "p","bb");
Tab J = Tab("y", "rr","kk");
Tab K = Tab("hh", "qq","z");
Tab L = Tab("uuu", "n","jj");
Tab M = Tab("ss", "ppp","ll");
Tab N = Tab("vv", "i","ppp");
Tab O = Tab("kk", "vv","mmm");
Tab P = Tab("t", "qq","ppp");
Tab Q = Tab("bb", "ggg","c");
Tab R = Tab("c", "qq","yyy");
Tab S = Tab("ee", "sss","eee");
Tab T = Tab("sss", "y","aaa");
Tab U = Tab("j", "qqq","aa");
Tab V = Tab("j", "kk","ppp");
Tab W = Tab("hh", "ii","i");
Tab X = Tab("hh", "b","ii");
Tab Y = Tab("x", "ii","aaa");
Tab Z = Tab("k", "tt","pp");
a.newTab(A);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(3);
b.newTab(B);
c.moveActiveTabTo(3);
d.newTab(C);
a.newTab(D);
b.newTab(E);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(F);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(G);
a.newTab(H);
b.newTab(I);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.newTab(J);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(0);
b.newTab(K);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(L);
b.moveActiveTabTo(1);
c.newTab(M);
d.changeActiveTabTo(1);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(N);
d.newTab(O);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(P);
a.newTab(Q);
b.changeActiveTabTo(4);
c.newTab(R);
d.moveActiveTabTo(4);
a.moveActiveTabTo(0);
b.newTab(S);
c.newTab(T);
d.changeActiveTabTo(0);
a.newTab(U);
b.newTab(V);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(W);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(X);
b.newTab(Y);
c.newTab(Z);
d.newTab(Z);
a.changeActiveTabTo(4);
c.changeActiveTabTo(4);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
b.moveActiveTabTo(2);
d.changeActiveTabTo(2);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(0);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
a.changeActiveTabTo(3);
d.changeActiveTabTo(3);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(4);
c.changeActiveTabTo(4);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->switchToWindow(2);
brows->switchToWindow(8);
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(5);
brows->getWindow(0);
brows->closeWindow();
brows->closeWindow();
brows->getWindow(6);
brows->closeWindow();
brows->switchToWindow(3);
brows->switchToWindow(5);
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(6);
brows->getWindow(8);
brows->print();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->getWindow(4);
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(8);
brows->print();
brows->getWindow(1);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(9);
brows->newWindow();
brows->switchToWindow(7);
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->getWindow(8);
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(7);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->switchToWindow(3);
brows->newWindow();
brows->print();
brows->print();
brows->getWindow(7);
brows->print();
brows->mergeAllWindows();
brows->print();
brows->switchToWindow(3);
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->getWindow(0);
brows->switchToWindow(6);
brows->getWindow(9);
brows->getWindow(4);
brows->switchToWindow(8);
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(1);
brows->print();
brows->getWindow(3);
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->closeWindow();
brows->print();
brows->print();
brows->getWindow(6);
brows->switchToWindow(6);
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->closeEmptyWindows();
delete brows;
}
	return 0;
}