#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("m", "vvv","ccc");
Tab B = Tab("ddd", "ddd","uu");
Tab C = Tab("ss", "b","ooo");
Tab D = Tab("h", "vvv","uuu");
Tab E = Tab("ddd", "t","a");
Tab F = Tab("n", "j","mm");
Tab G = Tab("ttt", "hh","b");
Tab H = Tab("rrr", "mmm","hh");
Tab I = Tab("f", "tt","zzz");
Tab J = Tab("x", "f","n");
Tab K = Tab("a", "mmm","ttt");
Tab L = Tab("ooo", "j","rr");
Tab M = Tab("y", "l","cc");
Tab N = Tab("t", "ddd","x");
Tab O = Tab("rrr", "gg","w");
Tab P = Tab("gg", "eee","ggg");
Tab Q = Tab("dd", "xx","ppp");
Tab R = Tab("h", "pp","g");
Tab S = Tab("k", "c","ggg");
Tab T = Tab("y", "mm","ll");
Tab U = Tab("z", "jj","b");
Tab V = Tab("ss", "vvv","xx");
Tab W = Tab("rr", "tt","cc");
Tab X = Tab("u", "h","aa");
Tab Y = Tab("gg", "uuu","mm");
Tab Z = Tab("mm", "www","kk");
a.newTab(A);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.newTab(B);
a.newTab(C);
b.newTab(D);
c.moveActiveTabTo(3);
d.newTab(E);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(F);
d.newTab(G);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(5);
b.newTab(H);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(I);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(J);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(K);
a.moveActiveTabTo(2);
b.newTab(L);
c.newTab(M);
d.newTab(N);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(O);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.newTab(P);
c.newTab(Q);
d.newTab(R);
a.newTab(S);
b.changeActiveTabTo(2);
c.newTab(T);
d.newTab(U);
a.changeActiveTabTo(1);
b.newTab(V);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.newTab(W);
b.moveActiveTabTo(3);
c.newTab(X);
d.moveActiveTabTo(3);
a.newTab(Y);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(Z);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
d.moveActiveTabTo(3);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
c.moveActiveTabTo(4);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->switchToWindow(8);
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(4);
brows->closeWindow();
brows->getWindow(3);
brows->getWindow(3);
brows->newWindow();
brows->closeWindow();
brows->getWindow(1);
brows->getWindow(8);
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(2);
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->switchToWindow(9);
brows->print();
brows->getWindow(6);
brows->print();
brows->closeWindow();
brows->print();
brows->getWindow(8);
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(8);
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(9);
brows->getWindow(0);
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(0);
brows->getWindow(1);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->getWindow(3);
brows->mergeAllWindows();
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->closeEmptyWindows();
brows->getWindow(7);
brows->mergeAllWindows();
brows->getWindow(1);
brows->newWindow();
brows->getWindow(1);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(3);
brows->switchToWindow(2);
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
delete brows;
}
	return 0;
}