#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("w", "jjj","c");
Tab B = Tab("ee", "iii","ppp");
Tab C = Tab("y", "mmm","z");
Tab D = Tab("b", "rr","aaa");
Tab E = Tab("kk", "uu","ttt");
Tab F = Tab("e", "kk","a");
Tab G = Tab("ss", "qqq","oo");
Tab H = Tab("iii", "rrr","n");
Tab I = Tab("mmm", "m","dd");
Tab J = Tab("cc", "t","ii");
Tab K = Tab("l", "ww","gg");
Tab L = Tab("cc", "uu","jjj");
Tab M = Tab("ee", "ppp","ii");
Tab N = Tab("jj", "oo","www");
Tab O = Tab("b", "n","kkk");
Tab P = Tab("u", "ttt","ccc");
Tab Q = Tab("lll", "h","a");
Tab R = Tab("ww", "bb","cc");
Tab S = Tab("v", "ll","hhh");
Tab T = Tab("ss", "nn","p");
Tab U = Tab("iii", "ii","ppp");
Tab V = Tab("y", "ddd","ggg");
Tab W = Tab("v", "m","ww");
Tab X = Tab("kkk", "zz","qqq");
Tab Y = Tab("uuu", "ff","ppp");
Tab Z = Tab("tt", "nnn","ss");
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(A);
d.newTab(B);
a.moveActiveTabTo(5);
b.newTab(C);
c.newTab(D);
d.changeActiveTabTo(5);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.newTab(E);
d.moveActiveTabTo(2);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(F);
a.newTab(G);
b.newTab(H);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(I);
d.newTab(J);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.newTab(K);
d.newTab(L);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(M);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.newTab(N);
d.newTab(O);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.newTab(P);
a.newTab(Q);
b.newTab(R);
c.newTab(S);
d.changeActiveTabTo(4);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(T);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(U);
b.newTab(V);
c.moveActiveTabTo(0);
d.newTab(W);
a.newTab(X);
b.newTab(Y);
c.moveActiveTabTo(0);
d.newTab(Z);
a.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
d.moveActiveTabTo(4);
b.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(5);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
a.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
a.moveActiveTabTo(4);
d.moveActiveTabTo(4);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
a.changeActiveTabTo(0);
a.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
b.moveActiveTabTo(1);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
d.moveActiveTabTo(4);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->switchToWindow(3);
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(5);
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(6);
brows->getWindow(0);
brows->switchToWindow(4);
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->getWindow(0);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(6);
brows->print();
brows->closeWindow();
brows->print();
brows->print();
brows->getWindow(0);
brows->getWindow(3);
brows->getWindow(6);
brows->print();
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(3);
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->switchToWindow(0);
brows->closeWindow();
brows->switchToWindow(2);
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(0);
brows->newWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->getWindow(5);
brows->closeEmptyWindows();
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->print();
brows->getWindow(8);
brows->getWindow(3);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->getWindow(5);
brows->closeWindow();
brows->print();
brows->print();
brows->print();
brows->switchToWindow(8);
brows->switchToWindow(0);
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->getWindow(6);
brows->getWindow(1);
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(1);
brows->closeEmptyWindows();
brows->getWindow(3);
brows->newWindow();
brows->getWindow(0);
brows->switchToWindow(5);
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->getWindow(1);
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->print();
brows->closeWindow();
delete brows;
}
	return 0;
}