#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("zz", "aa","nn");
Tab B = Tab("ww", "g","bb");
Tab C = Tab("yyy", "r","ll");
Tab D = Tab("ii", "jj","mmm");
Tab E = Tab("ll", "iii","ggg");
Tab F = Tab("yyy", "jjj","ggg");
Tab G = Tab("qqq", "ff","kkk");
Tab H = Tab("vvv", "z","iii");
Tab I = Tab("c", "zz","w");
Tab J = Tab("q", "yy","kk");
Tab K = Tab("xxx", "ccc","ccc");
Tab L = Tab("bb", "ooo","bb");
Tab M = Tab("ttt", "sss","aa");
Tab N = Tab("r", "ooo","v");
Tab O = Tab("n", "j","www");
Tab P = Tab("rrr", "kkk","hhh");
Tab Q = Tab("bb", "aaa","k");
Tab R = Tab("sss", "ccc","lll");
Tab S = Tab("ggg", "l","mmm");
Tab T = Tab("uu", "ccc","ooo");
Tab U = Tab("y", "p","qq");
Tab V = Tab("m", "kk","qqq");
Tab W = Tab("e", "ww","sss");
Tab X = Tab("n", "w","aaa");
Tab Y = Tab("ooo", "sss","jj");
Tab Z = Tab("r", "zz","hhh");
a.moveActiveTabTo(1);
b.newTab(A);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(B);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.newTab(C);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(1);
b.newTab(D);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(1);
b.newTab(E);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(F);
b.newTab(G);
c.newTab(H);
d.moveActiveTabTo(4);
a.moveActiveTabTo(4);
b.newTab(I);
c.newTab(J);
d.moveActiveTabTo(4);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(K);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(2);
b.newTab(L);
c.newTab(M);
d.newTab(N);
a.newTab(O);
b.newTab(P);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.newTab(Q);
d.newTab(R);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(S);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(T);
d.changeActiveTabTo(2);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(1);
b.newTab(U);
c.changeActiveTabTo(1);
d.newTab(V);
a.newTab(W);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.newTab(X);
d.moveActiveTabTo(0);
a.newTab(Y);
b.newTab(Z);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(2);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.moveActiveTabTo(1);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
a.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
b.changeActiveTabTo(4);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(1);
c.moveActiveTabTo(1);
b.moveActiveTabTo(0);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->switchToWindow(9);
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(7);
brows->getWindow(9);
brows->closeEmptyWindows();
brows->getWindow(6);
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->getWindow(9);
brows->closeEmptyWindows();
brows->getWindow(0);
brows->switchToWindow(0);
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->getWindow(7);
brows->print();
brows->getWindow(9);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->getWindow(8);
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(9);
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->getWindow(5);
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->getWindow(9);
brows->getWindow(9);
brows->newWindow();
brows->switchToWindow(9);
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->print();
brows->mergeAllWindows();
brows->print();
brows->getWindow(0);
brows->switchToWindow(4);
brows->closeWindow();
brows->switchToWindow(7);
brows->print();
brows->getWindow(4);
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(0);
brows->closeEmptyWindows();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(3);
brows->switchToWindow(2);
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(2);
brows->getWindow(3);
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->getWindow(5);
brows->print();
brows->print();
brows->newWindow();
brows->getWindow(4);
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->mergeAllWindows();
brows->switchToWindow(9);
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->print();
brows->switchToWindow(7);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->closeWindow();
delete brows;
}
	return 0;
}