#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("www", "c","qqq");
Tab B = Tab("v", "uuu","yy");
Tab C = Tab("h", "k","vvv");
Tab D = Tab("ff", "pp","qq");
Tab E = Tab("vv", "ii","ggg");
Tab F = Tab("nnn", "v","x");
Tab G = Tab("k", "oo","ggg");
Tab H = Tab("u", "r","mm");
Tab I = Tab("nnn", "pp","q");
Tab J = Tab("w", "oo","ss");
Tab K = Tab("uu", "ccc","h");
Tab L = Tab("uu", "ggg","ooo");
Tab M = Tab("s", "p","nn");
Tab N = Tab("vvv", "zz","cc");
Tab O = Tab("mmm", "c","y");
Tab P = Tab("ttt", "s","t");
Tab Q = Tab("xxx", "ll","ff");
Tab R = Tab("nn", "kk","cc");
Tab S = Tab("nn", "i","p");
Tab T = Tab("s", "u","ww");
Tab U = Tab("t", "jjj","ccc");
Tab V = Tab("nnn", "e","h");
Tab W = Tab("a", "vv","u");
Tab X = Tab("sss", "c","ppp");
Tab Y = Tab("a", "m","yy");
Tab Z = Tab("c", "www","bb");
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(A);
a.moveActiveTabTo(2);
b.newTab(B);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(C);
d.moveActiveTabTo(3);
a.changeActiveTabTo(2);
b.newTab(D);
c.moveActiveTabTo(2);
d.newTab(E);
a.moveActiveTabTo(2);
b.newTab(F);
c.changeActiveTabTo(2);
d.newTab(G);
a.newTab(H);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(I);
b.newTab(J);
c.newTab(K);
d.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.newTab(L);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(M);
d.changeActiveTabTo(0);
a.newTab(N);
b.moveActiveTabTo(2);
c.newTab(O);
d.newTab(P);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(Q);
d.changeActiveTabTo(5);
a.newTab(R);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(S);
a.changeActiveTabTo(0);
b.newTab(T);
c.moveActiveTabTo(0);
d.newTab(U);
a.newTab(V);
b.changeActiveTabTo(3);
c.newTab(W);
d.moveActiveTabTo(3);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(X);
a.newTab(Y);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(Z);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(3);
c.changeActiveTabTo(3);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
a.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(2);
c.changeActiveTabTo(2);
a.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
b.moveActiveTabTo(2);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(3);
d.moveActiveTabTo(3);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->mergeAllWindows();
brows->getWindow(5);
brows->switchToWindow(2);
brows->print();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->switchToWindow(9);
brows->print();
brows->switchToWindow(1);
brows->getWindow(5);
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->getWindow(3);
brows->newWindow();
brows->getWindow(5);
brows->getWindow(2);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->newWindow();
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->getWindow(9);
brows->getWindow(4);
brows->closeEmptyWindows();
brows->switchToWindow(8);
brows->getWindow(6);
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->newWindow();
brows->switchToWindow(2);
brows->print();
brows->closeWindow();
brows->getWindow(1);
brows->print();
brows->switchToWindow(5);
brows->print();
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(2);
brows->switchToWindow(3);
brows->mergeAllWindows();
brows->getWindow(4);
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->switchToWindow(7);
brows->print();
brows->newWindow();
brows->closeWindow();
brows->getWindow(0);
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->switchToWindow(9);
brows->getWindow(0);
brows->switchToWindow(0);
brows->switchToWindow(2);
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(9);
brows->switchToWindow(5);
brows->print();
brows->newWindow();
brows->switchToWindow(6);
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(4);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(3);
brows->print();
brows->print();
brows->closeWindow();
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->switchToWindow(7);
brows->getWindow(2);
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
delete brows;
}
	return 0;
}