#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("rrr", "tt","o");
Tab B = Tab("u", "kkk","l");
Tab C = Tab("z", "p","zzz");
Tab D = Tab("uu", "b","xx");
Tab E = Tab("u", "ii","uu");
Tab F = Tab("d", "ppp","n");
Tab G = Tab("o", "uu","b");
Tab H = Tab("vv", "u","c");
Tab I = Tab("fff", "nn","pp");
Tab J = Tab("aaa", "bbb","v");
Tab K = Tab("qqq", "v","l");
Tab L = Tab("mm", "ooo","qq");
Tab M = Tab("i", "m","mm");
Tab N = Tab("pp", "zz","mm");
Tab O = Tab("q", "vvv","q");
Tab P = Tab("lll", "y","aaa");
Tab Q = Tab("ss", "u","ccc");
Tab R = Tab("qqq", "www","rr");
Tab S = Tab("xx", "a","uuu");
Tab T = Tab("sss", "vvv","oo");
Tab U = Tab("zzz", "v","rr");
Tab V = Tab("nnn", "zzz","ooo");
Tab W = Tab("tt", "www","ddd");
Tab X = Tab("mmm", "h","fff");
Tab Y = Tab("lll", "hhh","xxx");
Tab Z = Tab("j", "h","pp");
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.newTab(A);
d.changeActiveTabTo(2);
a.newTab(B);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(5);
b.newTab(C);
c.newTab(D);
d.moveActiveTabTo(5);
a.newTab(E);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
b.newTab(F);
c.newTab(G);
d.changeActiveTabTo(4);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(H);
b.moveActiveTabTo(4);
c.newTab(I);
d.moveActiveTabTo(4);
a.newTab(J);
b.moveActiveTabTo(1);
c.newTab(K);
d.changeActiveTabTo(1);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(L);
a.newTab(M);
b.newTab(N);
c.newTab(O);
d.changeActiveTabTo(1);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(P);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(Q);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.newTab(R);
d.changeActiveTabTo(2);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(S);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.newTab(T);
d.newTab(U);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.newTab(V);
b.changeActiveTabTo(5);
c.newTab(W);
d.changeActiveTabTo(5);
a.newTab(X);
b.changeActiveTabTo(1);
c.newTab(Y);
d.moveActiveTabTo(1);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.newTab(Z);
b.newTab(Z);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
b.changeActiveTabTo(1);
d.moveActiveTabTo(1);
b.moveActiveTabTo(3);
d.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
a.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
b.moveActiveTabTo(5);
d.changeActiveTabTo(5);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
b.moveActiveTabTo(1);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->getWindow(4);
brows->closeWindow();
brows->getWindow(0);
brows->getWindow(7);
brows->print();
brows->print();
brows->mergeAllWindows();
brows->getWindow(1);
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(6);
brows->print();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->getWindow(2);
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(1);
brows->print();
brows->mergeAllWindows();
brows->print();
brows->mergeAllWindows();
brows->getWindow(0);
brows->newWindow();
brows->getWindow(2);
brows->print();
brows->mergeAllWindows();
brows->getWindow(0);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(0);
brows->print();
brows->newWindow();
brows->print();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->getWindow(2);
brows->newWindow();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->getWindow(3);
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(9);
brows->newWindow();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->getWindow(0);
brows->getWindow(6);
brows->closeWindow();
brows->switchToWindow(7);
brows->getWindow(1);
brows->getWindow(5);
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->getWindow(9);
brows->closeWindow();
brows->switchToWindow(9);
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->getWindow(0);
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->switchToWindow(8);
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
delete brows;
}
	return 0;
}