#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("gg", "uu","ddd");
Tab B = Tab("y", "jjj","bb");
Tab C = Tab("ii", "jjj","nnn");
Tab D = Tab("ee", "ggg","jj");
Tab E = Tab("mmm", "ss","ggg");
Tab F = Tab("b", "aaa","lll");
Tab G = Tab("u", "oo","ss");
Tab H = Tab("f", "ss","t");
Tab I = Tab("www", "o","bb");
Tab J = Tab("u", "ttt","q");
Tab K = Tab("ddd", "n","aaa");
Tab L = Tab("jjj", "vv","ppp");
Tab M = Tab("ss", "bbb","uuu");
Tab N = Tab("nnn", "q","s");
Tab O = Tab("ll", "aa","v");
Tab P = Tab("e", "g","zz");
Tab Q = Tab("yy", "ii","nnn");
Tab R = Tab("ccc", "fff","k");
Tab S = Tab("t", "cc","u");
Tab T = Tab("bb", "xxx","yyy");
Tab U = Tab("eee", "v","ddd");
Tab V = Tab("ooo", "lll","ii");
Tab W = Tab("ttt", "uu","bb");
Tab X = Tab("w", "ff","q");
Tab Y = Tab("ww", "h","z");
Tab Z = Tab("b", "a","h");
a.moveActiveTabTo(3);
b.newTab(A);
c.moveActiveTabTo(3);
d.newTab(B);
a.changeActiveTabTo(5);
b.newTab(C);
c.newTab(D);
d.moveActiveTabTo(5);
a.changeActiveTabTo(0);
b.newTab(E);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(F);
d.changeActiveTabTo(5);
a.changeActiveTabTo(3);
b.newTab(G);
c.newTab(H);
d.newTab(I);
a.newTab(J);
b.moveActiveTabTo(4);
c.newTab(K);
d.moveActiveTabTo(4);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.newTab(L);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(M);
d.changeActiveTabTo(0);
a.newTab(N);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(2);
b.newTab(O);
c.newTab(P);
d.newTab(Q);
a.changeActiveTabTo(1);
b.newTab(R);
c.newTab(S);
d.moveActiveTabTo(1);
a.newTab(T);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(U);
a.newTab(V);
b.changeActiveTabTo(2);
c.newTab(W);
d.newTab(X);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.newTab(Y);
d.changeActiveTabTo(4);
a.changeActiveTabTo(2);
b.newTab(Z);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(0);
a.moveActiveTabTo(5);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
b.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
a.moveActiveTabTo(1);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
a.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.moveActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(5);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(2);
d.changeActiveTabTo(2);
d.changeActiveTabTo(4);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(4);
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->getWindow(7);
brows->newWindow();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->getWindow(1);
brows->closeWindow();
brows->print();
brows->newWindow();
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->getWindow(7);
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->switchToWindow(7);
brows->newWindow();
brows->switchToWindow(0);
brows->switchToWindow(7);
brows->getWindow(4);
brows->switchToWindow(2);
brows->print();
brows->switchToWindow(8);
brows->mergeAllWindows();
brows->print();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->getWindow(2);
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->getWindow(0);
brows->print();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(9);
brows->switchToWindow(4);
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->print();
brows->newWindow();
brows->print();
brows->closeWindow();
brows->getWindow(5);
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->newWindow();
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(2);
brows->print();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(3);
brows->getWindow(8);
brows->mergeAllWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->print();
brows->print();
brows->getWindow(8);
brows->getWindow(3);
brows->newWindow();
delete brows;
}
	return 0;
}