#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("a", "b","r");
Tab B = Tab("qqq", "jjj","jj");
Tab C = Tab("vv", "m","hhh");
Tab D = Tab("xxx", "u","hhh");
Tab E = Tab("bb", "zz","b");
Tab F = Tab("b", "eee","ii");
Tab G = Tab("a", "pp","ooo");
Tab H = Tab("nnn", "n","w");
Tab I = Tab("ooo", "w","jj");
Tab J = Tab("qqq", "b","mm");
Tab K = Tab("f", "kk","tt");
Tab L = Tab("iii", "zz","zz");
Tab M = Tab("t", "kk","eee");
Tab N = Tab("nn", "lll","kk");
Tab O = Tab("rrr", "ppp","oo");
Tab P = Tab("ii", "p","zzz");
Tab Q = Tab("c", "h","kkk");
Tab R = Tab("pp", "kkk","ooo");
Tab S = Tab("qqq", "t","ttt");
Tab T = Tab("qqq", "ooo","x");
Tab U = Tab("rrr", "bbb","nn");
Tab V = Tab("zzz", "x","k");
Tab W = Tab("r", "ccc","lll");
Tab X = Tab("ooo", "x","nn");
Tab Y = Tab("a", "y","ggg");
Tab Z = Tab("hhh", "fff","r");
a.newTab(A);
b.moveActiveTabTo(0);
c.newTab(B);
d.moveActiveTabTo(0);
a.moveActiveTabTo(2);
b.newTab(C);
c.moveActiveTabTo(2);
d.newTab(D);
a.changeActiveTabTo(1);
b.newTab(E);
c.changeActiveTabTo(1);
d.newTab(F);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(G);
a.changeActiveTabTo(1);
b.newTab(H);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(I);
b.newTab(J);
c.newTab(K);
d.moveActiveTabTo(0);
a.moveActiveTabTo(5);
b.newTab(L);
c.changeActiveTabTo(5);
d.newTab(M);
a.newTab(N);
b.newTab(O);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(0);
b.newTab(P);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.newTab(Q);
b.newTab(R);
c.newTab(S);
d.changeActiveTabTo(0);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(T);
a.changeActiveTabTo(5);
b.newTab(U);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.newTab(V);
a.moveActiveTabTo(3);
b.newTab(W);
c.newTab(X);
d.moveActiveTabTo(3);
a.changeActiveTabTo(0);
b.newTab(Y);
c.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.newTab(Z);
d.changeActiveTabTo(0);
a.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
c.changeActiveTabTo(4);
a.moveActiveTabTo(4);
d.moveActiveTabTo(4);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
d.moveActiveTabTo(0);
c.changeActiveTabTo(3);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(1);
b.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(0);
d.moveActiveTabTo(0);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(1);
c.moveActiveTabTo(1);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->getWindow(4);
brows->getWindow(0);
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->getWindow(3);
brows->mergeAllWindows();
brows->print();
brows->print();
brows->getWindow(0);
brows->newWindow();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->getWindow(2);
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->getWindow(2);
brows->closeEmptyWindows();
brows->print();
brows->closeWindow();
brows->print();
brows->newWindow();
brows->print();
brows->newWindow();
brows->getWindow(5);
brows->closeWindow();
brows->newWindow();
brows->getWindow(8);
brows->print();
brows->switchToWindow(1);
brows->newWindow();
brows->newWindow();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->getWindow(9);
brows->getWindow(7);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->closeWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(9);
brows->getWindow(9);
brows->switchToWindow(6);
brows->mergeAllWindows();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(8);
brows->switchToWindow(7);
brows->getWindow(6);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->print();
brows->print();
brows->newWindow();
brows->switchToWindow(6);
brows->switchToWindow(7);
brows->print();
brows->print();
brows->closeWindow();
brows->switchToWindow(9);
brows->print();
brows->print();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->getWindow(0);
brows->closeEmptyWindows();
brows->switchToWindow(4);
brows->switchToWindow(8);
brows->print();
brows->getWindow(2);
brows->mergeAllWindows();
brows->switchToWindow(9);
brows->switchToWindow(5);
brows->switchToWindow(2);
brows->closeWindow();
delete brows;
}
	return 0;
}