#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("b", "zzz","w");
Tab B = Tab("p", "uuu","k");
Tab C = Tab("d", "h","www");
Tab D = Tab("p", "n","ii");
Tab E = Tab("b", "hhh","dd");
Tab F = Tab("r", "bb","hh");
Tab G = Tab("zzz", "ggg","hh");
Tab H = Tab("o", "q","ppp");
Tab I = Tab("rrr", "ss","eee");
Tab J = Tab("bbb", "ooo","kkk");
Tab K = Tab("aaa", "x","mm");
Tab L = Tab("yy", "rrr","z");
Tab M = Tab("qqq", "nnn","nnn");
Tab N = Tab("xx", "cc","vvv");
Tab O = Tab("xxx", "a","cc");
Tab P = Tab("ll", "ppp","lll");
Tab Q = Tab("j", "s","aa");
Tab R = Tab("h", "y","o");
Tab S = Tab("www", "jj","fff");
Tab T = Tab("h", "gg","uu");
Tab U = Tab("g", "uuu","tt");
Tab V = Tab("ss", "bbb","d");
Tab W = Tab("pp", "dd","nn");
Tab X = Tab("ii", "uu","zzz");
Tab Y = Tab("pp", "qq","nnn");
Tab Z = Tab("iii", "iii","ttt");
a.newTab(A);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(B);
d.moveActiveTabTo(5);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.newTab(C);
d.newTab(D);
a.changeActiveTabTo(4);
b.newTab(E);
c.changeActiveTabTo(4);
d.newTab(F);
a.newTab(G);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(5);
b.newTab(H);
c.moveActiveTabTo(5);
d.newTab(I);
a.newTab(J);
b.newTab(K);
c.newTab(L);
d.newTab(M);
a.newTab(N);
b.newTab(O);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.newTab(P);
b.changeActiveTabTo(3);
c.newTab(Q);
d.moveActiveTabTo(3);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(R);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.newTab(S);
a.newTab(T);
b.newTab(U);
c.newTab(V);
d.moveActiveTabTo(1);
a.newTab(W);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.newTab(X);
a.newTab(Y);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(Z);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
a.changeActiveTabTo(4);
d.changeActiveTabTo(4);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(5);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
c.changeActiveTabTo(4);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(1);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(4);
c.changeActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(3);
b.changeActiveTabTo(3);
c.changeActiveTabTo(3);
d.changeActiveTabTo(3);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.moveActiveTabTo(1);
c.moveActiveTabTo(1);
a.moveActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(2);
d.changeActiveTabTo(2);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
d.changeActiveTabTo(2);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.changeActiveTabTo(2);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
d.changeActiveTabTo(1);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.changeActiveTabTo(2);
a.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.changeActiveTabTo(0);
b.moveActiveTabTo(0);
d.changeActiveTabTo(0);
b.moveActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.changeActiveTabTo(4);
c.moveActiveTabTo(4);
d.changeActiveTabTo(4);
a.moveActiveTabTo(0);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->newWindow();
brows->switchToWindow(8);
brows->print();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(2);
brows->getWindow(7);
brows->getWindow(7);
brows->print();
brows->print();
brows->print();
brows->switchToWindow(3);
brows->closeWindow();
brows->closeWindow();
brows->print();
brows->switchToWindow(0);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->switchToWindow(7);
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(6);
brows->mergeAllWindows();
brows->switchToWindow(5);
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(1);
brows->getWindow(4);
brows->switchToWindow(4);
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->print();
brows->getWindow(0);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(6);
brows->print();
brows->switchToWindow(7);
brows->closeWindow();
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->closeWindow();
brows->newWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->newWindow();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeWindow();
brows->print();
brows->closeEmptyWindows();
brows->print();
brows->getWindow(9);
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeEmptyWindows();
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->print();
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->switchToWindow(3);
brows->getWindow(5);
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->mergeAllWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->newWindow();
brows->closeWindow();
brows->switchToWindow(7);
brows->getWindow(6);
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->switchToWindow(8);
brows->closeEmptyWindows();
brows->newWindow();
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->print();
brows->getWindow(0);
brows->closeWindow();
brows->newWindow();
brows->newWindow();
brows->getWindow(4);
brows->closeWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->print();
brows->getWindow(0);
brows->newWindow();
brows->closeEmptyWindows();
brows->mergeAllWindows();
brows->print();
brows->print();
brows->getWindow(8);
brows->closeEmptyWindows();
brows->getWindow(0);
brows->mergeAllWindows();
brows->newWindow();
brows->switchToWindow(4);
delete brows;
}
	return 0;
}