#include "../../your_code/Window.cpp"
#include "../../your_code/Browser.cpp"
#include "../../your_code/LinkedList.h"
int main() {
{
Browser* brows = new Browser();
Window a;
Window b;
Window c;
Window d;
Tab A = Tab("q", "z","qq");
Tab B = Tab("i", "eee","w");
Tab C = Tab("ll", "cc","mmm");
Tab D = Tab("yyy", "hhh","n");
Tab E = Tab("nn", "qqq","jj");
Tab F = Tab("aa", "b","y");
Tab G = Tab("gg", "xxx","eee");
Tab H = Tab("t", "g","www");
Tab I = Tab("jj", "p","u");
Tab J = Tab("p", "g","v");
Tab K = Tab("qq", "d","ff");
Tab L = Tab("uuu", "aa","x");
Tab M = Tab("ee", "w","oo");
Tab N = Tab("qq", "s","m");
Tab O = Tab("o", "ddd","iii");
Tab P = Tab("ee", "kkk","pp");
Tab Q = Tab("dd", "xxx","aa");
Tab R = Tab("kk", "qq","aaa");
Tab S = Tab("nnn", "ss","h");
Tab T = Tab("uuu", "vv","dd");
Tab U = Tab("cc", "bb","mm");
Tab V = Tab("pp", "vvv","y");
Tab W = Tab("uuu", "nn","dd");
Tab X = Tab("yy", "t","ii");
Tab Y = Tab("q", "uuu","z");
Tab Z = Tab("pp", "bbb","vv");
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
d.newTab(A);
a.newTab(B);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.newTab(C);
b.changeActiveTabTo(5);
c.changeActiveTabTo(5);
d.newTab(D);
a.newTab(E);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(0);
b.changeActiveTabTo(0);
c.moveActiveTabTo(0);
d.newTab(F);
a.changeActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(G);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.newTab(H);
a.newTab(I);
b.moveActiveTabTo(4);
c.newTab(J);
d.moveActiveTabTo(4);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
c.newTab(K);
d.moveActiveTabTo(3);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.newTab(L);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
d.moveActiveTabTo(0);
a.changeActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(M);
d.newTab(N);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.newTab(O);
d.changeActiveTabTo(5);
a.newTab(P);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
d.newTab(Q);
a.moveActiveTabTo(2);
b.changeActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(R);
b.newTab(S);
c.changeActiveTabTo(2);
d.moveActiveTabTo(2);
a.changeActiveTabTo(1);
b.changeActiveTabTo(1);
c.newTab(T);
d.newTab(U);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.newTab(V);
a.changeActiveTabTo(3);
b.newTab(W);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(2);
b.newTab(X);
c.changeActiveTabTo(2);
d.changeActiveTabTo(2);
a.changeActiveTabTo(2);
b.moveActiveTabTo(2);
c.moveActiveTabTo(2);
d.moveActiveTabTo(2);
a.newTab(Y);
b.changeActiveTabTo(0);
c.newTab(Z);
d.moveActiveTabTo(0);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
d.moveActiveTabTo(0);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
b.moveActiveTabTo(0);
c.changeActiveTabTo(0);
a.moveActiveTabTo(5);
b.changeActiveTabTo(5);
c.moveActiveTabTo(5);
d.changeActiveTabTo(5);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(3);
b.changeActiveTabTo(3);
d.moveActiveTabTo(3);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.moveActiveTabTo(0);
c.moveActiveTabTo(0);
d.changeActiveTabTo(0);
a.changeActiveTabTo(3);
b.moveActiveTabTo(3);
c.moveActiveTabTo(3);
d.changeActiveTabTo(3);
a.changeActiveTabTo(0);
d.changeActiveTabTo(0);
a.moveActiveTabTo(2);
c.changeActiveTabTo(2);
a.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
a.moveActiveTabTo(2);
b.moveActiveTabTo(2);
a.changeActiveTabTo(3);
b.changeActiveTabTo(1);
c.moveActiveTabTo(1);
d.moveActiveTabTo(1);
a.moveActiveTabTo(4);
b.moveActiveTabTo(4);
c.moveActiveTabTo(4);
d.moveActiveTabTo(4);
a.changeActiveTabTo(1);
b.moveActiveTabTo(1);
c.changeActiveTabTo(1);
a.moveActiveTabTo(5);
c.changeActiveTabTo(5);
d.moveActiveTabTo(5);
a.changeActiveTabTo(4);
b.changeActiveTabTo(4);
b.changeActiveTabTo(1);
c.changeActiveTabTo(1);
d.changeActiveTabTo(1);
b.changeActiveTabTo(4);
d.moveActiveTabTo(4);
a.moveActiveTabTo(5);
b.moveActiveTabTo(5);
c.moveActiveTabTo(5);
a.changeActiveTabTo(3);
c.moveActiveTabTo(3);
d.moveActiveTabTo(3);
a.moveActiveTabTo(0);
b.changeActiveTabTo(0);
c.changeActiveTabTo(0);
a.moveActiveTabTo(0);
c.changeActiveTabTo(0);
a.moveActiveTabTo(5);
brows->addWindow(a);
brows->addWindow(b);
brows->addWindow(c);
brows->addWindow(d);
brows->getWindow(8);
brows->closeWindow();
brows->print();
brows->switchToWindow(6);
brows->print();
brows->getWindow(8);
brows->switchToWindow(1);
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->newWindow();
brows->print();
brows->newWindow();
brows->switchToWindow(7);
brows->closeWindow();
brows->newWindow();
brows->print();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->closeWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->switchToWindow(4);
brows->closeWindow();
brows->newWindow();
brows->getWindow(0);
brows->print();
brows->switchToWindow(6);
brows->closeEmptyWindows();
brows->print();
brows->mergeAllWindows();
brows->newWindow();
brows->getWindow(5);
brows->print();
brows->newWindow();
brows->mergeAllWindows();
brows->getWindow(5);
brows->newWindow();
brows->getWindow(0);
brows->getWindow(0);
brows->getWindow(9);
brows->mergeAllWindows();
brows->newWindow();
brows->newWindow();
brows->closeWindow();
brows->closeWindow();
brows->switchToWindow(1);
brows->closeWindow();
brows->closeEmptyWindows();
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->switchToWindow(0);
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->getWindow(6);
brows->newWindow();
brows->switchToWindow(9);
brows->mergeAllWindows();
brows->print();
brows->closeWindow();
brows->getWindow(0);
brows->newWindow();
brows->print();
brows->switchToWindow(7);
brows->getWindow(1);
brows->switchToWindow(9);
brows->switchToWindow(4);
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->newWindow();
brows->getWindow(6);
brows->print();
brows->mergeAllWindows();
brows->switchToWindow(8);
brows->getWindow(3);
brows->switchToWindow(6);
brows->switchToWindow(1);
brows->closeWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeWindow();
brows->closeEmptyWindows();
brows->print();
brows->newWindow();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->closeEmptyWindows();
brows->getWindow(8);
brows->getWindow(2);
brows->print();
brows->getWindow(6);
brows->closeWindow();
brows->switchToWindow(0);
brows->getWindow(0);
brows->print();
brows->getWindow(0);
brows->switchToWindow(3);
brows->closeEmptyWindows();
brows->getWindow(2);
brows->newWindow();
brows->mergeAllWindows();
brows->mergeAllWindows();
brows->closeWindow();
brows->switchToWindow(4);
brows->newWindow();
brows->closeWindow();
brows->newWindow();
brows->switchToWindow(8);
brows->switchToWindow(5);
brows->closeEmptyWindows();
brows->closeWindow();
delete brows;
}
	return 0;
}